[0.14 backport] Don't require segwit in getblocktemplate for segwit signalling or mining
bitcoin/bitcoin pull request #10006
Opened 2017-03-16 01:43 UTC by sdaftuar

Backport of #9955 to the 0.14 branch (all conflicts were in `segwit.py`).

2017-03-16 04:03 UTC, gmaxwell approved these changes
ACK  (I have tested but not tested the tests.)

2017-03-16 10:32 UTC, laanwj commented
utACK, though please add backport metadata `Github-Pull:` and `Rebased-From:` in the commit message (e.g. see https://github.com/bitcoin/bitcoin/commit/8dee97f98253c7d7a5219f4ab0d0e6e9bec0dcef)

2017-03-16 14:54 UTC, sdaftuar commented
@laanwj Thanks, I updated the commit messages.

2017-03-17 11:07 UTC, earonesty requested changes

2017-03-17 11:07 UTC, earonesty commented on qa/rpc-tests/p2p-segwit.py
> +            assert_equal((block_version & (1 << VB_WITNESS_BIT) != 0), node == self.nodes[0])
extra parens needed here so operator precedence is clear

2017-03-17 18:43 UTC, MarcoFalke commented on qa/rpc-tests/p2p-segwit.py
> +            assert_equal((block_version & (1 << VB_WITNESS_BIT) != 0), node == self.nodes[0])
Note: This is a backport, so it is too late to fix style issues.

2017-03-17 19:38 UTC, TheBlueMatt commented on qa/rpc-tests/p2p-segwit.py
> +            assert_equal((block_version & (1 << VB_WITNESS_BIT) != 0), node == self.nodes[0])
Feel free to fix style issues in a new PR against master, though.

2017-03-18 10:39 UTC, merged