[qa] combine_logs: Use ordered list for logfiles
bitcoin/bitcoin pull request #10076
Opened 2017-03-25 14:11 UTC by MarcoFalke

According to the documentation of glob, "results are returned in arbitrary order". Thus, create each path separately by string formatting.

2017-03-25 22:34 UTC, jnewbery commented on test/functional/combine_logs.py
> +from test_framework.util import MAX_NODES
micronit: blank line between the standard library imports and local project imports please.

2017-03-25 22:34 UTC, jnewbery commented
Good catch! Tested ACK https://github.com/bitcoin/bitcoin/pull/10076/commits/fa32e5c16b7f281c500ef6064e6d0e0329465c74 with a micronit.

2017-03-25 22:35 UTC, jnewbery approved these changes

2017-03-26 12:51 UTC, jnewbery commented
Actually, thinking about this some more, I don't think I like the dependency on test_framework.utils here. At the moment combine_logs can be run from anywhere, even on a system that doesn't have bitcoin or the test_framework installed. You can tar the tmp directory, upload it somewhere and then do the post-processing on another system. I'd like to preserve that if possible.

Can you change this to use glob and then inspect the name of the directory to get the node index?

2017-03-26 12:51 UTC, jnewbery requested changes
Please remove dependency on test_framework

2017-03-28 09:41 UTC, MarcoFalke commented on test/functional/combine_logs.py
> +from test_framework.util import MAX_NODES
@jnewbery Removed this import

2017-03-28 12:42 UTC, jnewbery approved these changes
Looks great. Thanks Marco.

Tested ACK fa4535df574067700ed7d2227ae03605075b8730

2017-03-28 12:47 UTC, merged