Update bitcoin.conf with example for pruning
bitcoin/bitcoin pull request #10090
Opened 2017-03-26 20:32 UTC by coinables

This option is becoming more popular recently, and I propose an example to be shown in the bitcoin.conf.

2017-03-27 07:33 UTC, laanwj commented
Concept ACK on adding the example.

Explicitly mentioning 3GB is not a good idea. These numbers peppered around the documentation tend to get outdated sooner than later. The [size of the UTXO set](http://statoshi.info/dashboard/db/unspent-transaction-output-set) is growing every day, and that can't be pruned.

2017-03-27 07:41 UTC, laanwj commented on contrib/debian/examples/bitcoin.conf
> +# Pruning can drastically reduce the amount of disk space required to run bitcoin down to ~3GB.
You have the unit wrong, it's not in blocks but in MiB. Maybe you can borrow some description text from the help message:
```
  -prune=<n>
       Reduce storage requirements by enabling pruning (deleting) of old
       blocks. This allows the pruneblockchain RPC to be called to
       delete specific blocks, and enables automatic pruning of old
       blocks if a target size in MiB is provided. This mode is
       incompatible with -txindex and -rescan. Warning: Reverting this
       setting requires re-downloading the entire blockchain. (default:
       0 = disable pruning blocks, 1 = allow manual pruning via RPC,
       >550 = automatically prune block files to stay under the
       specified target size in MiB)
```

2017-03-27 17:12 UTC, paveljanik requested changes

2017-03-27 17:12 UTC, paveljanik commented on contrib/debian/examples/bitcoin.conf
> +# Enable pruning to reduce storage requirments by deleting old blocks.
requirements

2017-03-27 17:12 UTC, paveljanik commented on contrib/debian/examples/bitcoin.conf
> +# Value is in MiB. 550 is the minimum.
550 is the minimum, but you describe entering 1...

2017-03-27 17:12 UTC, paveljanik commented on contrib/debian/examples/bitcoin.conf
> +# default = 0, 1 = allows manual pruning via RPC, >550 = target to stay under in MiB.
>=550

2017-03-29 01:15 UTC, sipa commented
ACK after squashing.

2017-03-29 05:55 UTC, paveljanik requested changes

2017-03-29 05:55 UTC, paveljanik commented on contrib/debian/examples/bitcoin.conf
> +# 0 = default(no pruning).
space before "(". And please squash.

2017-03-29 05:55 UTC, paveljanik commented on contrib/debian/examples/bitcoin.conf
> +# Enable pruning to reduce storage requirments by deleting old blocks.
requirments -> requirements

2017-03-31 01:24 UTC, fanquake commented
utACK c0651cc

2017-03-31 07:29 UTC, merged

2017-03-31 10:14 UTC, laanwj commented
I think we should move this file somewhere else - `doc/examples` maybe? After all it is a general example of a `bitcoin.conf` and there is nothing debian-specific to it.