linearize script: Option to use RPC cookie
bitcoin/bitcoin pull request #10104
Opened 2017-03-28 04:21 UTC by achow101

This PR adds the a `datadir` option to the linearize configuration file to allow linearize-hashes to look for and use the RPC cookie file in the datadir. It will still allow rpcuser and rpcpassword to be specified and those options will take precendence if both rpcuser/pass and datadir config options are set.

closes #10103

2017-03-28 07:21 UTC, jonasschnelli commented
Nice.
utACK 476c6d4c8dcf41f9e3accf5be1b84fdd4718046b

2017-03-29 07:33 UTC, laanwj commented
Makes sense, utACK

2017-03-29 09:09 UTC, laanwj commented
@pstratem can you confirm that this implements what you requested in #10103?

2017-03-29 09:10 UTC, MarcoFalke commented
utACK 476c6d4

2017-03-29 18:09 UTC, pstratem requested changes

2017-03-29 18:09 UTC, pstratem commented on contrib/linearize/linearize-hashes.py
> +	with open(settings['datadir'] + '/.cookie', 'r') as f:
open(os.path.join(os.path.expanduser(settings['datadir']), '/.cookie'), 'r')

2017-03-29 18:55 UTC, achow101 commented on contrib/linearize/linearize-hashes.py
> +	with open(settings['datadir'] + '/.cookie', 'r') as f:
done

2017-03-29 23:47 UTC, pstratem commented
@achow101 need to import os.path

2017-03-29 23:57 UTC, pstratem commented
my bad
`diff --git a/contrib/linearize/linearize-hashes.py b/contrib/linearize/linearize-hashes.py
index 721d204..db8eb70 100755
--- a/contrib/linearize/linearize-hashes.py
+++ b/contrib/linearize/linearize-hashes.py
@@ -16,6 +16,8 @@ import json
 import re
 import base64
 import sys
+import os
+import os.path
 
 settings = {}
 
@@ -93,9 +95,9 @@ def get_block_hashes(settings, max_blocks_per_call=10000):
 
                height += num_blocks
 
-def get_rpc_cookie(settings):
+def get_rpc_cookie():
        # Open the cookie file
-       with open(os.path.join(os.path.expanduser(settings['datadir']), '/.cookie'), 'r') as f:
+       with open(os.path.join(os.path.expanduser(settings['datadir']), '.cookie'), 'r') as f:
                combined = f.readline()
                combined_split = combined.split(":")
                settings['rpcuser'] = combined_split[0]
@@ -150,6 +152,6 @@ if __name__ == '__main__':
 
        # Get the rpc user and pass from the cookie if the datadir is set
        if use_datadir:
-               get_rpc_cookie(settings)
+               get_rpc_cookie()
 
        get_block_hashes(settings)
`

2017-03-30 00:14 UTC, achow101 commented
@pstratem Is that right?

2017-04-05 05:59 UTC, merged