Add OSX keystroke to clear RPCConsole
bitcoin/bitcoin pull request #10324
Opened 2017-05-03 08:04 UTC by spencerlievens

Currently only Ctrl-L is mentioned in help, but, CMD-L works on OSX and isn't mentioned.

2017-05-03 08:05 UTC, jonasschnelli commented
ACK 6315a6fd0689c7469f9c266bf5b4f0e337ef79d4

2017-05-03 09:13 UTC, laanwj commented on src/qt/rpcconsole.cpp
> +                        tr("To clear screen use <b>Ctrl-L</b> on Windows/Linux or <b>⌘CMD-L</b> on OSX") + "<br>" +
I'm not usually a person to say this but: let's make this platform dependent instead of enumerating the platforms here.

2017-05-03 11:33 UTC, spencerlievens commented on src/qt/rpcconsole.cpp
> +                        tr("To clear screen use <b>Ctrl-L</b> on Windows/Linux or <b>⌘CMD-L</b> on OSX") + "<br>" +
ifdef it?

2017-05-03 11:50 UTC, spencerlievens commented
Improved the code to use an ifdef for OSX instead.

2017-05-03 11:51 UTC, laanwj commented on src/qt/rpcconsole.cpp
> +			tr("Type <b>help</b> for an overview of available commands.")) +
Possible suggestion:
```c++
#ifdef Q_OS_MAC
QString clearKeyStr = "<b>⌘cmd-L</b>";
#else
QString clearKeyStr = "<b>Ctrl-L</b>";
#endif
...
tr("Use up and down arrows to navigate history, and %1 to clear screen.").arg(clearKeyStr) + "<br>" +
```
After all:
- The key is not to be translated
- Also gets rid of the HTML formatting in the translation string in one go

2017-05-03 11:54 UTC, jonasschnelli commented on src/qt/rpcconsole.cpp
> +			tr("Type <b>help</b> for an overview of available commands.")) +
If we are already bikeshedding:
Alternative suggestion would be adding `QString generalFunctionKey()` to platformstyles.cpp.
Then use something like `tr("Use up and down arrows to navigate history, and %1-L to clear screen.").arg(platformStyle->generalFunctionKey())`

2017-05-03 11:58 UTC, spencerlievens commented on src/qt/rpcconsole.cpp
> +			tr("Type <b>help</b> for an overview of available commands.")) +
That is much tidier than my attempt 👍 

#ifdef Q_OS_MAC
QString clearKeyStr = "<b>⌘cmd-L</b>";
#else
QString clearKeyStr = "<b>Ctrl-L</b>";
#endif

2017-05-03 11:59 UTC, laanwj commented on src/qt/rpcconsole.cpp
> +			tr("Type <b>help</b> for an overview of available commands.")) +
Yes, adding it to platformStyle would be another step further, I didn't want to suggest that here to not make life too difficult for @spencerlievens while also not making life harder for translators by adding another message that is almost-the-same.

2017-05-03 12:03 UTC, spencerlievens commented on src/qt/rpcconsole.cpp
> +			tr("Type <b>help</b> for an overview of available commands.")) +
Yeah adding to platform style is certainly the more "correct" path, but induces a lot of work.

2017-05-03 12:41 UTC, spencerlievens commented
@laanwj When I find some time I will add to platformstyle.cpp and update the translation files as it isn't difficult, just time consuming.

2017-05-05 08:42 UTC, paveljanik requested changes
And please squash.

2017-05-05 08:42 UTC, paveljanik commented on src/qt/rpcconsole.cpp
> +
There is a TAB on this otherwise empty line.

2017-05-05 08:42 UTC, paveljanik commented on src/qt/rpcconsole.cpp
> +    QString clsKey = "<b>⌘cmd-L</b>";
Can you please move this HTML down to `arg(clsKey)`? E.g.
```C++
arg("<b>"+clsKey+</b>)
```
or something and remove it from here?

2017-05-05 08:42 UTC, paveljanik commented on src/qt/rpcconsole.cpp
> +			tr("Type <b>help</b> for an overview of available commands.")) +
Spaces replaced by TABS? Why?

2017-05-06 14:08 UTC, spencerlievens commented on src/qt/rpcconsole.cpp
> +			tr("Type <b>help</b> for an overview of available commands.")) +
Urgh that was my editor.

2017-05-06 14:13 UTC, spencerlievens commented on src/qt/rpcconsole.cpp
> +
Done

2017-05-06 14:13 UTC, spencerlievens commented on src/qt/rpcconsole.cpp
> +    QString clsKey = "<b>⌘cmd-L</b>";
Done

2017-05-06 14:20 UTC, paveljanik commented on src/qt/rpcconsole.cpp
> +                        tr("Use up and down arrows to navigate history, and %1 to clear screen.").arg("<b>"+clsKey+"<b>") + "<br>" +
`</b>`

2017-05-06 16:45 UTC, spencerlievens commented
@paveljanik thats what happens when you edit via mobile and online on GitHub

2017-05-06 18:15 UTC, spencerlievens commented
@laanwj @jonasschnelli @paveljanik 

All squashed and good to go ;)

2017-05-06 19:41 UTC, paveljanik commented
In the help of e.g. Terminal and Safari, I see Command (⌘)-L notation.

2017-05-07 09:36 UTC, spencerlievens commented
@paveljanik This is true, but I wanted to spell it out for the user and make it clear as day.

2017-05-08 19:45 UTC, spencerlievens commented
I realised that this work was not done on a Bitcoin fork and the fork of Dash that the work had been done on I have subsequently deleted, the new PR for this is #10362

2017-05-08 19:45 UTC, closed without merging