RPC/Mining: Restore API compatibility for prioritisetransaction
bitcoin/bitcoin pull request #10488
Opened 2017-05-31 16:08 UTC by TheBlueMatt

This is an alternative version of #10252, explaining that the first value is "dummy" instead of adding more references to priority now that we've removed it.

2017-05-31 16:11 UTC, sipa commented on src/rpc/mining.cpp
> +            "2. dummy          (numeric, optional) API-Compaibility for previous API. Must be zero or null.\n"
Typo: Compaibility

2017-05-31 17:15 UTC, luke-jr commented on src/rpc/client.cpp
> +    { "prioritisetransaction", 1, "dummy" },
This breaks the API compatibility...

2017-05-31 19:17 UTC, TheBlueMatt commented on src/rpc/client.cpp
> +    { "prioritisetransaction", 1, "dummy" },
I dont think we care for position-independant arguments? They're still super new and I would be highly surprised if anyone is prioritizing by priority in 0.14, where its highly unsupported and disabled by default?

2017-05-31 21:15 UTC, jnewbery reviewed
tested ACK 99445847d43da86724aa49ef193f57c63a97f17b . A couple of documentation suggestions inline.

2017-05-31 21:15 UTC, jnewbery commented on src/rpc/mining.cpp
> +        throw JSONRPCError(RPC_INVALID_PARAMETER, "Priority is no longer supported, adjustment thereof must be zero.");
`adjustment thereof` sounds a little tortured to me. How about `The second argument must be set to 0.0`

(simpler English and specifies precisely what the argument should be set to)

2017-05-31 21:15 UTC, jnewbery commented on src/rpc/mining.cpp
> +            "2. dummy          (numeric, optional) API-Compatibility for previous API. Must be zero or null.\n"
Suggest you add a note that the second (dummy) argument is deprecated and may be removed in a future version. Clients should change to calling this RPC with named `fee_delta` argument if possible for forward compatibility.

2017-06-06 14:03 UTC, MarcoFalke commented
Needs rebase if still relevant

2017-06-06 14:14 UTC, TheBlueMatt commented
Rebased.

2017-06-06 17:42 UTC, luke-jr requested changes

2017-06-06 17:42 UTC, luke-jr commented on src/rpc/mining.cpp
> +        throw JSONRPCError(RPC_INVALID_PARAMETER, "Priority is no longer supported, first argument to prioritisetransaction must be 0.");
Using named arguments, "first argument" may be confusing. Also suggest the recommendation should be null, not 0.

2017-06-06 17:42 UTC, luke-jr commented on src/rpc/mining.cpp
> +    { "mining",             "prioritisetransaction",  &prioritisetransaction,  true,  {"txid","dummy","fee_delta"} },
This breaks the API compatibility. IMO leave it alone here, and just update the help.

2017-06-06 17:57 UTC, MarcoFalke commented on src/rpc/mining.cpp
> +    { "mining",             "prioritisetransaction",  &prioritisetransaction,  true,  {"txid","dummy","fee_delta"} },
Compatibility is already broken, as we require `priority_delta==0`

2017-06-06 18:55 UTC, luke-jr commented on src/rpc/mining.cpp
> +    { "mining",             "prioritisetransaction",  &prioritisetransaction,  true,  {"txid","dummy","fee_delta"} },
Hmm, good point.

2017-06-06 19:13 UTC, TheBlueMatt commented on src/rpc/mining.cpp
> +        throw JSONRPCError(RPC_INVALID_PARAMETER, "Priority is no longer supported, first argument to prioritisetransaction must be 0.");
Fixed.

2017-06-08 20:26 UTC, ryanofsky reviewed
utACK 40796e1a9d01758ba61d0d68fd05574a4272e4eb.

Maybe rename PR to something like "Improve documentation for prioritisetransaction" since this isn't really about restoring API compatibility anymore.

Also, if you wanted to update the release notes here to mention the priority_delta->dummy rename, and requirement to pass 0 or null, that would be good.

2017-06-09 16:18 UTC, TheBlueMatt commented
Mentioned the release notes at #9889, updated PR title.

2017-06-09 19:44 UTC, sipa commented
utACK 40796e1a9d01758ba61d0d68fd05574a4272e4eb

2017-06-12 11:00 UTC, laanwj commented
utACK 40796e1

2017-06-12 11:01 UTC, merged