Use std::random::mt19937/uniform_int_distribution (C++11) instead of boost::random equivalents
bitcoin/bitcoin pull request #10547
Opened 2017-06-07 12:18 UTC by practicalswift

2017-06-07 12:27 UTC, laanwj commented
Why not use our own fast_random_context?

2017-06-07 14:41 UTC, practicalswift commented
@laanwj Good idea! Now using `FastRandomContext`. Looks OK now?

2017-06-07 14:46 UTC, laanwj commented
Yes, that's a cool minimal-impact solution using the lambda expressions.

2017-06-07 16:04 UTC, maflcko requested changes

2017-06-07 16:04 UTC, MarcoFalke commented on src/test/scheduler_tests.cpp
> +    auto randomDelta = [](FastRandomContext& rc) { return -1000 + rc.randrange(2001); }; // [-1000, 1000]
This lambda returns an unsigned expression and such can never be negative.

2017-06-07 16:22 UTC, laanwj commented on src/test/scheduler_tests.cpp
> +    auto randomDelta = [](FastRandomContext& rc) { return -1000 + rc.randrange(2001); }; // [-1000, 1000]
Good catch, hadn't realized `randrange` returns an unsigned value. This is a risk with `auto`.

2017-06-07 16:54 UTC, practicalswift commented on src/test/scheduler_tests.cpp
> +    auto randomDelta = [](FastRandomContext& rc) { return -1000 + rc.randrange(2001); }; // [-1000, 1000]
@MarcoFalke Oh, good catch! Now explicitly setting the return type. Thanks a lot for noticing!

2017-06-08 00:51 UTC, gmaxwell approved these changes
utACK

2017-06-08 06:27 UTC, jonasschnelli commented
utACK 227ae9b34dce632e42ca9f22139e6efad0485df1.
Great use of lambdas.

2017-06-08 10:40 UTC, merged