[Test] Tests for zmqpubrawtx and zmqpubrawblock
bitcoin/bitcoin pull request #10552
Opened 2017-06-08 01:02 UTC by achow101

2017-06-08 07:21 UTC, fanquake commented
Both linux builds timed out after ~48 minutes.

2017-06-08 14:30 UTC, jnewbery commented
I suspect that this timeout is due to the python3-zmq Context not closing cleanly at the end of the zmq_test.py test. See https://stackoverflow.com/questions/17140417/termination-of-python-script-while-using-zeromq-with-dead-server for example.

I'm working on a branch that fixes that behaviour here: https://github.com/jnewbery/bitcoin/tree/zmqtestimprovements . It's currently building in Travis. If that works, you might want to try rebasing this PR on top of that branch to see if it resolves this for you.

2017-06-08 15:05 UTC, jnewbery commented
Opened #10555 to fix the python zmq issue. @achow101 - if rebasing on that resolves your travis issue, could you review/ACK that PR?

2017-06-08 18:51 UTC, achow101 commented
Rebased on top of #10555

2017-06-18 12:26 UTC, MarcoFalke commented
Reopen. Was closed due to false positive regex match by GitHub.

2017-06-18 17:26 UTC, achow101 commented
Rebased after #10555 merge.

2017-08-15 21:55 UTC, achow101 commented
rebased

2017-08-23 20:20 UTC, jnewbery requested changes
An unfortunate aspect of this test is that it assumes an order for ZMQ notifications (tx > rawtx > hashblock > rawblock). I don't think that's necessary or should be asserted in the test. However, you've just extended what's already here, so concept ACK.

Please run a linter over this and fix up the warnings. There are a bunch of nits (unused imports, trailing whitespace, etc).

A few more nits inline.

2017-08-23 20:20 UTC, jnewbery commented on test/functional/test_framework/util.py
> +import hashlib
nit: why not placed alphabetically like the other imports?

2017-08-23 20:20 UTC, jnewbery commented on test/functional/test_framework/util.py
> +def sha256d(byte_str):
Please place this in the 'Utility Functions' section, rather than 'Node Functions'

2017-08-23 20:20 UTC, jnewbery commented on test/functional/zmq_test.py
> +        txhash = body
why not just assign `txhash` on line 69. There's no reason to have `body` in this section.

2017-08-23 20:20 UTC, jnewbery commented on test/functional/zmq_test.py
> +        assert_equal(genhashes[0], bytes_to_hex_str(sha256d(body[:80]))) #blockhash from generate must be equal to the hash of the block header
No need for the duplicated comment

2017-08-23 20:20 UTC, jnewbery commented on test/functional/zmq_test.py
> +        hashedZMQ = ""
No need for this line

2017-08-23 20:20 UTC, jnewbery commented on test/functional/zmq_test.py
> +        assert_equal(topic, b"rawtx")
I'd move this assert to immediately after the `topic = ...` line (like in the previous tests in this script).

2017-08-23 23:50 UTC, achow101 commented
Nits addresses (I think) and rebased (there were merge conflicts).

2017-09-06 22:57 UTC, jnewbery commented
Tested ACK ba0b4f1c0a2c47f2f8c342686c94c6e358ea4efe, but needs rebase.

2017-09-06 23:07 UTC, achow101 commented
Rebased

2017-09-06 23:53 UTC, jnewbery commented
utACK a3696dcec45f11f202c1666084c4aa1f8fabd37f

2017-09-07 00:05 UTC, promag reviewed
In the future we could (partially) change to one socket per notification. As it is, the order matters and requires checking for topic when iterating.

2017-09-07 00:14 UTC, promag commented
Just saw @jnewbery comment above:
> An unfortunate aspect of this test is that it assumes an order for ZMQ notifications (tx > rawtx > hashblock > rawblock).

Can be *fixed* with on socket per notification.

2017-09-18 15:44 UTC, achow101 commented on test/functional/test_framework/util.py
> +def sha256d(byte_str):
Done

2017-09-18 15:44 UTC, achow101 commented on test/functional/zmq_test.py
> +        self.extra_args = [['-zmqpubhashtx=%s' % ip_address, '-zmqpubhashblock=%s' % ip_address,
Done

2017-09-18 15:51 UTC, jnewbery commented
> Can be fixed with one socket per notification.

@promag - sounds like a very sensible change. This PR simply extends what's already there so I think we should merge this as is. I'd be happy to review a follow-up PR if you want to implement that.

2017-09-18 16:06 UTC, promag commented
@jnewbery agree. As for the follow up, I think it could be added somewhere in `TestFramework` something to abstract the sockets creation, to ease testing subscribers. As it is, it's too much verbose for testing purpose.

2017-09-18 17:53 UTC, promag reviewed
utACK.

2017-09-18 17:53 UTC, promag commented on test/functional/test_framework/util.py
> +def hash256(byte_str):
Move before `hex_str_to_bytes`.

2017-09-19 02:08 UTC, achow101 commented on test/functional/test_framework/util.py
> +def hash256(byte_str):
Done

2017-09-19 13:34 UTC, jnewbery commented
@promag 

> As for the follow up, I think it could be added somewhere in TestFramework something to abstract the sockets creation

If you're thinking of abstracting away the ZMQ interface, I think it would be better to add a new class in test_node.py to be owned by the `TestNode` class, like how I added a `TestNodeCLI` class in https://github.com/bitcoin/bitcoin/pull/10798

However, the ZMQ interface is only used in this one test script, and I think it's best to keep it that way, so I think it's best to leave the implementation in the `zmq_test.py` file.

We've wondered off-topic a bit for this PR. If you're interested in pursuing this further, feel free to ping me on IRC or open a separate issue.

2017-09-28 16:15 UTC, achow101 commented
Can this be merged?

2017-09-29 17:48 UTC, merged