Relax punishment for peers relaying invalid blocks and headers
bitcoin/bitcoin pull request #10593
Opened 2017-06-14 21:42 UTC by luke-jr

Supercedes #10512 by simply restricting punishments to our outgoing non-feeler connections, and only punishing with a disconnect, not a ban.

2017-06-20 11:39 UTC, ajtowns commented
This seems like a reasonable approach to me; any idea why stop_node in the zapwallettxes test isn't getting a 0 exit code?

2017-07-04 06:32 UTC, luke-jr commented
@ajtowns Not sure what you're asking? The tests are passing...

2017-07-05 02:56 UTC, ajtowns commented
I guess whatever I saw was a transient error then (or I was just confused)...

2017-10-05 21:49 UTC, jimpo commented on src/net_processing.cpp
>              State(it->second.first)->rejects.push_back(reject);
nit: Use nodestate instead of State(it->second.first)

2017-10-05 22:16 UTC, TheBlueMatt commented
Have we considered preferring a relatively short-time-period ban instead of purely disconnecting? If the peer is somehow braindead and tries to reconnect immediately we may prefer to keep them gone for 30 minutes or an hour instead of letting them get into some loop of connect-relay-disconnect.

2017-10-06 18:48 UTC, sdaftuar commented
It seems like this reverts #8305 with no mechanism to replace that functionality. Rationale?  This looks like a regression.

2017-10-07 16:16 UTC, achow101 commented
It was mentioned during the IRC meeting that this already did what I am planning on doing in #11446. However this doesn't seem to cover the case that I am concerned about: receiving a header for a block we have already marked as invalid. In such a case, `nDos` will be 0 and thus the peer won't be punished for relaying us the duplicate header.

2017-10-16 16:04 UTC, promag commented on test/functional/sendheaders.py
> -        # Now try to see how many unconnecting headers we can send
Test passes with the above changes.

2017-10-26 19:33 UTC, luke-jr commented
> It seems like this reverts #8305 with no mechanism to replace that functionality. 

I don't see how. The conditions this disconnects peers is a superset of the conditions #8305 did.

2018-11-04 21:43 UTC, practicalswift commented on test/functional/test_framework/mininode.py
> +            (sock, addr) = listen_sock.accept()
Use `(sock, _) = listen_sock.accept()` to clarify that the second element in the tuple is discarded intentionally

2018-11-05 19:06 UTC, sdaftuar requested changes
Re-NACK.  While I generally agree with the high-level goals described in the OP, it's not clear what changes here are still necessary to achieve that goal -- several related PRs have been merged in the year it's been since this was originally opened. This PR also seems to break the bugfix made in #8305, without explanation or other handling, which seems unnecessary and unrelated to the overall goal of the PR.  And the changes included in this PR seem disjointed (with comments not being updated to reflect new behavior, old nonsensical behavior left in cases that don't make sense, etc) -- presumably because the code changes here have gotten stale?  I didn't bother leaving detailed comments in all those cases because after reviewing this, it's not at all clear to me what you're trying to accomplish.

I suggest this PR be closed; if there are any remaining changes that are still relevant and worth proposing, we can evaluate fresh in a new PR.  If you think I'm mistaken, please give more detailed documentation and explanation of the reasoning behind these changes (for instance, why does the headers processing logic need to change at all?  what cases are you trying to cover, and which cases are still left out?).

Also some of the testing-related changes are separately useful/interesting and warrant their own discussion.  In particular I think supporting outbound peers that are not treated as "manual connections" for net processing purposes would be great, but I think those changes should be reviewed on their own -- I'd prefer we split those out into their own PR, rather than have them be an afterthought to support a test in a single PR.

2018-11-06 02:01 UTC, luke-jr commented
https://github.com/bitcoin/bitcoin/pull/10593#issuecomment-339776309 ... you never explained how you think it reverts #8305

2018-11-06 13:10 UTC, sdaftuar commented
@luke-jr The point of #8305 was to avoid giving DoS points to peers for the occasional unconnecting header.  This PR would immediately disconnect an outbound peer when it announces a header that doesn't connect.

2019-02-12 23:59 UTC, MarcoFalke commented
`feature_block.py` fails on all travis jobs that run it

2019-09-05 15:32 UTC, ajtowns commented
Probably should close this PR; it needs a pretty serious rebase, the RECENT_CONSENSUS_CHANGE stuff from #15141 probably warrants some more thought about the approach which might not happen until we've got a consensus change to go with it, and the current approach has a NACK...

#12674 and the "nodo-to-test connections" support for mininode are probably relevant for #14210 though.

2019-10-10 19:46 UTC, closed without merging

2019-10-16 02:48 UTC, luke-jr commented
>  it needs a pretty serious rebase

Rebase is now complete. Push needs to wait for the PR to be reopened, but @sdaftuar is right that it should probably be split up and smaller changes merged first.

> the RECENT_CONSENSUS_CHANGE stuff from #15141 probably warrants some more thought about the approach which might not happen until we've got a consensus change to go with it,

Recent consensus changes shouldn't be (at least in this context) treated any differently than other consensus rules. You're looking at it in the limited scenario of a softfork, but it needs to be broader to ensure we overwrite/reorg any attempts to hardfork without consensus too.