[Trivial] Improve end-of-namespace comment consistency
bitcoin/bitcoin pull request #10702
Opened 2017-06-29 12:25 UTC by MeshCollider

Continuing on from #9544 this just makes the end-of-namespace comments consistent across all files

2017-06-29 12:36 UTC, laanwj commented
Meh, why all the end-of-namespace pulls lately? We don't have a clear rule for these, no need to have a PR every three days that updates them.
Also `src/leveldb` changes should go into the appropriate upstream repository.

2017-06-29 12:40 UTC, MeshCollider commented
Just saw #9544 hadn't finished the job, because that was merged then this just makes it all consistent.
Good point on the leveldb though

2017-06-29 22:32 UTC, MeshCollider commented
Removed changes to src/leveldb/

2017-06-29 22:43 UTC, sipa commented
The style guide says that braces must be on the next line for namespaces, classes, methods, and functions.

2017-06-30 01:48 UTC, MeshCollider commented
Almost all the existing namespaces have the brace on the same line, would you prefer if they were all changed in this PR too?

2017-06-30 01:57 UTC, sipa commented
I don't think there is a need for a massive change one way or another, but certainly not for a change in the wrong direction.

2017-07-01 03:30 UTC, MeshCollider commented
Refactored as per style guide, no extra effort to get it fixed really :)

2017-07-03 09:28 UTC, promag requested changes
Missing documentation fix for https://github.com/bitcoin/bitcoin/commit/f3f1e2e7d38005fa3edecb01469a18a6f7500ea6.

2017-07-04 00:00 UTC, MeshCollider commented
@promag What do you mean?

2017-07-04 09:02 UTC, promag requested changes
At the end I would keep two commits like:
 - Fix namespace brace style (includes documentation fix)
 - Improve end-of-namespace comment consistency

Other than these, ACK.

2017-07-04 09:02 UTC, promag commented on src/memusage.h
> +namespace memusage {
Remove change?

2017-07-04 09:29 UTC, MeshCollider commented
Decided to squash them all into one commit because its all refactoring, and the previous commits were already squashed. Thanks for pointing out that missed brace @promag

2017-11-17 15:13 UTC, fanquake commented
Going to close this for now. You could rebase, extend the changes and reopen just after the next major branch off, as that is usually the best time to merge commits that touch a lot of files.

2017-11-17 15:13 UTC, closed without merging