Add configuration files for a Docker-based development environment
bitcoin/bitcoin pull request #10903
Opened 2017-07-22 05:31 UTC by jamesob

This PR introduces a number of configuration files which facilitate use of a Docker environment for local development and bitcoind execution. I've found this method to be an easy way to quickly setup a local dev environment; the use of a container also allows us to prevent polluting the host system with Bitcoin-specific dependencies.

The base image that I reference in the Dockerfile is maintained by Docker [in an "official" image repository](https://hub.docker.com/_/python/). It's based on Debian 8 "Jessie" and comes with Python 3.6.2 for running the tests.

After obtaining the Docker dependencies (as described in `docs/build-docker.md`), building and testing bitcoin from scratch can be done in a single command:
```
docker-compose run bitcoind test
```

During the docker image build (`docker-compose build bitcoind`), system dependencies are installed per `docs/build-unix.md` (including all non-GUI optional dependencies) but Bitcoin itself isn't compiled. This is because `docker-compose` attaches the source tree to the container as a mounted volume after build, which allows changes we make to the source on the host machine to propagate immediately to a running container. The entrypoint script (`./bin/docker_entrypoint.sh`) is responsible for handling bitcoind compilation as well as providing the `test*` commands. Clang is installed and used as the default compiler.

You'll notice that a few files (`Dockerfile`, `bin/`, `docker-compose.yaml`) are introduced to the top-level of the directory structure. I wasn't eager to do this -- I started out in `contrib/`, but in order for `docker-compose` to mount the entire source tree, commands have to be executed from the project root.

This is a modest suggestion and I'm happy to help incorporate feedback.

2017-07-22 06:52 UTC, emanuelb requested changes
added comments about stuff that better to change in Dockerfile.

2017-07-22 06:52 UTC, emanuelb commented on Dockerfile
> +RUN wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
1. it better to use https link with --no-check-certificate option (until download.oracle.com have valid SSL cert)
2. it better to use -O parameter to specify filename of downloaded file (there was issues in filename auto-detection of wget in the past)
3. use environment variable for 'db-4.8.30.NC' string and use it instead below (can be updated easily in future)

2017-07-22 06:52 UTC, emanuelb commented on Dockerfile
> +RUN tar -xzvf db-4.8.30.NC.tar.gz -C $BDB_PREFIX
remove the 'db-4.8.30.NC.tar.gz' file after extract operation.

2017-07-22 06:52 UTC, emanuelb commented on Dockerfile
> +RUN mkdir -p $BDB_PREFIX
use && instead of multiple RUN commands to avoid unneeded layers.

2017-07-22 13:26 UTC, stevendlander commented on Dockerfile
> +RUN ls ${BDB_PREFIX}
Unnecessary `ls` on the BDB directory.

2017-07-22 13:30 UTC, stevendlander commented on Dockerfile
> +RUN apt-get install -y clang
This should also be rolled up with the above apt install block, with the comment above it.

```docker
RUN apt-get update && apt-get install -y \
    libboost-system-dev \
    ...
    miniupnpc \
    # Install clang for potential use over g++.
    clang
```

2017-07-22 16:32 UTC, stevendlander commented on doc/build-docker.md
> +The Docker development enviornment does not facilitate development of the
nit: `environment`

2017-07-22 16:58 UTC, jamesob commented
@emanuelb @stevendlander thanks for the feedback. I've incorporated that as well as a few changes to make running bitcoind itself more straightforward.

2017-07-23 23:12 UTC, greenaddress commented
I didn't review and for now neutral on the concept but why jessie and not stretch?

2017-07-23 23:14 UTC, greenaddress commented
Also rather than having lots of && which make it very unreadable why not using COPY for a bash script file and then RUN on it? the script would be reusable to setup dependency on Jessie/Stretch non docker too.

2017-07-23 23:34 UTC, promag commented
I understand why you want this but a `Dockerfile` in the root usually is used to build the service container. The built image doesn't even have bitcoind. Also, `docker-compose.yml` has 1 service only, with the intent to avoid calling docker with those parameters.

The usage here is for development, so I would rename `Dockerfile` to `Dockerfile.dev` (or something), remove `docker-compose.yml` (less dependencies) and update the instructions. 

However I dunno if this is something worth to maintain here, or something you could put in another repo.

I can review if this receives concept ACK.

2017-07-23 23:57 UTC, jamesob commented
Those are all good points. I think closing this PR and creating a personal repo is probably the best route.

Does anyone think it would be worth filing a separate PR to put the db-4 installation script into `contrib/` or elsewhere?

2017-07-23 23:57 UTC, closed without merging

2018-05-06 19:25 UTC, Sjors commented
@jamesob did you ever end up updating your local repo?

I created yet another Dockerfile: https://github.com/Sjors/docker-bitcoin-core

It borrows a lot of code from @NicolasDorier's [project](https://github.com/NicolasDorier/docker-bitcoin), but it builds from source. It lets you build any tag or commit (only tried it for the latest master though). Only support modern BDB. It also lets you attach.

I tend to agree that there are too many ways to do this to warrant an "official" Docker file, unless perhaps if they end being used to replace Gitian, or maybe for Travis.