Build: Fix Automake warnings when running autogen.sh
bitcoin/bitcoin pull request #11013
Opened 2017-08-09 02:36 UTC by eklitzke

This fixes some harmless (but annoying) automake warnings when invokes `autogen.sh`. The warnings I'm referring to are the ones printed at the very end of running `autogen.sh`, on my system they look like:

```
Makefile.am:12: warning: user variable 'GZIP_ENV' defined here ...
/usr/share/automake-1.15/am/distdir.am: ... overrides Automake variable 'GZIP_ENV' defined here
src/Makefile.am: installing 'build-aux/depcomp'
src/Makefile.am:497: warning: user target '.mm.o' defined here ...
/usr/share/automake-1.15/am/depend2.am: ... overrides Automake target '.mm.o' defined here
```

 I did some research on both of these, and here's what I found:
 * Automake has been setting `GZIP_ENV` since 1998. They set it to `--best`, we set it to `-9n`. I'm not sure if the `-n` is really necessary, but using the `override` directive suppresses the warning.
 * Automake has had a rule for `.mm.o` targets (used for Objective C++) built in since Automake 1.12.1, which appears to have been released in 2012. Trusty (used by Travis and Gitian) is on Automake 1.14.1

It looks like both of these rules were added by @theuni when he did the initial autotools conversion in 2013. These warnings are harmless, but there's no reason not to fix them. While researching these I accidentally stumbled across a few forum posts and GitHub comments from end users who thought the errors meant their Bitcoin build was broken, so that's another reason to fix them.

2017-08-09 04:56 UTC, practicalswift commented
Concept ACK - good stuff! 👍

2017-08-09 06:59 UTC, paveljanik commented
ACK 
https://github.com/bitcoin/bitcoin/pull/11013/commits/2ad24b73e0aca883960d3128f91364bbb933e865

Verbose build logs are the same here (gzip and mm.o warnings are removed).

2017-08-09 08:11 UTC, fanquake commented
This is the documentation for -n or --no-name:

When compressing, do not save the original file name and time stamp by default. (The original name is always saved if the name had to be truncated.) When decompressing, do not restore the original file name if present (remove only the gzip suffix from the compressed file name) and do not restore the original time stamp if present (copy it from the compressed file). This option is the default when decompressing.

So this might be required as part of the gitian build process, requested a review from theuni.

2017-08-13 17:53 UTC, promag commented
utACK 2ad24b7.

2017-08-16 22:42 UTC, theuni requested changes
- GZIP_ENV was indeed added for determinism, but gitian exports this as needed, so it's not really necessary. I'd rather just remove it.

- The mm.o rule was added to support XCode 4.2's ancient version of automake. That's irrelevant now, so it makes sense to remove that too.

All darwin targets are PIE by default, so we don't technically need the flags, but I'd be more comfortable if we hooked up the OBJCXXFLAGS in case future ones are added. This should do it:
```diff
diff --git a/src/Makefile.qt.include b/src/Makefile.qt.include
index e4b64c1..0767ee1 100644
--- a/src/Makefile.qt.include
+++ b/src/Makefile.qt.include
@@ -368,6 +368,7 @@ BITCOIN_QT_INCLUDES = -I$(builddir)/qt -I$(srcdir)/qt -I$(srcdir)/qt/forms \
 qt_libbitcoinqt_a_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES) $(BITCOIN_QT_INCLUDES) \
   $(QT_INCLUDES) $(QT_DBUS_INCLUDES) $(PROTOBUF_CFLAGS) $(QR_CFLAGS)
 qt_libbitcoinqt_a_CXXFLAGS = $(AM_CXXFLAGS) $(QT_PIE_FLAGS)
+qt_libbitcoinqt_a_OBJCXXFLAGS = $(AM_OBJCXXFLAGS) $(QT_PIE_FLAGS)
 
 qt_libbitcoinqt_a_SOURCES = $(BITCOIN_QT_CPP) $(BITCOIN_QT_H) $(QT_FORMS_UI) \
   $(QT_QRC) $(QT_QRC_LOCALE) $(QT_TS) $(PROTOBUF_PROTO) $(RES_ICONS) $(RES_IMAGES) $(RES_MOVIES)
```

2017-08-27 02:10 UTC, fanquake commented
@eklitzke Can you follow up on theuni's changes?

2017-09-20 17:36 UTC, laanwj commented
@eklitzke Ping

2017-10-21 04:27 UTC, fanquake commented
Replaced by #11541

2017-10-21 04:27 UTC, closed without merging