[Qt] Search TX: Add delay before filtering
bitcoin/bitcoin pull request #11015
Opened 2017-08-09 07:00 UTC by lclc

As discussed in https://github.com/bitcoin/bitcoin/issues/3141.

This adds a QTimer pause of 200ms before start to filter so it should be possible to filter big data sets easier.

2017-08-09 07:16 UTC, promag reviewed
Should the interval be configurable? At least it's duplicated so have a const variable?

2017-08-09 07:16 UTC, promag commented on src/qt/transactionview.cpp
> +    connect(amountWidget, SIGNAL(textChanged(QString)), this, SLOT(changedAmount()));
Connect to start `QTimer::start()` slot instead, and configure the interval above.

2017-08-09 07:16 UTC, promag commented on src/qt/transactionview.cpp
> +    connect(addressWidget, SIGNAL(textChanged(QString)), this, SLOT(changedPrefix()));
Connect to start `QTimer::start()` slot instead, and configure the interval above.

2017-08-09 07:16 UTC, promag commented on src/qt/transactionview.cpp
> +void TransactionView::changedPrefix()
Can be removed.

2017-08-09 07:16 UTC, promag commented on src/qt/transactionview.cpp
> +void TransactionView::changedAmount()
Can be removed.

2017-08-09 07:18 UTC, promag commented
Nit, reword commit and PR title to `qt: Add delay before filtering transactions`?

2017-08-09 07:30 UTC, jonasschnelli commented
Concept ACK

2017-08-09 09:00 UTC, lclc commented
Thanks a lot for the fast review and suggestions for improvement @promag. I've updated the commit accordingly.

> Should the interval be configurable?

I don't think many people want to change that. If we see 200ms is not optimal we can still change it later.
Adding this as a config flag option would probably mostly add code that nobody uses in the end - but if more people think it's a good idea I can implement it.

2017-08-09 09:02 UTC, sipa commented
Don't make things configurable if there is no advice for what to set it to.

2017-08-09 09:59 UTC, promag reviewed
Agree with @sipa. A variable is enough to add meaning to the duration.

2017-08-09 09:59 UTC, promag commented on src/qt/transactionview.h
> +    static const int inputFilterDelay = 200;
Move to `.cpp`?

2017-08-09 09:59 UTC, promag commented on src/qt/transactionview.h
> +    QTimer *inputDelayPrefix;
The convention is to prefix with `m_` in new code.

2017-08-09 10:45 UTC, lclc commented on src/qt/transactionview.h
> +    QTimer *inputDelayPrefix;
I also like the m_ convention but I don't see it in any of the other Qt code.
Is the plan to slowly change to m_ over time or maybe take the effort to change (part of) the full source code at ones? Two different styles in the same file is not so nice I think.

2017-08-09 15:41 UTC, promag commented on src/qt/transactionview.h
> +    QTimer *inputDelayPrefix;
@lclc unfortunately there's mixed styles all over the place. Last time that was discussed, that I know of, is to use the defined convention in new or "touched" code.

2017-08-09 16:31 UTC, lclc commented on src/qt/transactionview.h
> +    QTimer *inputDelayPrefix;
Ok, thanks. I'll update.

2017-08-09 19:08 UTC, lclc commented
Improved as suggested by @promag.

2017-08-09 21:18 UTC, benma reviewed
ACK 0587d2e36a0a64535e8d296fb97fcb7a258637fe

I tested that the issue existed and that this PR fixes it.

2017-08-09 21:18 UTC, benma commented on src/qt/transactionview.h
> +    QTimer *m_inputDelayPrefix;
please use snake_case as per developer notes.

2017-08-09 21:18 UTC, benma commented on src/qt/transactionview.h
> +    void changedPrefix();
can be moved to the private Q_SLOTS section. All the others can as well, mabye in a separate commit?

2017-08-10 07:52 UTC, jonasschnelli commented on src/qt/transactionview.h
> +    QTimer *m_inputDelayPrefix;
To also drop my opinion here (though I don't care): Use the scheme of the surrounding code to not confuse new developers. New classes or complete rewrites may be different.

2017-08-10 07:57 UTC, sipa commented on src/qt/transactionview.h
> +    QTimer *m_inputDelayPrefix;
From the developer notes:

> When writing patches, favor the new style over attempting to mimick the surrounding style, except for move-only commits.

2017-08-10 08:11 UTC, jonasschnelli commented on src/qt/transactionview.h
> +    QTimer *m_inputDelayPrefix;
Hmm.. I see. My advice is against the developer notes then. It just looked confusing to have two single instance variables with sneak case where the rest is without `m_` and camel case. But I guess we have to start somewhere to adopt the style rules.

2017-08-10 17:59 UTC, laanwj commented
Concept ACK, thanks!

> Don't make things configurable if there is no advice for what to set it to.

Indeed, just make a choice, there's no use in making this configurable. No one will bother and it will just add more things to test.

2017-08-10 18:58 UTC, lclc commented on src/qt/transactionview.h
> +    void changedPrefix();
I plan to look at Q_SLOTS in general in a separate PR. There are a few other cases in different files where some slots are public that wouldn't need to be.

2017-08-10 19:01 UTC, lclc commented
Thanks a lot for clarifying, review and testing @benma. I changed the commit according to the developer notes.

2017-08-10 19:34 UTC, benma commented on src/qt/transactionview.h
> +    void changedPrefix();
+1

2017-08-10 19:35 UTC, benma commented
ACK 6d073a2d1c85ecc523d13c5f47514daa5de4757c

2017-08-18 07:41 UTC, promag commented on src/qt/transactionview.h
> +    QTimer *m_input_delay_prefix;
There is no need to have these here..

2017-08-18 07:42 UTC, promag commented
utACK 6d073a2.

2017-08-18 10:02 UTC, jonasschnelli commented
I couldn't really test this (all the machines where to fast). The delay seems very short (with 200ms). Will the timer be reset when entering the next char <200ms (I think so otherwise this would not work)?.
Maybe @promag can do a test?

2017-08-18 10:26 UTC, promag commented
@jonasschnelli yes start() resets.

2017-08-19 00:26 UTC, promag requested changes
For reference https://wiki.qt.io/Delay_action_to_wait_for_user_interaction.

2017-08-19 00:26 UTC, promag commented on src/qt/transactionview.cpp
> +    static const int inputFilterDelay = 200;
Use snake case. Comment to indicate unit?

FWIW there is this [global constant](https://github.com/bitcoin/bitcoin/blame/master/src/qt/guiconstants.h#L9) cc @sipa.

2017-08-19 00:26 UTC, promag commented on src/qt/transactionview.cpp
> +    if(BitcoinUnits::parse(model->getOptionsModel()->getDisplayUnit(), amountWidget->text(), &amount_parsed))
Missing space after `if`. Move below `{` to this line.

2017-08-19 00:26 UTC, promag commented on src/qt/transactionview.h
> +    QTimer *m_input_delay_prefix;
Please remove.

2017-08-19 00:26 UTC, promag commented on src/qt/transactionview.h
> +    QTimer *m_input_delay_amount;
Same as above.

2017-08-19 00:26 UTC, promag commented on src/qt/transactionview.h
> +    void changedPrefix();
Agree, all is done in this PR context.

2017-08-19 00:26 UTC, promag commented on src/qt/transactionview.h
> +    void changedAmount();
Nit, I would sort the slots.

2017-08-19 00:26 UTC, promag commented on src/qt/transactionview.cpp
> +    m_input_delay_amount = new QTimer(this);
Nit, change to `QTimer* amount_typing_delay = new QTimer(this);`

2017-08-19 00:26 UTC, promag commented on src/qt/transactionview.cpp
> +    /* Delay before before filtering transactions in ms */
Comments is this file are `// ...`.

2017-09-07 15:50 UTC, jonasschnelli commented
@lclc, could you address @promag's points? I'd like to get this in soon.

2017-09-11 05:30 UTC, lclc commented
I'll do it on Tuesday night.

Am 07.09.2017 17:52 schrieb "Jonas Schnelli" <notifications@github.com>:

> @lclc <https://github.com/lclc>, could you address @promag
> <https://github.com/promag>'s points? I'd like to get this in soon.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/11015#issuecomment-327841890>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABwrESCkYZHmbXMwSNGUFJuiEzuXFc7Rks5sgBEigaJpZM4OxrEB>
> .
>

2017-09-12 17:40 UTC, lclc commented
Updated.

Thanks for the reviews @promag - this version is now quite a bit simpler and cleaner by now than the first one :)

2017-09-12 19:07 UTC, promag commented
utACK a82976d. Will test in a couple of hours.

2017-09-12 21:59 UTC, promag commented
Tested ACK a82976d.

2017-09-15 19:56 UTC, flack commented
If the motivation is to make filtering large data sets easier, why not apply the delay only when the data set is sufficiently large? For other cases, it just reduces responsiveness. Or is the size of the data set not known when the UI is constructed?

2017-09-15 20:23 UTC, promag commented
200ms is very reasonable. See https://ux.stackexchange.com/a/38545.

2017-09-18 03:31 UTC, jonasschnelli commented
Tested ACK a82976d96009680ab61bcea763f15c7594b9afb0

2017-09-18 03:31 UTC, jonasschnelli commented on src/qt/transactionview.cpp
> +    // Delay before before filtering transactions in ms
nit: comment (before before)

2017-09-18 08:54 UTC, lclc commented on src/qt/transactionview.cpp
> +    // Delay before before filtering transactions in ms
Thanks, fixed.

2017-09-26 12:32 UTC, promag commented
Tested ACK 7b137ac.

2017-09-26 21:59 UTC, merged