Fix a-vs-an typos
bitcoin/bitcoin pull request #12393
Opened 2018-02-09 09:10 UTC by practicalswift

Fix a-vs-an typos.

2018-02-09 12:28 UTC, promag reviewed
ACK.

2018-02-09 12:28 UTC, promag commented on src/script/ismine.h
> + * and return an ISMINE_NO immediately, as an invalid script should never be considered as "mine". This is needed as
Remove `an`?

2018-02-09 12:45 UTC, practicalswift commented on src/script/ismine.h
> + * and return an ISMINE_NO immediately, as an invalid script should never be considered as "mine". This is needed as
Thanks! Fixed!

2018-02-09 15:37 UTC, randolf commented
ACK for 11 out of 12 changes...

NACK for 1 change in src/reverselock.h because the original "An RAII-style" is actually correct since acronyms tend to be read out letter-by-letter and the word "An" flows more easily and correctly when reading out loud.

2018-02-09 15:40 UTC, randolf requested changes
ACK for 11 out of 12 changes...

NACK for 1 change in src/reverselock.h because the original "An RAII-style" is actually correct since acronyms tend to be read out letter-by-letter and the word "An" flows more easily and correctly when reading out loud.

2018-02-09 16:06 UTC, practicalswift commented
@randolf Good point about RAII. Fixed. Please re-review :-)

2018-02-09 16:29 UTC, randolf commented
@practicalswift I don't see the fix yet, but perhaps GitHub just needs some time to synchronize.  I'll check again later and approve once the fix appears.  Thanks for the quick turn-around.

2018-02-10 01:20 UTC, randolf commented
@practicalswift I just asked some other developers about this, and they suspect that you may need to "push" your changes so that they'll appear here.

2018-02-10 15:12 UTC, practicalswift commented
@randolf Oh, I forgot to push after changing. Thanks for letting me know! Please re-review :-)

2018-02-10 15:39 UTC, randolf approved these changes

2018-02-10 16:39 UTC, MarcoFalke commented
Travis fails with `FAIL: subtree directory was touched without subtree merge`

2018-02-11 09:49 UTC, practicalswift commented
Removed the change to `src/univalue/` since that one should be reported upstream instead.

Please re-review :-)

2018-02-12 03:05 UTC, randolf approved these changes

2018-02-12 03:17 UTC, luke-jr approved these changes
utACK

2018-02-12 09:51 UTC, merged