qa: Fix python TypeError in script.py
bitcoin/bitcoin pull request #12475
Opened 2018-02-18 00:11 UTC by MarcoFalke

`__repr__` returns string, so don't mix it with byte strings.

This fixes

```
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'

2018-02-18 17:44 UTC, conscott commented
ACK fa82cacf601acf7f92b51a6f870cb4f6bbfe92db

2018-02-19 02:57 UTC, fanquake requested changes
Is this comment above now out of date? "For Python3 compatibility add b before strings so testcases don't need to change"

2018-02-19 04:43 UTC, MarcoFalke commented
Removed comment

On Feb 18, 2018 21:57, "fanquake" <notifications@github.com> wrote:

> *@fanquake* requested changes on this pull request.
>
> Is this comment above now out of date? "For Python3 compatibility add b
> before strings so testcases don't need to change"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/12475#pullrequestreview-97432575>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGGmv1_0JF7fqKhjCNDeB7IQJdHF0R1Aks5tWOMzgaJpZM4SJg99>
> .
>

2018-02-19 05:14 UTC, fanquake commented
utACK fa41d68

2018-03-05 16:32 UTC, laanwj commented
utACK fa41d68a2

2018-03-05 16:34 UTC, merged