Increase signal-to-noise ratio in debug.log by adjusting log level when logging failed non-manual connect():s
bitcoin/bitcoin pull request #12569
Opened 2018-02-28 20:34 UTC by practicalswift

Increase signal-to-noise ratio in `debug.log` by adjusting log level when logging failed non-manual `connect()`:s.

Before this patch:

```
$ src/bitcoind -printtoconsole
…
2018-02-28 18:42:51 UpdateTip: new best=0000000000005448b10a219683d34b770a28044e1cc421032dea1a79ff548948 height=1286903 version=0x20000000 log2_work=69.791313 tx=17408546 date='2018-02-28 18:42:46' progress=1.000000 cache=0.0MiB(173txo)
2018-02-28T18:37:52Z connect() 10.11.21.34:18333 failed after select(): Connection refused (111)
2018-02-28 18:43:22 connect() to 10.11.43.14:18333 failed after select(): Network is unreachable (101)
2018-02-28 18:44:49 UpdateTip: new best=000000000000029a521ff2803e1441b09413b876accff5084a4cccf7747d798b height=1286904 version=0x20000000 log2_work=69.791345 tx=17408559 date='2018-02-28 18:44:51' progress=1.000000 cache=0.1MiB(502txo)
2018-02-28 18:46:54 connect() to [2001:0:9d38:78ff:1234:1234:1234:1234]:18333 failed: Network is unreachable (101)
2018-02-28 18:48:56 connect() to [2001:0:9d38:6aff:1234:1234:1234:1234]:18333 failed: Network is unreachable (101)
2018-02-28 18:49:11 UpdateTip: new best=000000000000000206b79eb235e5dd907b6369de0e5d764330bf40ec0d460311 height=1286905 version=0x20000000 log2_work=69.791377 tx=17408577 date='2018-02-28 18:49:12' progress=1.000000 cache=1.0MiB(5245txo)
```

After this patch:

```
$ src/bitcoind -printtoconsole
…
2018-02-28 18:42:51 UpdateTip: new best=0000000000005448b10a219683d34b770a28044e1cc421032dea1a79ff548948 height=1286903 version=0x20000000 log2_work=69.791313 tx=17408546 date='2018-02-28 18:42:46' progress=1.000000 cache=0.0MiB(173txo)
2018-02-28 18:44:49 UpdateTip: new best=000000000000029a521ff2803e1441b09413b876accff5084a4cccf7747d798b height=1286904 version=0x20000000 log2_work=69.791345 tx=17408559 date='2018-02-28 18:44:51' progress=1.000000 cache=0.1MiB(502txo)
2018-02-28 18:49:11 UpdateTip: new best=000000000000000206b79eb235e5dd907b6369de0e5d764330bf40ec0d460311 height=1286905 version=0x20000000 log2_work=69.791377 tx=17408577 date='2018-02-28 18:49:12' progress=1.000000 cache=1.0MiB(5245txo)
```

Please note that "manual `connect()`:s" (invoked via `-connect`, `-proxy` or `addnode`) are still reported as usual:

```
$ src/bitcoind -printtoconsole -connect=10.11.12.13
…
2018-02-28 18:31:13 connect() to 10.11.12.13:18333 failed after select(): Connection refused (111)

$ src/bitcoind -printtoconsole -proxy=10.11.12.13
…
2018-02-28 18:32:32 connect() to 10.11.12.13:9050 failed after select(): Connection refused (111)

$ src/bitcoind -printtoconsole &
$ src/bitcoin-cli addnode "10.11.12.13" onetry
…
2018-02-28 18:33:40 connect() to 10.11.12.13:18333 failed after select(): Connection refused (111)
```

2018-02-28 21:38 UTC, randolf commented
Just to confirm:  With a higher debug level set, all those "connect" errors can still be logged?

2018-02-28 21:42 UTC, practicalswift commented
@randolf Exactly :-)

2018-02-28 21:45 UTC, randolf approved these changes

2018-03-01 00:18 UTC, Empact commented on src/net.cpp
> +void CConnman::OpenNetworkConnection(const CAddress& addrConnect, bool fCountFailure, CSemaphoreGrant *grantOutbound, const char *pszDest, bool fOneShot, bool fFeeler, bool fManualConnection)
FYI the style guide prefers the prior style (despite the inconsistency here):
"Variable and namespace names are all lowercase, and may use `_` to separate words (snake_case)"

2018-03-01 00:22 UTC, Empact commented on src/netbase.cpp
> +            }
Maybe extract a `LogConnectFailure` method to DRY these two up?

2018-03-09 15:17 UTC, practicalswift commented
@Empact Thanks for reviewing. Updated in light of review. Please re-review :-)

2018-03-09 20:15 UTC, instagibbs commented on src/netbase.cpp
> +    if (!ConnectSocketDirectly(proxy.proxy, hSocket, nTimeout, true)) {
not totally clear to me this should be `true`?

2018-03-11 08:32 UTC, eklitzke reviewed
Concept ACK. Regarding argument forwarding, there's related code for `FatalError()` in #11857 that I think you could re-use here.

2018-03-11 08:32 UTC, eklitzke commented on src/netbase.cpp
> +void LogConnectFailure(const std::string& error_message, bool manual_connection) {
I know this is annoying, but can you use argument forwarding or make this variadic? That would avoid allocation when the message is not going to be logged.

2018-03-11 09:50 UTC, practicalswift commented
@eklitzke Good point! Updated. Please re-review :-)

2018-03-13 05:19 UTC, eklitzke commented
That change looks good, but one other thing occurred to me just now. I think we already have special logic for handling peers added using `addnode`, and that should definitely be treated as a "manual" connection case. Can you take a look at that?

2018-03-13 06:58 UTC, practicalswift commented
@eklitzke It already is:

```
$ src/bitcoind -printtoconsole &
$ src/bitcoin-cli addnode 127.0.0.1:1234 onetry
…
2018-02-28 18:33:40 connect() to 127.0.0.1:1234 failed after select(): Connection refused (111)
```

:-)

2018-03-17 00:21 UTC, sipa commented
utACK cba2800e8c4e73c2eddff76880b55d930c5010f6

2018-03-17 01:16 UTC, eklitzke commented
utACK cba2800e8c4e73c2eddff76880b55d930c5010f6

2018-03-28 01:02 UTC, minhhoang123 requested changes
Good

2018-03-28 02:25 UTC, eklitzke approved these changes

2018-03-28 02:38 UTC, practicalswift commented
@laanwj Would it be possible to get this PR tagged with a 0.17.0 milestone? :-)

2018-04-12 09:15 UTC, ajtowns commented
utACK  cba2800e8c4e73c2eddff76880b55d930c5010f6

2018-04-13 17:26 UTC, merged