Print timestamp strings in logs using ISO 8601 formatting
bitcoin/bitcoin pull request #12567
Opened 2018-02-28 15:57 UTC by practicalswift

Print timestamp strings in logs using ISO 8601 formatting:
* `Z` is the zone designator for the zero UTC offset.
* `T` is the delimiter used to separate date and time.

This makes it clear for the end-user that the date/time logged is specified in UTC and not in the local time zone.

Before this patch:

```
2018-02-28 12:34:56 New outbound peer connected: version: 70015, blocks=1286123, peer=0
```

After this patch:

```
2018-02-28T12:34:56Z New outbound peer connected: version: 70015, blocks=1286123, peer=0
```

2018-02-28 16:04 UTC, randolf requested changes
In ``"%Y-%m-%dT%H:%M:%S"`` it looks like the Timezone (%Z) might be missing.

Optional:  Also, consider using %T instead of %H%M%S if it's supported.

2018-02-28 16:05 UTC, randolf commented
If you want to use ISO formatting though, then perhaps get rid of the dashes and the colons while you're at it so that it looks like this?

``20180228T123456Z``

2018-02-28 18:41 UTC, practicalswift commented
@randolf The `Z` is added three lines down. Removing the dashes and colons them would reduce readability so I'd like to keep them.

2018-02-28 21:39 UTC, randolf commented
@practicalswift Ah, yes, I see it now.  Thanks.

2018-02-28 21:40 UTC, randolf approved these changes

2018-03-01 10:12 UTC, laanwj commented
Concept ACK.

When changing the log timestamp format you will need to update some of the testing infrastructure, though, such as `test/functional/combine_logs.py`. This combines logs from bitcoind with logs from the test framework itself, which then should also use the new format.

> Removing the dashes and colons them would reduce readability, so I'd like to keep them around.

The ISO formatting allows for them, right? I'd also vote for keeping them.

2018-03-01 10:33 UTC, practicalswift commented
@laanwj Thanks for reviewing!

I'll take a look at `combine_logs.py`.

Yes, `2018-02-28T12:34:56Z` (with dashes and colons) is valid according to ISO 8601 :-)

2018-03-05 17:50 UTC, laanwj commented
This needs mention in the release notes too; some people might be using scripts that parse the log output that rely on a specific format.

2018-03-06 05:58 UTC, randolf commented
@laanwj I agree.  Perhaps a custom log formatting option is in order for the long-run?  I could probably tackle this after this PR is closed.

2018-03-06 14:15 UTC, laanwj commented
@randolf Could be, though personally I'd prefer to not add any more configurability to the log format (there is already `-logtimestamps`, `-logtimemicros`). This is all more option combinations that need to be maintained. 

In my opinion switching to a standard format (ISO 8601) seems a valid one-time move to do in the next major release. If anything it makes parsing easier because there are existing libraries to parse these. Just needs to be mentioned.

2018-03-06 14:42 UTC, practicalswift commented
I agree with @laanwj here. I'm not sure more configurability is better in this case.

@laanwj Can I do something to make sure a note is added to the 0.17.0 release notes? Is there a file that I can edit now or what is the procedure? :-)

2018-03-06 14:47 UTC, laanwj commented
> @laanwj Can I do something to make sure a note is added to the 0.17.0 release notes? Is there a file that I can edit now or what is the procedure? :-)

Sure - standard procedure is to just add an item to `doc/release-notes.md`, under notable changes.

2018-03-06 14:48 UTC, practicalswift commented
@laanwj Excellent! I'll do that and adjust the `TIMESTAMP_PATTERN` in `test/functional/combine_logs.py`.

2018-03-06 15:20 UTC, practicalswift commented
Updated. Please review :-)

2018-03-06 15:25 UTC, laanwj commented
You didn't update the log setup in `test_framework.py`:
```
        # Format logs the same as bitcoind's debug.log with microprecision (so log files can be concatenated and sorted)
        formatter = logging.Formatter(fmt='%(asctime)s.%(msecs)03d000 %(name)s (%(levelname)s): %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
```

2018-03-06 15:32 UTC, practicalswift commented
@laanwj Oh, sorry about that. Now fixed. Please re-review :-)

2018-03-06 15:56 UTC, practicalswift commented
@laanwj Would it make sense to add the following patch to this PR in order to make the switch to ISO 8601 complete, or is that a subject for a follow-up PR?

```diff
diff --git a/src/init.cpp b/src/init.cpp
index 1cc5c5f..09702cd 100644
--- a/src/init.cpp
+++ b/src/init.cpp
@@ -1223,7 +1223,7 @@ bool AppInitMain()
     }

     if (!fLogTimestamps)
-        LogPrintf("Startup time: %s\n", DateTimeStrFormat("%Y-%m-%d %H:%M:%S", GetTime()));
+        LogPrintf("Startup time: %s\n", DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", GetTime()));
     LogPrintf("Default data directory %s\n", GetDefaultDataDir().string());
     LogPrintf("Using data directory %s\n", GetDataDir().string());
     LogPrintf("Using config file %s\n", GetConfigFile(gArgs.GetArg("-conf", BITCOIN_CONF_FILENAME)).string());
diff --git a/src/net.cpp b/src/net.cpp
index 2019146..c439768 100644
--- a/src/net.cpp
+++ b/src/net.cpp
@@ -2782,7 +2782,7 @@ void CNode::AskFor(const CInv& inv)
         nRequestTime = it->second;
     else
         nRequestTime = 0;
-    LogPrint(BCLog::NET, "askfor %s  %d (%s) peer=%d\n", inv.ToString(), nRequestTime, DateTimeStrFormat("%H:%M:%S", nRequestTime/1000000), id);
+    LogPrint(BCLog::NET, "askfor %s  %d (%s) peer=%d\n", inv.ToString(), nRequestTime, DateTimeStrFormat("%H:%M:%SZ", nRequestTime/1000000), id);

     // Make sure not to reuse time indexes to keep things in the same order
     int64_t nNow = GetTimeMicros() - 1000000;
diff --git a/src/qt/paymentserver.cpp b/src/qt/paymentserver.cpp
index bc69d4f..57075ee 100644
--- a/src/qt/paymentserver.cpp
+++ b/src/qt/paymentserver.cpp
@@ -770,7 +770,7 @@ bool PaymentServer::verifyExpired(const payments::PaymentDetails& requestDetails
 {
     bool fVerified = (requestDetails.has_expires() && (int64_t)requestDetails.expires() < GetTime());
     if (fVerified) {
-        const QString requestExpires = QString::fromStdString(DateTimeStrFormat("%Y-%m-%d %H:%M:%S", (int64_t)requestDetails.expires()));
+        const QString requestExpires = QString::fromStdString(DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", (int64_t)requestDetails.expires()));
         qWarning() << QString("PaymentServer::%1: Payment request expired \"%2\".")
             .arg(__func__)
             .arg(requestExpires);
diff --git a/src/test/util_tests.cpp b/src/test/util_tests.cpp
index 463bed5..c21cfde 100644
--- a/src/test/util_tests.cpp
+++ b/src/test/util_tests.cpp
@@ -98,6 +98,7 @@ BOOST_AUTO_TEST_CASE(util_DateTimeStrFormat)
     BOOST_CHECK_EQUAL(DateTimeStrFormat("%Y-%m-%d %H:%M:%S", 0), "1970-01-01 00:00:00");
     BOOST_CHECK_EQUAL(DateTimeStrFormat("%Y-%m-%d %H:%M:%S", 0x7FFFFFFF), "2038-01-19 03:14:07");
     BOOST_CHECK_EQUAL(DateTimeStrFormat("%Y-%m-%d %H:%M:%S", 1317425777), "2011-09-30 23:36:17");
+    BOOST_CHECK_EQUAL(DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", 1317425777), "2011-09-30T23:36:17Z");
     BOOST_CHECK_EQUAL(DateTimeStrFormat("%Y-%m-%d %H:%M", 1317425777), "2011-09-30 23:36");
     BOOST_CHECK_EQUAL(DateTimeStrFormat("%a, %d %b %Y %H:%M:%S +0000", 1317425777), "Fri, 30 Sep 2011 23:36:17 +0000");
 }
diff --git a/src/util.cpp b/src/util.cpp
index 76aa1c0..71333c3 100644
--- a/src/util.cpp
+++ b/src/util.cpp
@@ -320,7 +320,7 @@ static std::string LogTimestampStr(const std::string &str, std::atomic_bool *fSt
         strStamped += "Z";
         int64_t mocktime = GetMockTime();
         if (mocktime) {
-            strStamped += " (mocktime: " + DateTimeStrFormat("%Y-%m-%d %H:%M:%S", mocktime) + ")";
+            strStamped += " (mocktime: " + DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", mocktime) + ")";
         }
         strStamped += ' ' + str;
     } else
diff --git a/src/validation.cpp b/src/validation.cpp
index d2438b0..0c7e378 100644
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -1267,13 +1267,13 @@ void static InvalidChainFound(CBlockIndex* pindexNew)

     LogPrintf("%s: invalid block=%s  height=%d  log2_work=%.8g  date=%s\n", __func__,
       pindexNew->GetBlockHash().ToString(), pindexNew->nHeight,
-      log(pindexNew->nChainWork.getdouble())/log(2.0), DateTimeStrFormat("%Y-%m-%d %H:%M:%S",
+      log(pindexNew->nChainWork.getdouble())/log(2.0), DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ",
       pindexNew->GetBlockTime()));
     CBlockIndex *tip = chainActive.Tip();
     assert (tip);
     LogPrintf("%s:  current best=%s  height=%d  log2_work=%.8g  date=%s\n", __func__,
       tip->GetBlockHash().ToString(), chainActive.Height(), log(tip->nChainWork.getdouble())/log(2.0),
-      DateTimeStrFormat("%Y-%m-%d %H:%M:%S", tip->GetBlockTime()));
+      DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", tip->GetBlockTime()));
     CheckForkWarningConditions();
 }

@@ -2179,7 +2179,7 @@ void static UpdateTip(const CBlockIndex *pindexNew, const CChainParams& chainPar
     LogPrintf("%s: new best=%s height=%d version=0x%08x log2_work=%.8g tx=%lu date='%s' progress=%f cache=%.1fMiB(%utxo)", __func__,
       pindexNew->GetBlockHash().ToString(), pindexNew->nHeight, pindexNew->nVersion,
       log(pindexNew->nChainWork.getdouble())/log(2.0), (unsigned long)pindexNew->nChainTx,
-      DateTimeStrFormat("%Y-%m-%d %H:%M:%S", pindexNew->GetBlockTime()),
+      DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", pindexNew->GetBlockTime()),
       GuessVerificationProgress(chainParams.TxData(), pindexNew), pcoinsTip->DynamicMemoryUsage() * (1.0 / (1<<20)), pcoinsTip->GetCacheSize());
     if (!warningMessages.empty())
         LogPrintf(" warning='%s'", boost::algorithm::join(warningMessages, ", "));
@@ -3804,7 +3804,7 @@ bool LoadChainTip(const CChainParams& chainparams)

     LogPrintf("Loaded best chain: hashBestChain=%s height=%d date=%s progress=%f\n",
         chainActive.Tip()->GetBlockHash().ToString(), chainActive.Height(),
-        DateTimeStrFormat("%Y-%m-%d %H:%M:%S", chainActive.Tip()->GetBlockTime()),
+        DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", chainActive.Tip()->GetBlockTime()),
         GuessVerificationProgress(chainparams.TxData(), chainActive.Tip()));
     return true;
 }
```

2018-03-06 15:56 UTC, laanwj commented
utACK https://github.com/bitcoin/bitcoin/pull/12567/commits/518820b1f8490eca2af82eebfc6e110857194229

2018-03-06 16:01 UTC, laanwj commented
@practicalswift sure - let's do that at once - though if we want to enforce a single format throughout the codebase, why not factor out the `DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", timespec) to a FormatISO8601` function?
Note that we have a function like that in `src/wallet/rpcdump.cpp`:
```c++
std::string static EncodeDumpTime(int64_t nTime) {
    return DateTimeStrFormat("%Y-%m-%dT%H:%M:%SZ", nTime);
}
```
But let's rename and move it to `src/utiltime` where it belongs.

2018-03-06 21:40 UTC, practicalswift commented
Updated. Please re-review :-)

2018-03-06 22:30 UTC, laanwj commented on src/utiltime.cpp
> +    return DateTimeStrFormat("%Y-%m-%d", nTime);
Do ISO 8601 dates require a timezone as well?

2018-03-06 22:32 UTC, practicalswift commented on src/utiltime.cpp
> +    return DateTimeStrFormat("%Y-%m-%d", nTime);
Nope they don't :-)

2018-03-06 22:47 UTC, laanwj commented
utACK ed802867d

2018-03-07 04:31 UTC, randolf commented
@laanwj I agree with your recommendation to standardize on the ISO format as I feel that it's the logical choice for use in log files, plus your point about keeping code maintenance simpler provides excellent justification in this case.

2018-03-07 04:34 UTC, randolf approved these changes
Standardizing on one set of date/time/date+time subroutines is excellent, and also makes it easier for future code to obtain consistently-formatted dates and times with less effort.

2018-03-09 14:02 UTC, practicalswift commented
Rebased!

2018-03-09 17:50 UTC, sipa commented
utACK a7324bd799591546c2ae069f29cb82a66d427769

2018-03-10 16:16 UTC, merged