travis: Generate a trap for signed arithmetic overflows (enable -ftrapv)
bitcoin/bitcoin pull request #12686
Opened 2018-03-14 10:42 UTC by practicalswift

By generating a trap for signed overflow on addition, subtraction, multiplication operations in the Travis testing we are more likely to identify problematic code prior to merging it.

2018-03-14 14:36 UTC, fanquake commented
```
The command "test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh" exited with 0.
$ mkdir build && cd build

The command "mkdir build && cd build" exited with 0.
$ ../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
configure: error: unrecognized option: `-ftrapv''
Try `../configure --help' for more information
cat: config.log: No such file or directory

The command "../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)" exited with 1.
$ make distdir VERSION=$HOST
make: *** No rule to make target `distdir'.  Stop.
```

2018-03-14 22:36 UTC, eklitzke commented
This is cool, utACK fa7d9895ef3ec37ffeb6ca51333cf20bc8622e73 .

GCC 4.8 also supports -fsanitize=address and -fsanitize=thread (and newer GCC versions have a whole plethora or really interesting options). What do you think about using those options in Travis as well?

2018-03-14 22:58 UTC, eklitzke requested changes
There's a shell quoting issue with how travis is running this.

2018-03-14 23:07 UTC, eklitzke commented
Here's an idea for another way to do this: https://github.com/eklitzke/bitcoin/commit/635e378383c41c8ef3ac03fca1755001c947b7f7 . The idea is to add -ftrapv when `--enable-debug` is used, and then use that option on all of the Travis jobs. `--enable-debug` also sets `-DDEBUG_LOCKORDER`.

What do you think of this approach?

2018-03-14 23:47 UTC, sipa commented
@eklitzke There was some work earlier to get the code to run cleanly under sanitizers (see #9743 and #9512), though I don't think we ever made it perfectly runnable without warnings.

2018-03-15 06:36 UTC, eklitzke commented
BTW the right way to fix the quoting issue in Travis is to use a bash array. It looks like Travis doesn't support these properly. If you still wanted to use this approach instead of modifying configure.ac as in my example two options:
 * `IFS` hacks
 * Create yet-another-Travis-variable and pass it down to the configure call

2018-03-15 07:20 UTC, practicalswift commented
@eklitzke Thanks for reviewing. I've now cherry-picked your commit (which is the better solution) into this PR.

Please re-review :-)

2018-03-15 08:06 UTC, eklitzke commented
It looks like this doesn't work for the MingW builds, I got timeouts in my travis runs that match the ones you just cherry-picked: https://travis-ci.org/eklitzke/bitcoin/builds/353587968 . Let's disable the option for those two builders.

I added some -fsanitize support to the configure script in #12692, which is a good start since it will make using those flags easier even if the code isn't currently clean under asan/tsan.

2018-03-15 15:16 UTC, practicalswift commented
@eklitzke To keep the changes as small as possible I've now enabled `-ftrapv` only for one of the Travis jobs (job: "Qt4 & system libs"). Makes sense?

Please re-review :-)

2018-03-16 02:09 UTC, fanquake commented
@practicalswift I don't think you've cherry-picked correctly, looks like you just swapped out the changes in your commit with @eklitzke's ?

2018-03-16 05:16 UTC, eklitzke commented
This looks right to me, utACK e23dfbb01df044e6d0dc65f6b9333e6547202fa7.

2018-03-18 17:46 UTC, practicalswift commented
@fanquake The cherry-pick was a previous version. e23dfbb01df044e6d0dc65f6b9333e6547202fa7 is correct. Please review :-)

2018-03-22 03:26 UTC, eklitzke commented
FYI this is going to conflict with #12695 . Should be an easy merge conflict though.

2018-04-02 13:12 UTC, laanwj commented
@theuni Can you take a look?

2018-04-14 13:09 UTC, practicalswift commented
Rebased! Please re-review :-)

2018-04-23 09:10 UTC, practicalswift commented
Judging from the Travis testing it seems that the trap is trigged indicating that we have a signed overflow taking place when running the tests. Let's find out where!

2018-04-23 18:05 UTC, theuni commented on .travis.yml
> -    - HOST=x86_64-unknown-linux-gnu PACKAGES="python3-zmq qtbase5-dev qttools5-dev-tools protobuf-compiler libdbus-1-dev libharfbuzz-dev" DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1 ALLOW_HOST_PACKAGES=1" RU
Removing ```DEBUG=1``` here should cause depends to no longer build as debug.

+1 on using --enable-debug, though.

2018-05-14 14:02 UTC, practicalswift commented
Now using `AX_CHECK_COMPILE_FLAG` for checking `-trapv` availability when compiled under `--enable-debug`:

```
$ ./configure --enable-debug
…
checking whether C++ compiler accepts -ftrapv... yes
…
  CXXFLAGS      =  -Og -g3 -ftrapv  -Wstack-protector -fstack-protector-all   -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter
…
```

@theuni, please re-review :-)

2018-05-15 22:51 UTC, theuni commented
Please add the CXXFLAG_WERROR argument so that we'll see false-positives. utACK otherwise.

2018-05-16 07:28 UTC, practicalswift commented
@TheBlueMatt Added the `CXXFLAG_WERROR` argument. Please re-review :-)

2018-05-29 22:06 UTC, practicalswift commented
Rebased!

2018-06-12 22:33 UTC, theuni commented
utACK 8bf481fe2e99e6a0e16a6127d7df826dd4bfa2e9

2018-06-24 18:36 UTC, practicalswift commented
Rebased!

2018-06-24 18:41 UTC, MarcoFalke commented
ACK 98d842cb52 (that the rebase was done correctly, didn't look at anything else)

2018-06-27 00:54 UTC, sipa commented
utACK 98d842cb52e69ea1f9961d908385c896e37fb877

2018-06-27 00:56 UTC, merged