wip: Use new Qt5 connect syntax
bitcoin/bitcoin pull request #13529
Opened 2018-06-24 15:19 UTC by promag

2018-06-24 15:35 UTC, MarcoFalke commented
Concept ACK. The new syntax has compile time checks, removing the need to debug impossible to find syntax errors during run time.

2018-06-24 15:40 UTC, laanwj commented
Concept ACK (because of @MarcoFalke's reasoning)

2018-06-24 16:11 UTC, promag commented
Thanks, I'll complete it then.

2018-06-24 17:15 UTC, promag commented
@MarcoFalke @laanwj see new lint script, it can be improved later with other checks related to Qt.

2018-06-26 19:36 UTC, jonasschnelli commented
Concept ACK

2018-07-01 06:44 UTC, fanquake commented
Concept ACK

2018-07-05 17:10 UTC, laanwj commented
> see new lint script, it can be improved later with other checks related to Qt

LGTM

2018-07-10 15:11 UTC, laanwj commented
> - found a connection to a private slot that doesn't work with the new syntax.
> - connection to/from overloaded slot/signal is ugly before qt 5.7 (see https://stackoverflow.com/a/16795664)

does this mean it's better to postpone this to a (far) future in which we can drop pre-5.7 support?

2018-07-10 15:18 UTC, promag commented
> does this mean it's better to postpone this to a (far) future in which we can drop pre-5.7 support?

Not really, until now just a couple of these where I have to cast the slot.

2018-07-10 15:38 UTC, laanwj commented
oh if it can be worked around and is just a couple of cases, I agree it's not a big issue, just need to be careful to test all behavior afterwards.

2018-07-22 00:47 UTC, promag commented
@fanquake ready to review.

2018-07-22 00:49 UTC, promag commented
> oh if it can be worked around and is just a couple of cases

@laanwj at the moment I count 25 cases.

2018-08-01 15:39 UTC, Sjors requested changes
Concept ACK. I'm a big fan of compile time checks. The new syntax also helps readability because you no longer have to guess the class name (e.g. `QTableView`) from the the variable name (e.g. `ui->tableView`).

Found a few problems with  ba34538 on macOS 10.13.6 though (Qt 5.11.1 and 5.9.6):
* application hides when I navigate to a new tab (e.g. from Overview to Transactions); maybe some event needs to be not propagated?
* all console window commands cause a segfault, so much for compile time checks :-(

Other than that I tested most `connect` instances and they all seem to work.

I ran into a bunch of existing issues, none of which are end of the world, but they're a distraction when reviewing if you don't know about them.

2018-08-01 15:39 UTC, Sjors commented on src/qt/overviewpage.cpp
> +    connect(ui->labelWalletStatus, &QPushButton::clicked, this, &OverviewPage::handleOutOfSyncWarningClicks);
Duplicate line

2018-08-01 15:39 UTC, Sjors commented on src/qt/transactionview.cpp
> +    connect(this, &TransactionView::doubleClicked, this, &TransactionView::showDetails);
Note for other reviewers: this was moved from `src/qt/walletview.cpp`

2018-08-19 22:59 UTC, promag commented on src/qt/overviewpage.cpp
> +    connect(ui->labelWalletStatus, &QPushButton::clicked, this, &OverviewPage::handleOutOfSyncWarningClicks);
Removed.

2018-08-20 00:15 UTC, promag commented
> all console window commands cause a segfault, so much for compile time checks :-(

@Sjors fixed in de93a0682.

2018-08-20 00:34 UTC, promag commented
> all console window commands cause a segfault, so much for compile time checks :-(

@Sjors fixed in 5261ab0.

> application hides when I navigate to a new tab (e.g. from Overview to Transactions); maybe some event needs to be not propagated?

Fixed in ac8661e.

2018-08-20 16:32 UTC, Sjors commented
Can confirm these issues are fixed in ac8661e.

2018-08-20 17:08 UTC, promag commented
Squashed and rebased. Thanks @Sjors!

2018-08-21 09:31 UTC, merged