add -debuglogsize=<n> option
bitcoin/bitcoin pull request #14169
Opened 2018-09-08 11:01 UTC by SuckShit

Add an option to limit maximum size of log files in MBytes, which renames itself to originname-datetimestamp.ext and creates a new log file if size reaches <n>. Default is 0, which means that the log file's size is unlimited.

2018-09-08 13:38 UTC, gmaxwell commented
this is pretty un-unixy, we already support external HUP signalled log rotation which is the standard thing.

2018-09-08 15:17 UTC, ghost reviewed
nice find

2018-09-08 15:18 UTC, ghost requested changes
change

2018-09-09 22:59 UTC, practicalswift commented on src/logging.cpp
> +                    if (i != std::string::npos && i + 1 < originname.size()) {
```
warning: result of comparison of constant 18446744073709551615 with expression of type 'uint32_t' (aka 'unsigned int') is always true [-Wtautological-constant-out-of-range-compare]
```

2018-09-09 23:00 UTC, practicalswift commented on src/logging.cpp
> +                    uint32_t i = originname.rfind(".");
```
warning: 'rfind' called with a string literal consisting of a single character; consider using the more effective overload accepting a character [performance-faster-string-find]
```

2018-09-22 19:08 UTC, practicalswift commented on src/logging.cpp
> +            //limit the max size of log
```
2018-09-22 21:06:39 cpplint(pr=14169): src/logging.cpp:229:  Should have a space between // and comment  [whitespace/comments] [4]
```

2018-09-23 07:47 UTC, practicalswift commented on src/logging.cpp
> +                        }
```
2018-09-22 21:06:39 cpplint(pr=14169): src/logging.cpp:270:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
```

2018-09-25 19:29 UTC, practicalswift commented on src/logging.cpp
> +                uint32_t sz = fs::file_size(m_file_path);
```
2018-09-25 19:59:57 clang(pr=14169): logging.cpp:231:31: warning: implicit conversion loses integer precision: 'boost::uintmax_t' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
```

2018-09-25 19:30 UTC, practicalswift commented on src/logging.cpp
> +                    uint32_t i = originname.rfind(".");
```
2018-09-25 19:59:57 clang(pr=14169): logging.cpp:236:45: warning: implicit conversion loses integer precision: 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size_type' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [
```

2019-02-04 20:23 UTC, practicalswift commented
Is this PR abandoned? Should it be closed? :-)

2019-02-04 21:54 UTC, MarcoFalke commented
Closing for now. Let me know when you want to work on this again, so I can reopen.

2019-02-04 21:54 UTC, closed without merging