Update univalue subtree
bitcoin/bitcoin pull request #14164
Opened 2018-09-07 12:23 UTC by MarcoFalke

This removes the deprecated `std::pair` wrappers from univalue, so that they are not accidentally re-introduced in our code base.

2018-09-07 13:02 UTC, fanquake commented
utACK https://github.com/bitcoin/bitcoin/pull/14164/commits/faad55a9a24601aac47b5e3bc44827ddb41d8f93

Ran `make check` and tested the subtree merge.
```
merge 14164
[pull/14164/local-merge a83101646] Merge #14164: Update univalue subtree
 Date: Fri Sep 7 20:55:42 2018 +0800
#14164 Update univalue subtree into master
* faad55a9a Update univalue subtree (MarcoFalke) (pull/14164/head)
* dc287c98f Squashed 'src/univalue/' changes from 51d3ab34ba..7890db99d6 (MarcoFalke)

Dropping you on a shell so you can try building/testing the merged source.
Run 'git diff HEAD~' to show the changes being merged.
Type 'exit' when done.
bash-3.2$ git fetch https://github.com/bitcoin-core/univalue.git
warning: no common commits
remote: Counting objects: 604, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 604 (delta 0), reused 1 (delta 0), pack-reused 602
Receiving objects: 100% (604/604), 125.21 KiB | 265.00 KiB/s, done.
Resolving deltas: 100% (332/332), done.
From https://github.com/bitcoin-core/univalue
 * branch                HEAD       -> FETCH_HEAD
bash-3.2$ ./test/lint/git-subtree-check.sh src/univalue
src/univalue in HEAD currently refers to tree e73765406fc0a0fb4796504ea08a2e05cfea8bc0
src/univalue in HEAD was last updated in commit dc287c98f8b33576f3c71db02a232106ef0e57d9 (tree e73765406fc0a0fb4796504ea08a2e05cfea8bc0)
src/univalue in HEAD was last updated to upstream commit 7890db99d693572d27ade3e14268bd7236134529 (tree e73765406fc0a0fb4796504ea08a2e05cfea8bc0)
GOOD
```

2018-09-07 13:51 UTC, jnewbery commented
tACK faad55a9a24601aac47b5e3bc44827ddb41d8f93

2018-09-09 22:53 UTC, promag commented
utACK faad55a.

2018-09-09 22:59 UTC, luke-jr requested changes
NACK, upstream is 88967f658663654a67f1cda93ca6f99de1f7c91f

Referenced 7890db99d693572d27ade3e14268bd7236134529 does not exist upstream

2018-09-09 23:30 UTC, luke-jr commented
Upstream is jgarzik/univalue

bitcoin-core/univalue should not exist. There is no rationale for deviating from upstream, and if anything, we should be working toward removing the subtree entirely and just using the system install.

2018-09-10 01:40 UTC, ken2812221 commented
utACK faad55a.

@luke-jr At least, it's a fork for now.

2018-09-10 03:45 UTC, luke-jr commented
There's no reason for it, so NACK making it so...

2018-09-10 14:30 UTC, jnewbery commented
Upstream has been bitcoin-core/univalue since at least https://github.com/bitcoin/bitcoin/pull/8807.

This PR doesn't change what the upstream branch is, so discussion of that seems off-topic for me.

ACK faad55a9a24601aac47b5e3bc44827ddb41d8f93

2018-09-10 15:02 UTC, merged