0.15.2 release notes
bitcoin/bitcoin pull request #14262
Opened 2018-09-18 16:45 UTC by Sjors

Semi manual, so please sanity check.

2018-09-18 19:04 UTC, hebasto requested changes

2018-09-18 19:04 UTC, hebasto commented on doc/release-notes.md
> +- #11647 `305f768` Limit AuthServiceProxyWrapper.__getattr__ wrapping (Russell Yanofsky)
Do you mean:
```
- #11647 `2eea279` Make AuthServiceProxy.\_batch method usable (Russell Yanofsky)
- #11647 `305f768` Limit AuthServiceProxyWrapper.\_\_getattr\_\_ wrapping (Russell Yanofsky)
```

2018-09-18 19:10 UTC, Sjors commented on doc/release-notes.md
> +- #11647 `305f768` Limit AuthServiceProxyWrapper.__getattr__ wrapping (Russell Yanofsky)
Thanks, added escape characters.

2018-09-18 19:11 UTC, Sjors commented
Removed translation credits, because they weren't updated for this release.

2018-09-18 21:41 UTC, laanwj commented
I think it'd make sense to combine this with #14263 and a bump-version commit

2018-09-18 23:29 UTC, fanquake commented on doc/release-notes.md
> +- #11662 `a69cc07` Sanity-check script sizes in bitcoin-tx
#11662 is a backport of #11554 from TheBlueMatt

2018-09-18 23:29 UTC, fanquake commented on doc/release-notes.md
> +- #12032 `cb7ef31` Make boost::multi_index comparators const
#12032 is a backport of #11847 from sdaftuar

2018-09-19 09:13 UTC, Sjors commented
* updated pull request numbers to reference originals rather than the backport. This is especially useful for #11647 which was one backport PR multiple PR's
* added missing authors @fanquake pointed out
* added RPC and Tests category
* added a version update commit
* moved manpage commit from #14263

2018-09-19 09:15 UTC, Sjors commented
From the manpage PR:
> I used the generator script from master and fixed the version number after running the script.
>
> Notable changes:
> * script verification threads changed from 6 to 4
> * maximum BIP141 block weight default changed from 3000000 to 3996000
> * blockmaxsize deprecated

2018-09-19 11:49 UTC, laanwj commented
ACK 391b2cf0250de44afcaeaaf977e3ef8ec5c4d55f

Thank you for doing this!

2018-09-19 11:50 UTC, merged