qt: Add Wallet and Window menus
bitcoin/bitcoin pull request #14573
Opened 2018-10-25 15:05 UTC by promag

This PR changes/moves menus/actions as follow:
 - add top level menu Window
 - rename lop level menu Settings to Wallet
 - move Sending/Receiving address to Window->Address Book
 - move Help->Debug window to Window
 - move Settings->Options to Window (not visible on macOS)

<img width="593" alt="screenshot 2018-10-25 at 15 58 53" src="https://user-images.githubusercontent.com/3534524/47509883-ea144800-d86e-11e8-9ec9-96e459df9530.png">

This removes the access to address book from the File menu "spotlight".

This also prepares for the multi wallet support.

As a follow up it may make sense to unify Sending/Receiving dialogs into "Address Book" dialog.

2018-10-27 14:20 UTC, ken2812221 reviewed
Concept ACK

2018-10-28 14:37 UTC, hebasto commented
Concept ACK.
Could move "Backup Wallet..." from File menu to Wallet menu?

From [Apple's Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/):

> Provide a Window menu even if your app has only one window. Include the Minimize and Zoom menu items so people using Full Keyboard Access can invoke these functions using their keyboard.

2018-10-31 16:19 UTC, promag commented
Removed the changes to the "Settings" menu.

2018-11-12 14:47 UTC, laanwj commented
I don't know what the conventions around this are, nowadays, but Concept ACK.

2018-11-12 14:49 UTC, MeshCollider commented
Concept ACK

2018-11-13 08:34 UTC, promag commented
Thanks @jonasschnelli, I'll see if others also toggle.

I have to test in windows.

2018-11-14 15:34 UTC, promag commented
@jonasschnelli on macos, if the active window is minimized then "Minimize" action is disabled. And "Zoom" action toggles between maximized and normal.

Also, some software add the main window to this menu, and I think we could too.

2018-11-19 14:19 UTC, Sjors commented
@hebasto wrote:

> Could move "Backup Wallet..." from File menu to Wallet menu?

Why? Loading, saving and backing up the wallet seem like document / File operations.

Moving message signing and verification from File to Window would make more sense to me.

Even more clear IMO, but haven't thought very deeply about it yet, is to have a _Wallet_ top level menu. In that case I'd be more in favour of adding Backup into that, as well as sign/verify, Sending/Receiving address. The Window menu would be used for Minimize, Debug Window.

I would also be fine with dropping the "Address Book" level and just having direct menu items for Sending and Receiving addresses.


Definitely out of scope, but I would still like to see each wallet represented as a window (rather than the little dropdown we have now). However I wouldn't want closing a window to cause unloading a wallet, so it's not obvious how this would work.

2018-11-22 21:32 UTC, hebasto commented
IMO, it would be better to avoid using native widgets ([Native Widgets vs Alien Widgets](https://doc.qt.io/qt-5.9/qwidget.html#native-widgets-vs-alien-widgets)) and related methods (`QWidget::windowHandle()`) and objects (`QWindow`).

@jonasschnelli 
> I think the "minimize" entry should toggle to "maximise" once minimized or at least maximises when selecting "minimize" in already minimized state.

@promag 
> on macos, if the active window is minimized then "Minimize" action is disabled. And "Zoom" action toggles between maximized and normal.

On macOS, if the active window is minimized the both "Minimize" and "Zoom" actions should be disabled. That is not the case for 3f779b3b99b674b7beecc9a30fa37bda1d722387.

2018-11-22 22:01 UTC, hebasto requested changes

2018-11-22 22:01 UTC, hebasto commented on src/qt/bitcoingui.cpp
> +        if (windowHandle()->windowState() == Qt::WindowMaximized) {
The same:
`if (isMaximized()) {`

2018-12-11 00:09 UTC, promag commented on src/qt/bitcoingui.cpp
> +        minimize_action->setEnabled(windowHandle()->windowState() != Qt::WindowMinimized);
Does not apply now since it's using `QWindow` now.

2018-12-11 00:09 UTC, promag commented on src/qt/bitcoingui.cpp
> +        if (windowHandle()->windowState() == Qt::WindowMaximized) {
Same as above.

2018-12-11 00:11 UTC, promag commented
Updated after feedback, thank you! Also updated screenshot. Windows/linux feedback would be awesome.

2018-12-11 00:32 UTC, promag commented
Pushed a commit to remove ellipsis from the sending/receiving addresses menu actions. Please see rationale in https://stackoverflow.com/a/637708.

2018-12-11 11:31 UTC, Sjors commented
tACK 6c72f91
A few nits, but don't let that stop anyone from merging:
*  you could amove Sign & Verify Message to Window (they do need ellipses)
* I don't find the Zoom item very useful, but don't mind it either
* when  `./configure --disable-wallet` or `disablewallet=1` you could still show Information, Console, Network Traffic and Peers in the Window menu. There may be some accessibility advantage to that.

2018-12-11 11:39 UTC, promag commented
> * you could move Sign & Verify Message to Window (they do need ellipses)

I'll leave that for later after we decide about top level menu "Wallet".

> * I don't find the Zoom item very useful, but don't mind it either (I'm just not a Bitcoin Core Window Maximalist)

Minimize and Zoom operate on the focus window, which can be the main window, address book dialogs, debug window..

> * when  `./configure --disable-wallet` or `disablewallet=1` you could still show Information, Console, Network Traffic and Peers in the Window menu.

I'll update with this suggestion, thanks @Sjors.

2018-12-11 17:01 UTC, Sjors commented
tACK 9ea38d0

```
git range-diff `git merge-base --all HEAD 6c72f91`...6c72f91 HEAD~3...HEAD
```

<img width="629" alt="schermafbeelding 2018-12-11 om 17 39 04" src="https://user-images.githubusercontent.com/10217/49816643-9dc58e80-fd6e-11e8-919d-fa451cf1ebe0.png">

2018-12-13 18:04 UTC, promag commented
@ken2812221 do you think you have the time to test this?

2018-12-14 01:20 UTC, MeshCollider commented
Tested ACK https://github.com/bitcoin/bitcoin/pull/14573/commits/9ea38d022281713e7f79a219b37651ac5648d695 on windows 10

I'm a little confused about the "Main Window" option, isn't the menu part of the main window implying that it is already focused? Also perhaps "Restore" should toggle between "Maximise" & "Restore"?

![image](https://user-images.githubusercontent.com/3211283/49977319-c8039000-ffaa-11e8-98fd-440a6c3db6f6.png)

2018-12-14 01:43 UTC, promag commented
@MeshCollider thanks! 

This was inspired on macos since it has a menu bar per application, not per window. Forgot that in windows it has menu bar in each window..

So next changes will be:
 - first section are actions on the current window (focused window on macos)
 - then comes the main windows — we only allow 1 main window for now — and this is used to bring it to front (I'll remove in windows, maybe linux too?)
 - then comes some dialogs — address book for now
 - then comes the debug dialogs

2018-12-15 10:11 UTC, Sjors commented
Rather than explicitly handling this per OS, does QT have any way to abstract that?

2018-12-15 13:15 UTC, promag commented
Not that I'm aware of.

2018-12-16 06:14 UTC, merged

2018-12-17 00:40 UTC, MarcoFalke commented
This does not compile because the addAction function was only introduced in Qt 5.6.

2018-12-17 04:10 UTC, Empact commented
An example of the failure: https://travis-ci.org/bitcoin/bitcoin/jobs/468706526

2019-04-23 20:05 UTC, molxyz commented
Hello, I also have a question on that button `Main Window` on windows bitcoin. If it has no purpose please remove that button before the official release to avoid confusions for windows users.

Thank you.

Please remove this button: 

![image](https://user-images.githubusercontent.com/21127776/56612154-99916380-65e1-11e9-8bac-3664b8a308b3.png)

2019-04-23 20:39 UTC, promag commented
@molxyz from the above https://github.com/bitcoin/bitcoin/pull/14573#issuecomment-447184073

> * then comes the main windows — we only allow 1 main window for now — and this is used to bring it to front (I'll remove in windows, maybe linux too?)

Sorry for forgetting about this, but at this stage I'm afraid it won't be removed for 0.18.

2019-04-23 20:44 UTC, molxyz commented
@promag Hi, I'll be happy to run tests for RC5.  Thanks.