Update `rpcbind` doc to match the manpage closes #9272
bitcoin/bitcoin pull request #14740
Opened 2018-11-16 22:37 UTC by sp4ke

The `rpcbind` documentation on the example file should match the Manpage. Even more they have opposite meanings. 

This should close #9272

2018-11-17 02:44 UTC, fanquake commented
Please fix the trailing whitespace on the lines you've modified.

2018-11-17 17:13 UTC, MarcoFalke commented
Unfortunately this file isn't really maintained. Couldn't we remove the help texts and refer everyone to the manpages/`bitcoind -help`?

2018-11-21 10:23 UTC, laanwj commented
I vaguely remember we had a script at some point that generated a sample `bitcoin.conf` from the option help. No idea though. Didn't even know this file was shipped.

2018-11-25 02:09 UTC, sp4ke commented
I tried looking for the script and could not find it. I am willing to make a new script to generate this file, is it ok to do it in python ? 

 Also there some sections in the sample conf with more details which are not in the Man, maybe they should moved the Man ?

On November 21, 2018 11:27:06 AM GMT+01:00, "Wladimir J. van der Laan" <notifications@github.com> wrote:
>BTW this will change with #14532
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bitcoin/bitcoin/pull/14740#issuecomment-440612921

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

2019-02-13 23:09 UTC, laanwj commented
@luke-jr can you please check whether this matches the changes you did in  #14532

2019-02-22 17:55 UTC, luke-jr requested changes

2019-02-22 17:55 UTC, luke-jr commented on share/examples/bitcoin.conf
> +# been specified, 0.0.0.0 and :: i.e., all addresses)
Default is only ever localhost now.

2019-03-02 10:10 UTC, fanquake commented
@sp4ke Are you able to follow up here?

2019-04-05 12:05 UTC, sp4ke commented
@fanquake sorry missed the notifications. I think the best would be to generate the doc from the manpage as previously stated. I will make a PR if I have sometime. It would be great if someone could share previous work done on this task so I can pick it up

2019-08-19 09:14 UTC, closed without merging