travis: Run thread sanitizer
bitcoin/bitcoin pull request #14764
Opened 2018-11-19 20:59 UTC by MarcoFalke

Currently fails in `((IsAligned(p, page_size_))) != (0)" (0x0, 0x0)`. Any help to fix it or work around for now would be appreciated:

```
Running tests: arith_uint256_tests from test/arith_uint256_tests.cpp
FATAL: ThreadSanitizer CHECK failed: /build/llvm-toolchain-6.0-QjOn7h/llvm-toolchain-6.0-6.0/projects/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_allocator_secondary.h:242 "((IsAligned(p, page_size_))) != (0)" (0x0, 0x0)
    #0 __tsan::TsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) <null> (test_bitcoin+0x10970d)
    #1 __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) <null> (test_bitcoin+0x127745)
    #2 __tsan::user_free(__tsan::ThreadState*, unsigned long, void*, bool) <null> (test_bitcoin+0xf33ec)
    #3 operator delete(void*) <null> (test_bitcoin+0x135507)
    #4 __gnu_cxx::new_allocator<char>::deallocate(char*, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/ext/new_allocator.h:125:2 (test_bitcoin+0x38d88)
    #5 std::allocator_traits<std::allocator<char> >::deallocate(std::allocator<char>&, char*, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/alloc_traits.h:462 (test_bitcoin+0x38d88)
    #6 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/basic_string.h:226 (test_bitcoin+0x38d88)
    #7 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose() /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/basic_string.h:221 (test_bitcoin+0x38d88)
    #8 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/basic_string.h:647 (test_bitcoin+0x38d88)
    #9 boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long) /usr/include/boost/test/tree/test_unit.hpp:249 (test_bitcoin+0x38d88)
    #10 __cxx_global_var_init.86 /home/travis/build/MarcoFalke/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/src/test/arith_uint256_tests.cpp:223 (test_bitcoin+0x38d88)
    #11 _GLOBAL__sub_I_arith_uint256_tests.cpp /home/travis/build/MarcoFalke/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/src/test/arith_uint256_tests.cpp (test_bitcoin+0x38d88)
    #12 __libc_csu_init <null> (test_bitcoin+0xbfcd7c)
    #13 __libc_start_main <null> (libc.so.6+0x21b27)
    #14 _start <null> (test_bitcoin+0x977d9)
Makefile:10944: recipe for target 'test/addrman_tests.cpp.test' failed
make[3]: *** [test/addrman_tests.cpp.test] Error 1

2018-11-19 21:35 UTC, sipa commented
This looks related: https://groups.google.com/forum/#!topic/thread-sanitizer/nmhRglhlohI

2018-11-20 12:35 UTC, practicalswift commented
Strong concept ACK

We really should test under all sanitizers in Travis – thanks for taking a step in that direction! :-)

2018-11-21 15:31 UTC, laanwj commented
utACK

2018-11-21 22:22 UTC, practicalswift requested changes
Excellent work @MarcoFalke!

utACK modulo suggested changes

Would be really nice to also have the functional tests running under TSan :-)

2018-11-22 16:49 UTC, MarcoFalke commented on .travis/test_03_before_install.sh
> +PATH=$PATH:/usr/lib/llvm-*/bin/
If there is only one folder that matches the wildcard, it should be properly expanded?

However, I just went and reverted that hunk.

2018-11-22 16:50 UTC, MarcoFalke commented on .travis.yml
> +        RUN_FUNCTIONAL_TESTS=false
They also need to be identified, which is the tricky part and imo better be suited for another pull request. (See my WIP in the suppressions file)

2018-11-22 16:56 UTC, MarcoFalke commented on .travis/test_04_install.sh
>  export UBSAN_OPTIONS="suppressions=${TRAVIS_BUILD_DIR}/contrib/sanitizers-ubsan.suppressions:print_stacktrace=1:halt_on_error=1"
Thanks, done.

2018-11-22 22:59 UTC, practicalswift commented on .travis/test_03_before_install.sh
> +PATH=$PATH:/usr/lib/llvm-*/bin/
@MarcoFalke No, the preceding `$PATH:` part prevents expansion:

```
$ mkdir testing
$ ls -d testin*
testing
$ TESTING=foo/:testin*
$ echo $TESTING
foo/:testin*
$ TESTING=testin*
$ echo $TESTING
testing
```

:-)

2018-11-23 14:40 UTC, merged