qt: Don't use the wallet name as map key
bitcoin/bitcoin pull request #14784
Opened 2018-11-22 13:17 UTC by promag

This a small refactor that doesn't change behavior. This is also necessary if in the future we allow renaming wallets.

2018-11-23 06:16 UTC, practicalswift requested changes

2018-11-23 06:16 UTC, practicalswift commented on src/qt/walletframe.h
> +    bool setCurrentWallet(WalletModel* walletModel);
Make sure parameter names match between declaration and definition :-)

2018-11-23 06:16 UTC, practicalswift commented on src/qt/walletframe.h
> +    bool removeWallet(WalletModel* walletModel);
Same here :-)

2018-11-23 09:07 UTC, laanwj commented
Concept ACK.

Small nit for clarity's sake: would make sense to word the PR title and commit as "use WalletModel pointer as map key" instead of what is *not* used, this tells reviewers more.

2018-11-23 12:06 UTC, promag commented
@laanwj sure, actually the commit was already along that.

@practicalswift done.

2018-11-24 18:01 UTC, hebasto commented
Concept ACK.

2018-11-25 05:44 UTC, jonasschnelli commented
I'm not entirely convince that holding raw pointers in a list is an improvement.

2019-01-02 13:19 UTC, laanwj commented
> @jonasschnelli what are your concerns?

I think the concern, versus using another kind of id, is that when using a pointer an inconsistency between the different data structures will cause crashes / use after free.

2019-01-02 20:03 UTC, ryanofsky approved these changes
utACK 492156b4b908ae1aa99b947a2efb314295d70749. This change looks like an improvement to me. Both pointers and strings should be unique but it seems easier to screw up string formatting and comparison than pointer equality checking.

In theory if there were use-after-free bugs we didn't know about, string comparisons could allow the code to limp along further without crashing, but I don't see where this could happen here because the pointers seem to be used for map lookups without getting dereferenced. Maybe you could replace `WalletModel*` with `intptr_t` to officially prevent dereferencing, though I think the `WalletModel*` is more obvious and easy to understand.

2019-01-03 07:12 UTC, laanwj commented
So is there no other suitable unique identifier except the pointer?

I ask this because a remote RPC client would have to do with only the name too, right?

2019-01-03 07:30 UTC, laanwj commented
> This is also necessary if in the future we allow renaming wallets.

I guess there's something to be said, then, for not ever changing that identifier while the wallet is loaded to avoid confusing remote clients, even if, say, the on-disk name or location changes.

2019-01-03 08:20 UTC, promag commented
@laanwj my point is if there is a rename the WalletModel is the same. I'm not saying anything regarding RPC :)

2019-01-03 08:30 UTC, laanwj commented
No, you don't say anything about RPC, but that the identifier should *probably* be constant while a wallet is loaded. Or does RPC use a different identifier for wallets than the GUI does?

2019-01-03 13:52 UTC, promag commented
The public unique identifier is the wallet name but here `WalletModel*` is used as the internal identifier in the GUI.

Maybe I shouldn't bring up "wallet rename".. I just think using the `WalletModel*` around is more convenient than looking up model by wallet name.

2019-01-04 12:19 UTC, promag commented
Rebased and also use `WalletModel*` in console window.

2019-01-04 14:55 UTC, laanwj commented
travis fail:
```
qt/libbitcoinqt.a(qt_libbitcoinqt_a-rpcconsole.o): In function `RPCConsole::on_lineEdit_returnPressed()':
/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/src/qt/rpcconsole.cpp:928: undefined reference to `WalletModel::getWalletName() const'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-rpcconsole.o): In function `RPCConsole::on_lineEdit_returnPressed()':
/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/src/qt/rpcconsole.cpp:928: undefined reference to `WalletModel::getWalletName() const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

2019-01-04 16:15 UTC, promag commented
Thanks @laanwj, fixed now.

2019-01-04 16:34 UTC, ryanofsky approved these changes
utACK 91b0c5b09616bb8c5ef8107efb432ce4c7c9a383. Changes since last review: rebase, adding new rpc console commit, and adding copyright year updates to earlier commits.

Not a big deal, but I think rpc console commit 91b0c5b09616bb8c5ef8107efb432ce4c7c9a383 goes a little too far in passing WalletModel to parse/execute functions which really only need a wallet name to pass along to the RPC engine, and not a full WalletModel instance. It might make this code slightly more difficult to separate and test.

2019-01-04 17:09 UTC, promag commented
@ryanofsky I had like that but RPC console already has `ENABLE_WALLET` macro to conditionally build the wallet endpoint. I think that a future refactor is to build the endpoint outside and inject it instead of passing the wallet.

2019-01-05 15:20 UTC, merged