qt: Remove hidden columns in coin control dialog
bitcoin/bitcoin pull request #14828
Opened 2018-11-28 12:26 UTC by promag

Instead of having hidden columns, store the data in specific roles.

Overlaps with #14817, fixes #11811.

2018-11-28 12:32 UTC, promag commented
Ah @laanwj already suggested this approach in https://github.com/bitcoin/bitcoin/issues/11811#issuecomment-349645182

2018-11-28 14:30 UTC, hebasto commented
Concept ACK.

2018-11-28 14:34 UTC, hebasto commented on src/qt/coincontroldialog.cpp
> +    contextMenuItem->setIcon(COLUMN_CHECKBOX, platformStyle->SingleColorIcon(":/i cons/lock_closed"));
What does this extra space mean?

2018-11-28 14:40 UTC, promag commented on src/qt/coincontroldialog.cpp
> +    contextMenuItem->setIcon(COLUMN_CHECKBOX, platformStyle->SingleColorIcon(":/i cons/lock_closed"));
Ops, ty.

2018-11-28 19:20 UTC, hebasto commented
There are some concerns about 4cd9a3a772807df825c27c410410c3ea96b59371 commit.

[QTreeView::uniformRowHeights](https://doc.qt.io/qt-5.9/qtreeview.html#uniformRowHeights-prop):
> This property should only be set to true if it is _guaranteed_ that all items in the view has the same height. This enables the view to do _some optimizations_.

1. IMO, it is not a good idea to mix a bugfix commit with an optimization commit in one PR (see [Pull Request Philosophy](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#pull-request-philosophy)).
2. There is no obvious need for such optimization.
3. How can 'the same height' condition be guaranteed now and then?
4. How can I test this optimization and measure the effect of it?

Could this optimization commit be moved out of this PR's scope?

2018-11-28 20:32 UTC, promag commented
@hebasto removed commit.

2018-11-29 07:24 UTC, hebasto requested changes

2018-11-29 07:34 UTC, hebasto commented
tACK 06cc0412da8fc3d031e804e7df0ae5b9686663b0 after [nit](https://github.com/bitcoin/bitcoin/pull/14828#discussion_r237375437)

2018-11-29 17:17 UTC, hebasto commented
re- tACK 1c28feb7d026bc18304149d96f81888059d52670

2018-12-04 08:19 UTC, jonasschnelli commented
Tested ACK 1c28feb7d026bc18304149d96f81888059d52670

2018-12-04 08:21 UTC, merged