rpc: Document default values for optional arguments
bitcoin/bitcoin pull request #14877
Opened 2018-12-05 22:00 UTC by MarcoFalke

2018-12-06 15:15 UTC, practicalswift requested changes

2018-12-06 15:15 UTC, practicalswift commented on src/rpc/rawtransaction.cpp
> +                                    {"sequence", RPCArg::Type::NUM, /* opt */ true, /* default_val */ "depends on the value of the 'replacable' and 'locktime' arguments", "The sequence number"},
Should be "replaceable" :-)

2018-12-06 15:15 UTC, practicalswift commented on src/rpc/rawtransaction.cpp
> +                                    {"sequence", RPCArg::Type::NUM, /* opt */ true, /* default_val */ "depends on the value of the 'replacable' and 'locktime' arguments", "The sequence number"},
Same here – should be "replaceable" :-)

2018-12-06 15:15 UTC, practicalswift commented on src/rpc/rawtransaction.cpp
> +                    {"iswitness", RPCArg::Type::BOOL, /* opt */ true, /* default_val */ "depends on heuritic tests", "Whether the transaction hex is a serialized witness transaction\n"
Should be "heuristic" :-)

2018-12-06 18:38 UTC, MarcoFalke commented
Thanks @practicalswift. Fixed my language

2018-12-09 23:09 UTC, jonasschnelli commented on src/rpc/mining.cpp
> +                    {"threshold", RPCArg::Type::NUM, /* opt */ true, /* default_val */ "0.95", "The proportion of transactions in a given feerate range that must have been\n"
what about using a stringprint of the `threshold` variable?

2018-12-09 23:14 UTC, jonasschnelli commented
utACK fa0c24c96e9937f666dcdd83d12145720c7b0329
Somehow I would be in favour of putting brackets around descriptive values (`(null)` instead of `null` and `(fallback to nodeid)` instead of `fallback to nodeid`) to avoid confusion between real default values and behavioural description.

2018-12-10 00:33 UTC, kristapsk commented
ACK fa0c24c96e9937f666dcdd83d12145720c7b0329

2018-12-10 17:48 UTC, ryanofsky approved these changes
ACK fa0c24c96e9937f666dcdd83d12145720c7b0329. I checked help output using the hack from https://github.com/bitcoin/bitcoin/pull/14726#pullrequestreview-175423309

This is a nice documentation change. If you wanted to follow up with more improvements I have some suggestions below:

- The fallback descriptions like "`fallback to wallet's default`" are vague and could be described in more detail.
- I don't think saying `(default=null)` or `(default=omitted)` is ever helpful. Just because of the way we check arguments, omitting an argument is always equivalent to passing `null`. And `(default=omitted)` is just a tautology. The point of the default documentation should be to say what an RPC call will do when  an argument is `null` or omitted. I actually think it would be better to drop the all the `(default=null)` and `(default=omitted)` strings if they can't be replaced with something more constructive, to avoid creating a bad precedent for future changes.

2018-12-10 17:48 UTC, ryanofsky commented on src/rpc/net.cpp
> +                    {"absolute", RPCArg::Type::BOOL, /* opt */ true, /* default_val */ "false", "If set, the bantime must be an absolute timestamp in seconds since epoch (Jan 1 1970 GMT)"},
/If set/If true/ might be more accurate

2018-12-10 17:58 UTC, kristapsk commented
> I don't think saying (default=null) or (default=omitted) is ever helpful. (...) I actually think it would be better to drop the all the (default=null) and (default=omitted) strings if they can't be replaced with something more constructive, to avoid creating a bad precedent for future changes.

If there is "default=" string outputted for each optional argument, functional test could be made that checks that people don't forget to document optional argument defaults for a new RPCs.

2018-12-10 18:41 UTC, kristapsk commented
Oh, yes, short list of a few exceptions probably is better idea.

2018-12-10 18:56 UTC, MarcoFalke commented
I have changes piled up locally to enforce that it is either a required arg or a default value is provided at compile time.

2018-12-10 19:05 UTC, merged

2018-12-10 20:52 UTC, ryanofsky commented
@MarcoFalke what do you want to do with all the `(default=null)` / `(default=omitted)` cruft? Do you want to address it in a future PR or maybe mark this one up for grabs so someone else can fill in useful default values?

2018-12-10 20:57 UTC, MarcoFalke commented
@ryanofsky Your suggestion is a one-line change after #14918, so either you leave feedback there or create a pull request after #14918 is merged.