doc: Update minimum required Qt
bitcoin/bitcoin pull request #14909
Opened 2018-12-10 06:58 UTC by fanquake

After #14725 the minimum required version of Qt is 5.2.

2018-12-10 08:06 UTC, hebasto requested changes
Concept ACK.

2018-12-10 08:06 UTC, hebasto commented on doc/dependencies.md
> +| FreeType | [2.7.1](https://download.savannah.gnu.org/releases/freetype) |  | No |  |  |
```
| FreeType | [2.7.1](https://download.savannah.gnu.org/releases/freetype) |  | No |  | [No](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/qt.mk#L33) |
```

And a similar change for `zlib`?

2018-12-10 16:34 UTC, MarcoFalke commented
ACK b7bee6af76e076e619b4ce5f165e81c6b4c52b2d

2018-12-12 12:45 UTC, laanwj commented
ACK https://github.com/bitcoin/bitcoin/pull/14909/commits/b7bee6af76e076e619b4ce5f165e81c6b4c52b2d

2018-12-12 12:51 UTC, merged