Install icon & .desktop file to XDG data
bitcoin/bitcoin pull request #15068
Opened 2018-12-31 06:20 UTC by luke-jr

With #13809 (packaging split off), we lost the `.desktop` and `.protocol` files.

This PR restores them, and puts them in their proper places as part of `make install`. (Systems without XDG can be configured `--without-xdg` to avoid this, and the macOS/Windows gitian descriptors are updated to use it.)

Note that:

* `bitcoin128.svg` needs to be named such because (for some reason) `bitcoin128` has become the de facto standard XDG icon name for the generic Bitcoin icon.
* `org.bitcoin.bitcoin-qt.desktop` is required to match `QAPP_ORG_DOMAIN`, which we have set to `"bitcoin.org"` for some reason. (Changing that is out of scope for this PR)

2018-12-31 10:17 UTC, MarcoFalke commented
Build fails with 
```
make[1]: *** No rule to make target 'src/qt/res/src/bitcoin128.svg', needed by 'all-am'.  Stop.

2018-12-31 11:50 UTC, hebasto commented
Could the `Comment` field in the `.desktop` file be updated with more languages?

2018-12-31 18:56 UTC, sharidz313 approved these changes

2018-12-31 21:07 UTC, luke-jr commented
@MarcoFalke Why? It's part of the git branch...

2018-12-31 21:29 UTC, sharidz313 approved these changes

2018-12-31 21:29 UTC, sharidz313 approved these changes

2018-12-31 21:32 UTC, sharidz313 approved these changes

2019-01-01 04:02 UTC, sharidz313 approved these changes

2019-01-01 04:02 UTC, sharidz313 commented on Makefile.am
> -BITCOIN_SVG = src/qt/res/src/bitcoin128.svg
Wow

2019-01-02 14:01 UTC, laanwj commented
Concept ACK, this the better way to do it IMO than installing it with the packaging.

2019-01-03 00:35 UTC, luke-jr commented
@hebasto After this PR, I don't see why not.

2019-01-03 07:33 UTC, hebasto commented
Concept ACK.

2019-01-08 14:33 UTC, laanwj commented
Regarding the build system issue, it looks like the icon is not part of `make dist`? Likely it needs to be added to another makefile variable.

2019-01-08 22:56 UTC, jonasschnelli commented
Concept ACK

> bitcoin128.svg needs to be named such because (for some reason) bitcoin128 has become the de facto standard XDG icon name for the generic Bitcoin icon

Do we want to set the standard Bitcoin icon? IMO Bitcoin Core is a specific application and not sure if that icon should be the default "Bitcoin Icon".

2019-01-08 23:19 UTC, luke-jr commented
There we go, Travis is happy now. Shall I squash?

2019-01-08 23:30 UTC, luke-jr commented
@jonasschnelli Bitcoin Core doesn't have its own icon at this time - we've always used the generic Bitcoin icon. When/if it does, then the PR adding it can change to use that instead...

2019-01-09 22:23 UTC, hebasto commented
The file name `org.bitcoin.bitcoin-qt.desktop` does not follow [Desktop Entry Specification](https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#file-naming):

> The name of the desktop entry should follow the "reverse DNS" convention: it should start with a reversed DNS domain name controlled by the author of the application, in lower case. The domain name should be followed by the name of the application, which is conventionally written with words run together and initial capital letters (CamelCase). For example, if the owner of `example.org` writes "Foo Viewer", they might choose the name `org.example.FooViewer`, resulting in a file named org.example.FooViewer.desktop.

> Well-known names containing the dash are allowed but not recommended, because the dash is not allowed in some related uses of reversed DNS names, such as D-Bus object paths and interface names, and Flatpak app IDs. If the author's domain name contains a dash, replacing it with an underscore is recommended: this cannot cause ambiguity, because underscores are not allowed in DNS domain names.

2019-01-09 23:00 UTC, hebasto requested changes

2019-01-10 02:44 UTC, luke-jr commented on share/qt/org.bitcoin.bitcoin-qt.desktop.in
> +Exec=bitcoin-qt %u
Why not? We expect URIs.

2019-01-10 02:45 UTC, luke-jr commented on share/qt/org.bitcoin.bitcoin-qt.desktop.in
> +[Desktop Entry]
This file predates the PR. It's just being restored at this time.

2019-01-10 02:47 UTC, luke-jr commented
@hebasto 
>* `org.bitcoin.bitcoin-qt.desktop` is required to match `QAPP_ORG_DOMAIN`, which we have set to `"bitcoin.org"` for some reason. (Changing that is out of scope for this PR)

2019-01-16 16:25 UTC, laanwj commented
> org.bitcoin.bitcoin-qt.desktop is required to match QAPP_ORG_DOMAIN, which we have set to "bitcoin.org" for some reason.

I think what he means is the second part, suggesting replacing `-` with `_`

2019-02-11 15:24 UTC, luke-jr commented
Ok, renamed it

2019-08-15 20:36 UTC, A6GibKm commented
Consider adding a appdata as in 
https://github.com/MarcoFalke/flathub/blob/f3d313f7991f6fec14f7ddc2c0fec19973f69814/org.bitcoincore.bitcoin-qt.appdata.xml
This should be installed to `{~/.local,/usr/local}/share/metainfo/bitcoin.appdata.xml` (or to `/usr/share...` but `/usr/local` should be prefered to `/usr`)

2020-08-04 07:27 UTC, hebasto commented
The alternative approach is https://github.com/bitcoin-core/gui/pull/38 that does not require `make install`, and works with downloaded official binaries.

2020-08-20 16:08 UTC, luke-jr commented
Rebased

2020-08-20 16:11 UTC, A6GibKm commented
Sorry about that, here is the working [link](https://github.com/flathub/org.bitcoincore.bitcoin-qt/blob/master/org.bitcoincore.bitcoin-qt.metainfo.xml). Which I just realized needs the 0.20.1 release.

2020-08-20 21:59 UTC, luke-jr commented
Which XDG standard defines this?

2020-08-20 22:20 UTC, A6GibKm commented
[This one.](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html)

2020-09-13 10:32 UTC, A6GibKm commented
- The Desktop file fails `desktop-file-validate`

```
$ desktop-file-validate org.bitcoin.bitcoin_qt.desktop.in
org.bitcoin.bitcoin_qt.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
org.bitcoin.bitcoin_qt.desktop: hint: value "Office;Finance;P2P;Network;Qt;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
```

- Consider renaming to org.bitcoincore.bitcoin-qt to match the already existing flatpak at https://github.com/flathub/org.bitcoincore.bitcoin-qt.

2022-03-22 09:00 UTC, MarcoFalke commented
This has been needing rebase for about 2 years, so I am closing for now. Can be reopened any time, just let us know when.

2022-03-22 09:00 UTC, closed without merging