Doc: Update release notes for master through to 2019-01-01
bitcoin/bitcoin pull request #15081
Opened 2019-01-02 20:51 UTC by harding

This adds release notes for the changes listed by `git log 11e1ac3...fb52d0684 --merges`, picking up where #14688 left off in my attempt to update the release notes every month or so (reducing the amount of work that needs to be done near release time).  I've excluded changes backported to the 0.17 branch (whether they've been released yet or not).

2019-01-03 00:23 UTC, fanquake requested changes

2019-01-03 00:58 UTC, harding commented on doc/release-notes.md
> +  ("app nap") during initial block chain download, when catching up from
I'm happy to change this, but is this the repository's policy or just your preference?  In previous (but admittedly dated) discussions I recall about this topic, the use of "block chain" (two words) was preferred.  E.g., #1910, #5242, and #6666

2019-01-03 01:01 UTC, fanquake commented on doc/release-notes.md
> +  ("app nap") during initial block chain download, when catching up from
@harding I'm not really fussed either way, was more for consistency with the rest of file. All other uses in here are `blockchain`.

2019-01-03 01:10 UTC, harding commented on doc/release-notes.md
> +- A new Window menu is added alongside the existing File, Settings, and
"is added" appears to be [grammatically correct](https://ell.stackexchange.com/questions/17132/difference-between-is-added-and-was-added) and is used 28 times in the current source code per `git grep`.  But, if you insist, I'm happy to change it (I prefer it over alternatives for its brevity).

2019-01-03 01:22 UTC, harding commented on doc/release-notes.md
> +  configuration.  If you need to expose RPC in order to use a tool
Why?  We don't typically require the use of an article before the name of a protocol, e.g. "If you need to expose {HTTP, SMTP, IMAP, SSL, bittorrent, ...} in order to use..."

2019-01-03 01:49 UTC, fanquake commented
Thanks, utACK f3d7d75. Not fussed about the other changes.

2019-01-03 08:58 UTC, fanquake approved these changes
Thanks, utACK f3d7d75. Not fussed about the other changes.

2019-01-03 09:00 UTC, laanwj commented
Thanks !!!

ACK f3d7d75e4e80bcd2c6058babb732c9c6cc7522c6

2019-01-03 09:24 UTC, merged

2019-01-05 13:19 UTC, MarcoFalke commented
> I've excluded changes backported to the 0.17 branch (whether they've been released yet or not).

Are they mentioned in the release notes on that branch?

2019-01-05 14:16 UTC, harding commented
@MarcoFalke I didn't check.  However, I don't believe any of the detached release notes I integrated applied to anything that had been backported to 0.17 so far, so no information should've been lost.  (I did not check pre-0.17 branches.)

The list of noteworthy changes for a typical maintenance release are much smaller than those for a major release, so I don't think the non-master branches would benefit much from periodic release notes updates (but, if you disagree, I'm happy to start opening PRs for that).

If there's anything I can do better, please let me know (or let me know if these updates are annoying and I'll stop).

2019-01-05 14:21 UTC, MarcoFalke commented
Oh no, they are very helpful. Usually we had no release notes at all for the whole rc cycle.

What I meant to say is that sometimes release notes get added to the master branch, but not the backport.

E.g. https://github.com/bitcoin/bitcoin/pull/14941/files#diff-c3924c30088c7adb0477128540f35c11R1
and https://github.com/bitcoin/bitcoin/pull/15002/files

So, it would be a pity if the notes get lost due to an oversight.

2019-01-05 14:48 UTC, harding commented
@MarcoFalke Ah.  So far I haven't removed anything from the notes for master because of a backport.  If I do remove anything, I'll be sure that it's documented at least on the current stable branch.

Somewhat related, I was wondering if it'd be useful to tag each item in the release note with the PR or PRs that went into it so that interested readers can learn more about the context.  If I do that, it ought to at least make it easier to grep whether the release notes contain any text about a backport of PRxxxxx.