gui: Show current wallet name in window title
bitcoin/bitcoin pull request #15149
Opened 2019-01-12 00:00 UTC by promag

<img width="876" alt="screenshot 2019-01-11 at 23 58 26" src="https://user-images.githubusercontent.com/3534524/51065458-d7ebaf80-15fc-11e9-9162-e37e9a10d448.png">

2019-01-12 00:05 UTC, promag commented on src/qt/bitcoingui.cpp
> +void BitcoinGUI::addWallet(WalletModel *walletModel)
nit, `WalletModel* walletModel`.

2019-01-12 00:08 UTC, promag commented on src/qt/bitcoingui.h
> +    void addWallet(WalletModel *walletModel);
Same as above.

2019-01-12 00:14 UTC, jonasschnelli commented
Yeah. Why not.
Concept ACK.
I suggest removing the text part "Wallet" | "Node".

2019-01-12 00:19 UTC, promag commented
> I suggest removing the text part "Wallet" | "Node".

@jonasschnelli I kind of agree, not very helpful I guess.

2019-01-12 03:32 UTC, promag commented
Now with Jonas suggestion.

2019-01-13 14:56 UTC, hebasto commented
Concept ACK.

2019-01-13 16:24 UTC, hebasto requested changes

2019-01-13 18:16 UTC, luke-jr commented
IMO this doesn't really make sense, since the same window is used for all loaded wallets currently.

2019-01-13 19:16 UTC, jonasschnelli commented
> IMO this doesn't really make sense, since the same window is used for all loaded wallets currently.

IMHO, window titles are okay to be context sensitive.

2019-01-14 08:00 UTC, hebasto commented on src/qt/bitcoingui.cpp
> +    }
@promag [from IRC](http://www.erisian.com.au/bitcoin-core-dev/log-2019-01-13.html#l-159)

> walletFrame can be empty right?

Exactly! That is why I suppose checking `walletFrame` is sufficient and checking `enableWallet` and `walletView` is redundant.

2019-01-14 08:01 UTC, hebasto commented
@promag [from IRC](http://www.erisian.com.au/bitcoin-core-dev/log-2019-01-13.html#l-159)

> walletFrame can be empty right?

Exactly! That is why I suppose checking `walletFrame` is sufficient and checking `enableWallet` and `walletView` is redundant.

2019-01-14 08:14 UTC, promag commented
@hebasto dropped `enableWallet` check, `walletFrame` is indeed sufficient:
https://github.com/bitcoin/bitcoin/blob/a9b71a09a0bbbdebc4c0b10d287bf2d53f628cf4/src/qt/bitcoingui.cpp#L101-L104 

Still checking `walletView` for the case the last wallet is unloaded.

Let me know so I can squash.

2019-01-14 08:42 UTC, hebasto commented
tACK c1e8f74f326f862adbf5a326eb1b9a65e6eb1edd

Checked the case when all wallets are unloaded:
![screenshot from 2019-01-14 10-38-00](https://user-images.githubusercontent.com/32963518/51102778-f6ae9980-17e8-11e9-8532-5be4408727bf.png)

2019-01-14 08:52 UTC, promag commented
Thanks @hebasto.

2019-01-14 13:39 UTC, laanwj commented
Concept ACK, agree it's fine for window titles to be dynamic and context sensitive.

2019-01-14 22:38 UTC, hebasto commented
re-tACK b0b2d112550817e31e469a19a2d69bcef97ae4be

2019-01-15 12:08 UTC, Sjors commented
Concept ACK, code changes look fine, tested.

I don't like the default behavior:  
<img width="291" alt="schermafbeelding 2019-01-15 om 13 01 36" src="https://user-images.githubusercontent.com/10217/51179417-b6711900-18c5-11e9-821d-b98dd3f63ffa.png">

"- [default wallet]" is visual clutter. If there's only one wallet loaded and it doesn't have a custom name, I would just show nothing.

2019-01-15 14:36 UTC, promag commented
Rebased after #14594 merge.

2019-01-15 15:35 UTC, Sjors commented
> That would be the same as no wallet is loaded.

That shouldn't cause any confusion. Either a wallet is visible or not.

It's not clear yet what we're going to do about the default wallet, e.g. do we force users to give it a name? I expect only a fraction of users to care about the multi-wallet stuff, so a term like "default wallet" is confusing.

2019-01-15 17:53 UTC, Sjors commented
tACK fe7048b

2019-01-15 19:02 UTC, merged

2019-01-19 15:06 UTC, Sjors commented
Oops, now we have a trailing `-` on mainnet.