Qt: remove macOS launch-at-startup when compiled with > macOS 10.11
bitcoin/bitcoin pull request #15208
Opened 2019-01-19 08:04 UTC by jonasschnelli

The launch-at-startup API Bitcoin Core uses on macOS where removed in macOS 10.11 leading to a segmentation-fault due to the weak-linking when not actively compiled against SDK 10.11 (`-mmacosx-version-min=10.11`)

This PR removes the launch-at-startup feature on macOS when compiled with macOS min version > 10.11 (the default is always the macOS version you compile on).

The depends built binaries (Gitian) are not affected since we are building with min macOS 10.10.

Users self compiling on macOS > 10.11 can re-enable the feature by compiling with min version <= 10.11 (`CXXFLAGS="-mmacosx-version-min=10.11" CFLAGS="-mmacosx-version-min=10.11" ./configure`)

**Isn't there a new API from Apple?**
Yes, [there is](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLoginItems.html).
It will require to create a helper application which needs to be embedded in the .app folder (needs code signing as well). Developers willing to go down that rabbit hole are welcome.

Fixes #15142

2019-01-19 08:39 UTC, hebasto commented
utACK 8441c90af88fb0f08762cf56e508803ed4b47d4c

2019-01-19 08:41 UTC, hebasto commented on doc/release-notes.md
> +- The launch-on-startup option in no longer available on macOS if
`in` --> `is` ?

2019-01-20 03:30 UTC, fanquake commented
Compiling 8441c90 on macOS `10.14.2`:
```
./autogen.sh && ./configure && make check -j6
```
The option is disabled.
<img width="655" alt="pr - no 10 11" src="https://user-images.githubusercontent.com/863730/51434776-8057de80-1ca3-11e9-9a32-0fdf04ae19e9.png">

However, when passing `-mmacosx-version-min=10.11` to  `./configure`:
```
./autogen.sh
CXXFLAGS="-mmacosx-version-min=10.11" CFLAGS="-mmacosx-version-min=10.11" ./configure
make check -j6
lldb src/qt/bitcoin-qt
```
I'm still seeing the same segfault behaviour as #15142:
```
Current executable set to 'src/qt/bitcoin-qt' (x86_64).
(lldb) run
Process 20678 launched: '/Users/michael/github/bitcoin/src/qt/bitcoin-qt' (x86_64)
2019-01-20 11:09:45.261118+0800 bitcoin-qt[20678:2180338] MessageTracer: Falling back to default whitelist
Process 20678 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
    frame #0: 0x00007fff72cb58bf libobjc.A.dylib`objc_retain + 31
libobjc.A.dylib`objc_retain:
->  0x7fff72cb58bf <+31>: testb  $0x4, 0x20(%rcx)
    0x7fff72cb58c3 <+35>: je     0x7fff72cb58f6            ; <+86>
    0x7fff72cb58c5 <+37>: testb  $0x1, %al
    0x7fff72cb58c7 <+39>: je     0x7fff72cb58e9            ; <+73>
Target 0: (bitcoin-qt) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
  * frame #0: 0x00007fff72cb58bf libobjc.A.dylib`objc_retain + 31
    frame #1: 0x00007fff484b8f18 SharedFileList`-[SFLLoginItemList removeItem:error:] + 35
    frame #2: 0x00007fff484bf3c7 SharedFileList`LSSharedFileListItemRemove + 127
    frame #3: 0x000000010007041f bitcoin-qt`GUIUtil::SetStartOnSystemStartup(bool) + 223
    frame #4: 0x00000001000a25fa bitcoin-qt`OptionsModel::setData(QModelIndex const&, QVariant const&, int) + 202
    frame #5: 0x000000010241a7a7 QtWidgets`QItemDelegate::setModelData(QWidget*, QAbstractItemModel*, QModelIndex const&) const + 295
    frame #6: 0x0000000102423b48 QtWidgets`___lldb_unnamed_symbol4564$$QtWidgets + 248
    frame #7: 0x0000000102424c7b QtWidgets`QDataWidgetMapper::submit() + 59
    frame #8: 0x000000010009573b bitcoin-qt`OptionsDialog::on_okButton_clicked() + 43
    frame #9: 0x00000001001e0f9a bitcoin-qt`OptionsDialog::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 202
    frame #10: 0x00000001001e136b bitcoin-qt`OptionsDialog::qt_metacall(QMetaObject::Call, int, void**) + 139
    frame #11: 0x0000000102e79bbd QtCore`QMetaObject::activate(QObject*, int, int, void**) + 1773
    frame #12: 0x000000010227aacf QtWidgets`___lldb_unnamed_symbol1034$$QtWidgets + 111
    frame #13: 0x000000010227a96c QtWidgets`___lldb_unnamed_symbol1032$$QtWidgets + 236
    frame #14: 0x000000010227ba9f QtWidgets`QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 271
```

2019-01-20 20:58 UTC, jonasschnelli commented
@fanquake: your right. There is something wrong with out implementation... I'll fix that soon.

2019-01-21 06:39 UTC, jonasschnelli commented
Current macOS launch at login code does release an item which belongs to an array that gets release later (double release) which causes a crash on certain macOS versions.

I added a commit that fixes the memory mismanagement.

2019-01-21 09:45 UTC, hebasto requested changes
Tested 541d287b805ecaad1d9810b5a776d2e0d8b87233 on macOS 10.13.6.

2019-01-21 09:45 UTC, hebasto commented on doc/release-notes.md
> +  CXXFLAGS="-mmacosx-version-min=10.11" for setting the deployment
`CFLAGS="-mmacosx-version-min=10.11"` could be added as well.
Without `CFLAGS` there are linker warnings:
![screenshot from 2019-01-21 11-38-04](https://user-images.githubusercontent.com/32963518/51465744-376e5b80-1d71-11e9-8363-f167505cb535.png)

2019-01-21 09:45 UTC, hebasto commented on src/qt/guiutil.cpp
> +LSSharedFileListItemRef findStartupItemInList(CFArrayRef listSnapshot, LSSharedFileListRef list, CFURLRef findUrl);
This function declaration seems unnecessary. Could it be removed?

2019-01-21 09:45 UTC, hebasto commented on src/qt/guiutil.cpp
> +    return res; // return boolified object
`res` is a `bool` already. Could the comment be removed?

2019-01-21 20:43 UTC, hebasto commented
tACK 35f5cb791de6bd47b62e031a74d885f00efd2585 (macOS 10.13.6 + Qt 5.11.2)

> The depends built binaries (Gitian) are not affected since we are building with min macOS 10.10.

Note: [official v0.17.1](https://bitcoincore.org/bin/bitcoin-core-0.17.1/bitcoin-0.17.1-osx.dmg) _is_ affected.
Could backport?

2019-01-22 08:36 UTC, practicalswift commented on doc/release-notes.md
> +  compiled with macosx min version greater then 10.11 (use
Should be "greater than" :-)

2019-01-22 08:43 UTC, jonasschnelli commented on doc/release-notes.md
> +  compiled with macosx min version greater then 10.11 (use
Fixed.

2019-01-22 21:52 UTC, laanwj commented
utACK da6011826a730837b59aef5664f3feab4787c9bc

2019-01-22 21:54 UTC, merged