remove deprecated mentions of signrawtransaction from fundraw help
bitcoin/bitcoin pull request #15245
Opened 2019-01-24 21:29 UTC by instagibbs

RPC call has been removed as of 0.17.99.

2019-01-29 12:21 UTC, instagibbs commented
Removed all mentions of signrawtransaction I could find(that weren't documentation says it was being removed or not to make RPC calls like it)

2019-01-29 18:19 UTC, MarcoFalke commented on src/wallet/rpcwallet.cpp
> +                            + HelpExampleCli("sendrawtransactionwithwallet", "\"signedtransactionhex\"")
Needs rebase

2019-02-04 14:09 UTC, instagibbs commented
rebased

2019-02-04 14:41 UTC, fanquake commented
@instagibbs Looks like you've lost the other `signrawtransaction` changes.

2019-02-04 15:02 UTC, instagibbs commented
@fanquake fixed, and noticed I was typing "withprivkey" sometimes, so fixed those as well.

2019-02-04 15:19 UTC, kristapsk requested changes

2019-02-04 15:19 UTC, kristapsk commented on src/wallet/rpcwallet.cpp
> +                            + HelpExampleCli("sendrawtransactionwithwallet", "\"signedtransactionhex\"")
It's still `sendrawtransaction`, not `sendrawtransactionwithwallet`.

2019-02-04 15:40 UTC, kristapsk approved these changes
utACK 851380ce177bccf0d608fa8017a383f2ac273dc1

2019-02-04 23:50 UTC, fanquake commented
utACK 851380c

2019-02-05 15:51 UTC, merged