[WIP] Fix InitError() and InitWarning() content
bitcoin/bitcoin pull request #15329
Opened 2019-02-02 21:14 UTC by hebasto

2019-02-02 21:17 UTC, MarcoFalke commented
I'd say some of the errors are exceptions that rarely happen and shouldn't be translated

2019-02-02 21:45 UTC, hebasto commented
@MarcoFalke added rationale, removed [WIP]

2019-02-02 21:51 UTC, laanwj commented
> I'd say some of the errors are exceptions that rarely happen and shouldn't be translated

I agree. There's also the problem, especially with extremely rare error messages (such as the secp256k1 failure) that translating them makes them impossible to google. This doesn't really weigh up to the advantage of translating the message if it's very technical in the first place.

So I'm not convinced this is a good thing.

2019-02-02 21:54 UTC, hebasto commented
@laanwj 

> There's also the problem, especially with extremely rare error messages (such as the secp256k1 failure) that translating them makes them impossible to google.

Agree. Should 128148775ee465047c2a9c0e2a92277981b1a4b7 commit be removed completely?

2019-02-02 21:58 UTC, laanwj commented
I'd say yes.
(coincidentally, too late for this for 0.18, translation string freeze was February 1)

2019-02-02 22:05 UTC, hebasto commented
@laanwj 
> (coincidentally, too late for this for 0.18, translation string freeze was February 1)

I know it from the last IRC meeting. 0.18 is not the target for this PR :)

2019-02-02 23:06 UTC, hebasto commented
Ref: [IRC discussion](http://www.erisian.com.au/bitcoin-core-dev/log-2019-02-02.html#l-265)

2019-02-02 23:59 UTC, hebasto commented
> I'd say some of the errors are exceptions that rarely happen and shouldn't be translated

Removed translations of error messages inside `InitSanityCheck()`.
PR description updated.

2019-02-03 12:33 UTC, hebasto commented
[Translation Strings Policy](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_strings_policy.md#gui-strings):
> Anything that appears to the user in the GUI is to be translated. This includes labels, menu items, button texts, tooltips and window titles. This includes messages passed to the GUI through the UI interface through **`InitMessage`**, `ThreadSafeMessageBox` or `ShowProgress`.

2019-02-03 12:39 UTC, hebasto commented
Ref: [comment](https://github.com/bitcoin/bitcoin/pull/6870#discussion_r42965071) by @laanwj:

> I think errors relating directly to user options should be kept translated.

2019-03-09 17:24 UTC, hebasto commented
Rebased.

2019-04-23 19:39 UTC, hebasto commented
Rebased.

2019-06-06 02:47 UTC, PastaPastaPasta requested changes

2019-06-06 02:47 UTC, PastaPastaPasta commented on src/init.cpp
> +                return InitError(strprintf(_("Unknown network specified in %s: '%s'"), "-onlynet", snet));
bodies of an if statement should be on the same line or in brackets, imo this could be fixed in this PR

2019-06-06 02:47 UTC, PastaPastaPasta commented on src/init.cpp
> +                return InitError(strprintf(_("Invalid %s address or hostname: '%s'"), "-onion", onionArg));
same as above, same line or brackets

2019-06-06 02:47 UTC, PastaPastaPasta commented on src/init.cpp
> +            return InitError(strprintf(_("Invalid netmask specified in %s: '%s'"), "-whitelist", net));
same as above, same line or brackets

2019-06-06 02:47 UTC, PastaPastaPasta commented on src/wallet/init.cpp
> +        return InitError(strprintf(_("%s is not allowed in combination with enabled wallet functionality"), "-sysperms"));
same line or brackets

2019-06-06 02:47 UTC, PastaPastaPasta commented on src/wallet/init.cpp
> +        return InitError(strprintf(_("Rescans are not possible in pruned mode. You will need to use %s which will download the whole blockchain again."), "-reindex"));
same line or brackets

2019-06-14 19:38 UTC, MarcoFalke commented on src/init.cpp
> +        return InitError(_("Initializing networking failed"));
Tend to NACK. This will put the translated message into the debug log

2019-06-14 19:40 UTC, MarcoFalke commented on src/init.cpp
> +        return InitError(_("Initializing networking failed"));
I guess the translation should be registered here only and then later translated in InitError with `_()`

2019-06-15 06:04 UTC, hebasto commented
@MarcoFalke
> Tend to NACK. This will put the translated message into the debug log

> I guess the translation should be registered here only and then later translated in InitError with `_()`

Agree. There was a dedicated PR #15340.

So, closing this PR now.

2019-06-15 06:04 UTC, closed without merging