Log the actual wallet file version and no longer publicly expose the "version" record
bitcoin/bitcoin pull request #15588
Opened 2019-03-13 05:14 UTC by achow101

The wallet file version is stored in the "minversion" record, not the "version" record. However "version" is no longer used anywhere except to record the highest versioned client which has opened a wallet file (which is currently only used to check whether this was most recently opened by a 0.4.0 or 0.5.0rc1 client which had a broken wallet encryption implementation). Furthermore, "version" was logged to the debug.log when "minversion" should have been as "minversion" is the actual wallet file version.

This PR changes it so that this confusion largely no longer exists. The wallet file version logging is changed to use "minversion" and reading and writing the "version" record is no longer publicly exposed to prevent potential confusion about whether the actual file version is being read or written. Lastly, in the one place it is actually used, the variable name is changed from nFileVersion to last_client to better reflect what that record actually represents.

2019-03-13 16:21 UTC, ryanofsky commented
Just to clarify, is the only user-visible change here replacing:

```
nFileVersion = [version number of the newest wallet software that ever opened the wallet in the past]
```

with

```
Wallet File Version = [minimum wallet software version required to open the wallet file]
```

?

2019-03-13 19:29 UTC, achow101 commented
> Just to clarify, is the only user-visible change here replacing:

Yes.

2019-03-17 14:49 UTC, jjjerrmmmy approved these changes

2019-04-10 11:47 UTC, laanwj commented
utACK 96a46f5bcd5433c3a4c5900ecc8be547e48f5f74

2019-04-16 16:42 UTC, achow101 commented on src/wallet/db.cpp
> +                Write(std::string("version"), CLIENT_VERSION);
I'm not sure that this is redundant. It's making sure that the `version` field exists, whereas `WalletBatch::LoadWallet` doesn't necessarily do that.

2019-06-29 01:18 UTC, achow101 commented on src/wallet/walletdb.cpp
> -                wss.nFileVersion = 300;
`nFileVersion` is being removed entirely, and all this `version` record did was fill it. At no point was `nFileVersion` being checked for anything less than 40000 so this if block is meaningless.

2019-07-09 18:00 UTC, achow101 commented on src/wallet/walletdb.cpp
> +    int last_client = CLIENT_VERSION;
I think I'll leave it as is.

2019-07-11 18:57 UTC, laanwj commented
@meshcollider can you please take a look here

2019-07-22 16:43 UTC, jb55 requested changes
Concept ACK, I reviewed the changes in detail and confirmed they make sense logically. I have a few comments before I Approach ACK. Let me know what you think.

2019-07-22 17:03 UTC, achow101 commented on src/wallet/walletdb.cpp
> +    pwallet->WalletLogPrintf("Wallet File Version = %d\n", wallet_version > 0 ? wallet_version : wss.nFileVersion);
Done

2019-07-22 18:53 UTC, ryanofsky approved these changes
utACK 35e60e790f2cd602d1bdd0be835d27f0ba37efa9. This code still pretty confusing, but a little simpler now. And the previous log statement was really misleading and useless compared to the new one here.

2019-07-23 04:54 UTC, jb55 commented
ACK 35e60e7, I compiled locally as a quick sanity check.

2019-07-27 10:44 UTC, meshcollider approved these changes
Looks good, thanks! utACK 35e60e790f2cd602d1bdd0be835d27f0ba37efa9

2019-07-27 10:46 UTC, merged