net: Simplify PONG handler, improve readability of the processing logic.
bitcoin/bitcoin pull request #15613
Opened 2019-03-17 16:39 UTC by pstratem

This significantly simplifies the logic.

2019-03-17 17:05 UTC, practicalswift commented
Is this intended as a pure refactoring or does the change come with any change in behaviour?

Is the change from `nAvail >= sizeof(nonce)` to `nAvail != sizeof(nonce)` intentional?

2019-03-17 17:13 UTC, pstratem commented
@practicalswift the change is intentional, the buffer should exactly match the expected length (yes i know this means we cant extend the pong message in the future)

2019-03-17 17:17 UTC, practicalswift commented
@pstratem Thanks for clarifying! Any other intentional deviations from a pure refactoring? :-)

2019-03-17 17:39 UTC, pstratem commented
@practicalswift the timing constraint is changed from > to >= as it's measured in microseconds. a ping time of zero seconds is almost certainly in error.

2019-03-17 17:39 UTC, pstratem commented
and obviously the error messages are changed to be more specific

2019-06-06 11:05 UTC, laanwj commented on src/net_processing.cpp
> +            LogPrint(BCLog::NET, "pong peer=%d: received pong before ping sent, maybe clock changed?\n", pfrom->GetId());
maybe "received pong before or at time ping sent"

2019-07-04 04:14 UTC, fqlx requested changes

2019-07-04 04:14 UTC, fqlx commented on src/net_processing.cpp
> +        // We didn't send a ping, there shouldn't be a pong
Instead of adding a comment here, we could make the LogPrint more informative (which would self comment the code).

2019-07-04 04:14 UTC, fqlx commented on src/net_processing.cpp
> +        if (nAvail != sizeof(nonce)) {
Is this intentional?  sizeof should return 8 (is 8 intentional here) but we might have side effects depending on the OS.
Why use sizeof here and not >0 or just nonce?

2019-08-23 12:25 UTC, fanquake commented
@pstratem did you want to follow up and address any comments here?

2019-09-30 12:36 UTC, laanwj commented
Closing, as this has been waiting for author for more than a month. Let me know if you want to reopen this.

2019-09-30 12:36 UTC, closed without merging