tests: Add std::to_string to list of locale dependent functions
bitcoin/bitcoin pull request #17851
Opened 2020-01-02 21:01 UTC by practicalswift

Add `std::to_string` to list of locale dependent functions:

> `std::to_string` relies on the current locale for formatting purposes […]

Context https://github.com/bitcoin/bitcoin/pull/17808#issuecomment-570329665

2020-01-02 22:13 UTC, MarcoFalke commented
ACK

2020-01-02 22:58 UTC, hebasto approved these changes
ACK 1f0adb3dac461b3f24f2a98b736d972e9713d67e, I have reviewed the code and it looks OK, I agree it can be merged.

2020-01-03 20:01 UTC, luke-jr requested changes

2020-01-03 20:43 UTC, MarcoFalke commented
Going to push this doc/test-only change. Bug fixes can be solved in a separate pull request.

2020-01-03 20:45 UTC, merged

2020-01-03 21:24 UTC, practicalswift commented on test/lint/lint-locale-dependence.sh
> +    "src/rpc/rawtransaction.cpp.*std::to_string"
I'm not sure I follow: how is this a bug?

Do you mean the inclusion of `src/rpc/rawtransaction.cpp` in this list, or do you mean the usage of `std::to_string` in `src/rpc/rawtransaction.cpp`?

Please clarify :)

Applies also to the cases below.

2020-01-04 06:07 UTC, sipa commented on test/lint/lint-locale-dependence.sh
> +    "src/rpc/rawtransaction.cpp.*std::to_string"
I believe @lukejr means that the current usage of that function in rpc/rawtransaction.cpp is a bug, and thus should not be silenced, but fixed.

2020-01-04 06:27 UTC, fanquake commented on test/lint/lint-locale-dependence.sh
> +    "src/rpc/rawtransaction.cpp.*std::to_string"
Opened an issue in #17866 so we don't lose track of this.

2020-01-04 10:29 UTC, practicalswift commented on test/lint/lint-locale-dependence.sh
> +    "src/rpc/rawtransaction.cpp.*std::to_string"
@sipa Ah, got it. FWIW I consider all entries in `KNOWN_VIOLATIONS` to be potential bugs :)