Doc: Fix BSD docs regarding gmake
bitcoin/bitcoin pull request #18129
Opened 2020-02-12 18:18 UTC by abitfan

Fixes #14404

2020-02-13 10:39 UTC, murrayn requested changes
Adding `MAKE=gmake` as an argument to the `./configure` command line examples might be preferable, as `setenv` is specific to `csh`.

2020-02-13 14:46 UTC, laanwj commented
I'm still confused why this is needed. I've been running a node on a FreeBSD machine for years, and never had to redefine `MAKE`.

Do you need this when building other autoconf projects as well? If not, I wonder what is different in our build system.

2020-02-13 15:40 UTC, abitfan commented
@murrayn There are at least two ./configure examples in each doc file and more can be added later on, imho it just clutters the documentation but it can be changed if deemed necessary. On top of that csh is the default shell on BSDs and compiling bitcoin from source requires some knowledge of the OS anyway.

@laanwj You ran ./configure with --disable-dependency-tracking which won't trigger the problem. This behavior is reproducible on any fresh bsd install. 
"Do you need this when building other autoconf projects...". Yes if you use **gmake** since autoconf will by default use the system's make.

2020-02-13 15:42 UTC, laanwj commented
So it's an alternative for `--disable-dependency-tracking`? Makes sense then.

2020-02-13 20:22 UTC, vasild commented on doc/build-freebsd.md
> +```
`setenv` is not portable between shells. Yes, it works on the default `csh` but does not work in others.

Given that `./configure MAKE=gmake` is an equivalent and works with any shell, I would suggest to add `MAKE=gmake` a few lines below where we show how to execute `./configure`.

2020-02-20 12:13 UTC, fanquake commented
I agree with the other commenters in using [`./configure MAKE=gmake`](https://github.com/bitcoin/bitcoin/issues/14404#issuecomment-431565631).

2020-03-13 03:26 UTC, fanquake commented
Picked this up in #18340.

2020-03-13 03:26 UTC, closed without merging