util: Avoid potential uninitialized read in FormatISO8601DateTime(int64_t n) by checking gmtime_s/gmtime_r return value
bitcoin/bitcoin pull request #18162
Opened 2020-02-16 19:55 UTC by practicalswift

Avoid potential uninitialized read in `FormatISO8601DateTime(int64_t)` by checking `gmtime_s`/`gmtime_r` return value.

Before this patch `FormatISO8601DateTime(67768036191676800)` resulted in:

```
==5930== Conditional jump or move depends on uninitialised value(s)
==5930==    at 0x4F44C0A: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==5930==    by 0x4F511A4: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==5930==    by 0x4037C3: void tinyformat::formatValue<int>(std::ostream&, char const*, char const*, int, int const&) (tinyformat.h:358)
==5930==    by 0x403725: void tinyformat::detail::FormatArg::formatImpl<int>(std::ostream&, char const*, char const*, int, void const*) (tinyformat.h:543)
==5930==    by 0x402E02: tinyformat::detail::FormatArg::format(std::ostream&, char const*, char const*, int) const (tinyformat.h:528)
==5930==    by 0x401B16: tinyformat::detail::formatImpl(std::ostream&, char const*, tinyformat::detail::FormatArg const*, int) (tinyformat.h:907)
==5930==    by 0x4017AE: tinyformat::vformat(std::ostream&, char const*, tinyformat::FormatList const&) (tinyformat.h:1054)
==5930==    by 0x401765: void tinyformat::format<int, int, int, int, int, int>(std::ostream&, char const*, int const&, int const&, int const&, int const&, int const&, int const&) (tinyformat.h:1064)
==5930==    by 0x401656: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > tinyformat::format<int, int, int, int, int, int>(char const*, int const&, int const&, int const&, int const&, int const&, int const&) (tinyformat.h:1073)
==5930==    by 0x4014CC: FormatISO8601DateTime[abi:cxx11](long) (…)
```

The same goes for other very large and very small arguments.

Fix by simply checking the `gmtime_s`/`gmtime_r` return value :)

2020-02-16 21:38 UTC, theStack requested changes
`gmtime_s` doesn't return a pointer, but `errno_t` (see https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/gmtime-s-gmtime32-s-gmtime64-s?view=vs-2019), hence the condition ` != 0` rather than `== nullptr` is needed in those cases to detect an error. See AppVeyor build failure.

2020-02-17 07:19 UTC, practicalswift commented
@theStack Oh, thanks for notifying! :) Now addressed . Please re-review updated version :)

2020-02-17 07:19 UTC, Empact commented
The `gmtime_s` return value seems to be a windows-specific situation: https://en.cppreference.com/w/c/chrono/gmtime

2020-02-17 07:22 UTC, practicalswift commented
@Empact 

> The `gmtime_s` return value seems to be a windows-specific situation: https://en.cppreference.com/w/c/chrono/gmtime

Yes, that's pretty strange :)  "The implementation of gmtime_s in Microsoft CRT is incompatible with the C standard since it has reversed parameter order."

2020-02-17 09:11 UTC, fanquake commented
The unit tests are not passing:
```bash
test/util_tests.cpp(155): error: in "util_tests/util_FormatParseISO8601DateTime": check FormatISO8601DateTime(std::numeric_limits<int64_t>::min()) == "" has failed [1970-01-01T00:00:00Z != ]
test/util_tests.cpp(156): error: in "util_tests/util_FormatParseISO8601DateTime": check FormatISO8601DateTime(std::numeric_limits<int64_t>::max()) == "" has failed [1969-12-31T23:59:59Z != ]
test/util_tests.cpp(157): error: in "util_tests/util_FormatParseISO8601DateTime": check FormatISO8601Date(std::numeric_limits<int64_t>::min()) == "" has failed [1970-01-01 != ]
test/util_tests.cpp(158): error: in "util_tests/util_FormatParseISO8601DateTime": check FormatISO8601Date(std::numeric_limits<int64_t>::max()) == "" has failed [1969-12-31 != ]
```

2020-02-17 18:35 UTC, theStack approved these changes
Code-Review ACK https://github.com/bitcoin/bitcoin/pull/18162/commits/6558ec35654d1a9990dcb534b18b5c88c5a4e165

2020-02-17 19:58 UTC, practicalswift commented
Added a valgrind CI job that would have caught this: see PR #18166 (`ci: Run fuzz testing test cases (bitcoin-core/qa-assets) under valgrind to catch memory errors`).

2020-02-19 16:09 UTC, elichai approved these changes
Nice find!
I'd refactor this out to a function that returns `Optional<struct tm>` but this can be done in a future PR
ACK 6558ec35654d1a9990dcb534b18b5c88c5a4e165

2020-02-19 22:42 UTC, practicalswift commented
Rebased and removed `--exclude integer,parse_iso8601` which is not needed after the merge of this PR.

2020-02-24 13:16 UTC, elichai approved these changes
re ACK 12a2f377185a413b740460db36812de22ee2e041

2020-02-24 16:17 UTC, MarcoFalke commented
ACK 12a2f377185a413b740460db36812de22ee2e041

2020-02-24 17:37 UTC, theStack commented
re-ACK https://github.com/bitcoin/bitcoin/commit/12a2f377185a413b740460db36812de22ee2e041

2020-02-25 02:06 UTC, merged