rpc: Fix RPCExamples
bitcoin/bitcoin pull request #18208
Opened 2020-02-25 16:18 UTC by yusufsahinhamza

This is a follow-up PR to #18197 that fixes RPCExamples.

Fixes #18185.

2020-02-26 14:40 UTC, leto commented
utACK: looks like an improvement to the tests + docs

2020-02-27 23:24 UTC, Empact commented
Concept ACK

2020-03-01 00:43 UTC, theStack requested changes
I'm not sure if it's a good idea to mix legacy and bech32 addresses in the same examples address array. The confusing consequence is that the index of the address array determines the resulting address type, and if someone e.g. would add another legacy address in front, many help strings that accessed at index 1 to get bech32 examples address woud then show legacy addresses again. To prevent that, it would be even okay right now if the legacy addresses stay in hardcoded (and the guidelines remain untouched).

2020-03-01 00:43 UTC, theStack commented on doc/developer-notes.md
> +- Use *invalid* addresses (e.g. in the constant array `EXAMPLE_ADDRESS`) for
The "bech32" part is actually important here, as we want to get rid of legacy addresses in the long term. Without that the reader of the guideline may think that any address format is fine.

2020-03-01 00:43 UTC, theStack commented on doc/developer-notes.md
> +    of example addresses by default.
That doesn't make sense. "Encourage the use of..." adresses the _user_ of the software here, not the developer. As above, "bech32" should stay here.

2020-03-01 00:43 UTC, theStack commented on src/rpc/misc.cpp
> +                    HelpExampleCli("validateaddress", EXAMPLE_ADDRESS[1]) +
The quotation marks around the address are missing. Previously they were included in `EXAMPLE_ADDRESS`, now as the constant contains the bare address, so they have to be added here.

2020-03-01 00:43 UTC, theStack commented on src/wallet/rpcwallet.cpp
> +                    HelpExampleCli("getaddressinfo", EXAMPLE_ADDRESS[1]) +
The quotation marks around the address are missing (see comment to `"validateaddress"` above).

2020-03-01 07:35 UTC, theStack commented
LGTM now, can you squash the commits, please? In the course of that, you could also change the commit title to be more descriptive (e.g. "change to bech32" than just "fix").

2020-03-01 15:06 UTC, jonatack reviewed
Concept ACK

2020-03-11 14:53 UTC, MarcoFalke commented
ACK 3e32499909ca8127baaa9b40ad113b25ee151bbd

2020-03-11 15:12 UTC, jonatack reviewed
ACK 3e32499

2020-03-11 16:44 UTC, merged