Use min relay value constant in QT
bitcoin/bitcoin pull request #18343
Opened 2020-03-13 13:55 UTC by instagibbs

2020-03-13 13:57 UTC, luke-jr commented
I guess it's a strict improvement, but shouldn't it be using the user-configured value??

2020-03-13 14:04 UTC, instagibbs commented
@luke-jr this value is the one that "rejects" too-low values, aka something that simply cannot propogate. 

(although I guess this can change too depending on current mempool minfee, eh?)

2020-03-13 14:53 UTC, maflcko requested changes
NACK, not sure what this is trying to solve

2020-03-13 14:53 UTC, MarcoFalke commented on src/qt/sendcoinsdialog.cpp
> +        CAmount requiredFee = model->wallet().getRequiredFee(DEFAULT_MIN_RELAY_TX_FEE);
Huh? The units don't match up here. 1000 is of unit kB and the constant you put in here is a feerate.

2020-03-13 15:10 UTC, instagibbs commented
hmm I thought I tested this locally but this is obviously wrong, closing

2020-03-13 15:10 UTC, closed without merging

2020-04-22 23:06 UTC, luke-jr commented
> aka something that simply cannot propogate

Literally anything CAN propagate.

Network policies are not constants, and should assume to vary.

2020-04-22 23:53 UTC, instagibbs commented
Not sure why you're necroing this PR.

On Wed, Apr 22, 2020, 7:06 PM Luke Dashjr <notifications@github.com> wrote:

> aka something that simply cannot propogate
>
> Literally anything CAN propagate.
>
> Network policies are not constants, and should assume to vary.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/18343#issuecomment-618084458>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMAFU6CLJC4LDRJPEJCVLDRN5Z7NANCNFSM4LHC7AFQ>
> .
>