test: Add test for wtxid transaction relay
bitcoin/bitcoin pull request #18446
Opened 2020-03-27 01:18 UTC by fjahr

Based on #18044 

This updates the functional testing framework to the p2p protocol version including wtxid transaction relay (70016) and adds a basic test for wtxid based relay.

2020-03-27 03:30 UTC, sipa commented on test/functional/test_framework/messages.py
> +MY_VERSION = 70016  # past bip-31 for ping/pong
Comment is outdated now.

2020-03-30 12:53 UTC, ajtowns commented
I think this isn't testing:

 * whether the node switches from sending TX invs to WTX invs when the wtxidrelay message is sent
 * whether we get a wtxidrelay message when we give a 70016 version, but not when we give a lower version
 * in either case, when we announce a TX inv, do we get a TX getdata back, and likewise for WTX?
 * when a tx is sent (not an INV but the actual tx) if it's an orphan, the missing parent's txid is requested as a TX not a WTX

I've had a go at some of the changes: https://github.com/ajtowns/bitcoin/tree/202003-wtxidrelay-test but haven't made it so it actually sends the `wtxidrelay` message.

2020-04-01 01:00 UTC, fjahr commented
@ajtowns Thank you, that is very helpful. My intuition was that many of these cases would be tested indirectly by upgrading the test framework but of course, explicit tests are always better and, as I have realized now, I also had not implemented it correctly. Your tests mainly did not pass because I had not implemented feature negotiation correctly. This is done now and I preserved your commit mostly so it is easier for you to review. If the test now does what you intended it to do then I can squash.

Overview of changes:
- Rebased
- Fixed outdated comment
- Added explicit test for wtxidrelay
- Fixed wtxidrelay feature negotiation
- Added @ajtowns code and with some further changes on top

2020-04-01 01:02 UTC, fjahr commented on test/functional/test_framework/messages.py
> +MY_VERSION = 70016  # past bip-31 for ping/pong
fixed

2020-04-06 09:24 UTC, ajtowns requested changes
I think this needs more changes to match the latest update to #18044; I merged them and added a fixup commit on https://github.com/ajtowns/bitcoin/tree/202003-wtxidrelay-test if you want to take a look. Feel free to squash the fixups anytime btw.

2020-04-20 16:51 UTC, fjahr commented on test/functional/p2p_segwit.py
> +        self.nServices = message.nServices
done

2020-04-20 17:03 UTC, fjahr commented
Thanks @ajtowns ! I pulled in latest changes in #18044 and your suggestions. Then squashed and edited commit messages for easier reviewing. Also left your suggested change `ignore non-wtxidrelay compliant invs` in for now, pending discussion in #18044 .

2020-04-21 16:27 UTC, fjahr commented
Pushed an update that should make all functional tests use wtxid relay by default (Github doesn't seem to be working properly at the moment, here is the commit: https://github.com/fjahr/bitcoin/commit/becdb68ab37fdcbc1dcf743b19ea8629f52677bb)

2020-06-22 16:54 UTC, sdaftuar commented
FYI -- I tried to cherry-pick the test commits here onto the latest version of #18044 but the p2p_segwit.py test is failing for me.

2020-06-26 21:00 UTC, fjahr commented
> FYI -- I tried to cherry-pick the test commits here onto the latest version of #18044 but the p2p_segwit.py test is failing for me.

@sdaftuar Thanks for the heads-up! I rebased with the latest state of #18044 and made several fixes plus squashed to three commits now.

2020-06-28 11:19 UTC, fjahr commented
These commits were pulled into #18044 so it can be closed.

2020-06-28 11:19 UTC, closed without merging