[0.19] Backports
bitcoin/bitcoin pull request #19025
Opened 2020-05-20 03:22 UTC by fanquake

Backports the following to the 0.19 branch:

* #17946 - Fix GBT: Restore "!segwit" and "csv" to "rules" key
* #18425 - releases: Update with new Windows code signing certificate
* #18676 - build: Check libevent minimum version in configure script

Can leave this open for a while for additional changes.

2020-05-20 09:20 UTC, promag commented
Do you want to include #18542 here?

2020-06-09 13:02 UTC, fanquake commented
> Do you want to include #18542 here?

Thanks. I've pulled in d3cfe0d6a472c748142b96c33de866478cca5545 from that PR.

2020-06-11 04:09 UTC, luke-jr commented
#19185 is a clean merge of the original commit. No need for an ugly re-commit as here.

Should remove the commits here, and reopen #19185 instead

2020-06-11 04:09 UTC, luke-jr requested changes
#19185 is a clean merge of the original commit. No need for an ugly re-commit as here.

Should remove the commits here, and reopen #19185 instead

2020-06-29 16:21 UTC, promag commented
#19300 was merged.

2020-08-11 08:41 UTC, jnewbery commented
ACK be951470bea132b4cbe1823cd564bf14aaf0ea7e

2020-08-11 09:07 UTC, MarcoFalke commented
cherry-pick ACK be951470bea132b4cbe1823cd564bf14aaf0ea7e 🌎

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

cherry-pick ACK be951470bea132b4cbe1823cd564bf14aaf0ea7e 🌎
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhiqAv+LLwsV4mNGsaTSOa3q9mT14B/bWuib9+CFffg8lBvedHfjs/B/jRRkbDt
R8zCFOZPJHed/8M3ICUYHi04FJkO5y4Bh8TzIY8087SPM6sDatE/MWXSCe5f9Ttt
aFTfYx19As/yaE4cMJZD+/3pwHVObZuQ4nzu9TZYbtUBRoJj912QP5Yq+gBZXxwt
M10O6pwz7e5IXwGCPeIIlhMLgiqmom7pJIsijZi3PaGeH+oR8sBnxB99B4dVwiJl
+E7VQSVldHNjoNcSftvp41deDc1L79hFn3au4ws2Zq6y1BXlgAxLOqBmkGSS6y1H
Qvq+YrtQM/pGblgRuXUD3Nb3qbehk7mVPka+RlI3diyj1yB6YbG0YAjDxvDmkQgp
VBqW7loKrAnxO6VRpaZ8+SGZyWwCQQQEii25WKvRZm4xR/5AoJgHv4PU1hK89jei
lzayyDZVUqbWS8PDD4zhes28m1u5iZaTKgALYFegyxnRl5YHuwSfACuLjQT2CMYM
wpMzwC5O
=AqoC
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `85457e8568a50d11680719483b91ec171c3e108883edca3d38bbae169190b69a  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e89294010885457e8568a50d11680719483b91ec171c3e108883edca3d38bbae169190b69af0108007f04033f96fa8ccd06c1c66fd39ca08fff01031cdb7efbba19611fa452b7321e3b83608f1045f325fbff008fb74f240498991840083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010b8be27e7bc024f17e93377cc6df037ec08f1045f325fbef0084dd6694a334568d00083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010cc9e343415e3f0a88fa1784e1540b1ec08f1045f325fbef00885be8dc39a313b990083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

2020-08-11 09:08 UTC, MarcoFalke commented on .appveyor.yml
> +      git checkout $env:VCPKG_COMMIT_ID
Any reason to check out the same commit twice?

You can avoid the conflicts by cherry-picking in the correct order:

```
$ git log -3 --oneline 
a51ffbe92c (HEAD) Remove cached directories and associated script blocks from appveyor CI configuration.
6646b5f891 appveyor: Remove clcache
bd95892b0d Updated appveyor job to checkout a specific vcpkg commit ID.

2020-08-11 09:59 UTC, merged

2020-08-11 10:01 UTC, MarcoFalke commented
> #19300 was merged.

This wasn't included here, but I went ahead and merged this to make the ci green on the other backport pulls