rpc: Validate provided keys for query_options parameter in listunspent
bitcoin/bitcoin pull request #19169
Opened 2020-06-04 21:36 UTC by PastaPastaPasta

At Dash, one of our developers was working with the `listunspent` RPC command, but instead of saying "minimumAmount" he said "minimmumAmount" as such the RPC wasn't working as expected. 

In https://github.com/dashpay/dash/pull/3507 we implemented a check so that `listunspent` returns an error if an unrecognized option is given. I figured I might as well adapt the code and throw up a PR here.

Cheers!

2020-06-05 17:16 UTC, luke-jr requested changes
Can you refactor this to use `RPCTypeCheckObj`?

2020-06-05 18:41 UTC, PastaPastaPasta commented
I like that, makes it simpler, changed, and squashed/force-pushed

2020-06-05 18:42 UTC, PastaPastaPasta commented
Tested with
```
generatetoaddress 105 bcrt1qwq0cnj557dn070dd8l52dhkathpx083qlg5v4w
listunspent 1 99999999 [] true "{\"minimumAmount\" : 49}"
listunspent 1 99999999 [] true "{\"minimumAmount\" : 51}"
listunspent 1 99999999 [] true "{\"minimumAAmount\" : 51}"
```

Everything worked as expected

2020-06-05 20:05 UTC, PastaPastaPasta commented
Resolved test failure. made amounts not have their type checked since that gets checked anyway in `AmountFromValue`

2020-08-05 05:27 UTC, adaminsky commented
ACK `a99a3c0bd`
Built, ran unit tests and functional tests, and manually tested RPCs with different `query_options` objects including unsupported parameters. Reviewed the code and it looks good.

2020-08-13 21:32 UTC, meshcollider reviewed
Seems fine to me. utACK a99a3c0bd6d5476503c015e23be569295fdd190c

2020-08-14 07:07 UTC, fanquake commented
@MarcoFalke can you take a look here?

2020-08-27 18:17 UTC, MarcoFalke commented
RPCman will do this in the future, but nothing wrong adding something like that in the meantime

2020-08-27 18:19 UTC, merged