build: Fix & improve the search for BDB
bitcoin/bitcoin pull request #19356
Opened 2020-06-23 02:42 UTC by gwillen

NOTE: This PR contains one important fix that I need (to make Bitcoin Core build cleanly on my system without shenanigans), plus some related general cleanup that is not really necessary, and could be annoying. (I am prepared to defend my argument that BDB_CFLAGS is wrong here, and BDB_CPPFLAGS is right, but this could bite anybody who has gotten in the habit of -- or scripted -- setting the former.)

---

On OS X, when searching Homebrew keg-only packages for BDB 4.8, if we find it,
use BDB_CPPFLAGS and BDB_LIBS instead of CFLAGS and LIBS for the result. This
is (1) more correct, and (2) necessary in order to give this location
priority over other directories in the include search path, which may include
system include directories with other versions of BDB.

Additionally, switch all our usages of BDB_CFLAGS to BDB_CPPFLAGS. The former
is specific to the C compiler, whereas the latter is used for both C and C++
compilation (which is what we want.) Previously, the bitcoin_find_bdb48.m4
configure script would look for BDB_CFLAGS for input, but then put the result
into BDB_CPPFLAGS in order to build -- this looks like a hack to fix some past
broken build, but the correct approach is not to use BDB_CFLAGS at all.

2020-06-23 03:04 UTC, gwillen commented
(It looks like the use of BDB_CFLAGS for overrides was introduced in #9705, switching from CPPFLAGS. @laanwj, is there a reason you preferred BDB_CFLAGS over BDB_CPPFLAGS here, or that was just how things happened to land?)

2020-06-23 09:02 UTC, Sjors commented
As suggested by @DrahtBot, #18870 is related, though it goes much further.

2020-06-23 10:05 UTC, gwillen commented
@Sjors: Thanks, per discussion with @theuni on IRC I'm going to rework the way I am doing this a bit anyway, so I'll rebase (thought it doesn't appear to conflict with #19240, fortunately.) I've been convinced that changing BDB_CFLAGS to BDB_CPPFLAGS, while tantalizing, is not actually correct.

As for testing -- in my case, I had bdb@4 unlinked, bdb 18 linked, and the result was that anything that touched the wallet would segfault. It was picking up bdb 18 headers from /usr/local/include, but bdb 4 libraries from /usr/local/opt/blahblahblah. After my change it correctly picks up bdb 4 only (for me.)

2020-06-23 11:47 UTC, gwillen commented
Ok, removed the refactor of `BDB_CFLAGS`, now it's just the tiny change to rearrange the include order so that we pick up the unlinked brew-installed BDB 4 consistently if present.

This does interact with #18870 a bit, but I think they're mostly orthogonal -- that one affects what we're looking for, whereas this one affects what we do with it if we find it.

2020-06-23 20:15 UTC, theuni requested changes
Concept ACK. Requested a few little changes.

2020-06-23 21:39 UTC, gwillen commented on configure.ac
> +         if test x$bdb_prefix != x && test "x$BDB_CFLAGS" = "x"; then
Yeah, that's true re: libs. I think it's incoherent to specify one and not the other, but in that case better for us to not be clever, and let the specified options go through. Will fix.

I _think_ $DEPENDENCY_CFLAGS has no other obvious purpose than specifying include paths, in which case it wouldn't make sense for someone to specify it and _also_ want to pick up the brew path -- you'd want the user path to override.

2020-06-23 21:39 UTC, gwillen commented on configure.ac
> +           AC_SUBST(BDB_CFLAGS)
Good point. I was originally trying to keep this standalone and effectively independent of BITCOIN_FIND_BDB48, but now that this is not possible, the SUBSTs are redundant. Will remove.

2020-06-24 05:09 UTC, gwillen commented
@theuni Comments addressed!

2020-06-24 13:17 UTC, laanwj commented
> (It looks like the use of BDB_CFLAGS for overrides was introduced in #9705, switching from CPPFLAGS. @laanwj, is there a reason you preferred BDB_CFLAGS over BDB_CPPFLAGS here, or that was just how things happened to land?)

I based it on some existing conventions in the build sytem. See `./configure --help`. All the additional library-specific flags have `_CFLAGS` and `_LIBS` pairs.

2020-06-24 15:37 UTC, theuni approved these changes
Thanks for the quick fixups.

ACK 8578c6fccd11404412d2c60f9bede311b79ca0d0.

2020-06-24 17:14 UTC, gwillen commented
> > (It looks like the use of BDB_CFLAGS for overrides was introduced in #9705, switching from CPPFLAGS. @laanwj, is there a reason you preferred BDB_CFLAGS over BDB_CPPFLAGS here, or that was just how things happened to land?)
> 
> I based it on some existing conventions in the build sytem. See `./configure --help`. All the additional library-specific flags have `_CFLAGS` and `_LIBS` pairs. None has `_CPPFLAGS` at least.

Yeah, some IRC conversation after my initial PR convinced me that you were in fact correct to do so after all.

2020-06-29 05:09 UTC, merged