torcontrol: Add V3 ED25519-V3 onions.
bitcoin/bitcoin pull request #19485
Opened 2020-07-10 15:55 UTC by Saibato

While fiddling around with the path to ADDRv2 and #19031
I noticed that it might be useful if we have already ED25519-V3 onions for the node created in torcontrol.

2020-07-10 15:59 UTC, luke-jr commented
What's the point if we can't advertise the address?

Also, shouldn't it be possible to have both v2 and v3 addresses?

2020-07-10 16:17 UTC, Saibato commented
> What's the point if we can't advertise the address?
> 
> Also, shouldn't it be possible to have both v2 and v3 addresses?

If BIP155 get merged...  ?
I have a working patch for @vasild Tor v3/ADDRv2  implementation that i will  post him now.

Btw. I use for myself a patch i made fro myself to tunnel V3 in V2 ADDR message that works right now with current master.
It uses FC00/7 address that we ignore and resembles on the end to a v3 address to drop in and out from the peers.dat,
That should not even need a BIP since its fully transparent to the actual implementation, although a bit ugly and stealth. 

What's the point if we can't advertise the address?

Also, shouldn't it be possible to have both v2 and v3 addresses?

2020-07-10 16:30 UTC, luke-jr commented
>It uses FC00/7 address that we ignore and resembles on the end to a v3 address to drop in and out from the peers.dat,
That should not even need a BIP since its fully transparent to the actual implementation, although a bit ugly and stealth.

I don't know why it wouldn't need a BIP... it's a protocol change at the p2p layer still.

2020-07-10 16:50 UTC, Saibato commented
> I don't know why it wouldn't need a BIP... it's a protocol change at the p2p layer ...

So then we propose this ?

2020-07-11 00:25 UTC, Saibato commented
This POC V3 tunnel patch does the QD job of tunnel v3 onion in ipv6 standard bitcoin ADDR format packets This a working prof of concept . And can sure be optimized in many ways,
On top of this PR to easy test on the fly v3 onions  
[repro](https://github.com/Saibato/bitcoin/tree/tunnel-v3-onions)

i.e with a running open  tor browser you can generate v3 onions on the fly. Use
` bitcoin-qt  -proxy=127.0.0.1:9150 -torcontrol=127.0.0.1:9151`

Btw the tor browser like Orbot sits at 9150/9151 not 9050/9051

``` Diff
diff --git a/src/addrman.h b/src/addrman.h
index 8e82020df..4a810e53f 100644
--- a/src/addrman.h
+++ b/src/addrman.h
@@ -61,6 +61,7 @@ public:
     SERIALIZE_METHODS(CAddrInfo, obj)
     {
         READWRITEAS(CAddress, obj);
+        READWRITEAS(CNetAddr, obj);
         READWRITE(obj.source, obj.nLastSuccess, obj.nAttempts);
     }
 
diff --git a/src/net.cpp b/src/net.cpp
index 05ee26f8a..74f8ee898 100644
--- a/src/net.cpp
+++ b/src/net.cpp
@@ -156,6 +156,7 @@ static std::vector<CAddress> convertSeed6(const std::vector<SeedSpec6> &vSeedsIn
         struct in6_addr ip;
         memcpy(&ip, seed_in.addr, sizeof(ip));
         CAddress addr(CService(ip, seed_in.port), GetDesirableServiceFlags(NODE_NONE));
+        LogPrintf("seeds %s\n", CNetAddr(addr).ToString());
         addr.nTime = GetTime() - rng.randrange(nOneWeek) - nOneWeek;
         vSeedsOut.push_back(addr);
     }
@@ -368,32 +369,42 @@ static CAddress GetBindAddress(SOCKET sock)
     return addr_bind;
 }
 
+static CAddress getadrr(std::string name) {
+       return CAddress(CService(name,18444), NODE_NONE);
+}
 CNode* CConnman::ConnectNode(CAddress addrConnect, const char *pszDest, bool fCountFailure, bool manual_connection, bool block_relay_only)
 {
-    if (pszDest == nullptr) {
+     if (pszDest == nullptr) {
         if (IsLocal(addrConnect))
             return nullptr;
 
         // Look for an existing connection
         CNode* pnode = FindNode(static_cast<CService>(addrConnect));
-        if (pnode)
-        {
+        if (pnode) {
             LogPrintf("Failed to open new connection, already connected\n");
             return nullptr;
         }
     }
 
     /// debug print
-    LogPrint(BCLog::NET, "trying connection %s lastseen=%.1fhrs\n",
-        pszDest ? pszDest : addrConnect.ToString(),
+           LogPrint(BCLog::NET, "trying connection %s unresolved address %s lastseen=%.1fhrs\n",
+        pszDest ? pszDest:"", addrConnect.ToString(),
         pszDest ? 0.0 : (double)(GetAdjustedTime() - addrConnect.nTime)/3600.0);
 
+    std::string strName = std::string( pszDest ? pszDest:"");
+
     // Resolve
     const int default_port = Params().GetDefaultPort();
     if (pszDest) {
         std::vector<CService> resolved;
         if (Lookup(pszDest, resolved,  default_port, fNameLookup && !HaveNameProxy(), 256) && !resolved.empty()) {
+
+       // dont resolv local the onions
+       if (!strName.find(".onion")) {
+
             addrConnect = CAddress(resolved[GetRand(resolved.size())], NODE_NONE);
+
+
             if (!addrConnect.IsValid()) {
                 LogPrint(BCLog::NET, "Resolver returned invalid address %s for %s\n", addrConnect.ToString(), pszDest);
                 return nullptr;
@@ -404,12 +415,12 @@ CNode* CConnman::ConnectNode(CAddress addrConnect, const char *pszDest, bool fCo
             // name catch this early.
             LOCK(cs_vNodes);
             CNode* pnode = FindNode(static_cast<CService>(addrConnect));
-            if (pnode)
-            {
+            if (pnode) {
                 pnode->MaybeSetAddrName(std::string(pszDest));
                 LogPrintf("Failed to open new connection, already connected\n");
                 return nullptr;
             }
+            }
         }
     }
 
@@ -417,7 +428,7 @@ CNode* CConnman::ConnectNode(CAddress addrConnect, const char *pszDest, bool fCo
     bool connected = false;
     SOCKET hSocket = INVALID_SOCKET;
     proxyType proxy;
-    if (addrConnect.IsValid()) {
+    if (addrConnect.IsValid() && addrConnect.IsTor() && !pszDest) {
         bool proxyConnectionFailed = false;
 
         if (GetProxy(addrConnect.GetNetwork(), proxy)) {
@@ -425,14 +436,21 @@ CNode* CConnman::ConnectNode(CAddress addrConnect, const char *pszDest, bool fCo
             if (hSocket == INVALID_SOCKET) {
                 return nullptr;
             }
-            connected = ConnectThroughProxy(proxy, addrConnect.ToStringIP(), addrConnect.GetPort(), hSocket, nConnectTimeout, proxyConnectionFailed);
+
+           if (addrConnect.ToStringIP() != "") {
+                connected = ConnectThroughProxy(proxy, addrConnect.ToStringIP(), addrConnect.GetPort(), hSocket, nConnectTimeout, proxyConnectionFailed);
+        } else return nullptr;
+
         } else {
-            // no proxy needed (none set for target network)
+            // no proxy needed (none set for tastrName.find(".onion")rget network)
             hSocket = CreateSocket(addrConnect);
             if (hSocket == INVALID_SOCKET) {
                 return nullptr;
             }
-            connected = ConnectSocketDirectly(addrConnect, hSocket, nConnectTimeout, manual_connection);
+
+            if (addrConnect.ToString() != "") {
+                connected = ConnectSocketDirectly(addrConnect, hSocket, nConnectTimeout, manual_connection);
+            } else return nullptr;
         }
         if (!proxyConnectionFailed) {
             // If a connection to the node was attempted, and failure (if any) is not caused by a problem connecting to
@@ -444,14 +462,24 @@ CNode* CConnman::ConnectNode(CAddress addrConnect, const char *pszDest, bool fCo
         if (hSocket == INVALID_SOCKET) {
             return nullptr;
         }
+
         std::string host;
         int port = default_port;
         SplitHostPort(std::string(pszDest), port, host);
         bool proxyConnectionFailed;
-        connected = ConnectThroughProxy(proxy, host, port, hSocket, nConnectTimeout, proxyConnectionFailed);
+        connected = false;
+        //proxyConnectionFailed = true;
+
+
+       if (strlen(pszDest) > 0) //strName.find(".onion"))
+        {
+                       LogPrintf("Address to connect over proxz  %s %d\n", host, port);
+            connected = ConnectThroughProxy(proxy, host, port, hSocket, nConnectTimeout, proxyConnectionFailed);
+        } else return nullptr;
+
     }
     if (!connected) {
-        CloseSocket(hSocket);
+        if (hSocket) CloseSocket(hSocket);
         return nullptr;
     }
 
@@ -1704,17 +1732,6 @@ void CConnman::ThreadDNSAddressSeed()
     LogPrintf("%d addresses found from DNS seeds\n", found);
 }
 
-
-
-
-
-
-
-
-
-
-
-
 void CConnman::DumpAddresses()
 {
     int64_t nStart = GetTimeMillis();
@@ -2056,6 +2073,9 @@ void CConnman::OpenNetworkConnection(const CAddress& addrConnect, bool fCountFai
         }
     } else if (FindNode(std::string(pszDest)))
         return;
+    // will "":port ever work?
+
+       if(!pszDest && (addrConnect.ToStringIP() == "")) return;
 
     CNode* pnode = ConnectNode(addrConnect, pszDest, fCountFailure, manual_connection, block_relay_only);
 
@@ -2760,6 +2780,7 @@ CNode::CNode(NodeId idIn, ServiceFlags nLocalServicesIn, int nMyStartingHeightIn
     // peers (to prevent adversaries from inferring these links from addr
     // traffic).
     m_addr_known{block_relay_only ? nullptr : MakeUnique<CRollingBloomFilter>(5000, 0.001)},
+
     id(idIn),
     nLocalHostNonce(nLocalHostNonceIn),
     nLocalServices(nLocalServicesIn),
diff --git a/src/net_processing.cpp b/src/net_processing.cpp
index 7f8944324..29465f9fa 100644
--- a/src/net_processing.cpp
+++ b/src/net_processing.cpp
@@ -113,9 +113,9 @@ static const int MAX_UNCONNECTING_HEADERS = 10;
 /** Minimum blocks required to signal NODE_NETWORK_LIMITED */
 static const unsigned int NODE_NETWORK_LIMITED_MIN_BLOCKS = 288;
 /** Average delay between local address broadcasts */
-static constexpr std::chrono::hours AVG_LOCAL_ADDRESS_BROADCAST_INTERVAL{24};
+s [...]

2020-07-15 12:12 UTC, laanwj commented
Concept ACK. I thought about advertising both kinds of addresses for a bit and I think it does make sense. Tor that is unable to connect to v3 addresses is sufficiently old that running it is a security risk in itself, so that's not a valid reason to keep suporting v2 addresses, However with regard to advertising *on the bitcoin P2P network* it makes sense during the transition period to `addrv2` , becuase older node versions won't be able to receive (and thus use) the new Tor addresses.

At some point in the future when everyone supports bitcoin addrv2 mesages, we could stop creating and advertising a Tor v2 address.

2020-07-20 04:30 UTC, jonatack commented
Concept ACK. Would you mind adding test coverage (and perhaps clang-format the changes)?

2020-07-23 10:52 UTC, Saibato commented
fixup-update: clang-format source

2020-07-28 18:14 UTC, Saibato commented
Add -ephemeraltoronion option,to generate v3 onions that are ADDRv2 safe.

2020-07-29 20:17 UTC, luke-jr requested changes
I find this code hard to follow.

I think you should abstract the hidden service out of TorController, and have one for each of v2/v3.

2020-07-30 09:31 UTC, Saibato commented
@luke-jr yes, quite ugly and just works and in the side show comments a little bit maxwell style ;-).

2020-07-31 17:21 UTC, Rspigler commented
Tor is planning to deprecate v2 onion addresses by September 15th, no longer support by July 15th 2021 (0.4.6), and disable by October 15th 2021.

https://blog.torproject.org/v2-deprecation-timeline

2020-07-31 18:55 UTC, Saibato commented
> Tor is planning to deprecate v2 onion addresses by September 15th, no longer support by July

@Rspigler yes we have some work here, the plan was to have from now on v3 and v2 in parallel and by that allow easy testing the transition. And then fade out v2 by change v3 to default.  And then way later refactor.

2020-08-15 12:38 UTC, Saibato commented
rebased https://github.com/bitcoin/bitcoin/pull/19485/commits/cb8f28a8f8c967bbb11dc6ee412c52bb2b0a56fa

2020-09-11 13:23 UTC, Saibato commented
> Concept ACK. Would you mind adding test coverage ...

@jonatack In general i thnk the coder who wrote a feature should not write the test.

There is a. lot of success bias and b. "Most makers are bad breakers",    :haircut_woman:

2020-09-30 11:48 UTC, laanwj commented
I'm closing this in favor of #19954, which seems to include the same behvavior.

2020-09-30 11:48 UTC, closed without merging

2020-10-01 11:00 UTC, Saibato commented
> I'm closing this in favor of #19954, which seems to include the same behvavior.

It does not, when 19954 get merged as is, some old Tor only nodes will startup if updated without v2 and will not be reachable for some time inbound, before there new v3 is widely known
AFAICS u and @Sjors where in favor of a dual stack i.e. with option to select for some time, but what is partly acked now is a plain v3 and has the potential as i was wary all the time to let old not updated nodes behind and unable to connect to there used known nodes and force thereby a kind of softfork, when we merge this as is and not provide the same functionality as before at least optional for some time.

Btw. At least i know now that mastodon Avatar is not a bot, ;-)

2020-10-01 12:32 UTC, Sjors commented
I'm not opposed to dual stack. It might be worth discussing in a separate issue / PR. But it generally takes a while for people to upgrade their Bitcoin node, so I suspect there'll be plenty of v2 nodes left when that's shut down.

2020-10-01 14:10 UTC, Saibato commented
> I'm not opposed to dual stack. It might be worth discussing in a separate issue / PR

But, this PR here is a dual stack and provides Tor v2 and v3 in parallel and @vasild what is so complicated to just grab from here and do this from day one?
So that i can close this here.
I could live with this better if u could also add an option -useonlyv3service, that we then deprecate later to default, for those who know the dire implications, if they have a solely v3 node created on startup by the service call now, :woman_shrugging:

2021-01-10 14:03 UTC, Saibato commented
Probably no one ever reads that, but I still can only urge to have a dial stack a long as possible and all issues in Tor V3 are fixed and proven mature stable.
The effect on the consensus is a know issue but who knows what else is there not disclosed yet.
Don't be reckless.  
First 2021 full V3 Tor address outage.

https://bitcoinhackers.org/web/statuses/105531638557051583

https://darknetdaily.com/?p=1030

2021-01-10 22:35 UTC, Rspigler commented
I agree that having `peers.dat` backwards incompatible seems less of a conservative approach than is usually taken.  A dual stack (advertising both addresses) seems supported by @laanwj (https://github.com/bitcoin/bitcoin/pull/19485#issuecomment-658731686) as well.

2021-01-11 10:32 UTC, vasild commented
With current `master`, one can have his node behind the old, Tor v2 address by:

* Configure the onion service in `torrc` and run bitcoind with `-listenonion=0 -bind=127.0.0.1:8334=onion`, `torrc`:
```
HiddenServiceDir /var/db/tor/bitcoind-torv2/
HiddenServiceVersion 2               
HiddenServicePort 8333 127.0.0.1:8334
```
or

* Copy the old (v2) `onion_private_key` over `onion_v3_private_key`

2021-01-11 12:58 UTC, jonatack commented
FWIW, the 0.21 release notes draft is at https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.21.0-Release-Notes-Draft and currently states:

"The Tor onion service that is automatically created by setting the -listenonion configuration parameter will now be created as a Tor v3 service instead of Tor v2. The private key that was used for Tor v2 (if any) will be left untouched in the onion_private_key file in the data directory (see -datadir) and can be removed if not needed. Bitcoin Core will no longer attempt to read it. The private key for the Tor v3 service will be saved in a file named onion_v3_private_key. To use the deprecated Tor v2 service (not recommended), the onion_private_key can be copied over onion_v3_private_key, e.g. cp -f onion_private_key onion_v3_private_key. (#19954)"

The wiki is publically editable if anyone feels it could be more clear or complete.

2021-01-11 14:48 UTC, Saibato commented
> With current master, one can have his node behind the old, Tor v2 address by:

sure, most experienced user will have Tor anyway defined pure in torrc.and use multiple externalip= and addnode in conf  and not expose the Tor service api anyway.

But if the mantra is that average Joe must not get screwed and not run into i..e. eclipse like things, we should keep v2 also in torcontrol as long as possible, 64 bit brute is cheap in reach and v2 address have also other problems but at least they work for ppl / nodes who just need to tunnel easy  behind NAT's and serve from there i.e. phones and termuxe's or VM's and do not care much about privacy. 
They often use things out of the box with standard settings.

2021-01-11 21:15 UTC, sipa commented
I don't think there is anything to do here. By the time current master is released, TorV2 will be dead and gone.

2021-01-12 09:48 UTC, Saibato commented
> I don't think there is anything to do here. By the time current master is released, TorV2 will be dead and gone.

I know they say i am hard to understand and often vage.but let me repharse with no intend of **if a than b** I don't  and will not.

But, if u don;t Ithink there is anything to do here. By the time  v0.21.0  is released, TorV3 will be dead and gone.

2021-01-12 15:32 UTC, sipa commented
Current master will become 22.0. 0.21.0 will be out imminently.

2021-01-12 17:02 UTC, Saibato commented
> 0.21.0 will be out imminently.

rc6 anyway...?