Replace `hidden service` with `onion service`
bitcoin/bitcoin pull request #19638
Opened 2020-08-01 13:19 UTC by RiccardoMasutti

For a couple of years, Tor documentation has made the term `hidden service` obsolete, in favor of `onion service`: [Tor Project | Onion Services](https://community.torproject.org/onion-services/)

This PR updates all the references.

2020-08-01 15:27 UTC, hebasto commented
Could it be done with a [scripted diff](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#scripted-diffs)?

2020-08-01 15:48 UTC, jonatack commented
Beyond the question of whether this is a change worth making and worth the review time it is requesting, it looks like this PR is a drive-by search and replace that touches a number of files that are auto-generated or not usually changed.

2020-08-01 17:35 UTC, Saibato commented
thx @RiccardoMasutti , for pointing this out and I somewhat like this kind of compliance on paper since disguise is the the sister of hidden,

,but as long 

tor source code;
./src/feature/rend/rendservice.h:

``` Code
  /* Other fields */
  crypto_pk_t *private_key; /**< Permanent hidden-service key. */
  char service_id[REND_SERVICE_ID_LEN_BASE32+1]; /**< Onion address without
                                                  * '.onion' */
  char pk_digest[DIGEST_LEN]; /**< Hash of permanent hidden-service key. */
  smartlist_t *intro_nodes; /**< List of rend_intro_point_t's we have,
                             * or are trying to establish. */
  /** List of rend_intro_point_t that are expiring. They are removed once
   * the new descriptor is successfully uploaded. A node in this list CAN
   * NOT appear in the intro_nodes list. */

```
names it, what it should be ?

So imho facts become not that different by wording.
But as this is kind of compliance on paper and disguise the the sister of hidden,
i somewhat like it.  

The moment even 
`HiddenServiceDir `parameter for use in torrc get renamed we should act.

2020-08-02 11:02 UTC, laanwj commented on src/qt/locale/bitcoin_en.ts
>      </message>
Please do not make manual changes to this file

2020-08-02 11:03 UTC, laanwj commented on doc/release-notes/release-notes-0.14.0.md
>  - #8567 `85d4e21` Add default port numbers to REST doc (djpnewton)
Please don't touch historical release notes.

2020-08-02 11:04 UTC, laanwj commented
Concept ACK. I think 'onion service' describes more concretely than 'hidden service' what is being talked about.

2020-08-02 11:22 UTC, jonatack commented on doc/man/bitcoin-qt.1
> +Automatically create Tor onion service (default: 1)
The first line of each of the `man` files states: `DO NOT MODIFY THIS FILE!  It was generated by...`

2020-08-03 15:52 UTC, practicalswift commented
Concept ACK assuming @laanwj's feedback is addressed

Welcome as a contributor @RiccardoMasutti! :)

2020-08-04 00:39 UTC, fanquake commented
You need to [squash your changes](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits) into a single commit, and use a proper commit message. i.e:

```bash
doc: replace hidden service with onion service

For a couple of years, Tor documentation has made 
the term hidden service obsolete, in favor of onion 
service.

This PR updates all the references in the code base.
```

2020-08-04 11:29 UTC, RiccardoMasutti commented
@fanquake @laanwj It should be okay now. Can you review it again please?

Ps: it's my first time squashing commits via git, and I'm really happy to have learned it. Usually I relied on GitHub repo maintainers who have the ability to do `merge and squash`

2020-08-04 11:47 UTC, jonatack commented on doc/tor.md
> +preconfigured and the creation of a onion service is automatic. If permission problems
s/a onion/an onion/ here and also lines 22 and 101

2020-08-04 12:56 UTC, practicalswift commented
ACK f2cd7a4dc93ac117438887cabe6dd095ecf611aa -- patch looks correct

2020-08-06 03:47 UTC, hebasto requested changes
Please change here: https://github.com/bitcoin/bitcoin/blob/19f812c57b420ae3e9ab5a95335e2adb5f54faf0/src/qt/forms/optionsdialog.ui#L460-L467

2020-08-06 16:37 UTC, laanwj commented
> Welcome as a contributor @RiccardoMasutti! :)

Yes and thanks for sticking with this, most admit that it's not really documented anywhere which files you are and are not allowed to change.

2020-08-07 13:02 UTC, RiccardoMasutti commented
@laanwj ready to merge

2020-08-07 16:51 UTC, hebasto approved these changes
ACK 1e72b68ab330c72644981508c8a1b3fa670d086f, tested on Linux Mint 20 (x86_64).

The GUI-related changes:
- master: 
![DeepinScreenshot_select-area_20200807194930](https://user-images.githubusercontent.com/32963518/89668990-5e569900-d8e7-11ea-9aa0-5bf7735ada52.png)
- this PR:
![DeepinScreenshot_select-area_20200807194725](https://user-images.githubusercontent.com/32963518/89669019-6a425b00-d8e7-11ea-94ed-bcc9f5a612f8.png)

2020-08-09 13:02 UTC, laanwj commented
Code review ACK 1e72b68ab330c72644981508c8a1b3fa670d086f

2020-08-09 13:09 UTC, merged