test: Rename wait until helper to wait_until_helper
bitcoin/bitcoin pull request #19816
Opened 2020-08-27 06:52 UTC by MarcoFalke

This avoid confusion with the `wait_until` member functions, which should be preferred because they take the appropriate locks and scale the timeout appropriately on their own.

2020-08-27 09:33 UTC, hebasto requested changes
Approach ACK fa1850fb59e4697622fa00c640f9fc6e18ee1a8d

2020-08-27 09:33 UTC, hebasto commented on test/functional/test_framework/util.py
>      from `P2PInterface` class in `mininode.py` has a preset lock.
fa40d0291427922e85e579def2b616d02a01b15b
See #19760:
```suggestion
    from `P2PInterface` class in `p2p.py` has a preset lock.
```

2020-08-27 09:48 UTC, MarcoFalke commented on test/functional/test_framework/util.py
>      from `P2PInterface` class in `mininode.py` has a preset lock.
thx, fixed

2020-08-28 10:48 UTC, theStack commented
Concept ACK

2020-09-01 11:39 UTC, laanwj commented
Code review ACK fa1cd9e1ddc6918c3d600d36eadea71eebb242b6

2020-09-01 13:55 UTC, hebasto approved these changes
ACK fa1cd9e1ddc6918c3d600d36eadea71eebb242b6, I have reviewed the code and it looks OK, I agree it can be merged.

2020-09-03 04:08 UTC, merged