BIP-322 support
bitcoin/bitcoin pull request #20154
Opened 2020-10-15 12:48 UTC by kallewoof

This is my WIP on BIP 322 support. It is based on the not yet merged pull request which significantly changes how BIP-322 does message signing: https://github.com/bitcoin/bips/pull/1003

2020-10-24 19:04 UTC, luke-jr requested changes
Incomplete review.

2020-10-24 19:04 UTC, luke-jr commented on src/qt/signverifymessagedialog.cpp
> +            tr("Message inconclusive (your node may need to be upgraded to validate new upgradable rules).")
This might need rephrasing to avoid an attack where someone uses this to trick a user into "upgrading" to malware...

2020-10-24 19:04 UTC, luke-jr commented on src/qt/signverifymessagedialog.cpp
> +            tr("Message valid, but encumbered by an unexpired time lock.")
This is probably confusing to end users.

2020-10-24 19:04 UTC, luke-jr commented on src/rpc/misc.cpp
> +                    {"inputs", RPCArg::Type::ARR, RPCArg::Optional::OMITTED_NAMED_ARG, "UTXOs in a proof of funds",
This should probably be an alternative to position 1 ("address"), and support a simpler "amount" usage.

2020-10-24 19:04 UTC, luke-jr commented on src/wallet/rpcwallet.cpp
> +            {"address", RPCArg::Type::STR, "", "Address to prove (should be omitted when including inputs)"},
Funds don't have addresses. This makes no sense.

2020-10-24 19:04 UTC, luke-jr commented on src/wallet/rpcwallet.cpp
> +            {"inputs", RPCArg::Type::ARR, RPCArg::Optional::OMITTED_NAMED_ARG, "UTXOs in a proof of funds",
Should probably have a simpler amount-only alternative.

2020-12-29 06:17 UTC, kallewoof commented
The BIP is changing substantially. Will revisit when that's done.

@luke-jr Thanks for the feedback. Will take it into consideration.

2020-12-29 06:17 UTC, closed without merging