p2p:  update wtxidrelay documentation per BIP339
bitcoin/bitcoin pull request #20592
Opened 2020-12-07 18:30 UTC by jonatack

BIP339 currently states:

*The wtxidrelay message MUST be sent in response to a version message from a peer whose protocol version is >= 70016 and prior to sending a verack. A wtxidrelay message received after a verack message MUST be ignored or treated as invalid.*

2020-12-07 18:43 UTC, MarcoFalke commented
ACK 4b7b58b3fef5b9566a475871c441ed6ae73af89e

Though, let's wait on merging this to make sure this doesn't cause any conflicts with pending backports

2020-12-08 06:30 UTC, practicalswift commented
ACK 4b7b58b3fef5b9566a475871c441ed6ae73af89e

2020-12-10 12:56 UTC, RiccardoMasutti requested changes
ACK 4b7b58b

2020-12-14 02:19 UTC, luke-jr approved these changes
ACK

2020-12-14 09:55 UTC, merged