rpc: Allow to ignore specific policy reject reasons
bitcoin/bitcoin pull request #20753
Opened 2020-12-23 16:01 UTC by MarcoFalke

The `-acceptnonstdtxn` footgun is only enabled for regtest/testnet due to several shortcomings:
* It can't be changed without restarting the node
* It applies to all txs and all reject reasons

This pull adds a new optional RPC parameter to ignore specific reject reasons for a specific tx.

2020-12-23 17:11 UTC, luke-jr requested changes
What's the goal of reinventing this rather than just reopening and reviewing #7533 (which is still maintained)?

2020-12-23 17:11 UTC, luke-jr commented on src/bench/block_assemble.cpp
> +            bool ret{::AcceptToMemoryPool(*test_setup.m_node.mempool, state, txr, nullptr /* plTxnReplaced */, {} /* ignore_rejects */, false /* bypass_limits */)};
IMO [the const empty_ignore_rejects](https://github.com/bitcoin/bitcoin/pull/7533/files#diff-1fc0f6b5081e8ed5dfa8bf230744ad08cc6f4c1147e98552f1f424b0492fe9bdR79) is cleaner.

2020-12-23 17:11 UTC, luke-jr commented on src/policy/policy.cpp
> +            MAYBE_REJECT(reason, "bare-multisig", ignore_rejects);
[The `else` below needs to go too, or we accidentally also ignore dust multisigs](https://github.com/luke-jr/bitcoin/commit/e786e726d4a0b8e68aa87bd38dfac4aeecc76be6#diff-ea6d307faa4ec9dfa5abcf6858bc19603079f2b8e110e1d62da4df98f4bdb9c0R174)

2020-12-29 10:14 UTC, jnewbery commented
I think this needs more motivation. Without a strong reason to do this, I tend to agree with the comments on #7533:

- "I'm not convinced about the need to ignore based on the exact reason (as that is likely something that's hard to maintain, as reasons change over time)." (https://github.com/bitcoin/bitcoin/pull/7533#issuecomment-292789614)
- "This is not going to be maintainable for API clients." (https://github.com/bitcoin/bitcoin/pull/7533#issuecomment-314520218)
- "making this too granular makes this unmaintainable as rejection reasons might come and go, or implemented differently, as policy changes. After all, policy is not standardized." (https://github.com/bitcoin/bitcoin/pull/7533#issuecomment-331264593)

2020-12-29 10:25 UTC, MarcoFalke commented
The reasons can only change if the server version changes. And the policy reject reasons may already change in all other RPCs (e.g. `sendrawtransaction`), so I don't see how this pull makes any difference. If you have specific concerns, it would be good to elaborate them with an example, so that it is easier to understand them.

2020-12-29 11:00 UTC, MarcoFalke commented
To extend my reply a bit: Currently it is only possible to override the baked-in behavior for some very specific policy checks via command line (e.g. `-dustrelayfee`) for all network and rpc transactions. The goal of this change is to allow to override policy reject reasons while also giving the user more flexibility than an "on-off" `-acceptnonstdtxn` setting. The reason that `-acceptnonstdtxn` is disabled is that it wouldn't be safe to turn on in normal operation for the default user. So I think the flexibility to have a per-tx override without restarting the node is useful. Maybe even outside the primary use case of one-off manual sends.

Simply having broader categories (or even a single category) doesn't solve the problem that policy changes between versions.

2020-12-29 16:08 UTC, luke-jr commented
(Concept ACK, will review code in detail later)

2020-12-29 19:02 UTC, sipa commented
Concept NACK on exposing this for mainnet. That seems like a huge footgun, even with the warning. What is the use case?

2020-12-30 08:53 UTC, MarcoFalke commented
One use case is to accept a transaction as a miner that has a large fee, but violates a policy limit (e.g. tx-version, dust, ...) and thus has issues to propagate the network and be accepted to the likely-default mempool the miner is running. If someone is using this without thinking, it might lead to issues, just like `invalidateblock` may lead to issues when using without thinking.

2020-12-30 08:58 UTC, stevenans9859 approved these changes

2020-12-30 17:01 UTC, luke-jr commented
Where is the footgun? Many policies are based on DoS risk, which doesn't exist if there's a user actively trying to add a transaction.

As for use cases, I know one real-world case where a user accidentally used an uncompressed key for a segwit address. He's figured out his mistake, and in theory he should be able to recover his coins, but he hasn't convinced any miners (last I checked) to modify their software to accept it. (This PR might not be enough to get that one past, but it demonstrates that there are legitimate needs to override policies.)

2020-12-31 23:55 UTC, glozow commented
I can imagine a user wanting to look at a transaction just based on consensus rules and not policy... `testmempoolaccept` will currently tell you exactly which policy a tx is failing; if a user wants to know "does my transaction pass _just_ consensus rules otherwise?" I think ability to toggle on/off might make sense. But if a user is trying to get a nonstandard tx included in a block and can't get a miner to accept it directly, how does this help? Core nodes still wouldn't (and shouldn't) relay it. Unless someone is planning to mine the tx themselves (not the typical user?) it would just be garbage sitting in their local mempool right?

2021-01-01 10:59 UTC, MarcoFalke commented
Correct, the transaction won't relay typically. (Unless you know that you are running an old version of Bitcoin Core to relay a tx that future versions of Bitcoin Core consider policy-"valid", but this is probably an edge case). Thus, I think the primary user of this feature is a miner. (And maybe some power users that know exactly what they are doing).


>  I think ability to toggle on/off might make sense.

I am happy to explore this direction. Though, `testmempoolaccept` will only tell you the *first* policy-failure reason, not the second one. So I was thinking that it might be safer to supply all failure reasons explicitly instead of hoping there was only one.

Another option would be for `testmempoolaccept` to continue and collect all policy-failures on the way and return all of them instead of only the first? This would make an on/off switch safe again, I believe.

2021-01-01 14:42 UTC, luke-jr commented
>But if a user is trying to get a nonstandard tx included in a block and can't get a miner to accept it directly, how does this help?

This is *how* a miner would accept it directly.

>Another option would be for testmempoolaccept to continue and collect all policy-failures on the way and return all of them instead of only the first?

This seems like a good idea regardless.

2021-01-01 19:46 UTC, glozow commented
> This is _how_ a miner would accept it directly.

Ah ok. Then, wrt maintainability, it still seems simpler to just set policy on/off entirely?

> Another option would be for `testmempoolaccept` to continue and collect all policy-failures on the way and return all of them instead of only the first? This would make an on/off switch safe again, I believe.

That sounds nice. Although I'd say it's tricky to implement - what we might consider individual policies aren't really mutually exclusive and we usually stop after the first violation because later checks would break / say the same thing but be more expensive. For example [too small](https://github.com/bitcoin/bitcoin/blob/e75f91eae3936269b40b4bfdfe540d5526270936/src/validation.cpp#L582) or [scriptSig size](https://github.com/bitcoin/bitcoin/blob/e75f91eae3936269b40b4bfdfe540d5526270936/src/policy/policy.cpp#L95). Would we run `EvalScript` multiple times for the [standard flags](https://github.com/bitcoin/bitcoin/blob/e75f91eae3936269b40b4bfdfe540d5526270936/src/policy/policy.h#L60)? I suppose this is where inputs specifying which policies to exclude would make sense, but still requires policy to be well-enumerated/defined.

2021-01-01 22:47 UTC, jnewbery commented
> Although I'd say it's tricky to implement - what we might consider individual policies aren't really mutually exclusive and we usually stop after the first violation because later checks would break / say the same thing but be more expensive.

Absolutely agree with this. Mempool acceptance logic should be optimized towards simplicity and performance. Making the internal logic more complex so that we can return additional debugging information over an interface that we can't guarantee to be stable doesn't seem like the right decision to me.

2021-01-03 18:16 UTC, MarcoFalke commented
> > Although I'd say it's tricky to implement - what we might consider individual policies aren't really mutually exclusive and we usually stop after the first violation because later checks would break / say the same thing but be more expensive.
> 
> Absolutely agree with this. Mempool acceptance logic should be optimized towards simplicity and performance. Making the internal logic more complex so that we can return additional debugging information over an interface that we can't guarantee to be stable doesn't seem like the right decision to me.

We already return the failure reason, and it is already not stable, so this wouldn't change anything fundamentally. Also, this doesn't change performance of mempool acceptance logic if not enabled. Yes, it might run checks that aren't mutually exclusive, but what is the problem with that if the user explicitly asks to do that. A user might also rescan the wallet in a loop, even though it has already been rescanned.

2022-07-22 13:19 UTC, closed without merging