Use C++17 std::array deduction for OUTPUT_TYPES, ALL_FEE_ESTIMATE_HORIZONS
bitcoin/bitcoin pull request #20787
Opened 2020-12-28 16:00 UTC by MarcoFalke

With the new C++17 array deduction rules, an array encompassing all values in an enum can be specified in the same header file that specifies the enum. This is useful to avoid having to repeatedly enumerate all enum vales in the code. E.g. the RPC code, but also the fuzz code.

2020-12-28 21:06 UTC, practicalswift commented
Concept ACK

2020-12-29 03:35 UTC, mjdietzx commented
ack fa6a79d859c82c2efc0cf7227cea922d5fc5d55a

2020-12-29 07:57 UTC, MarcoFalke commented
@mjdietzx Your `ack` won't get picked up by the merge script, btw. It needs to be any kind of `ACK`.

2020-12-29 08:21 UTC, jonatack commented
(@mjdietzx see https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/68 for context)

2020-12-29 14:39 UTC, vasild approved these changes
ACK fa6a79d859c82c2efc0cf7227cea922d5fc5d55a

2020-12-29 15:44 UTC, jonatack reviewed
ACK fa6a79d859c82c2efc0cf7227cea922d5fc5d55a

Thanks for the offline explanation @MarcoFalke on the differences between C++11 and C++17 std::array.

2021-01-03 17:01 UTC, theStack requested changes
Concept ACK

There are two more instances where the `ALL_FEE_ESTIMATE_HORIZONS` can be used now (found via `git grep SHORT_HALFLIFE`): 

```diff
diff --git a/src/test/fuzz/policy_estimator.cpp b/src/test/fuzz/policy_estimator.cpp
index 8a17a4b51..0562fc552 100644
--- a/src/test/fuzz/policy_estimator.cpp
+++ b/src/test/fuzz/policy_estimator.cpp
@@ -66,10 +66,10 @@ FUZZ_TARGET_INIT(policy_estimator, initialize_policy_estimator)
         }
         (void)block_policy_estimator.estimateFee(fuzzed_data_provider.ConsumeIntegral<int>());
         EstimationResult result;
-        (void)block_policy_estimator.estimateRawFee(fuzzed_data_provider.ConsumeIntegral<int>(), fuzzed_data_provider.ConsumeFloatingPoint<double>(), fuzzed_data_provider.PickValueInArray({FeeEstimateHorizon::SHORT_HALFLIFE, FeeEstimateHorizon::MED_HALFLIFE, FeeEstimateHorizon::LONG_HALFLIFE}), fuzzed_data_provider.ConsumeBool() ? &result : nullptr);
+        (void)block_policy_estimator.estimateRawFee(fuzzed_data_provider.ConsumeIntegral<int>(), fuzzed_data_provider.ConsumeFloatingPoint<double>(), fuzzed_data_provider.PickValueInArray(ALL_FEE_ESTIMATE_HORIZONS), fuzzed_data_provider.ConsumeBool() ? &result : nullptr);
         FeeCalculation fee_calculation;
         (void)block_policy_estimator.estimateSmartFee(fuzzed_data_provider.ConsumeIntegral<int>(), fuzzed_data_provider.ConsumeBool() ? &fee_calculation : nullptr, fuzzed_data_provider.ConsumeBool());
-        (void)block_policy_estimator.HighestTargetTracked(fuzzed_data_provider.PickValueInArray({FeeEstimateHorizon::SHORT_HALFLIFE, FeeEstimateHorizon::MED_HALFLIFE, FeeEstimateHorizon::LONG_HALFLIFE}));
+        (void)block_policy_estimator.HighestTargetTracked(fuzzed_data_provider.PickValueInArray(ALL_FEE_ESTMATE_HORIZONS));
     }
     {
         FuzzedAutoFileProvider fuzzed_auto_file_provider = ConsumeAutoFile(fuzzed_data_provider);
```

2021-01-03 17:40 UTC, MarcoFalke commented
Rebased on the already merged #20812 to fix the feedback by @theStack

2021-01-03 18:15 UTC, theStack approved these changes
cr ACK aaaa9878405f3f38f4f61c00feca110d7f9ca481 ⚙️

2021-01-11 13:45 UTC, fanquake approved these changes
ACK aaaa9878405f3f38f4f61c00feca110d7f9ca481

2021-01-11 13:46 UTC, merged