doc: Add explicit macdeployqtplus dependencies install step
bitcoin/bitcoin pull request #20890
Opened 2021-01-08 21:59 UTC by hebasto

This change is required on macOS 11 Big Sur:

-  #20371
- #20878

Close #20878.

2021-01-09 00:40 UTC, jarolrod commented
ACK aaa7b294f8323b0087b090180819aeadcf42a826

Confirming that without installing `argparse`, `ds_store`, `mac_alias`, make deploy fails on macOS Big Sur 11.1.

Deploying DMG is successful after installing these packages with `pip3`.

2021-01-09 00:41 UTC, jarolrod reviewed
ACK aaa7b294f8323b0087b090180819aeadcf42a826

Confirming that without installing `argparse`, `ds_store`, `mac_alias`, make deploy fails on macOS Big Sur 11.1.

Deploying DMG is successful after installing these packages with `pip3`.

2021-01-09 06:52 UTC, fanquake requested changes

2021-01-09 07:38 UTC, hebasto commented on doc/build-osx.md
> +pip3 install argparse ds_store mac_alias
> argparse is part of the Python standard library.

Indeed: https://docs.python.org/3/library/argparse.html

> It doesn't need installing.

Fixed.

2021-01-09 07:59 UTC, hebasto commented
Updated aaa7b294f8323b0087b090180819aeadcf42a826 -> 3e61b8c800180d350621cedda7ec46a48047ff04 ([pr20890.02](https://github.com/hebasto/bitcoin/commits/pr20890.02) -> [pr20890.03](https://github.com/hebasto/bitcoin/commits/pr20890.03), [diff](https://github.com/hebasto/bitcoin/compare/pr20890.02..pr20890.03)):

- addressed @fanquake's [comment](https://github.com/bitcoin/bitcoin/pull/20890#discussion_r554273503):
> argparse is part of the Python standard library. It doesn't need installing.

2021-01-10 07:02 UTC, fanquake approved these changes
ACK 3e61b8c800180d350621cedda7ec46a48047ff04

> This change is required on macOS 11 Big Sur:

There's nothing macOS 11 specific about this doc addition. The  same dependencies & dmg creation process is used you run `make deploy` on macOS 10.

2021-01-10 07:03 UTC, merged