contrib: embed C++11 patch in install_db4.sh
bitcoin/bitcoin pull request #20906
Opened 2021-01-11 17:55 UTC by gruve-p

This is a continuation of https://github.com/bitcoin/bitcoin/pull/20665

2021-01-12 10:05 UTC, jonasschnelli requested changes

2021-01-12 10:05 UTC, jonasschnelli commented on contrib/install_db4.sh
> + 			__db_errx(env,
Where is the `DB_STR("3025",` gone?

2021-01-12 10:05 UTC, jonasschnelli commented on contrib/install_db4.sh
> + 			MVCC_MPROTECT(bhp->buf, mfp->stat.st_pagesize,
This was `MVCC_MPROTECT(bhp->buf, mfp->pagesize,` before.

2021-01-12 10:05 UTC, jonasschnelli commented on contrib/install_db4.sh
> + 		hp->mtx_hash = (mtx_base == MUTEX_INVALID) ? MUTEX_INVALID :
```diff
-@@ -269,7 +269,7 @@ __memp_init(env, dbmp, reginfo_off, htab_buckets, max_nreg)
- 		hp->mtx_hash = (mtx_base == MUTEX_INVALID) ? MUTEX_INVALID :
- 		    mtx_base + i;
+@@ -302,7 +302,7 @@ no_prealloc:
+ 		} else
+ 			hp->mtx_hash = mtx_base + (i % dbenv->mp_mtxcount);
```

2021-01-12 10:09 UTC, gruve-p commented
@jonasschnelli The patch is an exact copy of https://github.com/bitcoin/bitcoin/blob/master/depends/patches/bdb/clang_cxx_11.patch

2021-01-12 13:07 UTC, laanwj commented
Concept ACK

2021-01-13 07:38 UTC, fanquake approved these changes
ACK 92370033a2606ee88f4d080193e0bf6da481dc2e. 

I checked that the patch is the same as what we carry in depends, and that the `*.a`s produced by the script are identical between master and this PR on macOS and Linux. i.e on macOS:
```bash
# master 7b975639ef93b50537a3ec6326b54d7218afc8da
CFLAGS="-Wno-error=implicit-function-declaration" ZERO_AR_DATE=1 ./contrib/install_db4.sh $(pwd)
mv db4 db4_master
# checkout #20906
CFLAGS="-Wno-error=implicit-function-declaration" ZERO_AR_DATE=1 ./contrib/install_db4.sh $(pwd)
diffoscope db4/lib db4_master/lib/ --exclude-directory-metadata=yes
```

2021-01-14 12:09 UTC, practicalswift commented
Concept ACK: in-repo is more robust and easier to review than out-of-repo :)

2021-01-15 21:26 UTC, jamesob commented
I am concept ACK on this, but why did you choose to change the patch format? This makes the change more difficult to review.

2021-01-15 21:31 UTC, gruve-p commented
@jamesob The patch format is exactly the same as we use for depends: https://github.com/bitcoin/bitcoin/blob/master/depends/patches/bdb/clang_cxx_11.patch

2021-01-19 16:29 UTC, laanwj commented
It would have been easier for reviewers if you made it clear in the PR description that this is now using the `depends/patches/bdb/clang_cxx_11.patch` and not the one from the gist.

Anyhow—I checked that it (apart from whitespace) matches.

ACK 92370033a2606ee88f4d080193e0bf6da481dc2e

2021-01-19 16:30 UTC, merged