validation: don't try to invalidate genesis block in CChainState::InvalidateBlock
bitcoin/bitcoin pull request #20921
Opened 2021-01-13 00:25 UTC by theStack

In the block invalidation method (`CChainState::InvalidateBlock`), the code for creating the candidate block map assumes that the passed block's previous block (`pindex->pprev`) is available and otherwise segfaults due to null-pointer deference in `CBlockIndexWorkComparator()` (see analysis by practicalswift in #20914), i.e. it doesn't work with the genesis block. Rather than analyzing all possible code paths and implications for this corner case, simply fail early if the genesis block is passed.

Fixes #20914.

2021-01-13 16:12 UTC, luke-jr approved these changes
utACK

2021-02-03 05:48 UTC, ViralTaco commented on src/validation.cpp
> +    if (pindex->nHeight == 0) return false;
This is actually not preventing UB, it's adding more.

2021-02-03 06:02 UTC, ViralTaco requested changes
Add `nullptr` check for `pindex` in `BlockValidationState&, CChainParams const&, CBlockIndex*)`

I'm sorry I can't commit I need to setup the environment

2021-02-09 23:16 UTC, theStack commented
@ViralTaco: Agree that there should also be a null pointer check `pindex` before access. Solved this now by adding a simple `assert` (alternatively one could change the parameter to a reference).

2021-03-19 02:24 UTC, sipa commented
ACK 787df19b09babf50dd8124b3ac990b29c33cfe93. Tested invalidation of generic on regtest.

Would be nice to add a functional test that attempts this, so that it gets detected if it were reintroduced.

2021-03-19 21:02 UTC, practicalswift commented
Tested ACK 787df19b09babf50dd8124b3ac990b29c33cfe93

Before:

```
$ git checkout master
$ make distclean
$ ./autogen.sh
$ CC=clang CXX=clang++ ./configure --with-sanitizers=address,undefined
$ make
$ src/bitcoind -regtest &
$ src/bitcoin-cli -regtest generatetodescriptor 1 'addr(bcrt1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3xueyj)#juyq9d97'
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
validation.cpp:89:30: runtime error: member access within null pointer of type 'const CBlockIndex'
==11604==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000044 (pc 0x56387ee23e87 bp 0x000000000008 sp 0x7f3a6e1b6570 T16)
==11604==The signal is caused by a READ memory access.
==11604==Hint: address points to the zero page.
```

After:

```
$ gh pr checkout 20921
$ make -C src/ bitcoind
$ src/bitcoind -regtest &
$ src/bitcoin-cli -regtest generatetodescriptor 1 'addr(bcrt1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3xueyj)#juyq9d97'
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
$ jobs
[1]+  Running                 src/bitcoind -regtest &
```

2021-03-20 11:47 UTC, merged