[RFC] docs: update developer notes to discourage very long lines
bitcoin/bitcoin pull request #20986
Opened 2021-01-22 10:04 UTC by jnewbery

Mandatory rules on line lengths are bad - there will always be cases where a longer line is more readable than the alternative.

However, very long lines for no good reason _do_ hurt readability. For example, this declaration in validation.cpp is 274 chars:

```c++
    bool ConnectTip(BlockValidationState& state, const CChainParams& chainparams, CBlockIndex* pindexNew, const std::shared_ptr<const CBlock>& pblock, ConnectTrace& connectTrace, DisconnectedBlockTransactions& disconnectpool) EXCLUSIVE_LOCKS_REQUIRED(cs_main, m_mempool.cs);
```

That won't fit on one line without wrapping on my 27" monitor with a comfortable font size. Much easier to read is something like:

```c++
    bool ConnectTip(BlockValidationState& state, const CChainParams& chainparams,
                    CBlockIndex* pindexNew, const std::shared_ptr<const CBlock>& pblock,
                    ConnectTrace& connectTrace, DisconnectedBlockTransactions& disconnectpool)
        EXCLUSIVE_LOCKS_REQUIRED(cs_main, m_mempool.cs);
```

Therefore, _discourage_ (don't forbid) line lengths greater than 100 characters in our developer style guide.

100 chars is somewhat arbitrary. The old standard was 80, but that seems very limiting with modern displays.

2021-01-22 10:04 UTC, jnewbery commented
Marking as draft for now. I expect people will have **opinions**.

2021-01-22 10:48 UTC, hebasto commented
Concept ACK. And forbid refactoring pulls just to make lines shorter.

2021-01-22 11:27 UTC, jonatack commented
The primary issue I experience as a reviewer is reformatting of lines, especially function signatures or function calls, to make lines shorter. It adds churn, obfuscates the diff and makes review more fatiguing, difficult and error-prone than it otherwise needed to be.

(The example in the PR description is more readable to me in one line than split into several.)

2021-01-22 12:10 UTC, jnewbery commented
> The primary issue I experience as a reviewer is reformatting of lines, especially function signatures or function calls, to make lines shorter.

My take on this is that if I need to add an argument to a 230 char wide function declaration, then I'd much prefer to split that line then turn it into a 260 char wide function declaration. The alternative results in lines that just grow without bound.

> ... obfuscates the diff and makes review more fatiguing, difficult and error-prone than it otherwise needed to be.

In my experience, it's pretty easy to see which changes are whitespace only, eg in meld:

![image](https://user-images.githubusercontent.com/1063656/105488522-ab69d400-5ca9-11eb-940f-2b7d8a6a6245.png)

compared to this for adding a new argument to a very long line:

![image](https://user-images.githubusercontent.com/1063656/105488605-ca686600-5ca9-11eb-917a-b997398726ed.png)

> The example in the PR description is more readable to me in one line than split into several

Can you share a screenshot? In my editor, with a column width of 126 chars, it looks like:

![image](https://user-images.githubusercontent.com/1063656/105489004-71e59880-5caa-11eb-9017-c9d719c6b42d.png)

which I find very difficult to read.

2021-01-22 13:51 UTC, theStack commented
Concept ACK.
The long lines have been bothering me for quite some time and I think in the long-term following this guideline will increase code quality. Agree with hebasto though that refactor PRs with the sole goal of line-shortening should be discouraged. (On the other hand, I think many reasonable refactorings _will_ as a side-effect lead to shorter lines.)

From a practical point of view, I personally (and know many people who do) enjoy being able to view two source code files side-by-side without line breaks on a single modern screen, and while 80 is likely too low, decades after 80x25 terminals were widespread (there has been an interesting discussion on the Linux Kernel Mailing List about this subject: https://lkml.org/lkml/2020/5/29/1038), a soft-limit of 100 seems to be a good compromise here. If 100 is still too low for some, the absolute maximum should be a number that is still visible on a single screen without line breaks. Lines longer than 180-200 chars are absolutely inacceptable, IMHO. And unfortunately, we have many instances of those, especially in `src/validation.cpp`.

> The primary issue I experience as a reviewer is reformatting of lines, especially function signatures or function calls, to make lines shorter. It adds churn, obfuscates the diff and makes review more fatiguing, difficult and error-prone than it otherwise needed to be.

Tend to agree with jnewbery here, that this can be solved by right usage of the diff-tool. In an ideal world the creator of commit would always put a review options suggestions in a commit message where the regular diff is hard to read. This is happening already, e.g. "best reviewed with -w --color-moved=..." etc. The drawback is that this doesn't work with the rendered diff online on github, but this shouldn't be encouraged anyways.

In the long term, after this rule with roughly be followed for quite some time, if there is still many instances where changes introduce line-breaks, there is more likely something wrong with the code. I don't think that having lots of functions/methods with 5+ parameters is desirable. Hence I would hope that in the long-term, with this rule applied the functions/methods are designed in a way most calls would still likely fit in a single line.

2021-01-22 14:33 UTC, jonatack commented
I review in buffers or screens of varying widths. For the diff I usually start with gitk (which I believe is widely used), or git in the terminal with -w / colorMoved = dimmed-zebra / colorMovedWs = allow-indentation-change. I'm open to suggestions on diff tooling or how I can use them better.

Adding a param to a long function without otherwise reformatting it is a trivial diff to review in gitk, but adding reformatting churn makes it more difficult, fatiguing and error-prone as the entire signature has to be reviewed, param by param. This reached the point where I stopped reviewing a couple of pulls lately (one of yours, John, and #20788) because there were several long function signatures being reformatted in a way that needlessly increased the review burden with no benefit. More work for the author, more work for the reviewers. In both cases I gave feedback on that, to no avail...and told myself that to say nothing more and add a caveat to my review that I did not verify (or do not have confidence in my verification of) all the parameters in the reformatted function signatures. I don't see justification or benefit in adding churn that entails the need for that, but this is open source--it's ad hoc and everyone has their point of view.

At the end of the day, I suppose it's the author's prerogative to propose churn and the reviewer's prerogative to review or not or give feedback or just shrug and move on. Some authors can get away with it, but I have enough difficulty attracting review (and the situation has not improved over the past two years from my point of view) that I try to make my proposals easy to review (I often don't succeed, but I try).

2021-01-22 14:56 UTC, jonatack commented
> Can you share a screenshot? In my editor, with a column width of 126 chars, it looks like:
> 
> ![image](https://user-images.githubusercontent.com/1063656/105489004-71e59880-5caa-11eb-9017-c9d719c6b42d.png)

Yes, the code looks like that in the editor for me, too. I did mind in the beginning (after decades of 80 or 100 character limits this codebase was a...change) but I suppose I adapted to it and in this codebase with its sometimes long function signatures, I grok why it was done and like it. Perhaps line wrapping is more predictable and easier for me to follow on different screen sizes than arbitrary line breaks. Anyway, that's only an opinion :tm:.

2021-01-22 15:22 UTC, theStack commented
@jonatack: Hm, I see your point of view. Though it's very reviewers-centric and not taking into account potential new contributors which could also be turned off just by seeing those long lines. (And overly huge function/method bodies, but that's another topic...)

I think in cases like #20788 where really lots of those line-breaks occur, the root of the problem is that stylistic changes and logical changes are mixed in one. It would make sense to first have an isolated commits that solely refactors the line-breaks, which could in theory be verified automatically (not sure if such a tool already exists, but I think it could be possible to "normalize" all white-space in two source files and then compare if they are still identical) and then based on this do the actual function signature changes. Reviewing the logical change would then be a piece of cake.

For example, instead of having a single commit that suffers from your described problem:
```diff
-static bool Socks5(const std::string& strDest, int port, const ProxyCredentials *auth, const SOCKET& hSocket)
+static bool Socks5(const std::string& strDest,
+                   int port,
+                   const ProxyCredentials* auth,
+                   const Sock& sock)
```
you would have a pure-line-break-refactor (potentially machine-verified) commit (1/2)
```diff
-static bool Socks5(const std::string& strDest, int port, const ProxyCredentials *auth, const SOCKET& hSocket)
+static bool Socks5(const std::string& strDest,
+                   int port,
+                   const ProxyCredentials *auth,
+                   const SOCKET& hSocket)
```

and then a logical human-verified commit (2/2) that focusses on the actual signature changes
```diff
 static bool Socks5(const std::string& strDest,
                    int port,
-                   const ProxyCredentials *auth,
-                   const SOCKET& hSocket)
+                   const ProxyCredentials* auth,
+                   const Sock& sock)
```

That's just an idea, don't know if it's worth chasing it further. My point is that it's not an absolute unavoidable consequence of proposed line-length limits that there _has_ to be churn. Like already described in a previous comment, I'd assume that the changes get less and less painful for reviewers once the first line-shortening is done. For newly written code, exceeding the line limit too much will serve as kind of a warning sign that the code structure is likely flawed and should be reconsidered.

2021-01-22 15:23 UTC, jonatack commented
See commit a4fb8abe06f9 for an example of what I'm referring to. There are several changes like this in that one commit, where every argument has to be re-verified in the name of shorter lines:

```diff
+++ b/src/netbase.h
@@ -68,7 +68,12 @@ std::unique_ptr<Sock> CreateSockTCP(const CService& address_family);
 extern std::function<std::unique_ptr<Sock>(const CService&)> CreateSock;
 
 bool ConnectSocketDirectly(const CService &addrConnect, const SOCKET& hSocketRet, int nTimeout, bool manual_connection);
-bool ConnectThroughProxy(const proxyType &proxy, const std::string& strDest, int port, const SOCKET& hSocketRet, int nTimeout, bool& outProxyConnectionFailed);
+bool ConnectThroughProxy(const proxyType& proxy,
+                         const std::string& strDest,
+                         int port,
+                         const Sock& sock,
+                         int nTimeout,
+                         bool& outProxyConnectionFailed);
```

2021-01-23 13:37 UTC, prusnak commented
You can enforce line lengths while allowing exceptions to the rule via the following:

``` c
// clang-format off
very long line .....
// clang-format on
```

We use this for Trezor and it's working perfectly. Code that deserves special handling is explicitly marked and the rule is followed everywhere else.

We also decided to follow Google practices (line length = 80, tab width = 2) for the following reasons:
- while most of the editors can show 100+ characters on modern displays without any problems; they can't show 160+ characters required for the side-by-side diffs - not having to scroll makes code review much less painful
- using tab width of 4 or more is very limiting when using only 80 chars per line; tab width of 2 saves a lot of precious line space and still provides good readability 

To wrap it up - I think it makes sense to have either line length of 100 + tab width of 4 or line length of 80 + tab width of 2, while the latter makes side-by-side reviews much more pleasant experience. 

I just shared to story to explain our thought processes; I am not trying to expose our formatting rules on the bitcoin codebase.

2021-01-25 16:03 UTC, lontivero commented
Concept ACK. It is cleaner and easier to compare in diffs.

2021-01-25 17:30 UTC, michaelfolkson commented
Concept ACK

2021-01-25 21:05 UTC, amitiuttarwar commented
concept ACK, code is much easier to read when I can see it :) 

I'd personally prefer 120 characters, esp with some of our long function names, but its nbd and would rather aim for 100 than off-the-page long.

2021-01-26 10:58 UTC, practicalswift commented
Concept ACK: when it comes to degrees of freedom in code formatting less is more :)

Personally I'm a big fan of `black`, `clang-format`, `gofmt`, etc: computers have a comparative advantage when it comes to non-creative tasks :)

2021-01-27 12:03 UTC, promag commented
Concept ACK, I think this notes what we currently try to do.

> Concept ACK. And forbid refactoring pulls just to make lines shorter.

@hebasto that's already noted:

> Do not submit patches solely to modify the style of existing code.

2021-01-27 16:43 UTC, laanwj commented
I'm fine with this, as long as it's meant as a review guideline for new code and not too zealously enforced. I wouldn't like to see e.g. PRs that just change line length all over the codebase.

2021-01-28 21:09 UTC, luke-jr requested changes
Concept NACK.

Editors can automatically wrap long lines when displaying, and to the editor's preferred style and length. Manually wrapped lines just make it less nice to work at other wrapping lengths.

2021-01-29 15:12 UTC, glozow commented
Concept ACK, I believe documenting general preferences (which we already have) would reduce the amount of time spent on style when coding and reviewing. I think it'd be most effective to just point to a tool or script that we can use to do it automatically.

2021-02-13 03:37 UTC, fanquake commented
ACK aa929abf8dc022e900755234c857541faeea8239 - this is basically just something to point too when a PR has unreasonably long lines for no particularly reason.

> I'm fine with this, as long as it's meant as a review guideline for new code and not too zealously enforced. I wouldn't like to see e.g. PRs that just change line length all over the codebase.

Agree. PRs opened just to shuffle code around and reduce line length will be closed.

Otherwise. I'm not sure what's left to do here?

2021-02-13 07:03 UTC, practicalswift commented
ACK aa929abf8dc022e900755234c857541faeea8239

2021-02-13 17:47 UTC, jnewbery commented
This seems to have broad support, so I'm moving it out of draft.

Several reviewers have highlighted that there shouldn't be PRs just to 'fix up' long lines. That's already covered further up in the developer notes:

```
Do not submit patches solely to modify the style of existing code.
```

2021-02-13 18:29 UTC, theStack approved these changes
ACK aa929abf8dc022e900755234c857541faeea8239

2021-02-14 02:30 UTC, amitiuttarwar commented
ACK aa929abf8dc022e900755234c857541faeea8239

2021-02-14 04:53 UTC, glozow reviewed
ACK https://github.com/bitcoin/bitcoin/commit/aa929abf8dc022e900755234c857541faeea8239

2021-02-14 08:50 UTC, merged