rpc: add the add_inputs option to bumpfee/psbtbumpfee
bitcoin/bitcoin pull request #21284
Opened 2021-02-23 18:46 UTC by danben

See #20935

2021-02-24 03:36 UTC, luke-jr requested changes

2021-02-24 03:36 UTC, luke-jr commented on src/wallet/rpcwallet.cpp
> +                    {"add_inputs", RPCArg::Type::BOOL, /* default */ "true", "For a transaction with existing inputs, automatically include more if they are not enough."},
Default should probably be "as needed", and let "true" (perhaps not now, but someday) be used to force additional inputs?

2021-02-24 20:16 UTC, prayank23 commented
Compiled successfully. Tests failed.

Tried experimenting with `add_inputs`:

1.  Transaction with 2 inputs selected manually and custom change address (A new receive address created and used as change):

FALSE

<pre>bumpfee fe60cda11767cd6c6c46a173a3ffa9cf3f71bc5f7af774ab641f6ede92fcd46a "{\"add_inputs\": false}"
</pre>

Error:

<pre>
Unable to create transaction. Insufficient funds (code -4)
</pre>

TRUE

<pre>
bumpfee fe60cda11767cd6c6c46a173a3ffa9cf3f71bc5f7af774ab641f6ede92fcd46a "{\"add_inputs\": true}"
</pre>

<pre>
{
  "txid": "2915edc7e7b8b375dc37a701146025b547903014e4a9652ba4dcb8cf77718ff8",
  "origfee": 0.00000208,
  "fee": 0.00005502,
  "errors": [
  ]
}
</pre>

2. Transaction with 2 inputs selected manually and custom change address (A new change address created and used as change):

FALSE

<pre>bumpfee 86d1a738d652d4511810cf9c820b4bb294edcaff845ab9559ce4c7c33543662f "{\"add_inputs\": false}"</pre>

No Error:

<pre>
{
  "txid": "a1a564ae1983e1a87e731c4b9b205f3e8edbd724bb03d4474090f32ccd8f55a0",
  "origfee": 0.00000208,
  "fee": 0.00001248,
  "errors": [
  ]
}
</pre>

Not sure if this option is really solving the issue or will help users until we fix other related issues.

2021-02-25 18:19 UTC, danben commented
@luke-jr I made the suggested change but am a little worried that it won't be clear to users what value to use if they don't want new inputs to be added.

@prayank23 I will look into what causes a change address to behave differently and possibly propose something. I agree that the current change will make things worse if the behavior is inconsistent.

2021-02-25 18:57 UTC, prayank23 commented
@danben Check https://github.com/bitcoin/bitcoin/issues/20795, https://github.com/bitcoin-core/gui/pull/186 and https://github.com/bitcoin/bitcoin/issues/20598

2021-02-27 02:35 UTC, danben commented
@prayank23 How did you create the change address in your second test case (i.e. the one that behaved wrongly)? Did you use `getrawchangeaddress` or something else?

2021-02-28 22:46 UTC, prayank23 commented
@danben I used `getnewaddress` and `getrawchangeaddress`

Problem is with 2 things:

1. Using address returned in `getnewaddress` or something that doesn't belong to wallet
2. Using address which has a label even if it was created with `getrawchangeaddress`

2021-04-01 13:09 UTC, danben commented on src/wallet/rpcwallet.cpp
> +                    {"add_inputs", RPCArg::Type::STR, /* default */ "as_needed", "For a transaction with existing inputs, automatically include more if they are not enough."},
@MarcoFalke That is what I had originally, but changed it to a string as per @luke-jr's suggestion from 2/23 (see above)

2021-04-01 13:57 UTC, MarcoFalke commented on src/wallet/rpcwallet.cpp
> +                    {"add_inputs", RPCArg::Type::STR, /* default */ "as_needed", "For a transaction with existing inputs, automatically include more if they are not enough."},
what is the use case to force adding inputs if none are needed?

2021-06-23 02:12 UTC, luke-jr commented on src/wallet/rpcwallet.cpp
> +                    {"add_inputs", RPCArg::Type::STR, /* default */ "as_needed", "For a transaction with existing inputs, automatically include more if they are not enough."},
I think you misunderstood me. I meant the documentation should be accurate, not that "as_needed" should be a value. Documenting it as "true" suggested that inputs would be added even if not needed.

If the user wants "as needed", they just would omit "add_inputs" (or specify it as null). But I suppose defaults should be possible to specify explicitly, too, so not sure how to handle that. :)

2022-04-26 12:55 UTC, closed without merging