build: Fix libbitcoinconsensus cross-compiling for Windows with DEBUG=1
bitcoin/bitcoin pull request #21344
Opened 2021-03-02 22:37 UTC by hebasto

Fix #19772.

Steps to reproduce the bug on a4128138b4837baadde75247cd4fd8ea463b7df5:
```
$ make -C depends HOST=x86_64-w64-mingw32 DEBUG=1 NO_QT=1 NO_QR=1 NO_ZMQ=1 NO_WALLET=1 NO_UPNP=1 NO_NATPMP=1
$ ./autogen.sh
$ CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --disable-wallet --disable-tests --disable-bench --without-utils --without-daemon --without-gui
$ make clean
$ make
...
  CXXLD    libbitcoinconsensus.la
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-merkle.o:merkle.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorI7uint256SaIS3_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS3_NSt9__cxx19986vectorIS3_S4_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorI7uint256SaIS3_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS3_NSt9__cxx19986vectorIS3_S4_EEEEEEEEvT_]+0x38): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-merkle.o:merkle.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorI7uint256SaIS3_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS3_NSt9__cxx19986vectorIS3_S4_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorI7uint256SaIS3_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS3_NSt9__cxx19986vectorIS3_S4_EEEEEEEEvT_]+0x5b): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x451): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x468): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x1150): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x116d): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x1724): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x172b): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputerNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputerNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_]+0x204): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputerNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputerNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_]+0x21b): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputer5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputer5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x1c2): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputer5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputer5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x1dc): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputer6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputer6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x1be): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputer6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputer6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x1d5): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-block.o:block.cpp:(.text+0xd21): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-block.o:block.cpp:(.text+0xd3b): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x7c9): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x7e0): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x1f19): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x1f33): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x2902): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x291f): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x2ba6): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x331e): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriterNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriterNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_]+0x795): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriterNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriterNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_]+0x7ac): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriter5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriter5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x7c7): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriter5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriter5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x7e1): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriter6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriter6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x79d): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: p [...]

2021-03-03 03:25 UTC, fanquake reviewed
Concept ACK. Please rebase this,  and remove/trim the link error output from the PR description. There's no need to have all of that pasted in there.

2021-03-03 07:01 UTC, hebasto commented
Rebased 99a1523ff38dd01c7758ab0ce43566c1e1770e98 -> f2b7ea4432eb2dab7351c502cd90fa8a6cf2cde1 ([pr21344.01](https://github.com/hebasto/bitcoin/commits/pr21344.01) -> [pr21344.02](https://github.com/hebasto/bitcoin/commits/pr21344.02)) due to the conflict with #21339.

@fanquake

> Please rebase this, and remove/trim the link error output from the PR description. There's no need to have all of that pasted in there.

Done.

2021-03-04 06:31 UTC, fanquake commented
Looks like this might also fix the issue of cross compiling libbitcoinconsensus for windows when building on macOS:

```bash
# Using brew installed Mingw-w64 v8.0.0 (based  on GCC 10.2).

  CXXLD    libbitcoinconsensus.la
/usr/local/Cellar/mingw-w64/8.0.0_3/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: /usr/local/Cellar/mingw-w64/8.0.0_3/toolchain-x86_64/x86_64-w64-mingw32/lib/libssp.a(ssp.o): in function `__stack_chk_fail':
/private/tmp/mingw-w64-20210210-85400-sa28mi/mingw-w64-v8.0.0/gcc/build-x86_64/x86_64-w64-mingw32/libssp/../../../libssp/ssp.c:183: multiple definition of `__stack_chk_fail'; /usr/local/Cellar/mingw-w64/8.0.0_3/toolchain-x86_64/x86_64-w64-mingw32/lib/../lib/libssp.dll.a(d000007.o):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

2021-03-08 14:58 UTC, hebasto commented
@fanquake 
> Looks like this might also fix the issue of cross compiling libbitcoinconsensus for windows when building on macOS:
> 
> ```shell
> # Using brew installed Mingw-w64 v8.0.0 (based  on GCC 10.2).
> 
>   CXXLD    libbitcoinconsensus.la
> /usr/local/Cellar/mingw-w64/8.0.0_3/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: /usr/local/Cellar/mingw-w64/8.0.0_3/toolchain-x86_64/x86_64-w64-mingw32/lib/libssp.a(ssp.o): in function `__stack_chk_fail':
> /private/tmp/mingw-w64-20210210-85400-sa28mi/mingw-w64-v8.0.0/gcc/build-x86_64/x86_64-w64-mingw32/libssp/../../../libssp/ssp.c:183: multiple definition of `__stack_chk_fail'; /usr/local/Cellar/mingw-w64/8.0.0_3/toolchain-x86_64/x86_64-w64-mingw32/lib/../lib/libssp.dll.a(d000007.o):(.text+0x0): first defined here
> collect2: error: ld returned 1 exit status
> ```

You are right. Tested on macOS Mojave 10.14.6 (18G8022) with Homebrew's `make`:

- master (a22653a636e8dfc1b898ef8dd18a77f2d31082a5) -- the same error as above

- this PR, merged into the current master (a22653a636e8dfc1b898ef8dd18a77f2d31082a5):
```
$ make -C depends HOST=x86_64-w64-mingw32 NO_QT=1
$ ./autogen.sh
$ CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure
$ make
```

2021-03-22 18:38 UTC, luke-jr requested changes
Won't this produce the *wrong* output? ie, a static library instead of shared?

It's called LIBTOOL_*APP*_LDFLAGS for a reason ;)

2021-03-22 21:42 UTC, hebasto commented
@luke-jr 

> Won't this produce the _wrong_ output?

You're right. The `libbitcoinconsensus-0.dll` is not produced with this PR.

Closing.

2021-03-22 21:42 UTC, closed without merging