Move external signer out of wallet module
bitcoin/bitcoin pull request #21467
Opened 2021-03-18 14:23 UTC by Sjors

In addition, this PR enables external signer testing on CI.

This PR moves the ExternalSigner class and RPC methods out of the wallet module.

The `enumeratesigners` RPC can be used without a wallet since #21417. With additional modifications external signers could be used without a wallet in general, e.g. via `signrawtransaction`.

The `signerdisplayaddress` RPC is ranamed to `walletdisplayaddress` because it requires wallet context. A future `displayaddress` RPC call without wallet context could take a descriptor argument.

This commit fixes a `rpc_help.py` failure when configured with `--disable-wallet`.

2021-03-22 07:52 UTC, fanquake reviewed
Concept ACK. While you're moving this around, could you also pull in a change similar to https://github.com/fanquake/bitcoin/commit/42228d716a263cb787cbe8125c855518127e9449. Note there are changes other than whitespace & formattting.

2021-03-22 07:52 UTC, fanquake commented on src/rpc/external_signer.cpp
>  #include <key_io.h>
I don't think you need `key_io.h` anymore?

2021-03-22 14:51 UTC, Sjors commented
@fanquake done

2021-03-22 18:46 UTC, MarcoFalke commented on src/wallet/rpcwallet.cpp
> +        "\nDisplay address on an external signer for verification.\n",
nit: I think the leading and trailing newlines should be the responsibility of RPCHelpMan. Also, they wouldn't make sense if the help is exported as json.

2021-03-22 18:46 UTC, MarcoFalke commented on src/wallet/rpcwallet.cpp
> +{
nit: For new code it would be good to use properly clang-formatted code. Any reason to make a change to move *away* from clang-formatted code?

2021-03-23 05:26 UTC, fanquake commented
@Sjors I discussed with @MarcoFalke, and given there isn't currently a correct `RPCHelpMan` formatting style, can you drop the formatting/whitespace changes? We'll just add the `[&]`s, the examples etc. Sorry for the bum steer.

2021-03-26 09:28 UTC, Sjors commented
@fanquake done (I think)

@MarcoFalke wrote:

> I think the leading and trailing newlines should be the responsibility of RPCHelpMan. Also, they wouldn't make sense if the help is exported as json.

I left out the newline characters.

2021-04-07 18:57 UTC, Sjors commented
After rebase the command `walletdisplayaddress(address1)` in `test/function/wallet_signer.py` line 99 fails with

```
test_framework.authproxy.JSONRPCException: rpc/util.cpp:539 (HandleRequest)
Internal bug detected: 'std::any_of(m_results.m_results.begin(), m_results.m_results.end(), [ret](const RPCResult& res) { return res.MatchesType(ret); })'
```

Not sure what I'm doing wrong here... @MarcoFalke?

2021-04-08 07:08 UTC, MarcoFalke commented on src/wallet/rpcwallet.cpp
> +        RPCResult{RPCResult::Type::NONE,"",""},
This is wrong. It is an obj

2021-04-08 16:05 UTC, xzavjierr commented
Well I checked it and if it's not paying me I don't want it but it's still good text syndicate

2021-04-09 18:18 UTC, ryanofsky approved these changes
Code review ACK 88d4d5ff2f5c71a9a2f4c78c2b2e2fd00568cfee

2021-04-11 15:17 UTC, RonSherfey requested changes
requested changes

2021-04-13 06:34 UTC, fanquake approved these changes
ACK 88d4d5ff2f5c71a9a2f4c78c2b2e2fd00568cfee

2021-04-13 06:35 UTC, merged