Fix assumeutxo crash due to missing base_blockhash
bitcoin/bitcoin pull request #21582
Opened 2021-04-03 13:27 UTC by MarcoFalke

This fixes an UB (which results in a crash with sanitizers enabled). Can be reproduced by cherry-picking the test without the other code changes. The fix:

* Adds an `Assert` to transform the UB into a clean crash, even when sanitizers are disabled
* Adds an early-fail condition to avoid the crash

2021-04-03 13:30 UTC, MarcoFalke commented
Introduced in #19806

2021-04-03 13:37 UTC, jamesob commented
Thanks for catching this. Why change behavior not to allow waiting for the headers to load?

2021-04-03 14:03 UTC, MarcoFalke commented
I couldn't find a code path that needs this behavior, so it seemed odd to keep the dead code. Note that in your parent PR the RPC does the waiting, so it doesn't have to be done again in validation.

2021-04-03 14:07 UTC, Ouch555 requested changes
Remove authorizationToken

2021-04-03 14:12 UTC, jamesob commented
> Note that in your parent PR the RPC does the waiting, so it doesn't have to be done again in validation.

Oh good point. I guess if we add some flag that allows specifying a snapshot to load (absent RPC) we'll have to add some similar code to init, but we can cross that bridge when we come to it.

In any case, concept ACK. Will test later today.

2021-04-03 14:25 UTC, MarcoFalke commented
> we can cross that bridge when we come to it

Indeed, I was never a fan of the "idle-loop" inside validation (See https://github.com/bitcoin/bitcoin/pull/19806#discussion_r480281665), so moving it to the caller (if needed at all) seems the way to go.

2021-04-03 16:01 UTC, ryanofsky approved these changes
Code review ACK fafcddcd5311064c2e98679dd08be059ef25b318. All changes look good, but I don't know when the bug happens in practice or how it was discovered.

Also it would be nice to have just the minimal fix and test together in same commit so it is more clear how the bug can be triggered and how it is fixed. Then it would be good to have the other cleanups in separate commits. IIUC:

- The bugfix is the new `if (!snapshot_start_block)` check in PopulateAndValidateSnapshot, triggered by the new test passing base hash `uint256::ONE`.
- Assert in GetUTXOStats adds an additional check at the point where the segfault previously happened
- Removing the header wait loop is dead code removal and bit of a design change (good change breaking up a big function)

2021-04-04 05:40 UTC, MarcoFalke commented
> separate commits

Thanks, force pushed so that the Assert is a separate commit, no code changes.

2021-04-05 17:59 UTC, jamesob approved these changes
ACK fa9b74f5ea89624e052934c48391b5076a87ffef ([`jamesob/ackr/21582.1.MarcoFalke.fix_assumeutxo_crash_due`](https://github.com/jamesob/bitcoin/tree/ackr/21582.1.MarcoFalke.fix_assumeutxo_crash_due))

Looks good, thanks.

<details><summary>Show signature data</summary>
<p>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK fa9b74f5ea89624e052934c48391b5076a87ffef ([`jamesob/ackr/21582.1.MarcoFalke.fix_assumeutxo_crash_due`](https://github.com/jamesob/bitcoin/tree/ackr/21582.1.MarcoFalke.fix_assumeutxo_crash_due))

Looks good, thanks.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEGNRVI1NPYuZCSIrGepNdrbLETwUFAmBrT/QACgkQepNdrbLE
TwULqw//SIwBkIK7OsgTB1ycHuwVJnJqnbO67v0oG/KI/2483t7jBJvMCznX2ecT
at4FcfJ7HmyrWve4EKz5mpa7851s565ftUNMy+K6nGj53tr+ejXyioDmEamol/AT
KzYah/LQjtwdS/WbNs1JyXE3NQ0briscUhi6053tdYGDwmtc+bdh4wdkcySRWHFR
a7SLoASpQ4rj3c2VlSyDzXoUCLNtpvylO9aRxgINC/IOU8UKS/F51LjMIGmeNHHP
oDDJ8cZwQURfSqg8bIQWpVDFwGBhPdXAFrQdl2kBdqJa48yp4PEg7KIHkh+H3xKV
W4sn2xMghzwB+MtFOCUDTY6ggy7yuh/6w/ZLqBuwrQaZyepMu3OUJ8PnEH8mk4OV
ddVL43/iGoEf9lH+X3f6WykZFIDTeMy1Np0YGjrDcFzc3qxDpQip++dvcm3rblDP
BlaUUm1UucSU8ZafZZJpv5Jg0EpbPaNlAMb8qp1N73AD94ngYq/LIlgahu280obM
v7lAxApGzUpufGl0Fg5ARqvKPWpwEuS8FoM0EUkv8wNaJeNxZAuUgIJ3R8PmoffH
ffAgxlNS5Q6o3aAPsTin9hSR7Bfkzit4/Tm9xMHiH+WCHJPiML4mlO4h5DbSUjYn
dyxgaI1e32gJBrY/xroaiu8v+EmyJeHeuDlcbN+lP7AzhDN4XfU=
=Pv7n
-----END PGP SIGNATURE-----

```

</p></details>

<details><summary>Show platform data</summary>
<p>

```
Tested on Linux-4.19.0-10-amd64-x86_64-with-glibc2.28

Configured with ./configure LDFLAGS=-L/home/james/src/bitcoin/db4/lib/ -L/home/james/.local/lib CPPFLAGS=-I/home/james/src/bitcoin/db4/include/ -I/home/james/.local/include CXXFLAGS=-fPIE -pipe -O2 -g -Wthread-safety-analysis -Wall -Werror=sign-compare -Wsign-compare -Werror=thread-safety-analysis --enable-wallet --enable-debug --with-daemon --enable-natpmp-default --enable-multiprocess PKG_CONFIG_PATH=/home/james/.local/lib/pkgconfig CXX=/usr/bin/clang++ CC=/usr/bin/clang PYTHONPATH= --disable-shared --with-pic --enable-benchmark=no --with-bignum=no --enable-module-recovery --enable-module-schnorrsig --enable-experimental --disable-shared --with-pic --enable-benchmark=no --with-bignum=no --enable-module-recovery --enable-module-schnorrsig --enable-experimental --no-create --no-recursion

Compiled with /usr/bin/ccache /usr/bin/clang++ -std=c++17 -mavx -mavx2 -fPIE -pipe -O2 -g -Wthread-safety-analysis -Wall -Werror=sign-compare -Wsign-compare -Werror=thread-safety-analysis -O0 -g3 -ftrapv  -Wstack-protector -fstack-protector-all -msse4 -msha -msse4.1 -msse4.2  i

Compiler version: clang version 7.0.1-8 (tags/RELEASE_701/final)
```

</p></details>

2021-04-06 01:39 UTC, ryanofsky approved these changes
Code review ACK fa9b74f5ea89624e052934c48391b5076a87ffef with no code changes since last review, just splitting up combocommit a little.

> This fixes an UB (which results in a crash with sanitizers enabled). Can be reproduced by cherry-picking the test without the other code changes. 

Look good, though I'm curious if the crash was happening before the new test. Was the bug causing a different crash in another test? Or was it just discovered reading code?

2021-04-06 06:13 UTC, MarcoFalke commented
> was it just discovered reading code?

This particular one was discovered by a fuzz target, which I wrote after I discovered a crash with code review: #21585

2021-04-07 05:34 UTC, merged

2021-04-09 16:05 UTC, practicalswift commented
Post merge cr ACK fa9b74f5ea89624e052934c48391b5076a87ffef

> > was it just discovered reading code?
> 
> This particular one was discovered by a fuzz target, which I wrote after I discovered a crash with code review: #21585

Nice fuzzing find! Fuzzing makes us: harder better faster^Wresilient stronger! 🎶 

Don't forget to add your find to the growing list of trophies over at https://github.com/bitcoin-core/bitcoin-devwiki/wiki/Fuzz-Trophies :)