refactor: Remove negative lock annotations from globals
bitcoin/bitcoin pull request #21598
Opened 2021-04-04 17:59 UTC by MarcoFalke

They only make sense for mutexes that are private members. Until cs_main is a private member the negative annotations should be replaced by excluded annotations, which are optional.

2021-04-04 23:36 UTC, hebasto commented
Concept ACK (in the light of #20272 discussion).

2021-04-04 23:45 UTC, szeli57 commented
2021. április 5., hétfő dátummal Hennadii Stepanov ***@***.***>
ezt írta:

> Concept ACK (in the light of #20272
> <https://github.com/bitcoin/bitcoin/pull/20272> discussion).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/21598#issuecomment-813116824>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS6VN6B3DGB3G6SLZWG7BMDTHDZ7HANCNFSM42LUH3QA>
> .
>

2021-04-05 01:52 UTC, hebasto reviewed
Tested faadb1b050dd37ea8d294def554f1da22029d3e6 on Ubuntu 21.10:
```
$ clang --version
Ubuntu clang version 12.0.0-++rc3-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

With this PR massive TSA warnings are gone.

Could the global namespace be explicitly used for global mutexes in the touched lines?

2021-04-05 03:04 UTC, hebasto requested changes
May I suggest to:
- add some missed annotations:
```diff
diff --git a/src/index/base.h b/src/index/base.h
index 8559e3cb6..ac3c429a5 100644
--- a/src/index/base.h
+++ b/src/index/base.h
@@ -109,7 +109,7 @@ public:
     /// sync once and only needs to process blocks in the ValidationInterface
     /// queue. If the index is catching up from far behind, this method does
     /// not block and immediately returns false.
-    bool BlockUntilSyncedToCurrentChain() const;
+    bool BlockUntilSyncedToCurrentChain() const LOCKS_EXCLUDED(::cs_main);
 
     void Interrupt();
 
diff --git a/src/rpc/rawtransaction.cpp b/src/rpc/rawtransaction.cpp
index 7932bd291..3a650923c 100644
--- a/src/rpc/rawtransaction.cpp
+++ b/src/rpc/rawtransaction.cpp
@@ -815,7 +815,7 @@ static RPCHelpMan signrawtransactionwithkey()
     };
 }
 
-static RPCHelpMan sendrawtransaction()
+static RPCHelpMan sendrawtransaction() LOCKS_EXCLUDED(::cs_main)
 {
     return RPCHelpMan{"sendrawtransaction",
                 "\nSubmit a raw transaction (serialized, hex-encoded) to local node and network.\n"
```
- fix `EXCLUSIVE_LOCKS_REQUIRED(!::cs_main)` example in https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md

?

2021-04-05 03:12 UTC, hebasto commented
This change reverts the @ajtowns's [idea](https://github.com/bitcoin/bitcoin/pull/19668#issuecomment-669312538) for `AssertLockNotHeld` but I cannot see the way to save it, unfortunately.

2021-04-05 06:33 UTC, ajtowns commented
Approach ACK, +1 on doc change as well

2021-04-05 06:43 UTC, MarcoFalke commented
> This change reverts

Correct, but the revert is only temporary (until cs_main is removed or a private member)

2021-04-05 06:43 UTC, MarcoFalke commented
Force pushed to address feedback

2021-04-05 06:49 UTC, hebasto approved these changes
ACK fa5eabe72117f6e3704858e8d5b2c57a120258ed

2021-04-05 14:55 UTC, vasild approved these changes
ACK fa5eabe72117f6e3704858e8d5b2c57a120258ed

No warnings with Clang 13.

2021-04-05 22:11 UTC, sipa commented
utACK fa5eabe72117f6e3704858e8d5b2c57a120258ed

2021-04-06 05:52 UTC, ajtowns commented
ACK fa5eabe72117f6e3704858e8d5b2c57a120258ed

2021-04-06 05:57 UTC, merged

2022-06-07 11:55 UTC, vasild commented
This silenced the compiler warnings at the time, so it was ok. I just wonder about the following reasoning, in the light of https://github.com/bitcoin/bitcoin/pull/24931:

> Remove negative lock annotations from globals ... They only make sense for mutexes that are private members.

Why is that? For example:

```cpp
Mutex g_mutex;

void f1()
{
    LOCK(g_mutex);
}

void f2()
{
    LOCK(g_mutex);
    f1();
}
```

This is undefined behavior that would be detected if `f1()` is annotated with `EXCLUSIVE_LOCKS_REQUIRED(!g_mutex)`.

To me it looks like that negative lock annotations "make sense" regardless of the scope of the mutex, no?

2022-06-07 12:11 UTC, MarcoFalke commented
This pull was done in light of https://github.com/bitcoin/bitcoin/pull/20272#discussion_r515215137 . If https://github.com/bitcoin/bitcoin/pull/24931 fixes the mentioned issues, then that is fine.

2022-06-13 02:21 UTC, ajtowns commented
@vasild The problem is when you call `f1` -- the negative annotation needs to keep getting propogated up the call stack:

```c++

Mutex g_mutex;
void f1() EXCLUSIVE_LOCKS_REQUIRED(!g_mutex)
{
    LOCK(g_mutex);
}

class X {
private:
    Mutex m_mut;
public:
    void f1() EXCLUSIVE_LOCKS_REQUIRED(!m_mut)
    {
        LOCK(m_mut);
    }
};
X g_x;

void caller() EXCLUSIVE_LOCKS_REQUIRED(!g_mutex)
{
    f1();
    g_x.f1();
}
```

2022-06-13 13:30 UTC, vasild commented
Yes, it has to be propagated, but I wouldn't call it a "problem" though because it works exactly as intended. True that it creates inconvenience with code isolation (like this code should not know about that mutex), but after all a global mutex is not isolated, so IMO it is ok and even desirable to propagate its negative annotation.