Create sanitizestring.cpp
bitcoin/bitcoin pull request #22171
Opened 2021-06-06 16:39 UTC by baptistapedro

Isolated harness for SanitizeString(), need a little edit to fit the fuzz coding pattern, I believe the extern "C" int LLVMFuzzerTestOneInput() would be translated to:
```
FUZZ_TARGET(sanitizestring)
{
    FuzzedDataProvider fuzzed_data_provider(buffer.data(), buffer.size());
    [...]
}
I am not that familiar with the whole fuzz codebase pattern yet to follow with the proper syntax.

The recommended fix from @laawnj is to " make the second argument of SanitizeString an "SafeChars" enum. This prevents a unhandled value from ever being passed in.
"

[1] and [2] point to so some references where the second argument is not passed as an enum but there is more cases under the same conditions so I recommend to do some x-reference to double check them.

2021-06-07 06:22 UTC, MarcoFalke requested changes
I haven't looked at this in detail, but it looks wrong from a first glance.

2021-06-07 06:22 UTC, MarcoFalke commented on src/test/fuzz/sanitizestring.cpp
> +    SanitizeString(fuzzdata, fuzzdata.size());
the second arg is an enum, not a size. See https://github.com/bitcoin/bitcoin/pull/6647#discussion_r38855960

2021-06-07 06:25 UTC, MarcoFalke commented on src/test/fuzz/sanitizestring.cpp
> +    SanitizeString(fuzzdata, fuzzdata.size());
Also, this method is already fuzzed in 

```
src/test/fuzz/string.cpp:    (void)SanitizeString(random_string_1, fuzzed_data_provider.ConsumeIntegralInRange<int>(0, 3));

2021-06-07 06:30 UTC, MarcoFalke commented on src/test/fuzz/sanitizestring.cpp
> +    SanitizeString(fuzzdata, fuzzdata.size());
See https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md#quickstart-guide on how to compile. To run, you'd have to pass `FUZZ=string ./src/test/fuzz/fuzz`. Let me know if you have any questions.

2021-06-07 09:13 UTC, baptistapedro commented on src/test/fuzz/sanitizestring.cpp
> +    SanitizeString(fuzzdata, fuzzdata.size());
I wrote this harness and reported to security@bitcoin without realizing you guys already wrote one 
However the second arg is passed as a size i.e. on [1] and [2] and other methods. See where SanitizeString is called and you can see different cases where the second arg is not an enum and thats why I referenced that the fix must be on the callers.
This issue was already confirmed by laawnj and he also confirmed that SanitizeString()'s second arg must be called as an enum but it does not happen in some cases but such cases are not so reliable as attack vectors so is not a priority fix.

2021-06-07 11:44 UTC, MarcoFalke commented on src/test/fuzz/sanitizestring.cpp
> +    SanitizeString(fuzzdata, fuzzdata.size());
I am not sure what `[1]` and `[2]` refer to, but if it was called anywhere with size, we could tell by existing tests crashing.

2021-06-07 11:46 UTC, MarcoFalke commented on src/test/fuzz/sanitizestring.cpp
> +    SanitizeString(fuzzdata, fuzzdata.size());
The only places I could find where the second parameter is passed at all is URI handling and UA comment handling, both of which look fine.

2021-06-07 11:47 UTC, MarcoFalke commented on src/test/fuzz/sanitizestring.cpp
> +    SanitizeString(fuzzdata, fuzzdata.size());
Commit 26c06f24e5dcc32a7599abb8d670d22993c82bc2 removed the last use of FILENAME, so I guess that constant can be removed now

2021-06-09 14:10 UTC, MarcoFalke commented
Closing for now, because we already have a fuzz target that covers this function. Other improvements and specially improvements of the fuzz tests are welcome.

2021-06-09 14:10 UTC, closed without merging