rpc/wallet: add optional transaction to getbalances
bitcoin/bitcoin pull request #22776
Opened 2021-08-23 04:13 UTC by kallewoof

An optional transaction provided to getbalances iterates over the inputs and outputs of the given transaction, and tallies up the balance change for the given wallet. This can be useful e.g. when verifying that a coin join like transaction doesn't contain unexpected inputs that the wallet will then sign for unintentionally.

This is an alternative to #22751.

2021-08-23 05:49 UTC, prayank23 commented
Concept ACK. Will try today.

2021-08-23 06:14 UTC, meshcollider commented
Approach ACK, definitely prefer this over #22751 👍

2021-08-23 06:33 UTC, MarcoFalke commented
How is the user going to use this? Call the RPC thrice and compare the results?

* Fist time to get the balances before
* Second time to get the balances with the tx included
* Third time to verify no other thread added a wallet tx in-between, which would invalidate the result

2021-08-23 07:23 UTC, kallewoof commented
@MarcoFalke The transaction is supposedly not yet broadcasted. They'd only need to call getbalances once. The existing output would give the wallet's balance as it is (excluding the transaction), and the added "changes" would show how the balance would change, if the transaction was broadcasted.

I.e. I get a coin-join with 100 other inputs and a bunch of outputs. I call `getbalances [hex]`, and the "changes" column tells me how much I gain/lose from broadcasting the transaction.

2021-08-23 07:31 UTC, MarcoFalke commented
Oh I didn't see the changed result, because the documentation wasn't updated.

2021-08-23 07:38 UTC, kallewoof commented
Good point, documentation updated.

2021-08-23 16:40 UTC, prayank23 approved these changes
tACK https://github.com/bitcoin/bitcoin/pull/22776/commits/67ff5ae4b092c3284da7481e13518dbbd3d945f5

Tested with different transactions (input from wallet, input not belonging to wallet, outputs from wallet, outputs outside wallet)

Example:

```
Request:

POST /wallet/W2 HTTP/1.1
Host: 127.0.0.1:18333
Authorization: Basic dXNlcjMzOnBhc3N3b3JkMzM=
Content-Type: text/plain
Content-Length: 521

{"jsonrpc": "1.0", "id": "curltest", "method": "getbalances", "params": ["02000000000101fff8d9d39105eeec162fb45bd2a3e796b255866469a2cc7de93e438f3722c1490000000000fdffffff02801a0600000000001600145b497cfd64324fb0c4f7317472ca591cd7eb3bbfe093040000000000160014b1348ec3acd422b7c84f97f8757a0a5c3db9e32d02473044022020c3a9d7d06429008de82f13de672aac7886c5d6557a7c330bcb8cbc20b8cf4f02203890042ed8bf331e92f07df5d2a7bf5d8ade12cbb216f14493a98d0a188c4918012103c65a6e4a66a4a6b4af981c5e81632bb2d7336bc75d7ccf83e055006a2693050f00000000"]}

Response:

{
    "result": {
        "mine": {
            "trusted": 5051.31588006,
            "untrusted_pending": 0.00000000,
            "immature": 0.00000000
        },
        "tx": {
            "changes": 0.00000000
        }
    },
    "error": null,
    "id": "curltest"
}
```

Everything looks good to me. Also tested by fuzzing this argument for `getbalances` with random strings. No issues.

2021-09-20 01:45 UTC, luke-jr commented
#22751 seems to make more sense IMO

If users need both pieces of information, they can just batch them.

2021-09-20 01:46 UTC, luke-jr requested changes

2021-09-20 01:46 UTC, luke-jr commented on src/wallet/rpcwallet.cpp
> +            {"rawtxs", RPCArg::Type::ARR, RPCArg::Optional::OMITTED_NAMED_ARG, "An array of hex strings of raw transactions.\n",
It seems weird to have an array of raw transactions as a positional argument here.

2021-09-21 10:54 UTC, kallewoof commented
I think #22751 is emerging as the superior option here. Ping if you disagree and I'll reopen this.

2021-09-21 23:53 UTC, kallewoof commented
Some prefer this over #22751, so reopening this for now.

2021-11-09 11:30 UTC, MarcoFalke commented on test/functional/wallet_balance_getbalances.py
> +        node0.generatetoaddress(nblocks=COINBASE_MATURITY + 1, address=w0.getnewaddress())
```suggestion
        self.generatetoaddress(...
```

2021-11-09 11:31 UTC, MarcoFalke commented on test/functional/wallet_balance_getbalances.py
> +        node0.generatetoaddress(nblocks=COINBASE_MATURITY + 1, address=w0.getnewaddress())
after a rebase, that is

2021-11-14 12:06 UTC, kallewoof commented on test/functional/wallet_balance_getbalances.py
> +        node0.generatetoaddress(nblocks=COINBASE_MATURITY + 1, address=w0.getnewaddress())
Thanks!

2021-12-17 15:02 UTC, laanwj commented
> I would prefer a broader "see how transactions modify the wallet without actually modifying it" RPC rather than trying to jam that functionality into an existing one.

I tend to agree here. It is useful functionality but I think it's cleaner to have it separated as a seperate RPC.

2022-07-25 09:28 UTC, closed without merging