Bugfix: Skip tests for tools not being built
bitcoin/bitcoin pull request #23027
Opened 2021-09-18 16:56 UTC by luke-jr

2021-09-21 04:44 UTC, fanquake commented
Not sure what you expect to be done here. Even if Github, Appveyor and DrahtBot are all wrong about there being a conflict, if this PR can't be merged using the [merge-script](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/github-merge.py) (it currently can't), it's not going to be merged. The fact that no CI is running is also a blocker. I'd suggest rebasing on a master more recent than April 2020.

2021-09-21 06:52 UTC, MarcoFalke commented
DrahtBot and appveyor use the GitHub API, so this is mostly a GitHub bug.

2021-12-22 13:03 UTC, MarcoFalke commented
My suggestion would be to close this pull request, since it is not possible to merge with the merge script without modifying it.

2021-12-22 17:17 UTC, luke-jr commented
Please open a new, separate issue for bugs in your merge script/bots. It's off-topic here.

This PR still merges cleanly to master. 0.20, and 0.21.

2021-12-22 18:41 UTC, kristapsk commented
Btw, I'm using the same recent `github-merge.py` script for JoinMarket, it also fails with empty pull request description.

2022-10-12 18:40 UTC, achow101 commented
Are you still working on this?

2023-02-06 11:56 UTC, fanquake commented on test/config.ini.in
> +@BUILD_BITCOIN_UTIL_TRUE@ENABLE_UTIL_UTIL=true
We already have `ENABLE_BITCOIN_UTIL`, so we should use that.

2023-05-04 15:48 UTC, theuni requested changes
@luke-jr If you're still interested in this, I agree with the previous reviewers:
- PR needs a description, if only for posterity
- As @fanquake mentioned, `ENABLE_BITCOIN_UTIL` could be used here.

I'm not at all familiar with the test framework, but this looks a lot like a re-implementation of something that's already cleanly abstracted. What exactly isn't getting correctly skipped?

2023-08-17 12:33 UTC, fanquake commented
> May want to close this, given the ongoing cmake transition obsoletes it either way?

Think I agree. If the (asked-for) review/questions are addressed, can still be re-opened.

2023-08-17 12:33 UTC, closed without merging