Bump minimum python version to 3.7
bitcoin/bitcoin pull request #23270
Opened 2021-10-13 10:06 UTC by Empact

Python 3.6 is set to reach end-of-life in 2021-12-23.
https://www.python.org/dev/peps/pep-0494/#lifespan
https://docs.python.org/3/whatsnew/3.7.html

2021-10-13 10:24 UTC, Empact commented
Previously updated in https://github.com/bitcoin/bitcoin/pull/19504
Python 3.7 EOL is set for 2023-06-27
https://www.python.org/downloads/

2021-10-14 13:16 UTC, maflcko requested changes
Doesn't work in the current state

2021-10-14 13:17 UTC, closed without merging

2022-10-03 13:30 UTC, MarcoFalke reviewed
This doesn't work, but https://github.com/bitcoin/bitcoin/pull/26226 should work

2022-10-03 13:30 UTC, MarcoFalke commented on ci/test/00_setup_env_native_nowallet.sh
>  export PACKAGES="python3-zmq clang-7 llvm-7 libc++abi-7-dev libc++-7-dev"  # Use clang-7 to test C++17 compatibility, see doc/dependencies.md
`python3-zmq` installs `python3` (3.6), which is picked by the functional tests (shebang `python3`), so this doesn't actually work