RPC: Better safety with newkeypool command and wallet backups
bitcoin/bitcoin pull request #23341
Opened 2021-10-23 01:38 UTC by meshcollider

This PR prevents `newkeypool` from being run on non-HD wallets, because this would require a new backup every time, so it isn't very safe.

David Harding also suggested [here](https://github.com/bitcoin/bitcoin/pull/23093#issuecomment-945350003) that the RPC help text should include a warning to the users about the interaction between newkeypool.

2021-10-25 02:28 UTC, lsilva01 approved these changes
Code Review ACK 04153bc

2021-10-28 13:42 UTC, stratospher reviewed
Tested ACK 04153bc on a non HD wallet. The warning is really helpful.

```
$ src/bitcoin-cli --testnet -rpcwallet=mynonHD newkeypool
error code: -4
error message:
Error: Cannot use newkeypool on non-HD wallets.
```

2021-10-29 16:52 UTC, luke-jr requested changes
Concept NACK. Users of non-HD wallets *expect* to make new backups regularly. No reason to deny them this RPC method...

2021-10-29 20:42 UTC, meshcollider commented
@luke-jr can you provide a reason for it's usefulness? It was only just added, so I can't imagine anyone relying on it...

2021-10-29 23:08 UTC, luke-jr commented
Maybe I'm missing the point of it entirely? I'm just saying artificially blocking non-HD wallets from using it seems unreasonable. I can't think of a use case for this with a HD wallet (won't the new keypool just end up with the same keys?), but it seems useful for non-HD wallets to intentionally avoid new funds from being accessible with old (compromised?) backups.

2021-10-30 04:40 UTC, meshcollider commented
HD wallets will be restocked with entirely new keys. That's an interesting use-case, I mainly had in mind people who have upgraded non-HD to HD and want to clear out all their non-HD keys in one go. But I can just add some large warnings in the non-HD case.

2021-12-08 03:56 UTC, meshcollider commented
Rebased.

2021-12-10 16:57 UTC, achow101 commented
I agree with @luke-jr. This RPC is useful for non-HD wallets too. It just need to come with large warnings about backups.

2021-12-12 06:05 UTC, meshcollider commented
Done 👍

2021-12-20 19:39 UTC, achow101 commented
ACK a2a92317ad4ab88cfca234f68337a7cd37897f10

2021-12-20 19:51 UTC, merged