util: Add "importfromcoldcard" command to bitcoin-wallet tool
bitcoin/bitcoin pull request #23362
Opened 2021-10-26 11:27 UTC by hebasto

Coldcard firmware v4.1.3+ supports wallet export via descriptors:
- https://github.com/Coldcard/firmware/commit/3151369e67951f68e86ba993ef1e7dfaaa39c13f
- [Using Coldcard with Bitcoin Core](https://github.com/Coldcard/firmware/blob/3151369e67951f68e86ba993ef1e7dfaaa39c13f/docs/bitcoin-core-usage.md#bitcoin-core-v0210)

This PR adds a new command `importfromcoldcard` for the `bitcoin-wallet` tool which creates a new wallet and fills it with the provided descriptors.

Usage example:
```
$ src/bitcoin-wallet -wallet=MyNewShinyCC -dumpfile=/home/hebasto/Coldcard/bitcoin-core.txt importfromcoldcard
```

To point to the "bitcoin-core.txt" file, the `-dumpfile` option is re-used.

Also the created wallet is forced for rescanning, to guarantee the access to all transactions even for wallets that were previously used some time before being imported into Bitcoin Core.

TODO (not here):
- [ ] add tests for the `importfromcoldcard` command to the `tool_wallet.py` functional test
- [ ] add the same functionality to the GUI

Based on bitcoin/bitcoin#23349.

2021-10-26 22:39 UTC, mjdietzx reviewed
Very cool‼️ One comment/question

2021-10-29 17:05 UTC, luke-jr requested changes
Suggest making a BIP for the format, and renaming this to something vendor-neutral.

2021-10-30 21:39 UTC, lsilva01 commented
I agree.
> Suggest making a BIP for the format, and renaming this to something vendor-neutral.

2021-11-08 18:02 UTC, laanwj commented
> -0 on adding device specific code into Core.

Yes. I'm all for making the flows easy to use with hardware wallets, but supporting specific hardware seems to go a step too far. Also, we don't have the test framework (e.g. device simulation) set up for use-cases like this.

>  No. It's practically infeasible for a non-tech-savvy person to create a safe setup of "Bitcoin Core + python HWI" on a new Windows laptop. I tested this scenario many times IRL with different users ((

So then we need to make that process easier. This cannot be an argument for absorbing HWI's functionality.

2021-11-22 02:32 UTC, meshcollider commented
Absolutely agree with the above comments, its definitely an excellent goal to improve integration with hardware wallets but not at the expense of burdening this repository with a bunch of case handling. Look forward to a vendor-independent proposal 👍

2021-12-27 08:52 UTC, fanquake commented
What's the state of this PR? From the discussion the current approach is not going to be merged, so I think this should either be closed, or at least drafted, until the approach is changed.

2021-12-27 08:56 UTC, hebasto commented
> What's the state of this PR? From the discussion the current approach is not going to be merged, so I think this should either be closed, or at least drafted, until the approach is changed.

Drafted.

2022-03-24 18:17 UTC, closed without merging