build: Fix cross compiling with DEBUG=1 for Windows
bitcoin/bitcoin pull request #23612
Opened 2021-11-27 14:27 UTC by hebasto

On master (200d97faf2ed0bd0cbef93dd4bbbe77cf8fe5d13) cross compiling for Windows with depends being built with `DEBUG=1` is broken in two places:
- `libbitcoinconsensus`, see bitcoin/bitcoin#19772
- `libunivalue`, see https://github.com/bitcoin/bitcoin/pull/22646#issuecomment-974780821

This PR workarounds both cases.

Closes bitcoin/bitcoin#19772.

2021-11-30 18:39 UTC, laanwj commented
Cannot test this at the moment. I'm confused why `enable_shared=no` works in this case, tagged @fanquake as reviewer because of https://github.com/bitcoin/bitcoin/issues/19772#issuecomment-677962733 .

2021-11-30 19:32 UTC, hebasto commented
> Cannot test this at the moment. I'm confused why `enable_shared=no` works in this case

It controls who the libtool will be configured by the following `./configure` script.

2021-11-30 23:07 UTC, luke-jr requested changes
Concept NACK. This doesn't fix the build, just prevents it...

2021-12-01 04:12 UTC, fanquake commented
I agree with Luke. It's hard to call this a fix when it's just ignoring what's broken. As-is, we'd also get an undocumented special casing in our `config.site`, which I'd rather avoid. If this a big problem for someone, maybe we could carry this in the interim, but this isn't a long term solution, and shouldn't be merged undocumented.

2022-04-25 12:23 UTC, closed without merging