2022 03 reduce coin selection iterations
bitcoin/bitcoin pull request #24712
Opened 2022-03-29 22:31 UTC by Xekyo

Remove coin selection iteration requiring 6 confs
    
It's not clear what purpose we serve with this additional iteration of coin selection that restricts foreign UTXOs to at least six confirmations.
    
If the wallet hasn't been used in a long time, requiring six confirmations or one is equivalent. If the wallet has just received
    funds, the important distinction is still between confirmed and    unconfirmed UTXOs: we haven't had any reorgs of more than a single block    in multiple years, and the ones we had have been benign—the differences    of included transactions between blocks at the same height is generally    minuscule and can be explained by transaction relay latency or the rate    of block template updates. The risk of a UTXO getting reorged out due to    requiring a single confirmation instead of six can be discounted and    doesn't suffice to instigate a full additional coin selection iteration.

2022-03-30 09:39 UTC, 1440000bytes commented
> If the wallet has just received
funds, the important distinction is still between confirmed and unconfirmed UTXOs: we haven't had any reorgs of more than a single block in multiple years, and the ones we had have been benign—the differences of included transactions between blocks at the same height is generally minuscule and can be explained by transaction relay latency or the rate of block template updates.

How will this work in an attack shared in this tweet? https://nitter.net/AchimWar/status/1505980778458484736

> The risk of a UTXO getting reorged out due to requiring a single confirmation instead of six can be discounted and doesn't suffice to instigate a full additional coin selection iteration.

I am not sure if all users will be okay with this discount. Disagree and if it ain't broke, don't fix it.

2022-03-30 21:14 UTC, achow101 commented
Concept ACK

2022-03-31 03:51 UTC, ClaraBara22 commented
1440000bytes, why on earth do people have a problem with the discount? I don't even know how much it is, but I think you all work hard enough that whatever you get, you've earned it...fair and square. When I was like a real working person I got paid for every patient I saw. I really do get it. May we live long and prosper.

2022-03-31 06:10 UTC, MarcoFalke commented
This can also happen in normal operation, absent any attack, if fee bumping becomes more common. Two competing blocks often contain the same tx with different fee rates (thus different txid). Even if it happens only once a month, I think it can be inconvenient for users to having to re-send a payment, risking double-pay if the new payment gets confirmed in a chain with the (presumed) stale block.

2022-03-31 23:47 UTC, 1440000bytes requested changes
Concept NACK

> The likelihood of a situation arising in which this is relevant is so minuscule that performing the additional computation step is not justified

This situation looks possible with governments involved in bitcoin, mining, councils etc. We have not disabled firewall in our office because there were no attacks in last few months.

We are going through lot of things that I don't want to share here as it will be offtopic but still affects bitcoin and I expect bitcoin developers to respect it.

> This can also happen in normal operation, absent any attack, if fee bumping becomes more common. Two competing blocks often contain the same tx with different fee rates (thus different txid). Even if it happens only once a month, I think it can be inconvenient for users to having to re-send a payment, risking double-pay if the new payment gets confirmed in a chain with the (presumed) stale block.

This is another point and I appreciate adversarial thinking by maintainers.

tl;dr: I respect PR author's contribution in coin selection and bitcoin however I am not okay with this change

2022-04-12 00:40 UTC, luke-jr commented
>we haven't had any reorgs of more than a single block in multiple years, and the ones we had have been benign

But a change like this creates an incentive to do so.

Agree with @1440000bytes - this probably isn't a good idea.

(Maybe if we could automatically detect and handle problems?)

2022-04-12 01:23 UTC, kristapsk commented
Agree with @1440000bytes and @luke-jr here, NACK as it is. Probably 6 could be configurable number and then user could set it to 1 if he wants to?

2022-04-12 15:17 UTC, Xekyo commented
Okay, thanks for the feedback.

2022-04-12 15:17 UTC, closed without merging