mempool: Add option to bypass contextual timelocks in testmempoolaccept
bitcoin/bitcoin pull request #25434
Opened 2022-06-21 03:31 UTC by w0xlt

Picking up https://github.com/bitcoin/bitcoin/pull/21413 (labeled "Up for grabs").

This PR adds a new option (`bypass_timelocks`) to RPC `testmempoolaccept` that skips `CheckFinalTxAtTip` and `CheckSequenceLocksAtTip`, i.e. transaction `nLocktime` and `nSequence` will not be evaluated according to block height/time current.

Script checks are still done as-is, so if the transaction itself has an error, it will still fail.

2022-06-21 08:25 UTC, glozow commented
Thanks for picking this up. I just realized I probably should have left a comment summarizing what work needs to be done. Not sure if you saw https://github.com/bitcoin/bitcoin/pull/21413#issuecomment-827228002? We'll want to add (1) an option to override relative timelocks between transactions passed in, (2) a param for what MTP/height to mock, either for the whole thing or at each transaction. This would also require more tests, i.e. utilizing the new options to ensure it works beyond not breaking things.

2022-06-28 00:11 UTC, ariard reviewed
Concept ACK

If you're interested by the whole context, I think there are multiple contingent checks interesting to bypass to sanitize a L2 pre-signed transactions :
- relative timelock (`CheckFinalTxAtTip()` L731 in `validation.cpp`)
- absolute timelock (`CheckFinalTxAtTip()` L731 in `validation.ccp`)
- feerate accuracy (`CheckFeeRate()` L858 in `validation.cpp`)
- CSV execution (`CheckSequence()` L588 in `interpreter.cpp`)
- CLTV execution (`CheckLocktTime()` L554 in `interpreter.cpp`)

Do we have more contingent checks interesting to bypass for a L2 ? The ones listed should be good for LN at least.

Instead of bypassing purely the timelocks checks, it could be interesting to allow passing MTP and height parameters, as suggested in #21413. That would enable to verify that your pre-signed transactions nLocktime and CLTV argument have been paired with correct values.

A further interesting feature would be to allow _dummy_ signatures in the witness script. The intended use-case of such bypass options is to verify the consensus and policy validity of a transaction as pre-signed by your counterparty. However, to limit interference with signers policy it would be ideal for the local L2 node to _not_ have to produce her signature during the verification flow.

Even further, on the LDK-side, we're targeting mostly mobile hosts, on which we might not be able to ship a Bitcoin Core node and access a RPC interface due to constraining OS application policies. It would be ideal to have a `libstandardness` in the spirit of the `bitcoinconsensus` library, exposing a high-level `verify_transaction_standardness()`.

Anyway, good to go move step by step. Effectively it would be nice to break each option in its own PR. For passing a specific height, we could have `testmempoolaccept(height=100)`.

2022-06-29 01:08 UTC, ariard commented
@w0xlt 

Actually a combination of both. The first one + "mock_mtp / mock_height". 
It sounds a lot of flexibility but I think that's what you're aiming for to verify Lightning HTLC-timeout.

2022-07-01 19:19 UTC, luke-jr commented
IMO the idea for `mock_{mtp,height}` is a better approach. "Valid in 9999 years" seems closer to "never valid" than "valid eventually".

2022-07-02 15:39 UTC, w0xlt commented
I pushed some changes:

. `struct MempoolTestCriteria` was created to allocate all parameters suggested in https://github.com/bitcoin/bitcoin/pull/25434#pullrequestreview-1020896809. (https://github.com/bitcoin/bitcoin/pull/25434/commits/be52f8ace2e30aa5981852fafc4fe8f10eb8e759)
. `bypass_timelocks` has been split into `bypass_relative_timelocks` and `bypass_absolute_timelocks`, as suggested in the same comment. (https://github.com/bitcoin/bitcoin/pull/25434/commits/ef766e10225eaed8f24a50304629026709165354)
. The tests were split in two commit: one tests that bypass_timelocls works and the other tests that it doesn't affect OP_CSV and OP_CLTV checks. (https://github.com/bitcoin/bitcoin/pull/25434/commits/9c7b5180f43ef428ef89be9fb5e26e8bef99c659 and https://github.com/bitcoin/bitcoin/pull/25434/commits/81d4bf7fcdc0fc380f5107fd3bd50de0d9ef5db5)

2022-07-02 16:52 UTC, christ79ma approved these changes

2022-07-03 04:19 UTC, w0xlt commented
https://github.com/bitcoin/bitcoin/pull/25532 adds the `bypass_feerate_accuracy` option,

I prefer to keep the different option (or group of options) in different PRs for ease of review.

2022-07-08 01:27 UTC, ariard reviewed
Sounds to move in the good direction. I think it could be good to have a "how-to" in `doc/policy`. I can write it if you would like.

I think it could be good to get one more ACK on the API by someone likely interested by such testmempoolaccept options cc @darosior @instagibbs

2022-07-08 12:15 UTC, w0xlt commented
@ariard Thanks for the review. I will address your suggestions soon.

#25570 adds `bypass_{csv,cltv}` options. This way I think all the options in the list in https://github.com/bitcoin/bitcoin/pull/25434#pullrequestreview-1020896809 are implemented.

2022-07-10 04:38 UTC, w0xlt commented on src/rpc/mempool.cpp
> +                    {"bypass_relative_timelocks", RPCArg::Type::BOOL, RPCArg::Default{false}, "Don't enforce BIP68 relative lock-time.\n"}
Done in https://github.com/bitcoin/bitcoin/pull/25434/commits/7ec64163107a7fc301ed3858ef2e9427e4c4aef8

2022-07-10 04:39 UTC, w0xlt commented on src/rpc/mempool.cpp
> +                    max_raw_tx_fee_rate = CFeeRate(AmountFromValue(options["maxfeerate"]));
Done in https://github.com/bitcoin/bitcoin/commit/7ec64163107a7fc301ed3858ef2e9427e4c4aef8

2022-07-10 04:40 UTC, w0xlt commented on src/validation.cpp
> +        const MempoolTestCriteria m_test_criteria;
Changed it to `const MemPoolBypass m_mempool_bypass` in https://github.com/bitcoin/bitcoin/pull/25577/commits/26ee1a47e4bafe8faf60e16c987504d7d1b71c29

2022-07-10 04:42 UTC, w0xlt commented on src/validation.cpp
> +    assert(args.m_test_criteria.AllowFinalizeTransaction());
Done in https://github.com/bitcoin/bitcoin/pull/25434/commits/12ac626430beda7bc0c8b79b0af6efe5f0e96119

2022-07-10 04:46 UTC, w0xlt commented on src/validation.cpp
> +                                       const std::optional<MempoolTestCriteria>& test_criteria)
Done in #25577.

`test_accept` and `bypass_limits` are used elsewhere, not just `testmempoolaccept`.
#25577 creates `struct MemPoolBypass` that encompasses both variables.

2022-07-10 04:46 UTC, w0xlt commented on src/validation.h
> +struct MempoolTestCriteria {
Done in https://github.com/bitcoin/bitcoin/pull/25577/commits/9e8703ca5ff0ce7a45f160ca26ac3ba7f1f71116

2022-07-10 04:51 UTC, w0xlt commented
@ariard  I addressed most of your suggestions in a new PR (https://github.com/bitcoin/bitcoin/pull/25577).

That PR does not change behavior, it just refactors the use of `test_accept` and `bypass_limits`, allocating them in a new struct `MemPoolBypass`.

I rebased this PR on top of #25577.

2022-07-11 09:56 UTC, darosior commented
I would like to see a stronger rationale for this change, as well as for the end goal of the path to conditionally bypass mempool checks. In short, i'm worried we are going to introduce a lot of complexity to this critical part of the codebase with only marginal -if any- benefits.

It seems like [the motivation is helping to test applications which use offchain contracts](https://github.com/bitcoin/bitcoin/pull/21413#issuecomment-796294039). Any reasonable such application has a functional test framework (similar to ours) in which many sequences of events are tested in a blackbox manner. It is necessary to test the different spending paths of a Script, but does a lot more. Adding the option to bypass timelocks would only allow the most basic of those tests to use `testmempoolaccept` instead of generating a couple of blocks before using `sendrawtransaction`. Sure, that would reduce the runtime of those tests (by what, a few hundred milliseconds?). But i don't think it's a good tradeoff for us to make.
Furthermore, functional tests are for simulating real conditions and you necessary want to test *the very same* codepath that your application would use in prod. That is, using `sendrawtransaction`. We could assure them `testmempoolaccept` actually uses almost the very same codepath as `sendrawtransaction` (which is becoming less true as we add more complexity there), but i don't think it would be very convincing: if testing the exact codepath your application will trigger in prod is a `node.generate(6)` away, you'll just do it.
If the motivation for these PRs, and the direction things are taking, is "it'll help L2s apps to test better, maybe, eventually" i would suggest we take a step back and examine: how would such an application testing framework actually use it? For instance, here are two functional tests from two candidate projects i'm familiar with:
- For C-lightning, https://github.com/ElementsProject/lightning/blob/42783aaa928da79e1295dcdc53123a66cb2433cc/tests/test_closing.py#L480-L599
- For Revault, https://github.com/revault/revaultd/blob/7cd856d5a345319cebc815aa61f3b66cebb48b86/tests/test_rpc.py#L996-L1121

Both (implicitly or not) test the validity of transactions critical to the security of the protocol. I don't think `testmempoolaccept` with any form of bypass would help here. Neither would it for a lot other test.

Even assuming this feature might eventually be used. In #20833 we introduced `testmempoolaccept`, which could be used to quickly sanity check [the "static" standardness bounds of a transaction](https://github.com/bitcoin/bitcoin/pull/20833#issuecomment-762080588). It was probably a good tradeoff. Now, we want to push this forward with allowing to also be able to test timelocked transactions. And by the same logic it was [suggested](https://github.com/bitcoin/bitcoin/pull/25434#pullrequestreview-1020896809) to then allow for mocking the transaction with dummy values for Script. Where do we stop? We have a clear layer violation here. What is suggested with dummy signatures is precisely what we do internally with the [`DummySignatureChecker`](https://github.com/bitcoin/bitcoin/blob/327b7e9236e3b0cde750df72d5f75821e52e545c/src/script/sign.cpp#L586-L623)! Does it mean we should expose all our internals via RPC? I don't think so, it would only result in cluttered code and interfaces and would not eliminate the need for any L2 application to have a functional test framework in which they create keys, spin up nodes, sign transactions and broadcast them in different sequences.

Therefore i think we need some kind of a plan for this bypass-everything direction, as well as some more motivation for going this way.

2022-07-14 18:52 UTC, ariard commented
Motivation of this work is to provide tools enabling L2 applications to verify that issued transactions (not only pre-signed ones) can broadcast well on the p2p network, at least on the majority of nodes running the default Core policy. As a reminder, for this type of application, confirming transactions in due time is critical for the security of funds, a point I believe none of us deny.

For a typical Lightning implementation, this "standardness defect" risk can manifest itself at reception of the counterparty signatures for commitment / HTLC transactions. For the latest one, the `nLocktime` is set and the feerate is 0 (post `option_anchors_zero_fee_htlc_tx`). Therefore those transactions, of which the broadcast time is unknown, would be rejected by `testmempoolaccept` due to to non-compliance with contingent policy checks like timelocks or feerates.

As of today, if you would like to currently assert the standardness of those transactions (to eliminate vulnerabilities like CVE-2020-26895 to slip in), I think the solution is to rewrite by yourself all the policy checks in your implementation library (e.g in rust-bitcoin, we  have a [dust threshold](https://github.com/rust-bitcoin/rust-bitcon/blob/9cfa9bd9df4402363493e7503b86ff6bfd63a14c/src/blockdata/script.rs#L583)) check. However, there is no guarantee that those checks are re-implemented _correctly_ or even that there are _exhaustive_ compared to Bitcoin Core mempool policy ones.

That `testmempoolaccept` code path diverges from `sendrawtransaction` is an unfortunate fact that iirc I raised during the reviews of the mempool package accept PRs. As sketched out above, I think the ideal interface would rather be a`libstandardness` with bypass options allowing direct access to `AcceptToMemoryPool()` not only to make the verification codepath as similar to the broadcast codepath, but also as an architecture convinency for mobile clients and a performance improvement for LN routing hops (relying on RPC call adds latency in HTLC relay due to process context-switch).

I don't think the advocated layer violation matters. In system engineering, you'll always find layer violation, e.g using ASM snippets in your high-level language source code to access CPU registers and boost your computation performance likewise with mathematic libraries (even if 99,99% of the userspace applications won't do that). So I think the question is more about if the layer violation is justified in the present case. About the scope, I think we should allow to check for as much standardness bounds that it makes sense for the application semantic.

That said, I think we should put apart the question of what should be the ideal interface to verify the standardness bounds (i.e RPC call, new shared library, new Capn' Proto interface, etc). In my understanding, I think the question where we diverge is if every L2 implementation should rewrite the Core standardness logic to verify its transaction validity, as much as you can in function of the application semantics, or rather we should expose this standardness logic in a straightforward way.

I think the first approach is not only duplicating the engineering cost for any L2 implementation, instead to factor in Core but also far more error-prone.

2022-07-16 16:58 UTC, luke-jr requested changes
As mentioned on #25532, simply ignoring a rejection should take the approach used in #7533 and #20753.

Special-casing time locks only makes sense if it supports keeping the check but mocking a specific future/past time/height.

2022-08-01 10:38 UTC, glozow commented
Based on https://github.com/bitcoin/bitcoin/pull/25434#issuecomment-1180197200 and the fact that #21413 was in conceptual review stage, marking this as "needs conceptual review" until there is stronger support for this change.

2022-10-04 01:18 UTC, ariard commented
Seeing #25532 closed, still renewing my interest to have an exportable Core "compliant" policy rules checker for second-layers toolchains. From an offline discussion with @darosior there is a scale of severity difference between two class of L2 time-sensitive protocols:
- "static" transactions like Revault, where no participant is able to propose modifications to the transactions input/output/size/scriptpubkeys during the protocol execution
- "malleable" transactions like Lightning where counterparties are proposing modifications to the transaction input/output/size/scriptpubkey (e.g `update_add_htlc` to add a HTLC output on both local/remote commitment transactions)

From my comprehension, the second set of protocols is expected to increase in scope with the deployment of the interactive transaction construction protocol in the LN space, where a set of N participants might contribute to a transaction.  

Looking forward to tackle this project by myself if there is no more interest by the current PR author after done with full-rbf, or at least introduce the subject at IRC meetings to collect more people thoughts on the design space and worthiness of such new API.

2022-10-04 08:33 UTC, glozow commented
> Looking forward to tackle this project by myself if there is no more interest by the current PR author after done with full-rbf, or at least introduce the subject at IRC meetings to collect more people thoughts on the design space and worthiness of such new API.

@ariard thanks for the proactivity, I agree the concept should be discussed with more people (hence "needs conceptual review") - pinging @w0xlt to see if there is a plan to do something like this?

Btw just to clarify, #25532 was closed because it was blocked by this PR and this PR is currently also blocked. I wasn't rejecting the concept, just attempting to focus review attention more to make progress.

2022-10-12 20:14 UTC, w0xlt commented
@glozow I'm not sure I understand your question correctly, but I'm available to discuss this PR (or any other changes).

2022-10-13 14:27 UTC, glozow commented
> @glozow I'm not sure I understand your question correctly, but I'm available to discuss this PR (or any other changes).

From my perspective, this isn't / #21413 wasn't blocked based on code getting written, but because there isn't strong consensus that it's a good idea. I'm wondering what the plan is to get more conceptual review, e.g. through soliciting opinions from specific people or bringing it up in a meeting/mailing list. My question was whether you plan on doing the advocacy work, as it seems @ariard is offering to do so. Hope this clarifies what I meant.

2022-10-23 23:21 UTC, ariard commented
> I'm wondering what the plan is to get more conceptual review, e.g. through soliciting opinions from specific people or bringing it up in a meeting/mailing list.

Still thinking it would be nice to explain all the standardness malleability issues raised by policy for second-layers in a post, though ideally with PoC code. In the light of the recent [LND bug](https://bitcoin.stackexchange.com/questions/115527/what-is-the-october-2022-bug-in-lnd-what-caused-it-and-what-would-prevent-a-sim) due to old policy check in their dependency, I think well-engineered API/RPC calls would minimize the odds of such critical bugs in the future (orthogonal of how a watchtower infrastructure or better error-handling could have prevented this specific LND bug).

Happy to extend on the subject soon, though from my understanding the pipeline of "mempool-as-L2-interface" is quite busy those days between full-rbf, v3 policy, package RBF, ephemeral anchor and else. If someone would like to needle forward on that please do so (though a lot of conceptual things here).

2023-02-06 15:10 UTC, fanquake commented
Closing for now. Not clear what the status of this is. Has needed rebase for > 6 months and had been rebased on top of a PR that is now closed.

2023-02-06 15:10 UTC, closed without merging