wallet: standardize change output detection process
bitcoin/bitcoin pull request #25979
Opened 2022-09-01 20:40 UTC by furszy

This work aims to define, and implement a base standard mechanism to
detect individual change outputs.

### Context

Currently, the wallet detects whether an output is change or not based
on data stored in the address book.

There is no notion of “change outputs”, the wallet detects change scripts.

Connoting that any address book data modification has implications
on all the historical outputs related to a particular destination as all of
them can either be change or not. There is no middle-ground.

#### How Change Detection Currently Works?

The wallet walks-through the transaction outputs, extracts the script
destination and verify the following two points:

1) If the destination doesn't exist in the address book, then the script
    is a "change address".
   
2) If the destination exists in the address book, but it doesn't have a
     label, then the script is a "change address".

### Motivation

There are a good number of problems in the current approach:

- We make the wallet dependent on an external structure, with separate storage.
   Which has to be updated and maintained along with the wallet state.

- It cannot be maintained nor recovered across different wallet instances.
   Cannot re-create the address book data only by importing the wallet descriptor string.

- As the address book is an structure that the user can freely modify, the change
   detection process might differ through different wallets.
 
- The current rudimentary assumptions of "no address book entry" or "no label set for the address book entry"
  to denote that certain script destination is change or not can easily be broken:
  E.g. derive an address from one of the wallet’s external paths manually. Then send coins to it.
  As the receive destination wasn't created inside the wallet, the wallet has no associated address book entry.
  So, the reception is invalidly detected as change (added a test case for it).

- The wallet can't detect change outputs on more complex scripts such as multi-sig change outputs.

- The wallet is not able to detect any change output going to an internal address if the internal address has a label.
  (E.g. the user can manually set a label for the internal address and, doing that, make that all the change outputs,
   in the wallet history, that were sent to the destination are no longer detected as change).

- There isn’t a way to distinguish the external reception of coins into an internal address. Coins reception on any
   internal address are always detected as change.

### New Change Detection Mechanism Goals

Aiming to:

* Define a base mechanism to align different wallet implementations. Preventing each piece of software
  from diverging on the basic change outputs distinction.

* Detect change outputs on-demand without requiring to maintain an external data structure synced with the
   latest wallet state.

* Independently, and accurately, detect change outputs regardless data stored in structures that the user
   can freely modify.

* Granular distinction between change vs non-change outputs that were sent to the same internal address.
  E.g. the reception of coins, from an external source, on internal addresses will not longer be detected
  as change anymore.

* Expand the change detection to more complex scripts such as a multi-sig protected addresses. (While they
  are added into the wallet on an internal spkm)

#### Change Output Detection Rules

A transaction output is change if it fulfills the following points:

1) At least one of the parent transaction inputs is from the wallet. (If none of them are, then the wallet is receiving coins
    on an internal address).

2) The script extracted destination is from the wallet and is located in one of the internal script pub key manager.
    (e.g. derived from an internal derivation path)

#### What about legacy wallets?

If the legacy wallet is HD post-split, we have an internal derivation path, so we can follow the same process as
descriptors wallet. Unless the destination is on the pre-split key pool, in which case, we fallback to the follow-up
case.

If the legacy wallet is pre-split, we continue using the address book as we either have an HD wallet with keys
derived only on the external path, or we are using raw keypool.

———————————————————————

#### Extra Note
This PR, in about 85% at least, is about expanding the current test coverage for the change output detection area.

#### TO DO (still WIP):

* [ ] Save “internal” flag on non-active descriptors so the wallet can use them on the change detection process.
   (which will fix the currently failing test cases).

* [ ] Re-organize commits so tests always pass.

2022-09-02 02:31 UTC, 1440000bytes commented
Interesting pull request although I haven't tested it yet. 

Does this also fix https://github.com/bitcoin/bitcoin/issues/20935 and https://github.com/bitcoin/bitcoin/issues/20795 ?

 > How Change Detection Currently Works?
The wallet walks-through the transaction outputs, extracts the script
destination and verify the following two points:

> If the destination doesn't exist in the address book, then the script
is a "change address".

> If the destination exists in the address book, but it doesn't have a
label, then the script is a "change address".

I was assuming change address had different derivation path. Is that false?

2022-09-02 16:09 UTC, furszy commented
> Does this also fix #20935 and #20795 ?

Yes for the change outputs detection part. It will allow us to properly detect each individual output as change or not independently on what is stored in the address book entry (making the process deterministic across instances, and not dependent on a data structure that the user can freely modify).

As an edge case example; with this, users could even receive coins on an internal address and the new mechanism will properly detect it as an external reception, not a change output (the transaction inputs aren't from the wallet, so no coins are returning to it). Still, this behavior is obviously not encouraged, nor should be easy to do in the wallet, as it breaks the whole idea of internal/external derivation paths.

Plus, would recommend you to check [#25685](https://github.com/bitcoin/bitcoin/pull/25685) as well. The first commit there fixes a misleading wallet behavior where even if you set `add_inputs=false` (telling the wallet to disallow automatic coin selection), the wallet will still fetch coins internally and use them in the Coin Selection process (if you don't pre-set inputs manually).


> > How Change Detection Currently Works?
> > The wallet walks-through the transaction outputs, extracts the script
> > destination and verify the following two points:
> 
> > If the destination doesn't exist in the address book, then the script
> > is a "change address".
> 
> > If the destination exists in the address book, but it doesn't have a
> > label, then the script is a "change address".
> 
> I was assuming change address had different derivation path. Is that false?

Not entirely, the assumption is most of the time correct. It breaks on pre-split legacy wallets, where we don't have an internal derivation path. In those wallet versions we (1) only use an external path to derive public and change addresses, or if we go further back in time, (2) we use a raw pool of keys with no derivation paths at all. (Thus why the initial change detection process was implemented using the address book).

2022-09-03 05:41 UTC, 1440000bytes commented
Concept ACK

2022-10-31 19:53 UTC, achow101 commented
While I like the idea this is going for, I don't think it is sufficient. It relies on `m_internal_spk_managers` which only contains the currently active SPKMs. If a user were to remove a SPKM from being active, all of the addresses that were produced by that would no longer be detected as change. This is especially problematic with #25907 which rotates all of the currently active descriptors.

In general, I'm not sure that we can determine which output is change without storing additional metadata. What has been suggested before is to explicitly store an "IsChange" value in address book entries, with a "smart" fallback like what this PR does.

2023-05-19 13:42 UTC, furszy commented
Thanks for the ping marko, rebased.
Yeah, this is still relevant. Change detection is still an issue.

The base work is done, just need some extra love.
Will kept it rebased, so anyone can review/test it up until I'm able to get back to it.

2023-05-19 13:52 UTC, furszy commented
This now depends on #27601.
Moved to draft until that one gets merged.

2024-01-16 01:39 UTC, Sadiq272 requested changes
Oba

2024-01-16 01:40 UTC, Sadiq272 commented
Pul

2024-01-16 01:40 UTC, Sadiq272 commented
Heti canavarlar

2024-01-16 03:00 UTC, furszy reviewed
This is on a long-working path. Will try to rebase it in the coming days or close it until we proceed with the preceding PRs if it is too behind.

2024-11-04 20:45 UTC, murchandamus commented
Hey @furszy, is this ready for review?

2025-05-04 22:53 UTC, furszy commented
> The dependency was closed more than a year ago: [#27601 (comment)](https://github.com/bitcoin/bitcoin/pull/27601#issuecomment-1989555740)

Time flies. Closing for now as it is not in my priorities.

2025-05-04 22:53 UTC, closed without merging