rpc: Improve error when wallet is already loaded
bitcoin/bitcoin pull request #26192
Opened 2022-09-28 13:15 UTC by aureleoules

Currently, trying to load a descriptor (sqlite) wallet that is already loaded throws the following error:
> error code: -4
> error message:
> Wallet file verification failed. SQLiteDatabase: Unable to obtain an exclusive lock on the database, is it being used by another instance of Bitcoin Core?

I don't think it is very clear what it means for a user.

While a legacy wallet would throw:
> error code: -35
> error message:
> Wallet file verification failed. Refusing to load database. Data file '/home/user/.bitcoin/signet/wallets/test_wallet/wallet.dat' is already loaded.

This PR changes the error message for both types of wallet to:
> error code: -35
> error message:
> Wallet file verification failed. Wallet "test_wallet" is already loaded.

2022-09-29 20:51 UTC, ryanofsky commented on test/functional/wallet_multiwallet.py
> +            assert_raises_rpc_error(-35, f"Wallet file verification failed. Wallet \"{wallet_names[0]}\" is already loaded.", self.nodes[0].loadwallet, wallet_names[0])
In commit "rpc: Improve error when wallet is already loaded" (ca8eba38a19a3c1eac8fc41ae7f9f9a17660710c)

Note for other reviewers: it seemed like a potential concern that this test is dropping coverage for the "Unable to obtain an exclusive lock" error, which can still be triggered. But it looks like there is another check for that error in  in `feature_filelock.py`, so this should be ok.

2022-09-29 20:54 UTC, aureleoules commented on src/wallet/wallet.cpp
> +                // return SQLiteDataFile(wallet_path) == wallet->GetDatabase().Filename();
forgot to remove this, will remove if this gets concept acked

2022-10-01 01:01 UTC, luke-jr commented
Instead of getting this deep into loading, maybe just check if the wallet name is already loaded?

2022-10-01 23:57 UTC, aureleoules commented
> Instead of getting this deep into loading, maybe just check if the wallet name is already loaded?

Yes that makes more sense, pushed it. For some reason I wanted to implement it the same way it was done for the legacy wallet, but this is better.

2022-10-16 13:53 UTC, rajarshimaitra approved these changes
Concept ACK on unifying the wallet loading error message. I remember this caused me confusion and took some time to figure that its an "already loaded" error. 

Code changes looks clean and tests performing as expected..

2022-10-16 17:25 UTC, w0xlt approved these changes
ACK https://github.com/bitcoin/bitcoin/pull/26192/commits/6cde3551e4437ca86410c494d4ac126044abd28a

2022-10-18 16:16 UTC, hernanmarino requested changes
tested ACK, suggested a small nit as a comment.

2022-10-18 16:16 UTC, hernanmarino commented on test/functional/wallet_multiwallet.py
>          path = os.path.join(self.options.tmpdir, "node0", "regtest", "wallets", "w1", "wallet.dat")
```suggestion
```
A small nit, I think this line is not really needed, since the variable **path** is not used anymore with the new error message.

2022-10-18 16:57 UTC, pablomartin4btc reviewed
Tested ACK, verified the errors before and after this fix debugging the python funtional test.
It was clever to check the wallet name on the context at `wallet.cpp` to avoid the db error.

2022-10-20 09:57 UTC, aureleoules commented
Removed unused line.

2022-10-21 14:30 UTC, pablomartin4btc approved these changes
re-ack 0460928

2022-10-21 14:36 UTC, hernanmarino approved these changes
ACK  0460928

2023-01-03 12:49 UTC, theStack approved these changes
Tested ACK 04609284ad5e0b72651f2d4b43263461ada40816

2023-01-03 17:50 UTC, achow101 commented
ACK 04609284ad5e0b72651f2d4b43263461ada40816

2023-01-03 18:02 UTC, merged