Remove Taproot activation height
bitcoin/bitcoin pull request #26201
Opened 2022-09-29 11:16 UTC by Sjors

Drop `DEPLOYMENT_TAPROOT` from `consensus.vDeployments`.

Now that the commit (https://github.com/bitcoin/bitcoin/commit/7c08d81e119570792648fe95bbacddbb1d5f9ae2) which changes taproot to be enforced for all blocks is sufficiently buried by other commits, and thus less likely to be reverted, it seems a good time to remove no longer needed non-consensus code.

Clarify what is considered a BuriedDeployment (see discussion in #26162).

We drop taproot from getdeploymentinfo RPC, rather than mark it as `buried`, because this is not a buried deployment in the sense of BIP 90. This is because the activation height has been completely removed from the code, rather than hard coded.

2022-10-02 14:04 UTC, luke-jr commented
Concept ~0, but I object the claim in general that commits "sufficiently buried by other commits, and thus less likely to be reverted". Git isn't PoW, and "burying" commits does not make them less likely to be reverted.

2022-10-03 09:22 UTC, Sjors commented
@luke-jr changed the wording to "is (probably) included in v24.0".

2022-10-08 03:47 UTC, ajtowns commented
This should be updating `MinBIP9WarningHeight` above the taproot activation height (otherwise you should see `"warnings": "Unknown new rules activated (versionbit 2)"` due to miner signalling)

2022-11-01 09:41 UTC, Sjors commented
@ajtowns done

2022-11-01 09:48 UTC, MarcoFalke commented on src/consensus/params.h
> +     * This prevents us from warning about the CSV,segwit and taproot activations. */
```suggestion
     * This prevents us from warning about the CSV, segwit and taproot activations. */
```

nit

2022-11-01 09:49 UTC, MarcoFalke commented on doc/release-notes-26201.md
> +- 'taproot' has been removed from 'getdeploymentinfo', rather than marked as buried,
```suggestion
- 'taproot' has been removed from 'getdeploymentinfo',
```

nit: I think release notes should describe changes, not provide extended discussion about alternatives

2023-04-25 15:23 UTC, achow101 commented
Are you still working on this?

2023-05-08 14:12 UTC, Sjors commented
I'll rebase soon(tm).

2023-07-27 00:54 UTC, luke-jr requested changes

2023-07-27 00:54 UTC, luke-jr commented on src/deploymentinfo.cpp
> -    },
This will need `aRules` in `rpc/mining.cpp` updated

2023-08-18 10:30 UTC, Sjors commented on src/rpc/mining.cpp
> +        aRules.push_back("!taproot");
@luke-jr like this?

> This will need `aRules` in `rpc/mining.cpp` updated

2023-08-18 10:50 UTC, Sjors commented on src/rpc/mining.cpp
> +        aRules.push_back("!taproot");
Oh wait, without `!`

I'll push a fix and add a test...

Before and after this change it should be:

```
bitcoin-cli getblocktemplate '{"rules": ["segwit"]}' | jq '.rules'
[
  "csv",
  "!segwit",
  "taproot"
]
```

2023-08-18 11:12 UTC, Sjors commented
Rebased after kernel changes. Fixed a regression in `getblocktemplate`'s `rules` result, and added a test for tit.

2023-08-18 11:16 UTC, Sjors commented on src/rpc/mining.cpp
> +    if (!fPreSegWit) {
In #27433 I propose getting rid of `fPreSegWit`.

2023-10-09 14:41 UTC, Sjors commented
Rebased after #28591.

2023-10-23 07:38 UTC, Sjors commented on src/consensus/params.h
> -    DEPLOYMENT_TAPROOT, // Deployment of Schnorr/Taproot (BIPs 340-342)
Added. IIUC the WarningBitsConditionChecker uses ComputeBlockVersion (also used by the miner), which in turn uses VersionBitsConditionChecker, which uses vDeployments to determine if a softfork is STARTED or LOCKED_IN. If so it won't issue the warning. This logic is rather convoluted…

2024-01-09 09:06 UTC, Sjors commented
Rebased because #27433 needed it.

2024-03-07 10:36 UTC, Sjors commented
Rebased due to (trivial) merge conflict after #29547.

2024-08-12 08:38 UTC, Sjors commented
Rebased after #30560 and #29775.

2024-08-26 08:42 UTC, Sjors commented
Rebased after #30658.

2024-09-17 07:42 UTC, Sjors commented
#27433 needed the rebase here

2024-09-18 08:10 UTC, Sjors commented
Removed ~ from the description (wasn't relevant anymore anyway), since @jonatack pointed out in #28358 that these don't get rendered nicely in merges.

2025-03-04 23:16 UTC, l0rinc approved these changes
Concept ACK

2025-03-06 13:26 UTC, Sjors commented
Rebased after #31978.

2025-03-07 03:36 UTC, jonatack reviewed
Light approach ACK 301e41985ef8cc8e3098d1d737864a5ae1f5108e

2025-03-07 03:37 UTC, jonatack commented on src/consensus/params.h
> + * Consensus changes for which the new rules enforced from genesis are not listed here.
Should this be like https://github.com/bitcoin/bitcoin/pull/26201/files#diff-decae4be02fb8a47ab4557fe74a9cb853bdfa3ec0fa1b515c0a1e5de91f4ad0bR1418?

```suggestion
 * Consensus changes for which the new rules are enforced from genesis are not listed here.
```

2025-03-07 09:19 UTC, Sjors commented on src/consensus/params.h
> + * Consensus changes for which the new rules enforced from genesis are not listed here.
Done

2025-04-30 13:09 UTC, Sjors commented
Rebased after #29039.

2025-05-14 07:01 UTC, Sjors commented
Trivial rebase after #32386.

2025-06-19 08:09 UTC, Sjors commented
Rebased after https://github.com/bitcoin/bitcoin/pull/31981 for minor conflict in `mining_basic.py`.

2025-06-19 08:17 UTC, maflcko commented on src/rpc/mining.cpp
> +    if (!fPreSegWit) {
this was https://github.com/bitcoin/bitcoin/pull/31625, but then closed

2025-06-19 08:18 UTC, maflcko commented on doc/bips.md
> +  always active as of **v24.0** ([PR 23536](https://github.com/bitcoin/bitcoin/pull/23536)).
could split up this doc-only update?

2025-06-19 09:12 UTC, Sjors commented on src/rpc/mining.cpp
> +    if (!fPreSegWit) {
Indeed it was split out from #27433 into its own PR #31625, which after some discussion I marked up for grabs.

2025-06-19 09:16 UTC, Sjors commented on doc/bips.md
> +  always active as of **v24.0** ([PR 23536](https://github.com/bitcoin/bitcoin/pull/23536)).
Done in #32776

2025-06-19 14:54 UTC, maflcko commented on doc/bips.md
> +  always active as of **v24.0** ([PR 23536](https://github.com/bitcoin/bitcoin/pull/23536)).
needs rebase

2025-06-19 15:02 UTC, Sjors commented
Rebased after splitting the `doc/bips.md` changes off into https://github.com/bitcoin/bitcoin/pull/32776.

2025-09-03 11:32 UTC, Sjors commented
Rebased after #33274.

2025-12-28 17:03 UTC, sedited commented
Concept ACK

Seems reasonable given that we say "Consensus changes for which the new rules are enforced from genesis are not listed here."

2026-02-24 09:07 UTC, sedited commented
> We drop taproot from getdeploymentinfo RPC, rather than mark it as buried, because this is not a buried deployment in the sense of [BIP 90](https://github.com/bitcoin/bips/blob/master/bip-0090.mediawiki). This is because the activation height has been completely removed from the code, rather than hard coded.

Looking at this a bit more, how is the taproot deployment different here from the segwit deployment? AFAICT the segwit height is only used for checking the `NeedsRedownload` condition, and the purpose of that functionality has been questioned recently too. Can you elaborate on this in the motivation?

2026-02-24 09:26 UTC, Sjors commented
@sedited `Consensus::DEPLOYMENT_SEGWIT` is also used to determine whether a block is allowed to have witness data (`IsBlockMutated`) and for [BIP147](https://github.com/bitcoin/bips/blob/master/bip-0147.mediawiki). I expanded the PR description.

2026-02-27 20:08 UTC, darosior reviewed
Concept ACK.

I find it confusing that we don't simply make it a buried deployment like we did for the past 5 soft forks. But since we always enforce it from genesis, it would probably be even more confusing (for instance setting `-testactivationheight=taproot@42` wouldn't have the intended effect).

Could you update the PR title? There is no Taproot activation height. Maybe "Remove Taproot BIP 9 deployment"?

2026-02-27 20:14 UTC, darosior commented
> But since we always enforce it from genesis, it would probably be even more confusing (for instance setting `-testactivationheight=taproot@42` wouldn't have the intended effect).

I guess it's already equally confusing for `-testactivationheight=segwit@42`. Oh well..

2026-02-28 17:38 UTC, ajtowns reviewed
ACK ec17c82846686cb56da0535051bb701b3c84cfea

2026-02-28 17:38 UTC, ajtowns commented on src/consensus/params.h
> +    // missing witness data is not. BIP 147 also relies on hardcoded activation height.
I think it might be good (not necessarily in this PR) to change `VBDeploymentInfo` in deploymentinfo.h/cpp to perhaps specify the SCRIPT_VERIFY flags related to a deployment, or to add a `std::string` with some info about the deployment (EDIT: and to report this information via getdeploymentinfo).

2026-02-28 17:38 UTC, ajtowns commented on src/rpc/blockchain.cpp
> +        "Consensus changes for which the new rules are enforced from genesis are not listed here.",
Since #32998 we report `"script_flags": [ .., "TAPROOT", .. ]` via getdeploymentinfo for all blocks except the hardcoded exceptions. I think that's sufficient indication that the soft-fork is still enforced even if it's not listed in the "deployments" section anymore. Maybe this comment would be better phrased as 'are not listed ~~here~~ in "deployments".' ?

2026-03-01 12:37 UTC, sedited approved these changes
ACK ec17c82846686cb56da0535051bb701b3c84cfea

2026-03-02 13:28 UTC, Sjors commented on src/consensus/params.h
> +    // missing witness data is not. BIP 147 also relies on hardcoded activation height.
I indeed prefer to leave this for a followup (and as you mention, maybe not needed).

2026-03-02 17:31 UTC, Sjors commented on src/rpc/blockchain.cpp
> +        "Consensus changes for which the new rules are enforced from genesis are not listed here.",
Changed the wording locally, will push later.

2026-03-10 15:17 UTC, Sjors commented on src/rpc/blockchain.cpp
> +        "Consensus changes for which the new rules are enforced from genesis are not listed here.",
Pushed

2026-03-10 15:17 UTC, Sjors commented
Rebased after #34677 v31 chainparams update.

2026-03-11 08:09 UTC, sedited approved these changes
Re-ACK 74f71c5054ff32a9ba922eed59fceeaf79ec1ed8

2026-03-19 11:57 UTC, sedited commented
Ping @ajtowns and @darosior to take another look.

2026-03-19 21:16 UTC, darosior approved these changes
utACK 74f71c5054ff32a9ba922eed59fceeaf79ec1ed8

2026-03-20 02:31 UTC, fanquake commented
cc @instagibbs

2026-03-20 04:43 UTC, ajtowns commented
reACK 74f71c5054ff32a9ba922eed59fceeaf79ec1ed8

2026-03-20 21:57 UTC, achow101 commented
ACK 74f71c5054ff32a9ba922eed59fceeaf79ec1ed8

2026-03-20 22:22 UTC, merged

2026-04-30 16:16 UTC, fanquake commented
Note that this resulted in atleast some changes downstream: https://github.com/lightningnetwork/lnd/pull/10683

2026-04-30 17:56 UTC, Sjors commented
I opened #35183 to document this.