test: Remove confusing DUMMY_P2WPKH_SCRIPT
bitcoin/bitcoin pull request #26277
Opened 2022-10-07 09:18 UTC by MarcoFalke

It is confusing because, it is *not* a P2WPKH script, and it is nonstandard.

See also https://github.com/bitcoin/bitcoin/pull/26265/files#r989827855

Fix all issues by removing it, and also remove the no longer needed `-acceptnonstdtxn` setting from the test.

2022-10-07 10:17 UTC, theStack reviewed
Concept ACK

An alternative to introducing another (magic-number) constant would be to directly use `script_to_p2wsh_script(CScript([OP_TRUE])))` instead, though it's slightly longer.

2022-10-07 11:13 UTC, MarcoFalke commented
Thanks, pushed an alternative that only modifies a single file to reduce merge-conflicting lines.

2022-10-07 13:45 UTC, theStack approved these changes
Code-review ACK fa8a305ddde15abc0df03a3af0a03b92405d68f6 📜

2022-10-07 14:13 UTC, instagibbs commented
ACK https://github.com/bitcoin/bitcoin/pull/26277/commits/fa8a305ddde15abc0df03a3af0a03b92405d68f6

All the replacements of scripts and injection of witnesses look correct, and allows simplification/removal of other tests and utils.

2022-10-08 09:01 UTC, darosior requested changes
Looks like you didn't actually remove `DUMMY_P2WPKH_SCRIPT`'s definition from `test_framework/script_util.py`?

2022-10-10 02:09 UTC, fanquake commented
> Looks like you didn't actually remove DUMMY_P2WPKH_SCRIPT's definition from test_framework/script_util.py?

Yep. Looks like that and `DUMMY_2_P2WPKH_SCRIPT` can be deleted there.

2022-10-10 07:20 UTC, MarcoFalke commented
`DUMMY_2_P2WPKH_SCRIPT` is already unused, so it seems better to remove them in a pull unrelated to this. As removing both would also remove the comment, which may or may not want to be kept. I didn't want to have the discussion here. The only goal here is to cleanup the consensus test.

2022-10-10 07:29 UTC, merged