WIP: Fix coinstatsindex overflow issue
bitcoin/bitcoin pull request #26426
Opened 2022-10-31 00:01 UTC by fjahr

Closes #26362

This changes cumulative values in coinstatsindex to be per-block instead. This is still work in progress and needs further testing and cleanup. Please refer to #26362 for conceptual discussion for now.

2022-11-05 19:25 UTC, luke-jr requested changes

2022-11-05 19:25 UTC, luke-jr commented on src/rpc/blockchain.cpp
> +                        {RPCResult::Type::STR_AMOUNT, "total_unspendable_amount", /*optional=*/true, "The amount of coins permanently excluded from the UTXO set from this block onwards (only availabl
"onwards" seems unlikely to be correct?

2022-11-05 19:25 UTC, luke-jr commented on src/rpc/blockchain.cpp
> +                        {RPCResult::Type::STR_AMOUNT, "total_unspendable_amount", /*optional=*/true, "The amount of coins permanently excluded from the UTXO set from this block onwards (only availabl
Should rename the field if it's a different value

2024-07-01 05:51 UTC, closed without merging

2024-07-17 10:46 UTC, fjahr commented
#30469 continues the work here