Improve address decoding errors
bitcoin/bitcoin pull request #26514
Opened 2022-11-16 18:33 UTC by aureleoules

Attempt to fix #21741.

2022-11-19 21:22 UTC, luke-jr requested changes
NACK on talking about "different networks". While this could in theory be Lightning or sidechains, it's more likely to lead users toward scamcoins.

2022-11-19 21:22 UTC, luke-jr commented on src/key_io.cpp
> +            error_str = strprintf("Invalid prefix for Base58-encoded address on %s. This may be an address for a different network. Valid address starts with `1` or `3` (mainnet) and `m` or `n` or `2
```suggestion
            error_str = strprintf("Invalid or unsupported Base58-encoded address.", params.NetworkIDString());
```

2022-11-19 21:22 UTC, luke-jr commented on src/key_io.cpp
> +            error_str = "Not a valid Segwit (Bech32) or Base58 encoding. This may be an address for a different network.";
```suggestion
            error_str = "Invalid or unsupported Segwit (Bech32) or Base58 encoding.";
```

2022-11-19 21:22 UTC, luke-jr commented on src/key_io.cpp
> +            error_str = strprintf("Invalid prefix for Segwit (Bech32) address on %s (expected %s, got %s). This may be an address for a different network.",
```suggestion
            error_str = strprintf("Invalid or unsupported prefix for Segwit (Bech32) address on %s (expected %s, got %s).",
```

2022-11-24 07:37 UTC, aureleoules commented
Thanks @luke-jr I addressed your suggestions.

2022-11-24 07:42 UTC, aureleoules commented on src/key_io.cpp
> +            error_str = strprintf("Invalid prefix for Segwit (Bech32) address on %s (expected %s, got %s). This may be an address for a different network.",
I also removed the `on %s` (network)

2023-03-09 19:38 UTC, willcl-ark commented
Concept ACK

2023-03-11 13:49 UTC, davidgumberg commented
Maybe add a message for not-yet-understood witness versions and a test case?

```diff
  if (version == 1 && data.size() == WITNESS_V1_TAPROOT_SIZE) {
      static_assert(WITNESS_V1_TAPROOT_SIZE == WitnessV1Taproot::size());
      WitnessV1Taproot tap;
      std::copy(data.begin(), data.end(), tap.begin());
      return tap;
  }
+
+ if (version > 1 && version <= 16) {
+     error_str =  "Invalid or unsupported Bech32 address witness version."
+     return CNoDestination();
+ }
+
  if (version > 16) {
      error_str = "Invalid Bech32 address witness version";
      return CNoDestination();
  }
```

2023-03-11 14:02 UTC, davidgumberg commented
@sipa Thanks! I misunderstood.

2023-03-11 15:31 UTC, 1440000bytes approved these changes
utACK https://github.com/bitcoin/bitcoin/pull/26514/commits/962a0930e699b74b3c4d019427df6e2b3af5c831

---

> NACK on talking about "different networks". While this could in theory be Lightning or sidechains, it's more likely to lead users toward scamcoins.

Ideally it should have been 'chain' instead of network as networks are ipv4, ipv6, tor, i2p etc. although we should not be concerned about scammers if they ever use this software but use correct technical terms in errors IMO.

The comment is anyways addressed by author and I think PR improves error messages.

2023-03-13 15:40 UTC, davidgumberg commented
ACK https://github.com/bitcoin/bitcoin/pull/26514/commits/962a0930e699b74b3c4d019427df6e2b3af5c831

2023-03-13 16:58 UTC, merged