rpc: Prevent unloading a wallet when rescanning
bitcoin/bitcoin pull request #26618
Opened 2022-12-01 16:09 UTC by aureleoules

Fixes #26463.

This PR prevents a user from unloading a wallet if it is currently rescanning.

To test:

```bash
./src/bitcoin-cli -testnet -named createwallet wallet_name=wo disable_private_keys=true
./src/bitcoin-cli -testnet -rpcwallet=wo importdescriptors '[{
	  "desc": "addr(mmcuW74MyJUZuLnWXGQLoNXPrS9RbFz6gD)#tpnrahgc",
      "timestamp": 0,
      "active": false,
      "internal": false,
      "next": 0
}]'
./src/bitcoin-cli -testnet unloadwallet wo
error code: -4
error message:
Wallet is currently rescanning. Abort existing rescan or wait.

2022-12-02 16:43 UTC, stickies-v reviewed
Current behaviour seems to be that `unloadwallet` waits until the scan is finished. Changing that by throwing could affect downstream users that are expecting `unloadwallet` to just wait. I think the behaviour in this PR is better if it were implemented like that from the start. I'm not sure if it's worth changing though? ~0 on this for now.

2022-12-03 01:05 UTC, ishaanam reviewed
> Current behaviour seems to be that unloadwallet waits until the scan is finished.

This is what I have observed as well. Even so, I think that it would be better if instead of waiting for the rescan to finish (which could take hours), `CWallet::AbortRescan` is called from `unloadwallet`. This seems better because `unloadwallet` should ideally be able to unload the wallet relatively quickly regardless of the processes that the wallet is running. A warning could be given when a rescan has been aborted by `unloadwallet` so that a user is not surprised.

2022-12-03 10:28 UTC, aureleoules commented
> Changing that by throwing could affect downstream users that are expecting unloadwallet to just wait.

Do you know any software that would use this behavior? I understand this could affect users but this seems a bit hacky.

> A warning could be given when a rescan has been aborted by unloadwallet so that a user is not surprised.

I don't really have an opinion on this. But an argument for keeping the warning in 8198c76a3008094fefbbae1b11e5d5673a993158 is that an user may not realize that the wallet is still rescanning and wouldn't want to abort it when trying to unload.
As a compromise we could add a 'force' argument to unloadwallet to abort the rescan if there is one.

2022-12-03 20:06 UTC, w0xlt commented
> As a compromise we could add a 'force' argument to unloadwallet to abort the rescan if there is one.

I think this is a good approach.

2022-12-07 01:34 UTC, luke-jr commented
Agree with a force option (named only / options Object).

But also, we probably shouldn't return from `unloadwallet` until the wallet is actually unloaded fully, independently of whether that's due to a rescan or otherwise.

I guess this PR is strictly better than the current behaviour, though, so Concept ACK.

2022-12-07 14:09 UTC, aureleoules commented
I added the named `force` option that will abort the rescan in progress.
https://github.com/bitcoin/bitcoin/compare/8198c76a3008094fefbbae1b11e5d5673a993158..bee026e801cf692707477ca51505d708ef051cae

2022-12-07 20:28 UTC, promag reviewed
Tiny concept NACK.

I think `unloadwallet` should just fail if a scan is in progress. We already have that behavior/warning elsewhere: `Wallet is currently rescanning. Abort existing rescan or wait.` I understand it can be seen as a breaking change, but makes more sense than what happened in #26463.

---
Regardless of the above, the current code is still not ideal, for instance, a scan can be initiated after `IsScanning` check if `importdescriptors` is called concurrently. I think you should use `WalletRescanReserver` because it allows checking if a rescan is in progress and at the same time prevent concurrent scans.

A test case would be nice.

2022-12-07 21:15 UTC, luke-jr requested changes

2022-12-07 21:15 UTC, luke-jr commented on src/wallet/rpc/wallet.cpp
> +                    {"force", RPCArg::Type::BOOL, RPCArg::Optional::OMITTED_NAMED_ARG, "Force unload of wallet. This will abort any rescan in progress."},
This is a positional parameter. See `simulaterawtransaction` for how to do named-only parameters in an options Object.

(Maybe move "load_on_startup" there too)

2022-12-08 00:01 UTC, ziggie1984 commented
Thanks for fixing this issue. I like the approach more where we just fail the `unloadwallet` call but the force flag is also a good way. 

>  a scan can be initiated after IsScanning check if importdescriptors is called concurrently.

Definitly important to prevent bitcoind from crashing. I was able to bring bitcoind down when unloading the wallet (blocking in the background) deleting the walletdir and then importing the descriptors with the same wallet name again (an then there was a dependence that one sync finished before the other). So would be important if we would not allow loading a wallet which is currently in rescan (at least not with the same name).

2022-12-08 12:47 UTC, furszy commented on src/wallet/rpc/wallet.cpp
> +        wallet->AbortRescan();
As `AbortRescan()` does not abort the scanning process right away (only sets a flag that is later read by the wallet's scanning thread), might be good to add a "wait until scan aborts" here.

So there is no race between the wallet removal and the scanning process.

2022-12-08 15:30 UTC, promag requested changes
Concept ACK, `unloadwallet` fails if a rescan is in progress. Needs:
 - release notes
 - test, not sure how 
 - follow-up in the GUI

2022-12-08 15:30 UTC, promag commented on src/wallet/rpc/wallet.cpp
> +    WalletRescanReserver reserver(*wallet);
`reserver` destructor needs to be called before `UnloadWallet`, something like:
```cpp
{
    WalletRescanReserver reserver(*wallet);
    ....
    
    RemoveWallet()
}
UnloadWallet();

```

2022-12-08 15:47 UTC, aureleoules commented
Thanks, @promag. I added release notes.

I think the test should be a follow-up as there are many other instances where this warning is not tested.

2022-12-08 16:08 UTC, promag commented
> I think the test should be a follow-up as there are many other instances where this warning is not tested.

The general rule of thumb is that tests are added when there are changes.

2022-12-08 16:34 UTC, aureleoules commented
> The general rule of thumb is that tests are added when there are changes.

I agree but the RPC error `Wallet is currently rescanning. Abort existing rescan or wait` has not been tested in other RPCs either and if a test were to be added, the other RPCs should be tested too and that may be out of scope.

```
grep -nrIi "Wallet is currently rescanning. Abort existing rescan or wait" ./src
src/wallet/rpc/backup.cpp:159:            throw JSONRPCError(RPC_WALLET_ERROR, "Wallet is currently rescanning. Abort existing rescan or wait.");
src/wallet/rpc/backup.cpp:254:        throw JSONRPCError(RPC_WALLET_ERROR, "Wallet is currently rescanning. Abort existing rescan or wait.");
src/wallet/rpc/backup.cpp:447:        throw JSONRPCError(RPC_WALLET_ERROR, "Wallet is currently rescanning. Abort existing rescan or wait.");
src/wallet/rpc/backup.cpp:516:        throw JSONRPCError(RPC_WALLET_ERROR, "Wallet is currently rescanning. Abort existing rescan or wait.");
src/wallet/rpc/backup.cpp:1351:        throw JSONRPCError(RPC_WALLET_ERROR, "Wallet is currently rescanning. Abort existing rescan or wait.");
src/wallet/rpc/backup.cpp:1658:        throw JSONRPCError(RPC_WALLET_ERROR, "Wallet is currently rescanning. Abort existing rescan or wait.");
src/wallet/rpc/transactions.cpp:872:        throw JSONRPCError(RPC_WALLET_ERROR, "Wallet is currently rescanning. Abort existing rescan or wait.");
src/wallet/rpc/wallet.cpp:444:            throw JSONRPCError(RPC_WALLET_ERROR, "Wallet is currently rescanning. Abort existing rescan or wait.");
```

```
grep -nrIi "Wallet is currently rescanning. Abort existing rescan or wait" ./test
<empty>
```

I'll look into adding a test though.

2022-12-08 16:36 UTC, promag commented
My suggestion is to test the just introduced error, the other are indeed out of scope.

2022-12-08 23:02 UTC, ziggie1984 commented
Is it conceptionally possible to abort the rescan, if the wallet_dir is deleted ? My tests showed me that bitcoind will happily rescan further ? Or is it somehow a user-misbehaving we should not take into account ?

2022-12-08 23:07 UTC, promag commented
@ziggie1984 user-misbehaving

2022-12-09 03:53 UTC, luke-jr commented
Yeah, I would think deleting data files out from under the software should be expected to crash ;)

2022-12-14 19:43 UTC, aureleoules commented
I added a test in #26700 @promag.

2022-12-16 14:38 UTC, w0xlt approved these changes
ACK https://github.com/bitcoin/bitcoin/pull/26618/commits/109cbb819ddd20220a255791c40261f746260f42

2023-01-09 15:44 UTC, kouloumos reviewed
ACK 109cbb819ddd20220a255791c40261f746260f42
The implementation is consistent with how the `WalletRescanReserver` is used in the rest of the related RPCs as pointed out in https://github.com/bitcoin/bitcoin/pull/26618#pullrequestreview-1209074941 .
(check the rest of the RPCs with `git grep -n "Wallet is currently rescanning. Abort existing rescan or wait"`)

I would also prefer to see a test as part of this PR, but looking at the linked draft PR implementation it seems that the relative complexity to include a test (other test cases missing, refactor of an existing test file) justifies a follow-up.

2023-01-09 16:22 UTC, promag reviewed
ACK 109cbb819ddd20220a255791c40261f746260f42

2023-01-09 21:18 UTC, achow101 commented
ACK 109cbb819ddd20220a255791c40261f746260f42

2023-01-09 22:02 UTC, achow101 commented
This was merged

2023-01-09 22:02 UTC, closed without merging