CLI: Only one Request Handler can be specified.
bitcoin/bitcoin pull request #27815
Opened 2023-06-04 00:07 UTC by Brotcrunsher

Previously it was possible to specify multiple, however only one was picked in this arbitrary and (probably) undocumented priority: getinfo > netinfo > generate > addrinfo.

2023-06-24 01:52 UTC, luke-jr requested changes

2023-06-24 01:52 UTC, luke-jr commented on src/bitcoin-cli.cpp
> +        if (nRh > 1) {
```suggestion
        if (gArgs.IsArgSet("-getinfo") + gArgs.GetBoolArg("-netinfo", false) + gArgs.GetBoolArg("-generate", false) + gArgs.GetBoolArg("-addrinfo", false) > 1) {
```

This is admittedly a bit obscure, so maybe there's a better way (but it's still an improvement over the temporary variable IMO)

2023-07-03 00:12 UTC, luke-jr commented
nit: Commit summary is too long. Would also be nice to rebase on top of 42af9596ce85a541988abee54eed8a9b271a46a1

2023-10-25 15:41 UTC, pablomartin4btc commented
Concept ACK.

I agree this validation should be put in place, please check #26990 if you haven't already, in the second commit 11e0a80b19a98b79adaa25a06f14d564da3ba85b there's a function that already does this (`IsExclusivelyCliCommand()`), feel free to take anything you find useful.

As pointed out by @luke-jr please check the project [guidelines](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#committing-patches) regarding commits specifications.

Also, for future reference, check the [guidelines](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#coding-style-c) regarding C++ coding style and naming conventions (e.g. `nRh` in your code change).

Thanks for working on this!

2023-11-16 11:48 UTC, closed without merging