build: pass sanitize flags to instrument libsecp256k1 code
bitcoin/bitcoin pull request #27991
Opened 2023-06-28 13:48 UTC by fanquake

secp256k1 functions are now instrumented:
```bash
# objdump --disassemble-symbols=_secp256k1_xonly_pubkey_serialize src/test/fuzz/fuzz | grep sanitizer_cov
100eb5244: 73 5d 01 94 	bl	0x100f0c810 <___sanitizer_cov_trace_const_cmp8>
100eb53f0: cc 5c 01 94 	bl	0x100f0c720 <___sanitizer_cov_trace_pc_indir>
100eb5418: c2 5c 01 94 	bl	0x100f0c720 <___sanitizer_cov_trace_pc_indir>
100eb5444: b7 5c 01 94 	bl	0x100f0c720 <___sanitizer_cov_trace_pc_indir>
```

Not sure if this is the best solution. Would fix #27990.

2023-06-28 13:51 UTC, hebasto commented
Is it guaranteed that sanitizer flags for a C++ compiler are acceptible by a C compiler?

2023-06-28 14:01 UTC, dergoegge commented
Concept ACK

All of the CI task that make use of the `integer` sanitizer are probably gonna fail.

2023-07-04 15:07 UTC, luke-jr requested changes

2023-07-04 15:07 UTC, luke-jr commented on configure.ac
> +ac_configure_args="${ac_configure_args} --disable-shared --with-pic --enable-benchmark=no --enable-module-recovery --disable-module-ecdh CFLAGS=${SANITIZER_CFLAGS}"
Won't this lose the other `CFLAGS` currently passed by the user?

2023-07-23 13:54 UTC, hebasto commented
FWIW, CMake [works](https://github.com/bitcoin/bitcoin/issues/27990#issuecomment-1646846003) out of the box :)

2023-07-23 20:48 UTC, emc99 commented
> Maybe mark as draft for as long as CI is red?

When does CI happen? Why would CI be red in this case?

2023-09-07 11:00 UTC, fanquake commented
Maybe we can followup with this in future (regardless of anything CMake related).

2023-09-07 11:00 UTC, closed without merging