init: adding check for : for -torcontrol flag
bitcoin/bitcoin pull request #28018
Opened 2023-06-30 21:24 UTC by kevkevinpal

right now for -torcontrol you can pass in any string as long as it doesn't have a : but that is invalid. I added an additional check before calling SplitHostPort to see if there is a :

closes https://github.com/bitcoin/bitcoin/issues/23589

2023-06-30 21:42 UTC, kevkevinpal commented
<img width="500" alt="Screenshot 2023-06-30 at 4 40 24 PM" src="https://github.com/bitcoin/bitcoin/assets/15950706/d95ba8f9-dad2-4ada-b235-41acf8b58aa4">

-----

<img width="500" alt="Screenshot 2023-06-30 at 4 40 12 PM" src="https://github.com/bitcoin/bitcoin/assets/15950706/d2280a41-b1c2-44e6-b32a-9112321b1664">

-----

<img width="500" alt="Screenshot 2023-06-30 at 4 39 51 PM" src="https://github.com/bitcoin/bitcoin/assets/15950706/ec94182a-b9dd-4701-b57d-6a45ad3487b3">

2023-07-02 20:46 UTC, Ayush170-Future commented
Overall, I think the code is good. However, there have been some earlier remarks in this [comment](https://github.com/bitcoin/bitcoin/pull/23605#issuecomment-980045955) on where to place this code.

Someone with a better understanding of the entire codebase should comment on the placement of this. 

In any case, I'm testing it locally and will report back on whether it meets the requirements soon.

2023-07-03 02:21 UTC, kevkevinpal commented
> Overall, I think the code is good. However, there have been some earlier remarks in this [comment](https://github.com/bitcoin/bitcoin/pull/23605#issuecomment-980045955) on where to place this code.
> 
> Someone with a better understanding of the entire codebase should comment on the placement of this.
> 
> In any case, I'm testing it locally and will report back on whether it meets the requirements soon (one suggestion I think you should avoid using `/` in the branch name)

Yea I could totally move the logic to a util or somewhere other than init.cpp since there might be too much logic in there. Not exactly sure where would be the best spot.

Also another thing I wanted to clarify is that will `-torcontrol` always be in the format of `host:port` or is there ever a chance of being abe to just provide one or the other? because then we can try splitting and validating each part individually

2023-07-03 13:48 UTC, Ayush170-Future commented
Tested this locally.

1. Any string that is not of the type `<host>:<port>` is rejected. 
Example: `./src/bitcoind -torcontrol=1`.

2. Also works for Domain names. 
Example: `./src/bitcoind -torcontrol=localhost:9051` is accepted.

3. But multiple instances of `:` are also accepted. 
Example: `./src/bitcoind -torcontrol=localhost:9051:23` is also accepted.
This should also be avoided, right?


> Also another thing I wanted to clarify is that will `-torcontrol` always be in the format of `host:port` or is there ever a chance of being abe to just provide one or the other? because then we can try splitting and validating each part individually

Yes, I think `-torcontrol` should always be of form `<host>:<port>`.

2023-07-03 13:54 UTC, Ayush170-Future commented on src/init.cpp
> +        bool fHaveColon = colon != socket_addr.npos;
I believe here. You might additionally check the count of `:` characters in `socket_addr` and return an error if they are more than one.

2023-07-03 21:41 UTC, bitcoinfinancier approved these changes

2023-07-04 15:20 UTC, luke-jr requested changes
Concept NACK. Port isn't required (the default is 9051). Furthermore, even "1" is a valid value (it would be the same as 0.0.0.1:9051), though I suppose it wouldn't hurt to check for it specifically and reject it.

2023-07-05 12:12 UTC, Ayush170-Future commented
A gentle ping to @luke-jr, what about this issue then? [23589](https://github.com/bitcoin/bitcoin/issues/23589)

2023-07-05 17:05 UTC, bitcoinfinancier approved these changes

2023-07-11 13:38 UTC, willcl-ark commented
Unrelated to the implementation here, but in general I disagree with most of Luke's comment:

> Port isn't required (the default is 9051). 

The way this is currently documented, both host and port should be required:

```

The option is `torcontrol` and should require `host::port` if specified. If we used independant options `torcontrolhost` and `torcontrolport` then we could reasonably have defaults for both, and make both optional, but having _half of a single option_ be optional seems pretty weird.

> Furthermore, even "1" is a valid value (it would be the same as 0.0.0.1:9051), though I suppose it wouldn't hurt to check for it specifically and reject it.

Whilst this is true for low-level networking (code), IMO it's extremely un-common to not require users to use dot-decimal notation for hosts, and I think we should reject non dot-decimal hosts to prevent exactly the issue in https://github.com/bitcoin/bitcoin/issues/23589. We'll lose no flexibility by doing so as users who want to use 0.0.0.1 can just, set the option to that directly?

2023-09-05 17:14 UTC, kevkevinpal commented
closing this PR for now since this https://github.com/bitcoin/bitcoin/pull/28101 should fix the issue, the PR just changes the helper text to explain that a default port is included but no additional checks are added

2023-09-05 17:14 UTC, closed without merging