refactor: use string_view for passing string literals to Parse{Hash,Hex}
bitcoin/bitcoin pull request #28172
Opened 2023-07-27 19:54 UTC by jonatack

as `string_view` is optimized to be trivially copiable, whereas the current code creates a `std::string` copy at each call.

These utility methods are called by quite a few RPCs and tests, as well as by each other.

```
$ git grep "ParseHashV\|ParseHashO\|ParseHexV\|ParseHexO" | wc -l
61
```

Also remove an out-of-date external link.

2023-07-28 06:10 UTC, maflcko requested changes
Not sure. This has no effect on the compiled binary and is only changing the style of the code.

2023-08-03 06:26 UTC, maflcko approved these changes
string_view is dangerous, because it can lead to use-after-free, but here it seems fine. lgtm.

I think you can remove the 4 links to random blog posts, because everyone is able to type `std::string_view` into a search engine, if they want to. Also, I don't think the benchmark is useful in this context and can be removed. If we cared about an RPC call taking a few femtoseconds less, there are much lower hanging fruits to pick. A benchmark would be useful if this showed an end-to-end improvement, but it seems more likely that the compiler already optimized all of this down to the same number of cycles when the functions are called in a complex RPC method.

2023-09-15 18:23 UTC, brunoerg commented on src/rpc/util.cpp
> +uint256 ParseHashV(const UniValue& v, std::string_view name)
What is the difference of changing `std::string` to `std::string_view` in comparision of changing it to `const std::string& name`? The overhead of a reference to the entire object?

2023-09-18 11:48 UTC, brunoerg commented on src/rpc/util.cpp
> +uint256 ParseHashV(const UniValue& v, std::string_view name)
Cool, thanks!

2023-09-18 11:48 UTC, brunoerg approved these changes
crACK bb91131d545d986aab81c4bb13676c4520169259

2023-10-13 22:47 UTC, ns-xvrn commented
Tested locally and reviewed the code changes, looks good.

ACK https://github.com/bitcoin/bitcoin/commit/bb91131d545d986aab81c4bb13676c4520169259

2023-11-02 19:43 UTC, achow101 commented
ACK bb91131d545d986aab81c4bb13676c4520169259

2023-11-02 19:45 UTC, merged