contrib: verify-binaries accept full arch-platform specifier
bitcoin/bitcoin pull request #28418
Opened 2023-09-05 21:18 UTC by willcl-ark

Currently the verify-binaries script will accept "wildcards" such as "linux" or "darwin" as binary specifiers.

Builders however usually only want to verify for their specific architecture-platform that they want to use, or verify everything. Update the script to accept single full architecture-platform specifiers as used by the binary repositories.

Previously if you tried to use a complete specifier, e.g. 25.0-x86_64-linux-gnu it would download all `linux-gnu` platform binaries as this is parsed into 4 parts, and so `version_rc` and `version_os` are [unspecified](https://github.com/bitcoin/bitcoin/blob/9d3b216e009a53ffcecd57e7f10df15cccd5fd6d/contrib/verify-binaries/verify.py#L107-L114).

With the new parser it's still possible to specify "25.0-linux" or "25.0-x86_64" to verify multiple builds if so desired.

2023-09-08 13:51 UTC, TheCharlatan commented
Approach ACK

2024-05-22 18:02 UTC, BenWestgate commented
Concept ACK

Have not tested this branch but based on reading the diff it Closes #30145.

Approach:
The script doesn't need to know what part of the string is `arch`, `os` or `platform` to match the file.
Considering this, a much simpler parser produces the same functionality:
https://github.com/bitcoin/bitcoin/blob/9f6ccfced950cc4e334163af911ffc620bd5e216/contrib/verify-binaries/verify.py#L102-L111
Is there a reason to capture these in separate variables that I am missing?

Comparing to `VERSION_ARCHES` and `VERSION_PLATFORMS` lists makes this file more work to maintain as it needs updates each time Bitcoin supports a new architecture or OS.

The user interface strings of this branch are better than master. I have a test written for the "download only one file" scenario in the linked similar PR.

2024-05-22 21:45 UTC, BenWestgate requested changes
Approach NACK

Does not seem to completely solve the "Download just one file" use case in the commit description for certain inputs. Will fail with error if the user attempts to specify further the file they want downloaded. More complex code than necessary that requires updates if new platforms or architectures are supported by Bitcoin.

This is too much shoe horning and a pattern match on the file name in SHA256SUM, after special handling `<version>[-rcN]` since these have special rules, seems sufficient.

I have tested this branch and found the following issues:

This is the result whether `27.0-arm` or `27.0-arm-` are given to the command. It downloads both arches. In my PR, `27.0-arm-` would just download only arm and not arm64.
```
[INFO] downloading bitcoin-27.0-arm-linux-gnueabihf.tar.gz to /tmp/bitcoin_verify_binaries.27.0-arm
[INFO] downloading bitcoin-27.0-arm64-apple-darwin.zip to /tmp/bitcoin_verify_binaries.27.0-arm
[INFO] downloading bitcoin-27.0-arm64-apple-darwin.tar.gz to /tmp/bitcoin_verify_binaries.27.0-arm
```

Here's two files being downloaded for no reason
```
python3 verify.py -q pub 27.0-x86_64-apple-darwin
VERIFIED: bitcoin-27.0-x86_64-apple-darwin.zip
VERIFIED: bitcoin-27.0-x86_64-apple-darwin.tar.gz
```
Trying to dial it down further makes it fail:
```
ben@ben$ python3 verify.py -q pub 27.0-x86_64-apple-darwin.zip
[ERROR] unable to parse version; expected format is <major>.<minor>[.<patch>][-rc[0-9]][-arch][-operating_system]
[ERROR]   e.g. 22.0-x86_64 or 23.1-rc1-apple-darwin or 25.0-x86_64-linux-gnu
[ERROR] Supported architectures: ['aarch64', 'arm', 'arm64', 'osx', 'osx64', 'powerpc64', 'powerpc64le', 'riscv64', 'x86_64']
[ERROR] Supported platforms: ['apple', 'apple-darwin', 'linux-gnu', 'linux-gnueabihf', 'win64']
```

I can't search for all "linux" (yes, I know I ignored the rules, but why *should* this be invalid?)
```
ben@ben$ python3 verify.py -q pub 27.0-linux
[ERROR] unable to parse version; expected format is <major>.<minor>[.<patch>][-rc[0-9]][-arch][-operating_system]
[ERROR]   e.g. 22.0-x86_64 or 23.1-rc1-apple-darwin or 25.0-x86_64-linux-gnu
[ERROR] Supported architectures: ['aarch64', 'arm', 'arm64', 'osx', 'osx64', 'powerpc64', 'powerpc64le', 'riscv64', 'x86_64']
[ERROR] Supported platforms: ['apple', 'apple-darwin', 'linux-gnu', 'linux-gnueabihf', 'win64']
```

2024-05-22 21:45 UTC, BenWestgate commented on contrib/verify-binaries/verify.py
> +    hashes_to_verify = parse_sums_file(SUMS_FILENAME, [version_arch, os_filter])
As mentioned earlier, some values of `version_arch` and `os_filter` are still going to download multiple files but should not.
Such as:
"27.0-arm" fetches arm64 as well
"27.0-arm64" fetches both .zip and .tar.gz
"27.0-x86_64-apple-darwin" fetches both .zip and .tar.gz
"27.0-win64" fetches both setup.exe and .zip
etc.

So we need to be able to specify more than this.

That's why I suggested a simpler approach that doesn't try to understand what it's matching and just gets the matching or partially matching file name(s) in SHA256SUMS I feel that gives users more flexibility and is less code to maintain.

2024-05-22 21:45 UTC, BenWestgate commented on contrib/verify-binaries/verify.py
> +        log.error("no files matched the platform specified. check available versions on bitcoincore.org/bin")
Another good error message I'm borrowing it.

2024-05-24 09:47 UTC, closed without merging