txorphanage: add size accounting, use wtxids, support multiple announcers
bitcoin/bitcoin pull request #28481
Opened 2023-09-14 13:59 UTC by glozow

This PR contains changes to `TxOrphanage` needed for package relay stuff. See #27463 for project tracking and #28031 for how this code is used.

2023-09-14 15:29 UTC, dergoegge commented
```sh
$ echo "/wGS/6UKCpKl/wEH6P9LAf9++v8B//////8CO/86p/87NJ//n/87//86//+xEzsxAP8CO/87Mp/+
n/87//86pwEin/87Bf8A/1sA9VsB/wD6/wEAAAClkpJbEQH1pT0QejGppf82yaNb+v8BAAClkpJb
EQH1o1sdS0tL/////////////wH/APr/AQAAAKWSklsRAfUPAKNb+v8H6P9LAf8A+v8BAP9bAf8A
+v8BAEAApZKSWxEB9aU9EHoxqaX/NsmjW/r/AQAApZKSWxEB9aNbHUtLS///////////////////
//////////94eHj//0tLS/0=" | base64 -d > orphanage_crash
$ FUZZ=txorphan ./src/test/fuzz/fuzz orphanage_crash
...
test/fuzz/txorphan.cpp:98 operator(): Assertion `orphanage.BytesFromPeer(peer_id) >= ref->GetTotalSize()' failed.
...
```

2023-09-15 17:55 UTC, instagibbs reviewed
initial comments, reviewed everything, also replicated the same fuzzer crash locally

2023-09-15 17:55 UTC, instagibbs commented on src/txorphanage.cpp
> +    if (!Assume(m_peer_bytes_used.count(peer) == 0)) m_peer_bytes_used.erase(peer);
leave a comment that this is belt-and-suspenders only, the condition should fail since the item should have been already erased

2023-09-15 17:55 UTC, instagibbs commented on src/txorphanage.h
> +    bool AddTx(const CTransactionRef& tx, NodeId peer, const std::vector<uint256>& parent_txids) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex);
Should describe the new argument as something like "all unique parent transaction txids"

2023-09-15 17:55 UTC, instagibbs commented on src/txorphanage.h
> +    /** Get an orphan's parent_txids, or std::nullopt if the orphan is not present. */
```Suggestion
    /** Get an orphan's unique parent_txids, or std::nullopt if the orphan is not present. */
```

2023-09-15 17:55 UTC, instagibbs commented on src/txorphanage.h
> +    /** Limit the orphanage to the given maximum. Returns all expired entries. */
```Suggestion
    /** Limit the orphanage to the given maximum. Returns all expired entries by wtxid. */
```

2023-09-15 17:55 UTC, instagibbs commented on src/txorphanage.cpp
> +    std::vector<uint256> expired;
s/expired/expired_wtxids/

2023-09-15 17:55 UTC, instagibbs commented on src/txorphanage.cpp
>      unsigned int nEvicted = 0;
can remove this and use size of `expired(_wtxids)` set isntead

2023-09-15 17:55 UTC, instagibbs commented on src/txorphanage.h
> +    std::vector<uint256> EraseForPeer(NodeId peer) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex);
please remove this return https://github.com/bitcoin/bitcoin/pull/28031#discussion_r1326094730

2023-09-15 17:55 UTC, instagibbs commented on src/txorphanage.cpp
> +std::vector<uint256> TxOrphanage::EraseForBlock(const CBlock& block)
unused in this PR, but is exercised in tests so I'm happy for it to be used later :+1:

2023-09-15 17:55 UTC, instagibbs commented on src/test/orphanage_tests.cpp
> +    // Ensure txid != wtxid
could this get mechanically asserted as extra-belt-and-suspender

2023-09-15 17:55 UTC, instagibbs commented on src/test/fuzz/txorphan.cpp
> +                    orphanage.EraseForBlock(block);
might as well capture the return and check it here too

2023-09-18 17:55 UTC, Yugthakkar04 approved these changes
add this to the first line of array or a bolleyan function and then to the first line of paragraph..

2023-09-18 17:56 UTC, Yugthakkar04 requested changes
make this a transidental function and then work upon it and mechanically assert it up than.

2023-09-22 16:35 UTC, glozow commented on src/net_processing.cpp
> +            m_orphanage.EraseTx(orphan_wtxid);
Uh, unsure what a r-lambda function is and pretty sure calling something else doesn't make sense so I'm resolving this comment.

2024-04-30 15:01 UTC, closed without merging

2024-08-09 14:50 UTC, Theschorpioen approved these changes