improve MallocUsage() accuracy
bitcoin/bitcoin pull request #28531
Opened 2023-09-25 22:17 UTC by LarryRuane

The `MallocUsage()` function takes an allocation size as an argument and returns the amount of physical memory consumed, which is greater due to memory allocator overhead and alignment. It was first added in 2015 (first commit of #6102), but its accuracy has degraded as memory allocation libraries have evolved. It's used when it's important that large data structures, such as the coins cache and mempool, should use a predictable, configurable (limited) amount of physical memory (see the `-dbcache` and `-maxmempool` configuration options), as well as a few other places.

@sipa figured out a concise, efficient [expression](https://github.com/bitcoin/bitcoin/pull/27748#discussion_r1215541260) that this function can use, and that's what's implemented here.

Also add a unit test, which is more helpful than usual in this case since platforms, operating systems, and libraries vary significantly in this area.

2023-09-25 22:17 UTC, LarryRuane commented
The results of the old and new versions of this function should differ only slightly; it would be bad if the new one gave very different results, because node operators might find too much memory being consumed, or (not as bad) not enough. To manually test this, I ran `-reindex-chainstate` on Ubuntu, and watched memory usage by printing `/proc/pid/statm` and watching the `data` (6th) field. On master, the value settled to 315140 (units are 4k pages); with this PR it was 315606, which indicates that the new version produces slightly smaller results, but they're close.

2023-09-27 15:11 UTC, LarryRuane commented
Changing to draft because CI on a couple of the platforms failed the new test, so the physical memory calculation will need to be different on those platforms, I try to figure that out.

2023-11-20 08:24 UTC, martinus commented
I can reproduce the same results with glibc 2.31 and 2.38, in 32bit and 64bit. I don't think it needs to be perfect on all platforms, I think your new calculation is fine.

I played a bit with a reproducer, here is mine:  https://godbolt.org/z/zqhzxoobx I refactored your `MallocUsage` formula a bit, but it's basically the same

2024-02-29 20:28 UTC, LarryRuane commented
Force-pushed to 04f3fbe308728d2fb18fad418603cab97f0b9f59 - rebase only. (CI is still expected to fail, I'm working on that now.)

2024-03-15 22:34 UTC, LarryRuane commented
@martinus
Can you think of why the macOS and Win64 are failing (I have only Ubuntu, which passes)? As an experiment, I changed the memory usage ratio needed to pass to the resource map being just less than `std_map`, but not even that passes (that is, the resource map uses more space). Both of those platforms fail the same way (you can see this in the CI results, this is Win64):
```
D:/a/bitcoin/bitcoin/src/test/pool_tests.cpp(183): error: in "pool_tests/memusage_test": 
  check memusage::DynamicUsage(resource_map) <= memusage::DynamicUsage(std_map) * 100 / 100 
  has failed [466624 > 451088]
```
On earlier runs, some other tests have failed, but I'm not sure if those are spurious failures.

I'm not sure what to do now, any thoughts or suggestions are welcome!

2024-03-19 17:40 UTC, LarryRuane commented
@sipa - I don't think the test failures could be due to differences in memory allocation overhead across platforms. The actual memory allocation overhead isn't being tested at all. To do that would probably require a test that uses `/proc/meminfo` (which doesn't exist on all platforms) or similar.

I don't mind giving up and closing this PR, but as @martinus said in an [earlier comment](https://github.com/bitcoin/bitcoin/pull/28531#issuecomment-1818440265), this calculation doesn't need to be perfect, just better.

I think this test failure must be due to differences in `std::unordered_map` implementations. That container does various allocations for different reasons, and it must be that with this PR's change in memory usage calculation, the `std::unordered_map` on macOS and Win64 (at least) are doing more a kind of allocation that the new calculation thinks has higher overhead. Something like that.

I thought I had it figured out; I verified with the debugger that as the test adds the 10k entries to the two maps, it has to repeatedly grow the bucket array. The allocation sizes (in bytes) for the bucket array that I saw here on Ubuntu were: 104, 232, 472, 1026, 2056, 4328, 8872, 18856, 40696, and finally, 82184. The tradeoff one makes when using the pool resource allocator is that memory allocations that are freed but then those same sizes not allocated again, those allocations are, in effect, leaked (until the resource is destroyed). The pool resource works great when freeing and allocating the same sizes (rounded up to the alignment, usually 8 bytes) repeatedly. This is, of course, the case for the individual map entries.

So the latest force-push simply calls `reserve()` initially on both maps (this is only really needed for the pool resource map). Debugging verifies that this does prevent the bucket array from being reallocated, here on Ubuntu. But it didn't fix the problem on at least macOS and Win64. Maybe those platforms' implementations of `std::unordered_map` ignore the `reserve()` hint?

It's difficult when CI fails on platforms that I don't have access to. Do others have a solution to that? Can I install macOS on Ubuntu or Windows 10 (I have both) as a VM? Maybe I can set up my Windows laptop to build and run the debugger, but that seems like a lot of work.

2024-03-20 09:32 UTC, martinus commented
@LarryRuane The problem here is that the `DynamicUsage(const std::unordered_map<X, Y, Z>& m)` just estimates the memory usage by thinking that internally it uses a node with a single pointer (see `struct unordered_node : private X` in `memusage.h`). That this estimation is probably not correct on all platforms, e.g. windows seems to use a double linked list, so this underestimates memory usage.

The inconcsistency now comes when using `DynamicUsage` with a pool resource. Here the actual real world memory usage is counted (because it uses a custom allocator, there's no need for estimating node size), and here the real world usage is reflected in the number.

So, with your new MallocUsage the numbers are most likely more correct, but this seems to trigger the incorrect underestimation for `DynamicUsage(const std::unordered_map<X, Y, Z>& m)`

2024-03-21 17:37 UTC, LarryRuane commented
@martinus - thanks, that makes perfect sense! I hadn't thought of the possibility of the nodes having two pointers instead of one (double instead of single linked list). Seems like a bad design, but anyway.

I don't think there would be much benefit to fixing `DynamicUsage(const std::unordered_map<X, Y, Z>& m)` to account for this (make it dependent on platform), because this function is no longer important since we're using the pool resource. It's probably really used only in the test. So it's really just a test problem. I'll see what I can do to fix this.

2024-05-22 19:12 UTC, LarryRuane commented
**NOTE**, this PR isn't ready to merge; at the very least it has some debug prints that need to be removed.

CI was failing on some platforms (Windows and macOS), in `test/functional/mempool_limit.py: test_mid_package_eviction()`. I think this test is fragile; this very-unrelated PR shouldn't be able to cause it to fail IMO. The problem turned out to be the following:

This test calls the test utility function `fill_mempool()`. This function creates independent physically-large (around 65kb) transactions at varying fee rates until the one with the lowest feerate is evicted due to the mempool becoming full. The functional tests run with `-maxmempool=5` (MB), so that requires about 72 transactions.

After `fill_mempool()` returns, the mempool likely won't be _completely_ full, because these were large transactions, so there's some space left but not enough for another transaction. The test, `test_mid_package_eviction`, then submits a smaller transaction (weight around 8k) called `mempool_evicted_tx` with a fee just barely high enough to be accepted, and expects that transaction to be accepted. (It has this name, `mempool_evicted_tx`, because the test expects it to be evicted later.)

With this PR, that transaction was not accepted on Windows and macOS. Some debug prints show that on those platforms, when `fill_mempool()` returns, there are only 1200 bytes of free space in the mempool. This is because the `std::unordered_map` library implementations are different on these platforms, and this causes the memory usage calculation (for the entire map) to be slightly different in this PR. So it's really just bad luck. This is why I think the test is fragile.

After trying a few fixes to the test that didn't work, what finally worked (the current branch) is, to have `fill_mempool()`, just before it returns, submit another transaction that _replaces_ (RBF) an existing one in the mempool, but is slightly smaller. This frees up about 10kb of additional space, which allows room for the 8k transaction to be reliably accepted. This doesn't break the other tests that call `fill_mempool()`.

This attempt didn't work the first time, however, because the mempools wouldn't reliably sync in `test/functional/p2p_1p1c_network.py`. This test starts 4 nodes, and calls `fill_mempool()` on node 0 then waits for all 4 mempools to become synced. Sometimes they do but other times this never happens. I wonder if there might be an unrelated bug (I can investigate later), but what often happens (it's timing dependent and thus random) is that the replacement tx (added by this PR) does appear on all nodes, but a low-feerate tx that was evicted on node 0 remains on nodes 1-3. I can explain what I'm seeing in more detail later if needed. What ended up fixing this is to [delay](https://github.com/bitcoin/bitcoin/pull/28531/files#diff-1a6267ad805cafba25aba03b9c6e3f8315b3f9eb9a938e7c64d4c2b8fac525f9R91) a few seconds before submitting the RBF transaction. It's ugly, maybe there's a better way, but syncing mempools is kind of non-deterministic anyway, so I don't think it's terribly bad.

@glozow and @theStack, can you let me know your opinion? You two have worked a lot in this area.

2024-05-23 20:58 UTC, LarryRuane commented
Your patch is much better, @theStack, thanks! It's simpler and doesn't need that weird `sleep`. Force-pushed your patch. If it passes CI, I think this is the way to go. I had tried something similar, but I didn't think to make the sending of that extra (smaller) transaction conditional based on available mempool space.

2024-05-24 18:31 UTC, LarryRuane commented
CI passed, thanks @theStack. I just force-pushed swapping of the two commits, the test commit has to be first for each commit to pass CI.

2025-03-19 08:37 UTC, l0rinc commented on test/functional/test_framework/mempool_util.py
> +                                                utxo_to_spend=confirmed_utxos.pop(0), target_weight = 32500 * 4)
After https://github.com/bitcoin/bitcoin/pull/30718 this should likely be:
```suggestion
                                                utxo_to_spend=confirmed_utxos.pop(0), target_vsize=32500)
```

2025-03-19 11:06 UTC, l0rinc requested changes
I think this is an important change, I'm running a full reindex to check for any noticeable behavior changes.

I left a few recommendations, this patch contains all my recommendations:
```patch
diff --git a/src/memusage.h b/src/memusage.h
index 501f7068ca..5855e9d18b 100644
--- a/src/memusage.h
+++ b/src/memusage.h
@@ -24,9 +24,6 @@
 namespace memusage
 {
 
-/** Compute the total memory used by allocating alloc bytes. */
-static size_t MallocUsage(size_t alloc);
-
 /** Dynamic memory usage for built-in types is zero. */
 static inline size_t DynamicUsage(const int8_t& v) { return 0; }
 static inline size_t DynamicUsage(const uint8_t& v) { return 0; }
@@ -48,7 +45,7 @@ template<typename X> static inline size_t DynamicUsage(const X * const &v) { ret
  *  application data structures require more accurate inner accounting, they should
  *  iterate themselves, or use more efficient caching + updating on modification.
  */
-static inline size_t MallocUsage(size_t alloc)
+static constexpr size_t MallocUsage(size_t alloc)
 {
     // There are few if any actual zero-length allocations; when
     // DynamicUsage(std::vector<X>& v) calls this function, and v.capacity() == 0,
@@ -59,20 +56,16 @@ static inline size_t MallocUsage(size_t alloc)
     // library-dependent.
     if (alloc == 0) return 0;
 
-    static constexpr size_t overhead = sizeof(void*);
-#if defined(__arm__)
-    // tested with ARM 32bit
-    static constexpr size_t step = sizeof(void*) * 2;
-    static constexpr size_t min_alloc = 9;
+#if defined(__arm__) || SIZE_MAX == UINT64_MAX
+    constexpr size_t min_alloc{9};
 #else
-    static constexpr size_t step = 16U;
-    static constexpr size_t min_alloc = sizeof(void*) == 8 ? 9 : 0;
+    constexpr size_t min_alloc{0};
 #endif
-    // step should be nonzero and a power of 2
-    static_assert(step > 0);
-    static_assert((step & (step-1)) == 0);
-    // tested with Linux glibc 2.31 and 2.38, 32bit and 64bit
-    return (std::max(min_alloc, alloc) + overhead + (step - 1)) & ~(step - 1);
+    constexpr size_t overhead{sizeof(void*)};
+    constexpr size_t step{alignof(std::max_align_t)};
+    static_assert(std::has_single_bit(step));
+
+    return (std::max(min_alloc, alloc) + overhead + (step - 1)) & -step;
 }
 
 // STL data structures
diff --git a/src/test/mempool_tests.cpp b/src/test/mempool_tests.cpp
index f0094dce59..9e9ae4d73c 100644
--- a/src/test/mempool_tests.cpp
+++ b/src/test/mempool_tests.cpp
@@ -804,4 +804,13 @@ BOOST_AUTO_TEST_CASE(MempoolAncestryTestsDiamond)
     BOOST_CHECK_EQUAL(descendants, 4ULL);
 }
 
+BOOST_AUTO_TEST_CASE(BitwiseStepSimplificationTest)
+{
+    for (uint64_t step{1}; step != 0; step <<= 1) {
+        std::cout << step << std::endl;
+        BOOST_CHECK(std::has_single_bit(step));
+        BOOST_CHECK_EQUAL((~(step - 1)), -step);
+    }
+}
+
 BOOST_AUTO_TEST_SUITE_END()
```

the updated https://godbolt.org/z/45EnoP16T shows that the output is the same as currently

2025-03-19 11:06 UTC, l0rinc commented on src/memusage.h
> +// It is believed that some containers use two pointers per node, so this
can we add some references to avoid having to rely on beliefs?

2025-03-19 12:05 UTC, l0rinc reviewed
Some of the usages seem to contain some magical values, tailored to the previous behavior:
* https://github.com/bitcoin/bitcoin/blob/master/src/txmempool.cpp#L1066
* https://github.com/bitcoin/bitcoin/blob/master/src/test/disconnected_transactions.cpp#L39-L43

Do any of them need adjustments now?

2025-03-19 20:24 UTC, LarryRuane reviewed
@l0rinc - thank you for the excellent review and great suggestions. I especially like making `MallocUsage()` a `constexpr` function.

I'll force-push a commit taking all of them except moving the first (test-only) commit (I left a comment explaining my reasoning).

2025-03-19 20:24 UTC, LarryRuane commented on test/functional/test_framework/mempool_util.py
> +    if node.getmempoolinfo()['usage'] >= 4_990_000:
I think it's okay that it's initially dead code because it makes the test less fragile in general. In theory, a different project could cherry-pick just this test-only commit, and later make some other changes that would have caused this test to break (when it's really a false-positive failure), but because of taking this commit, that doesn't happen (the test continues to pass). Or, a similar way to think of it is, the test could have been written this way to begin with (and that would not have seemed strange). But I don't feel strongly about, I can make that change if you'd like.

I'll update the commit comment, good catch.

2025-03-19 20:36 UTC, l0rinc commented on test/functional/test_framework/mempool_util.py
> +    if node.getmempoolinfo()['usage'] >= 4_990_000:
I would like to avoid having a false sense of security by putting this before the fix, which usually indicates that the desired behavior is reproduced and is retained after this fix - which isn't the case here exactly. And the dead code part also bothers me for a similar reason.

2025-03-19 20:39 UTC, l0rinc commented on src/memusage.h
> +    static constexpr size_t step = sizeof(void*) * 2;
I forgot to include this in the full patch, my bad

2025-03-27 20:00 UTC, l0rinc requested changes

2025-03-27 20:14 UTC, LarryRuane commented on src/memusage.h
> +    void* ptr2;
No, I'll write a detailed comment later today or tomorrow, but it turns out the lack of this second pointer caused the pool test to fail, because on macOS and Windows; they really do have two pointers per node. I was able to determine this with certainty with debug printing (you can see it in some of the force-pushes above). I added a comment just before the start of this `struct unordered_node` definition to explain this second pointer, did you see that? I didn't call it forward and previous because I really don't know that, I only know that there are 16 bytes in this part of the struct (but I am going to assume that there are two pointers).

2025-03-28 22:25 UTC, LarryRuane commented on src/memusage.h
> +    return usage_resource + usage_chunks + MallocUsage(2 * sizeof(void*) * m.bucket_count());
I'm making this and two similar changes above (for `std::unordered_set` and `std::unordered_map` because CI debug prints show that on some platforms (macOS and Win64), each element of the bucket array uses 16 bytes (likely two pointers) rather than 8 bytes (one pointer). This is probably because the bucket lists are doubly-linked. (This gives a performance advantage for removal by iterator; it's not necessary to hash the key to find the bucket, then walk that bucket's list looking for the element being removed.)

There is no way to tell at compile time if the bucket lists should be assumed to be one or two pointers, so it's better to be conservative and assume it's two. (This may result in actual memory usage being slightly less than what the user configured for large data structures like the mempool and the coins cache.)

2025-04-10 09:49 UTC, l0rinc commented on test/functional/test_framework/mempool_util.py
> +    if node.getmempoolinfo()['usage'] >= 4_990_000:
yes, it's fine if it's in the same commit, of course.

2025-04-10 09:49 UTC, l0rinc commented on src/test/validation_flush_tests.cpp
> +    constexpr size_t COIN_SIZE{64};
This is a surprising change, can you please explain it?
Do we even get to `BOOST_CHECK_EQUAL(view.DynamicMemoryUsage(), is_64_bit ? 32U : 16U);` here - and if so, how come none of the other values need changing?

2025-04-10 09:49 UTC, l0rinc commented on test/functional/test_framework/mempool_util.py
> +                                                utxo_to_spend=confirmed_utxos.pop(0), target_weight = 32500 * 4)
This is introduced here incorrectly and fixed in a later commit - as discussed, could you please add it in the same or after the fix commit?

2025-04-10 09:49 UTC, l0rinc commented on src/memusage.h
> +    constexpr size_t min_alloc{9};
could we document this number here, it's definitely not obvious

2025-04-10 09:49 UTC, l0rinc commented on src/memusage.h
> +    return MallocUsage(sizeof(unordered_node<std::pair<const X, Y> >)) * m.size() + MallocUsage(2 * sizeof(void*) * m.bucket_count());
`2 * sizeof(void*)` refers to `ptr` + `ptr2`, right? Can we extract that to an explanatory constant?

2025-04-10 09:49 UTC, l0rinc commented on src/memusage.h
> +    return usage_resource + usage_chunks + MallocUsage(2 * sizeof(void*) * m.bucket_count());
> likely two pointers

Is there a way to verify and document that explicitly (pointing to doc or code)?

2025-04-10 09:49 UTC, l0rinc commented on test/functional/test_framework/mempool_util.py
> +    test_framework.generate(ephemeral_miniwallet, 2 + num_of_batches * tx_batch_size)
same, can we extract the `2` to a named constant?

2025-04-15 08:45 UTC, l0rinc commented on src/test/validation_flush_tests.cpp
> +    constexpr size_t COIN_SIZE{64};
[I've checked](https://github.com/bitcoin/bitcoin/pull/32244) and most of the test is dead for the [past 3 years](https://github.com/bitcoin/bitcoin/pull/25325), cc @martinus.

Could you update the modified test all the way to revive it and define the desired behavior?

2025-05-15 23:15 UTC, LarryRuane commented
The main change in the latest force push is to address the [review comment](#discussion_r2044004503) about `validation_flush_tests.cpp`. I ended up almost completely rewriting the `getcoinscachesizestate` test case; it was kind of a mess. It was far too fragile because it required equality of various values related to memory usage (which is why this test started failing with this PR, even though nothing had actually broken). This is especially difficult when a test must run in both the 32-bit and 64-bit environments. A test like this should be more of a sanity check. 

This test case also tested things outside of the `GetCoinsCacheSizeState()` function, which is what the test case name implies. The new version tests exactly that function, driving it to return its various possible results. It's more focused and easier to understand now, in my opinion.

Also, I squashed the three commits, two of them test-only, down to a single commit, as [suggested above](#discussion_r2003105459); it's still a pretty small commit.

Reviewers, please let me know if the commit message is too wordy. It's almost entirely about the test changes (I preserved the text from what used to be separate commits), because those were the trickiest parts of this PR. But maybe it would be better for some of that explanation to be here in the PR instead of the commit message.

@l0rinc, thank you for your excellent review comments. There were a few suggestions I didn't take (so far, at least); I'll leave comments as replies to yours.

2025-05-15 23:30 UTC, LarryRuane commented on src/memusage.h
> +    constexpr size_t min_alloc{9};
That constant came from your [comment](#pullrequestreview-2697495377) (which I've adopted into this PR), so I really don't know how to document this value. Where did you get it from? This stuff tends to have magic numbers; I don't think this PR makes it any worse.

2025-05-15 23:30 UTC, LarryRuane commented on src/memusage.h
> +    return MallocUsage(sizeof(unordered_node<std::pair<const X, Y> >)) * m.size() + MallocUsage(2 * sizeof(void*) * m.bucket_count());
Yes, and there is a fairly detailed comment on lines 194-195 (just before the `unordered_set` version of `DynamicUsage`), so I think that's sufficient. But if you feel strongly, I'll try to come up with something.

2025-05-15 23:30 UTC, LarryRuane commented on test/functional/test_framework/mempool_util.py
> +    test_framework.generate(ephemeral_miniwallet, 2 + num_of_batches * tx_batch_size)
I think the comment immediately above explains it sufficiently, and the "1" was not a named constant either (so this pull is not making it worse). But if you feel strongly, I can do something. (As someone once said, the hardest part of programming is coming up with good names!)

2025-05-15 23:30 UTC, LarryRuane commented on test/functional/test_framework/mempool_util.py
> +    if node.getmempoolinfo()['usage'] >= 4_990_000:
Fixed.

2025-05-16 17:02 UTC, LarryRuane commented
Rebased to see if that fixes CI failure (which seems unrelated), the branch was previously rebased on Mar 17 2025.

2025-05-27 15:34 UTC, l0rinc requested changes
Thanks for getting back to this change.
We should synchronize it with `CCoinsMap`, chich already claims to account for an "overhead of 1 or 2 pointers".
Also, the test should pass before the change as well, so it would be helpful to add it as a separate commit before the change to make it easy to see how it behaves before and after the change as well.
The test still contains a lot of repetition, please see my suggestion on how to compact it a bit more.
There are still uncovered parts of the code, I'd feel more comfortable if all modified code parts are exercised by tests.

2025-05-27 15:34 UTC, l0rinc commented on src/memusage.h
> +    size_t usage_bucket_array = MallocUsage(2 * sizeof(void*) * m.bucket_count());
https://github.com/bitcoin/bitcoin/blob/master/src/coins.h#L219 already claims to account for 1-2 pointers, do we need any other change to synchronize it with the current PR?

2025-06-04 09:34 UTC, l0rinc commented
I understand the difficulties of guessing the correct memory usage of such an app (especially when the user cannot even provide total memory usage requirements, just `dbcache` ones), trying to find a formula that is good enough on all OSs, compilers, versions, 32/64 bits, architectures, etc.
I ran a simple benchmark to see if this memory accounting changed the behavior of IBD (simulated via a `reindex-chainstate` with default `dbcache=450` until block 888,888).

For reference, the commits I used are:
*   3f83c744ac - master with old `MallocUsage`
*   4228018ace - this PR with new `MallocUsage`

<details>
<summary>The PR introduces a ~2% slowdown</summary>

```bash
COMMITS="3f83c744ac28b700090e15b5dda2260724a56f49 4228018ace848adcafd197776cbb4afc2400bf16"; \
STOP=888888; DBCACHE=450; \
CC=gcc; CXX=g++; \
BASE_DIR="/mnt/my_storage"; DATA_DIR="$BASE_DIR/BitcoinData"; LOG_DIR="$BASE_DIR/logs"; \
(echo ""; for c in $COMMITS; do git fetch -q origin $c && git log -1 --pretty='%h %s' $c || exit 1; done; echo "") && \
hyperfine \
  --sort command \
  --runs 1 \
  --export-json "$BASE_DIR/rdx-$(sed -E 's/(\w{8})\w+ ?/\1-/g;s/-$//'<<<"$COMMITS")-$STOP-$DBCACHE-$CC.json" \
  --parameter-list COMMIT ${COMMITS// /,} \
  --prepare "killall bitcoind; rm -f $DATA_DIR/debug.log; git checkout {COMMIT}; git clean -fxd; git reset --hard && \
    cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release && ninja -C build bitcoind && \
    ./build/bin/bitcoind -datadir=$DATA_DIR -stopatheight=$STOP -dbcache=10000 -printtoconsole=0; sleep 10" \
  --cleanup "cp $DATA_DIR/debug.log $LOG_DIR/debug-{COMMIT}-$(date +%s).log" \
  "COMPILER=$CC ./build/bin/bitcoind -datadir=$DATA_DIR -stopatheight=$STOP -dbcache=$DBCACHE -reindex-chainstate -blocksonly -connect=0 -printtoconsole=0"
```

> 3f83c744ac Merge bitcoin/bitcoin#32526: fuzz: Delete wallet_notifications
> 4228018ace improve MallocUsage() accuracy

```bash
Benchmark 1: COMPILER=gcc ./build/bin/bitcoind -datadir=/mnt/my_storage/BitcoinData -stopatheight=888888 -reindex-chainstate -blocksonly -connect=0 -printtoconsole=0 -dbcache=450 (COMMIT = 3f83c744ac28b700090e15b5dda2260724a56f49)
  Time (abs ≡):        19573.674 s               [User: 35453.443 s, System: 2822.880 s]

Benchmark 2: COMPILER=gcc ./build/bin/bitcoind -datadir=/mnt/my_storage/BitcoinData -stopatheight=888888 -reindex-chainstate -blocksonly -connect=0 -printtoconsole=0 -dbcache=450 (COMMIT = 4228018ace848adcafd197776cbb4afc2400bf16)
  Time (abs ≡):        20031.162 s               [User: 36761.112 s, System: 2992.418 s]
```

```python
Relative speed comparison
        1.00          COMPILER=gcc ./build/bin/bitcoind -datadir=/mnt/my_storage/BitcoinData -stopatheight=888888 -reindex-chainstate -blocksonly -connect=0 -printtoconsole=0 -dbcache=450 (COMMIT = 3f83c744ac28b700090e15b5dda2260724a56f49)
        1.02          COMPILER=gcc ./build/bin/bitcoind -datadir=/mnt/my_storage/BitcoinData -stopatheight=888888 -reindex-chainstate -blocksonly -connect=0 -printtoconsole=0 -dbcache=450 (COMMIT = 4228018ace848adcafd197776cbb4afc2400bf16)
```
</details>

To understand the performance and memory implications, I ran the same benchmark with Massif profiling, revealing that after this PR we're using ~4% less total memory now
<details>
<summary>3f83c744ac28b700090e15b5dda2260724a56f49 has 790MB peak</summary>

```
    MB
790.2^#
     |#:   :  :           :        :                           :
     |#:   :  :        :  :        :               :  :  :: : :: ::   @   :
     |#::  :  :        :  :        :       :     : :  :  :: : :: ::   @   :
     |#::  :  :        :  :        :       :     :::  : ::: : :: ::   @   : :
     |#::  :  : :      :: : :      :      ::   : :::  : ::: : :: ::  :@   : ::
     |#::  :  ::: :    :: : :     :::::   :::  : :::  ::::::: :: ::  :@:  : ::
     |#::  :  :::::    :: : :  : :::: :   :::: : :::: ::::::: :: ::  :@:  : ::
     |#::  :  :::::   ::: : :  : :::: : :::::: : :::: ::::@::::: :: ::@:: : ::
     |#:: ::  :::::   :::::::  : :::: ::: :::::: :::: ::::@::::: :: ::@:::: ::
     |#:::::  ::::::  ::::::: :: :::: ::: ::::::::::::::::@::::: :: ::@:::: @:
     |#::::: :::::::  :::::::::: :::: ::: ::::::::::@:::::@:::::@:: ::@:::: @:
     |#::::: ::::::::::::::::::: :::: ::: ::::::::::@:::::@:::::@:: ::@:::::@:
     |#:::::::::::::::::::::::::::::: ::: ::::::::::@:::::@:::::@:::::@:::::@:
     |#:::::::::::::::::::::::::::::: ::: ::::::::::@:::::@:::::@:::::@:::::@:
     |#:::::::::::::::::::::::::::::: ::: ::::::::::@:::::@:::::@:::::@:::::@:
     |#:::::::::::::::::::::::::::::: ::: ::::::::::@:::::@:::::@:::::@:::::@:
     |#:::::::::::::::::::::::::::::: ::: ::::::::::@:::::@:::::@:::::@:::::@:
     |#:::::::::::::::::::::::::::::: ::: ::::::::::@:::::@:::::@:::::@:::::@:
     |#:::::::::::::::::::::::::::::: ::: ::::::::::@:::::@:::::@:::::@:::::@:
   0 +----------------------------------------------------------------------->h
     0                                                                   77.36
```
</details>


<details>
<summary>4228018ace848adcafd197776cbb4afc2400bf16 has 760MB peak</summary>

```
    MB
760.9^                                                      ##
     |               @@        @                            #        :   :
     |               @         @    :::           ::        #        :   ::
     |  ::     :     @  :      @    : : ::        :         #  :::   :   ::
     |  : ::   :  :: @  :  ::  @    : : : : :    :: ::      #  ::    :   ::
     |  : : :: :  :  @  :  :   @    : : : : :  :::: :       #  :: @  :   ::
     |  : : : ::  :  @  :  :   @ :: : :@: : :  : :: :       #  :: @  :   ::
     |  : : : ::  :  @  :  :   @ : :: :@: : :  : :: : ::    #  :: @  :   ::
     | :: : : ::  :  @ ::  :   @ : :: :@: : :  : :: : :     #  :: @ ::  ::::
     | :: : : ::  :  @ ::  :   @:: :: :@: : :::: :: : : ::  #  :: @ ::  ::::
     | :: : : ::  : :@ :::::   @:: :: :@: :@:: : :: : : : ::#  :: @ ::  :::: :
     | :: : : ::::: :@ ::: : ::@:: :: :@: :@:: : :: : : : : #  :: @ ::::::::@:
     | :: : : ::: : :@ ::: : : @:: :: :@: :@:: : :: : : : : #  :: @:::: ::::@:
     | :: : : ::: : :@ ::: : : @:: :: :@: :@:: : :: : : : : # ::: @:::: ::::@:
     | :: : : ::: : :@ ::: : : @:: :: :@: :@:: : :: : : : : # ::: @:::: ::::@:
     | :: : : ::: : :@ ::: : : @:: :: :@: :@:: : :: : : : : # ::: @:::: ::::@:
     | :: : : ::: : :@ ::: : : @:: :: :@: :@:: : :: : : : : # ::: @:::: ::::@:
     | :: : : ::: : :@ ::: : : @:: :: :@: :@:: : :: : : : : # ::: @:::: ::::@:
     | :: : : ::: : :@ ::: : : @:: :: :@: :@:: : :: : : : : # ::: @:::: ::::@:
     | :: : : ::: : :@ ::: : : @:: :: :@: :@:: : :: : : : : # ::: @:::: ::::@:
   0 +----------------------------------------------------------------------->h
     0                                                                   79.52
```
</details>

It's not immediately obvious if this is more accurate than before, so I've checked the dbcache related memory usages, which we can see in the logs as:
> Using 440.0 MiB for in-memory UTXO set (plus up to 4.8 MiB of unused mempool space)

<details>
<summary>3f83c744ac28b700090e15b5dda2260724a56f49 - 414,449,664B for nodes + 47,738,776B for buckets = ~440MiB dbcache usage</summary>

```
->50.02% (414,449,664B) 0x7D42A2: std::__detail::_Hash_node<std::pair<COutPoint const, CCoinsCacheEntry>, false>* std::__detail::_Hashtable_alloc<PoolAllocator<std::__detail::_Hash_node<std::pair<COutPoint const, CCoinsCacheEntry>, false>, 144ul, 8ul> >::_M_allocate_node<std::piecewise_construct_t const&, std::tuple<COutPoint const&>, std::tuple<> >(std::piecewise_construct_t const&, std::tuple<COutPoint const&>&&, std::tuple<>&&) [clone .isra.0] (in /mnt/my_storage/bitcoin/build/bin/bitcoind)
| ->48.66% (403,177,472B) 0x7D5F9B: CCoinsViewCache::BatchWrite(CoinsViewCacheCursor&, uint256 const&) (in /mnt/my_storage/bitcoin/build/bin/bitcoind)
| | ->48.66% (403,177,472B) 0x7D4C15: CCoinsViewCache::Flush() (in /mnt/my_storage/bitcoin/build/bin/bitcoind)
| |   ->48.66% (403,177 [...]

2025-06-08 18:15 UTC, l0rinc commented on src/test/util_malloc_usage_tests.cpp
> +BOOST_AUTO_TEST_SUITE(util_malloc_usage_tests)
@LarryRuane, most of these tests will be executed on your own fork as well (except a few Cirrus fuzzers).
You can freely experiment there - see for example my attempts as https://github.com/l0rinc/bitcoin/pull/20

2025-06-08 18:20 UTC, LarryRuane commented on src/test/util_malloc_usage_tests.cpp
> +BOOST_AUTO_TEST_SUITE(util_malloc_usage_tests)
I didn't know that, that will prevent clutter here with that temporary stuff, thanks! I'll do that from now on (I want to do a few more similar experiments).

2025-06-08 18:22 UTC, l0rinc commented on src/test/util_malloc_usage_tests.cpp
> +BOOST_AUTO_TEST_SUITE(util_malloc_usage_tests)
yeah, I also have a few experiments where I'm not sure about the state of CI so I push to my local fork first - though the remaining CIs still surprise me sometimes after upstream push :)

2025-06-08 19:31 UTC, sipa commented
I wonder if perhaps it would be feasible to run a little runtime self-calibration at startup to find the malloc overhead parameters, so that they would be correct on all platforms.

It would make calls to `MallocUsage` much slower of course, but maybe not to such an extent that it is measurable.

2025-06-10 22:43 UTC, l0rinc commented
As @LarryRuane noticed, the new address-diff test sometimes disagrees with `MallocUsage` on macOS and on sanitizer builds.

I had to read a bit to understand why - I never needed the gory details until now. 🙂

It seem to me that macOS's nano allocator, and the allocators used by TSan/ASan, store per-chunk metadata in shadow tables rather than inline with the user block. For example, this might be related to what we're seeing: https://github.com/aosm/libmalloc/blob/master/src/nano_malloc.c#L181.
And because the test measures only the spacing between user-visible blocks, it doesn't account for that out-of-band metadata and ends up underreporting (e.g. it sees 16 bytes used when the real usage is 24). And let's not forget that we also have a specialized `PoolAllocator` which we should probably include in our testing to be able to measure the main memory hog properly.

So maybe we could specialize the tests by platform/compiler/arch/OS (without duplicating `MallocUsage` of course) - skipping sanitizers if they still behave differently - and only checking that our estimate is never lower, and if higher, not more than a fixed or a relative amount.

I personally would avoid the runtime self-calibration path -  rather abstracting away our findings and generalizing it based on self-contained test behavior sounds more predictable to me.

If we decide to keep the current settings (even though my massif memory allocation measurements (which should actually measure everything instead of just hoping that it instruments every call) do show it to be less accurate), and if we're still over-counting in the end, we can probably increase the default `-dbcache` slightly to adjust for the calculation difference.
That's why I'm trying to remeasure with `heaptrack` as well to know if it's just some bias of the tool.

2025-07-18 12:39 UTC, maflcko commented
Could turn into draft while CI is red?

2025-07-20 01:02 UTC, l0rinc commented on src/test/validation_flush_tests.cpp
> +    // Repeat (continuing with the existing cache) but with a non-zero max mempool;
I have extracted the suggested test to a separate PR: https://github.com/bitcoin/bitcoin/pull/33021

2025-10-22 15:42 UTC, achow101 commented
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

Marking as up for grabs.

cc @l0rinc @sipa

2025-10-22 15:42 UTC, closed without merging

2026-09-23 21:05 UTC, LarryRuane commented
@achow101 - I'd like to try this again. Please reopen. Thanks!

2026-10-16 05:07 UTC, LarryRuane commented
Closing in favor of #36549