Remove the legacy wallet and BDB dependency
bitcoin/bitcoin pull request #28710
Opened 2023-10-23 23:36 UTC by achow101

The final step of #20160.

A bare minimum of legacy wallet code is kept in order to perform wallet migration. Migration of legacy wallets uses the independent BDB parser and a minimal `LegacyDataSPKM` that allows the legacy data to be loaded so that the migration can be completed.

All tests which tested legacy wallet behavior have been removed. The `--descriptors` and `--legacy-wallet` options are removed from the functional tests.

BDB has been removed as a dependency and documentation have been updated to reflect that.

Depends on #26596

2024-03-09 01:21 UTC, jess2505 approved these changes

2024-04-09 10:26 UTC, laanwj commented on src/wallet/migrate.cpp
> +    DELETE = 0x80, // Indicate this record is deleted. This is AND'd with the real type.
OR'ed, i guess?

2024-06-27 16:10 UTC, Sjors commented
You can also drop the `BerkeleyDatabaseSanityCheck` related suppression in `contrib/devtools/check-devs.sh`

2024-11-05 22:48 UTC, achow101 commented
> It looks like all three dependencies got merged, is this ready for review?

Currently it is still dependent on #30328 but I suppose it doesn't have to be.

2025-01-13 14:20 UTC, Sjors commented on src/wallet/scriptpubkeyman.cpp
> +IsMineResult LegacyWalletIsMineInnerDONOTUSE(const LegacyDataSPKM& keystore, const CScript& scriptPubKey, IsMineSigVersion sigversion, bool recurse_scripthash=true)
e6ccd17275e06e6278473587257f80c2d9bd8834: maybe move the legacy wallet migration code to a separate file? And mark it read-only :-)

2025-02-09 01:27 UTC, onlinesipahimithu commented
Helli how to develop

2025-04-11 19:00 UTC, achow101 commented
The test each commit task fails because the HEAD of this PR has bdb removed from that task's install list, but the earlier commits in this PR still needs BDB. I guess we can leave it there for now and remove it later?

2025-04-24 21:57 UTC, achow101 commented on doc/files.md
> +
I think it's fine to leave as is, it's under the "Legacy subdirectories and Files" heading. This document discusses the files that Bitcoin Core creates and uses, and legacy wallets are neither created nor really used after this PR.

2025-04-24 21:57 UTC, achow101 commented on CMakePresets.json
>          "WARN_INCOMPATIBLE_BDB": "OFF",
Done.

2025-04-25 16:10 UTC, achow101 commented
Rebased and added a couple commits for followups from #31250

2025-04-25 16:14 UTC, fanquake commented on depends/packages/bdb.mk
> -  patch -p1 < $($(package)_patch_dir)/clang_cxx_11.patch && \
`clang_cxx_11.patch` also needs deleting.

2025-04-25 19:30 UTC, achow101 commented on depends/packages/bdb.mk
> -  patch -p1 < $($(package)_patch_dir)/clang_cxx_11.patch && \
Removed

2025-04-25 19:31 UTC, achow101 commented
> There's also a `libdb++-dev` instance in `workflows/ci.yml` & `deadlock:libdb` / `BerkeleyBatch` etc in tsan suppressions. `Berkeley*` in walletdb.h. `BerkeleyEnvironment::Salvage` in `utils_tests.cpp`.

Removed

2025-04-28 09:35 UTC, Sjors requested changes
Concept ACK.

bc3f07e384c2e145d6d14cfa3ad65b976233b538 looks good, except:

1. The GUI now shows a watch-only balance for descriptor wallets. See inline for the culprit.

2. In that same commit, the churn in `wallet/scriptpubkeyman.cpp` is hard to follow, both here on Github as well as a `git show --color-moved=dimmed-zebra`. I'm guessing you're moving stuff around, deleting and modifying? _Update_: use `--histogram`, it's just deletes.

And a few details:
- there's one more `-DWITH_BDB=ON` in `test-each-commit-exec.sh`
- `test_framework/bdb.py` seems unused now
- `fuzz/wallet_dbd_parser` checks for the presence of `USE_BDB` which is dropped.
- `DEFAULT_FLUSHWALLET` is unused
- `wallet_createwallet.py` has a comment referring to `sethdseed`
- `importprivkey` and friends are still in `bitcoin-cli.bash`

Also it might be good to rename the `importprivkey` test helper to e.g. `importkey`, so it's not confused with the disappeared RPC method.

As I mentioned in an earlier review https://github.com/bitcoin/bitcoin/pull/28710/commits/bc3f07e384c2e145d6d14cfa3ad65b976233b538#r1913267051, rather than naming functions `DONOTUSE` you could also move the migration code into a new file. But that could be a nice followup, along with changes to remove any legacy wallet weirdness from `scriptpubkeyman.h`

2025-04-28 09:35 UTC, Sjors commented on src/wallet/interfaces.cpp
> +        return m_wallet->IsWalletFlagSet(WALLET_FLAG_DESCRIPTORS);
In dc7bf5fd6a320c4528a28cef2a565366bbab3877 "wallet: Delete LegacySPKM": why doesn't this just return `false` like before? And if so, can't the entire helper be dropped?

2025-04-28 09:35 UTC, Sjors commented on src/wallet/test/CMakeLists.txt
> -    ismine_tests.cpp
In dc7bf5fd6a320c4528a28cef2a565366bbab3877 "wallet: Delete LegacySPKM": this test (file) and the one below still exist.

2025-04-28 09:53 UTC, maflcko approved these changes
lgtm ACK bc3f07e384c2e145d6d14cfa3ad65b976233b538 💇

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: lgtm ACK bc3f07e384c2e145d6d14cfa3ad65b976233b538 💇
eF2eywtBy1XVEkBKNQpSjNzCFy6rQijB2u0oSJ5ekqHuSEbmLrtrlwP1Y1QQ9QHaog9QUeesH7zr4jfYiCYqAg==
```

</details>

2025-04-28 10:19 UTC, Sjors commented on src/wallet/interfaces.cpp
> +        return m_wallet->IsWalletFlagSet(WALLET_FLAG_DESCRIPTORS);
It causes a bug in the GUI, see (1) here: https://github.com/bitcoin/bitcoin/pull/28710#pullrequestreview-2798630677

2025-04-28 10:22 UTC, Sjors commented
@maflcko `--patience` did the trick. It can be made default too if your computer is fast enough: `git config --global diff.algorithm patience`

2025-04-28 20:08 UTC, achow101 commented on src/qt/overviewpage.cpp
Probably, but I'm going to leave that for a followup, this diff is large enough already.

2025-04-28 20:14 UTC, achow101 commented on src/wallet/walletdb.cpp
> -        return DBErrors::LOAD_OK;
Descriptor wallets can't use non-HD keys in the "keypool", so it doesn't make sense to keep this for such wallets.

All migrated wallets get new descriptors anyways for new addresses. The keypool is entirely dumped.

2025-04-28 20:17 UTC, achow101 commented on src/wallet/interfaces.cpp
> +    void flush() override {}
`flush()` is inherited from `ChainClient`, which defines it as pure virtual, so it needs to have an implementation here even if it does nothing.

2025-04-28 20:25 UTC, achow101 commented on src/wallet/interfaces.cpp
> +        return m_wallet->IsWalletFlagSet(WALLET_FLAG_DESCRIPTORS);
Indeed, removed.

2025-04-28 20:25 UTC, achow101 commented on src/wallet/test/CMakeLists.txt
> -    ismine_tests.cpp
Apparently since this PR was opened, descriptor specific tests were added to those files. I've removed the legacy ones from them and added back to the `CMakeLists.txt`.

2025-04-28 20:26 UTC, achow101 commented on src/wallet/interfaces.cpp
> +        return m_wallet->IsWalletFlagSet(WALLET_FLAG_DESCRIPTORS);
Removed

2025-04-28 20:27 UTC, achow101 commented on src/wallet/wallet.cpp
> -/** @} */ // end of Actions
Done

2025-04-28 20:27 UTC, achow101 commented on src/wallet/wallet.cpp
> +    wallet->WalletLogPrintf("Releasing wallet\n");
Removed

2025-04-28 20:29 UTC, achow101 commented
> And a few details:

Removed these

> Also it might be good to rename the `importprivkey` test helper to e.g. `importkey`, so it's not confused with the disappeared RPC method.

I'm going to leave that for a followup.

> You can use `--patience`. Maybe add this to the commit message?

Done, also mentioned `--histogram`.

2025-04-29 10:00 UTC, Sjors commented
The `updateWatchOnlyLabels` stuff is still wrong. I think the entire second column for watch-only needs to be stripped from the GUI. But at least not rendered.

2025-04-29 18:58 UTC, achow101 commented
> The `updateWatchOnlyLabels` stuff is still wrong. I think the entire second column for watch-only needs to be stripped from the GUI. But at least not rendered.

Fixed it so it doesn't render. The full removal can be done in a followup.

2025-05-01 13:29 UTC, Sjors commented
ACK 1c0d89358e12fc871e99c8304d5cb50965cf7b9d

🌲 🪚

2025-05-01 13:30 UTC, Sjors approved these changes
ACK 1c0d89358e12fc871e99c8304d5cb50965cf7b9d 🌲 🪚

2025-05-01 15:14 UTC, furszy reviewed
In 425c39c6f520a1b0d18c6e782141f711509b2947:

Could probably also remove the proxy functions we have in the test framework for those RPC commands. Look [at this line](https://github.com/bitcoin/bitcoin/blob/fc6346dbc8dc3db40aad4079210332b5f8b332ed/test/functional/test_framework/test_node.py#L979) for example (same for importpubkey, importprivkey and addmultisigaddress).

Also, on an orthogonal topic — I'm wondering if, instead of completely removing `importaddress()`, we might want to quickly make it compatible with descriptor wallets (e.g., by reviving #27034). This is also connected to #30175.
I’m bringing this topic up because removing something in one release and reintroducing it in another one could be annoying for users.

2025-05-06 08:13 UTC, maflcko approved these changes
re-review ACK 1c0d89358e 🎽

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: re-review ACK 1c0d89358e 🎽
PZKgfTbviYeE2sXUccefHEGzNEiLnxq231kR9x+Kbs/03JOhEOQNRuGw8xDKO5Oz1bBAAIPB1ljq05mIAK6UBQ==
```

</details>


Only stuff is some follow-up ideas:

* https://github.com/bitcoin/bitcoin/pull/28710#issuecomment-2842132320
* https://github.com/bitcoin/bitcoin/pull/28710#discussion_r2063317183
* https://github.com/bitcoin/bitcoin/pull/28710#discussion_r2063011962
* https://github.com/bitcoin/bitcoin/pull/28710#discussion_r2063234336

2025-05-06 19:25 UTC, achow101 commented on test/functional/wallet_createwallet.py
> +        self.generate(node, 1)
Done both.

2025-05-06 19:27 UTC, achow101 commented on doc/files.md
Removed:
* `importmulti' in doc/descriptors.md
* bdb.cpp in linter
* `WriteHDCHain` and WriteCScript`

I would prefer to leave further cleanups for follow up RPs as I am sure there are plenty of things that were missed and trying to catch them all in this one PR is going to be very annoying and just delay this even more.

2025-05-06 22:09 UTC, w0xlt commented on src/wallet/wallettool.cpp
> +        assert(false);
```suggestion
assert(wallet_instance->IsWalletFlagSet(WALLET_FLAG_DESCRIPTORS));
```

2025-05-06 22:21 UTC, w0xlt commented on src/wallet/scriptpubkeyman.cpp
> +IsMineResult LegacyWalletIsMineInnerDONOTUSE(const LegacyDataSPKM& keystore, const CScript& scriptPubKey, IsMineSigVersion sigversion, bool recurse_scripthash=true)
I agree.

2025-05-06 22:28 UTC, w0xlt reviewed
ACK https://github.com/bitcoin/bitcoin/pull/28710/commits/be3c13a22fa8d49fe15cde941e8030e1cd2b522f with 2 non-blocking nits commented earlier.

Regarding the removed RPC functons, I think less is better in this case, and unless I'm missing something, the cases mentioned in https://github.com/bitcoin/bitcoin/issues/30175 can be performed by `importdescriptors`.

2025-05-06 23:51 UTC, achow101 commented on src/wallet/scriptpubkeyman.cpp
> +IsMineResult LegacyWalletIsMineInnerDONOTUSE(const LegacyDataSPKM& keystore, const CScript& scriptPubKey, IsMineSigVersion sigversion, bool recurse_scripthash=true)
Maybe for a followup.

2025-05-06 23:53 UTC, achow101 commented on src/wallet/wallettool.cpp
> +        assert(false);
Done

2025-05-07 01:21 UTC, w0xlt reviewed
reACK https://github.com/bitcoin/bitcoin/pull/28710/commits/de054df6dc32cbd8b127c6761d9c65d95025e08f

2025-05-07 08:31 UTC, Sjors commented
re-ACK de054df6dc32cbd8b127c6761d9c65d95025e08f

2025-05-07 11:58 UTC, rkrux reviewed
Couple of points in 8ede6dea0c55bb4afefa790b83dd4da48a2f84da, can be done in follow up if no more changes being in this PR.

2025-05-07 11:58 UTC, rkrux commented on src/wallet/rpc/transactions.cpp
> +            + HelpExampleCli("rescanblockchain", "") +
Besides the typo `s/an/a` above, the comment "Import a private key" doesn't go well with `rescanblockchain`.

2025-05-07 11:58 UTC, rkrux commented on src/wallet/rpc/backup.cpp
> -    bool can_keypool = parsed_descs.at(0)->IsSingleKey();
In #31243, `IsSingleKey` was added with a TODO to remove it after removing legacy wallets.
I checked that no other usage of `IsSingleKey` is left, it can be removed. 

https://github.com/bitcoin/bitcoin/blob/6d5edfcc585bab3374ae14aa7918b3e178e016aa/src/script/descriptor.h#L114-L117

2025-05-07 14:19 UTC, merged

2025-05-07 14:42 UTC, pablomartin4btc reviewed
post-merge ACK de054df6dc32cbd8b127c6761d9c65d95025e08f