build: disable external-signer for Windows
bitcoin/bitcoin pull request #28967
Opened 2023-11-29 14:05 UTC by fanquake

It's come to light that Boost ASIO (a Boost Process sub dep) has in some
instances, been quietly  initialising our network stack on Windows (see
PR https://github.com/bitcoin/bitcoin/pull/28486 and discussion in https://github.com/bitcoin/bitcoin/issues/28940).

This has been shielding a bug in our own code, but the larger issue
is that Boost Process/ASIO is running code before main, and doing things
like setting up networking. This undermines our own assumptions about
how our binary works, happens before we run any sanity checks,
and before we call our own code to setup networking. Note that ASIO also
calls WSAStartup with version `2.0`, whereas we call with `2.2`.

It's also not clear why a feature like external signer would have a
dependency that would be doing anything network/socket related,
given it only exists to spawn a local process.

See also the discussion in https://github.com/bitcoin/bitcoin/issues/24907. Note that the maintaince of Boost Process in general,
has not really improved. For example, rather than fixing bugs like https://github.com/boostorg/process/issues/111, 
i.e, https://github.com/boostorg/process/pull/317, the maintainer chooses to just wrap exception causing overflows
in try-catch blocks: https://github.com/boostorg/process/commit/0c42a58eacab6a96b19196e399307bad8a938a27. These changes get merged in large,
unreviewed PRs, i.e https://github.com/boostorg/process/pull/319.

This PR disables external-signer on Windows for now. If, in future, someone
changes how Boost Process works, or replaces it entirely with some
properly reviewed and maintained code, we could reenable this feature on
Windows.

Based on https://github.com/bitcoin/bitcoin/pull/28486.

2023-11-29 16:56 UTC, hebasto commented
The same for MSVC builds: https://github.com/bitcoin/bitcoin/blob/8cf2137dbeaa681f0178f1e2fd70b639e6d4f717/build_msvc/bitcoin_config.h.in#L44-L45
?

2023-11-29 17:19 UTC, fanquake commented
> The same for MSVC builds: 

Added.

2023-11-30 17:12 UTC, TheCharlatan commented
Concept ACK

2023-12-01 02:21 UTC, hebasto approved these changes
> It's come to light that Boost ASIO (a Boost Process sub dep) has in some instances, been quietly initialising our network stack on Windows (see PR #28486 and discussion in #28940).
> 
> This has been shielding a bug in our own code, but the larger issue is that Boost Process/ASIO is running code before main, and doing things like setting up networking. This undermines our own assumptions about how our binary works, happens before we run any sanity checks, and before we call our own code to setup networking. Note that ASIO also calls WSAStartup with version `2.0`, whereas we call with `2.2`.
> 
> It's also not clear why a feature like external signer would have a dependency that would be doing anything network/socket related, given it only exists to spawn a local process.
> 
> See also the discussion in #24907. Note that the maintaince of Boost Process in general, has not really improved. For example, rather than fixing bugs like [boostorg/process#111](https://github.com/boostorg/process/issues/111), i.e, [boostorg/process#317](https://github.com/boostorg/process/pull/317), the maintainer chooses to just wrap exception causing overflows in try-catch blocks: [boostorg/process@0c42a58](https://github.com/boostorg/process/commit/0c42a58eacab6a96b19196e399307bad8a938a27). These changes get merged in large, unreviewed PRs, i.e [boostorg/process#319](https://github.com/boostorg/process/pull/319).

Working closely with Boost.Process source recently I agree with every statement above.
Sigh...

> This PR disables external-signer on Windows for now. If, in future, someone changes how Boost Process works, or replaces it entirely with some properly reviewed and maintained code, we could reenable this feature on Windows.

I still believe that the "external signer" feature is extremely important for Bitcoin Core users, who prefer to keep their keys in dedicated devices. So I hope we shall manage to make https://github.com/bitcoin/bitcoin/pull/28981 (or something better) merged before the v27 release.

ACK 9ff589c60c931a8cb19cb984cc69a223186181ca.

Suggesting to rebase on top of the bitcoin/bitcoin#28938 and drop `boost-process` from `vcpkg.json`.

2023-12-01 10:47 UTC, fanquake commented
> and drop boost-process from vcpkg.json.

Added.

2023-12-01 10:49 UTC, hebasto approved these changes
re-ACK 308aec3e5655327d98e0428d8205d246f24d6af5.

2023-12-01 11:48 UTC, TheCharlatan approved these changes
ACK 308aec3e5655327d98e0428d8205d246f24d6af5

2023-12-05 02:45 UTC, luke-jr requested changes
Let's at least let builders explicitly enable it?

2023-12-13 10:53 UTC, fanquake commented
> Let's at least let builders explicitly enable it?

That would mostly defeat the point of this change, and leave us supporting code that we've deemed unsafe and unreviewed. If someone wants to do that, they are free to understand the risks, and patch their own code.

2023-12-13 11:55 UTC, merged

2024-02-08 05:16 UTC, hebasto commented
As it seems that https://github.com/bitcoin/bitcoin/pull/28981 won't make it into v27.0, I suggest reflecting the disabling of external signer support for Windows in the release notes. This will allow users who rely on it to skip the next release update.

2024-02-27 16:23 UTC, Sjors commented
For historical context: we disabled Windows support for external signers in Januari 2022 with #24065. We re-enabled it in May 2023 in #25696. It was included in v26.0, but not mentioned in the release notes: https://bitcoincore.org/en/releases/26.0/

2024-03-04 11:57 UTC, fanquake commented
Added rel-note todo to the draft wiki.