fuzz: Exit and log stdout for parse_test_list errors
bitcoin/bitcoin pull request #29304
Opened 2024-01-24 10:55 UTC by dergoegge

We should log all errors that occur when attempting to print the harness list in the fuzz test runner.

2024-01-24 10:56 UTC, dergoegge commented
This is currently a problem in the qa-assets CI, listing the harnesses fails but there is no output: https://cirrus-ci.com/task/5433841842651136?logs=ci#L9235

```
...
+ test/fuzz/test_runner.py -j6 -l DEBUG /ci_container_base/ci/scratch/qa-assets/fuzz_seed_corpus/ --empty_min_time=60
No fuzz targets found
```

2024-01-24 11:12 UTC, maflcko requested changes

2024-01-24 11:28 UTC, dergoegge commented on test/fuzz/test_runner.py
> +        stderr=subprocess.STDOUT,
Inheriting is better, done!

2024-01-24 11:43 UTC, dergoegge commented on test/fuzz/test_runner.py
> +        sys.exit(1)
great, done!

2024-01-24 15:14 UTC, merged

2024-01-25 09:49 UTC, fanquake commented
Looks like this is working as intended https://cirrus-ci.com/task/5482198250291200?logs=ci#L9646:
```bash
+ test/fuzz/test_runner.py -j6 -l DEBUG /ci_container_base/ci/scratch/qa-assets/fuzz_seed_corpus/ --empty_min_time=60
==29805==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55ef0724925d  (/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/fuzz/fuzz+0x93625d)
    #1 0x55ef09320bb9  (/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/fuzz/fuzz+0x2a0dbb9)
    #2 0x55ef0717e664  (/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/fuzz/fuzz+0x86b664)
    #3 0x7fd0ab3e9eba  (/lib/x86_64-linux-gnu/libc.so.6+0x29eba) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
Traceback (most recent call last):
  File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/fuzz/test_runner.py", line 382, in <module>
    main()
  File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/fuzz/test_runner.py", line 106, in main
    test_list_all = parse_test_list(fuzz_bin=os.path.join(config["environment"]["BUILDDIR"], 'src', 'test', 'fuzz', 'fuzz'))
  File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/fuzz/test_runner.py", line 369, in parse_test_list
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/fuzz/fuzz' returned non-zero exit status 1.
````

2024-01-25 09:49 UTC, fanquake commented
We should also fix the symbolizing in that env.