test: check_mempool_result negative feerate
bitcoin/bitcoin pull request #29459
Opened 2024-02-21 03:18 UTC by kevkevinpal

Adds test coverage in `mempool_accept.py` to check if a negative `maxfeerate` is input into `check_mempool_result`
Asserts "Amount out of range" error message and `-3` error code

Motivated by this [comment](https://github.com/bitcoin/bitcoin/pull/29434/files#r1491112250)

2024-02-21 08:23 UTC, maflcko requested changes

2024-02-21 16:08 UTC, kevkevinpal commented on test/functional/mempool_accept.py
>          # ... 0.99 passes
oops fixed in [bf264e0](https://github.com/bitcoin/bitcoin/pull/29459/commits/bf264e05981e3809715f34f548138d53991db6f2)

2024-02-22 13:54 UTC, brunoerg commented
nice, utACK bf264e05981e3809715f34f548138d53991db6f2

2024-03-11 20:00 UTC, davidgumberg commented
Looks great, ACK https://github.com/bitcoin/bitcoin/pull/29459/commits/bf264e05981e3809715f34f548138d53991db6f2

If you need to rebase you could also add a check that the same error is thrown when `maxfeerate` exceeds `MAX_MONEY`:

```cpp
inline bool MoneyRange(const CAmount& nValue) { return (nValue >= 0 && nValue <= MAX_MONEY); }

CAmount AmountFromValue(const UniValue& value, int decimals)
{
    // [...]
    if (!MoneyRange(amount))
        throw JSONRPCError(RPC_TYPE_ERROR, "Amount out of range");
    // [...]
}
```

The same tests should probably be added for `sendrawtransaction` but that could be done in a follow up.

2024-03-14 11:17 UTC, merged