contrib: list other binaries in manpage output
bitcoin/bitcoin pull request #29585
Opened 2024-03-07 13:19 UTC by fanquake

Add a `SEE ALSO` section to the manpages.

Master:
![master](https://github.com/bitcoin/bitcoin/assets/863730/da6f0151-e43a-4578-983d-4f2def80a8eb)

This PR:
![pr](https://github.com/bitcoin/bitcoin/assets/863730/d57a1c9a-50c7-4f1a-834e-0f8af8520921)

Should be enough to close #29558.

2024-03-14 23:40 UTC, luke-jr requested changes
The manpage you're viewing shouldn't be listed in See Also...

2024-03-15 00:01 UTC, luke-jr commented
https://github.com/bitcoin/bitcoin/commit/96008babf55d9d70aeff716e138e363016da6fd2

2024-03-21 09:16 UTC, willcl-ark approved these changes
ACK 7c3ac598dd9a1f1a506c4931249ff6c9f1c949ba

I don't see it as a big issue to list all related binaries in the bitcoin "ecosystem" in the SEE ALSO section myself.

2024-04-15 14:33 UTC, pablomartin4btc approved these changes
utACK 7c3ac598dd9a1f1a506c4931249ff6c9f1c949ba

2024-04-24 07:44 UTC, laanwj commented on contrib/devtools/gen-manpages.py
> +    footer.write(', '.join(s.rpartition('/')[2] + '(1)' for s in BINARIES))
Could use `os.path.basename` it's slightly more readable and will always pick the last path item.

2024-04-24 07:44 UTC, laanwj commented
Good idea, concept ACK.

2024-04-24 07:49 UTC, laanwj approved these changes
Code review ACK 7c3ac598dd9a1f1a506c4931249ff6c9f1c949ba

2024-04-24 13:24 UTC, merged