scripted-diff: Use LogInfo over LogPrintf
bitcoin/bitcoin pull request #29641
Opened 2024-03-12 20:21 UTC by maflcko

`LogPrintf` has many issues:

* It does not mention the log severity (info).
* It is a deprecated alias for `LogInfo`, according to the dev notes.
* It wastes review cycles, because reviewers sometimes point out that it is deprecated.
* It makes the code inconsistent, when both versions of the alias are used.

Fix all issues by removing the deprecated alias.

2024-03-13 02:19 UTC, kevkevinpal commented
I noticed that there are helper functions such as the following using the `LogPrintf` naming scheme
- `WalletLogPrintf` in `src/wallet/wallet.h`
- `LogPrintfCategoryWithThreadNames, LogPrintfCategory, LogPrintfCategoryWithoutThreadNames, LogPrintfWithoutThreadNames, LogPrintfWithThreadNames` in `./src/bench/logging.cpp`

---

Using this grep `grep -nri "\<LogPrintLevel\>" ./src --binary-files=without-match`
I also noticed that we are using `LogPrintLevel` when we could be using `LogInfo`, `LogWarning`, `LogError`, `LogDebug` and `LogTrace`

these might want to be addressed in a separate PR though

2024-03-18 16:42 UTC, hebasto commented
> `LogPrintf/LogPrint` are problematic...

Some of them are just broken. For example, https://github.com/bitcoin/bitcoin/pull/29480.

2024-06-25 20:31 UTC, TheCharlatan commented
Concept ACK

2024-08-11 08:10 UTC, Theschorpioen approved these changes

2024-08-11 08:11 UTC, Theschorpioen approved these changes

2024-09-09 11:41 UTC, l0rinc commented on src/validation.cpp
> +            LogInfo("ERROR: %s: Missing input %d in transaction \'%s\'\n", __func__, i, tx.GetHash().GetHex());
Based on the message and
> - `LogError(fmt, params...)` should be used in place of `LogInfo` for
  severe problems that require the node (or a subsystem) to shut down
  entirely (e.g., insufficient storage space).
  
and the discussion in https://github.com/bitcoin/bitcoin/pull/30849#discussion_r1750090426, this looks like a `LogError` instead (will throw in https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L895-L898 if `nullopt` is returned).

2024-09-18 12:24 UTC, l0rinc requested changes
Concept ACK

2024-09-18 12:24 UTC, l0rinc commented on contrib/devtools/bitcoin-tidy/logprintf.h
> +// Warn about any use of LogInfo that does not end with a newline.
We should likely rename the file and class as well to match

2024-09-18 12:24 UTC, l0rinc commented on contrib/devtools/bitcoin-tidy/example_logprintf.cpp
> +    LogInfo("hello world!"); // NOLINT(bitcoin-unterminated-logprintf)
does the custom lint name need an update now?

2024-09-18 12:24 UTC, l0rinc commented on contrib/devtools/bitcoin-tidy/example_logprintf.cpp
> +#define LogInfo(...) LogPrintLevel_(LogFlags::NONE, Level::None, __VA_ARGS__)
Since the file contains `LogInfo` examples now, we should rename the file as well.

2024-09-18 12:24 UTC, l0rinc commented on contrib/devtools/bitcoin-tidy/example_logprintf.cpp
> +        LogInfo(__VA_ARGS__); \
this line seems weird now, defining `debug` as `Info`

2024-11-21 11:02 UTC, fanquake commented on .github/workflows/ci.yml
> +          brew install --quiet coreutils ninja gnu-getopt ccache boost libevent zeromq qt@5 qrencode
forgot to add pkgconf?

2025-11-25 13:24 UTC, fanquake approved these changes
ACK 317b71bcd2e552f93ac2131b16a8acab414567dd - I think the conflicts here are small, and a number are themselves draft / WIP.

2025-11-25 13:46 UTC, l0rinc commented
Is this ready for review now?

2025-11-27 10:08 UTC, maflcko commented
> Is this ready for review now?

No. Someone would have to pick up https://github.com/bitcoin/bitcoin/pull/29231, because most of the logs are alerts, and not info logs.

So i went ahead and did that in https://github.com/bitcoin/bitcoin/pull/33960

2025-12-04 20:01 UTC, maflcko commented on src/validation.cpp
> +            LogInfo("ERROR: %s: Missing input %d in transaction \'%s\'\n", __func__, i, tx.GetHash().GetHex());
It is an internal bug, so it is dead code and doesn't really matter much. I think internal bugs should be using `Assume(false)`. Logs could go with `LogError("%s", STR_INTERNAL_BUG("..."))`, but I wanted to keep the changes here minimal. Happy to go with `LogError("%s", STR_INTERNAL_BUG(` if you feel strongly.

2025-12-05 16:16 UTC, stickies-v approved these changes
ACK fa4395dffd432b999002dfd24eb6f8d7384fbcbe

nit: would be nice to update the scripted-diff to also remove trailing newlines if that's not a huge pita

2025-12-05 18:25 UTC, ajtowns commented
ACK fa4395dffd432b999002dfd24eb6f8d7384fbcbe

2025-12-06 09:55 UTC, rkrux approved these changes
lgtm ACK fa4395dffd432b999002dfd24eb6f8d7384fbcbe

Thanks for the cleanup, best to remove the deprecated `LogPrintf` alias.

> It wastes review cycles, because reviewers sometimes point out that it is deprecated.

I reviewed #34008 where exactly this^ happened: https://github.com/bitcoin/bitcoin/pull/34008#discussion_r2592395736

2025-12-06 10:03 UTC, maflcko commented
> nit: would be nice to update the scripted-diff to also remove trailing newlines if that's not a huge pita

Thx, I can take a look, if I have to re-touch.

2025-12-06 13:47 UTC, merged