validation: do not wipe utxo cache for stats/scans/snapshots
bitcoin/bitcoin pull request #30610
Opened 2024-08-08 17:49 UTC by sipa

Since #28280, the cost of a non-wiping sync of the UTXO cache is only proportional to the number of dirty entries, rather than proportional to the size of the entire cache. Because of that, there is no reason to perform a wiping flush in case the contents of the cache is still useful.

Split the `FlushStateMode::ALWAYS` mode into a `FORCE_SYNC` (non-wiping) and a `FORCE_FLUSH` (wiping), and then use the former in `scantxoutset`, `gettxoutsetinfo`, and in the currently-unused `CreateUTXOSnapshot`.

2024-08-08 18:36 UTC, andrewtoth commented
Concept ACK

Indeed, the `FlushStateMode::ALWAYS` variant is now confusing. It could mean we want to always write the chainstate to disk, or we want to always erase the dbcache. Splitting it up into the two cases makes sense.

2024-08-09 14:18 UTC, paplorinc commented
> I'd suggest a reindex test

Thanks for the hint, running the following, please let me know if you think this isn't representative:
```bash
hyperfine \
--runs 5 \
--parameter-list COMMIT 27a770b34b8f1dbb84760f442edb3e23a0c2420b,4471aafb25b37fa8f780c87a4067b2bb52aef347 \
--prepare 'git checkout {COMMIT} && git clean -fxd && git reset --hard && ./autogen.sh && ./configure && make -j8' \
'COMMIT={COMMIT} ./src/bitcoind -datadir=/mnt/sda1/BitcoinData -dbcache=16384 -reindex -stopatheight=500000 -printtoconsole=0'
```

2024-08-09 14:30 UTC, andrewtoth commented
@paplorinc I don't see anything in this PR that would affect reindexing. This PR seems like a refactor only.

2024-08-12 20:55 UTC, paplorinc commented
> Because of that, there is no reason to perform a wiping flush in case the contents of the cache is still useful.

I assumed (without diving into the code) that this meant an optimization.
<details>
<summary>Did 2x5 reindex checks until 500k blocks - 0% change.</summary>

  Time (mean ± σ):     15396.778 s ± 31.337 s    [User: 81183.230 s, System: 364.223 s]
  Range (min … max):   15363.334 s … 15427.586 s    5 runs

  Time (mean ± σ):     15410.168 s ± 20.832 s    [User: 81268.923 s, System: 363.370 s]
  Range (min … max):   15381.363 s … 15429.772 s    5 runs

Summary
  'COMMIT=f40365460247e3ce14dd59ca441fc243e679f228 ./src/bitcoind -datadir=/mnt/sda1/BitcoinData -dbcache=16384 -reindex -stopatheight=500000 -printtoconsole=0' ran
    1.00 ± 0.00 times faster than 'COMMIT=27a770b34b8f1dbb84760f442edb3e23a0c2420b ./src/bitcoind -datadir=/mnt/sda1/BitcoinData -dbcache=16384 -reindex -stopatheight=500000
-printtoconsole=0'


</details>

2024-09-03 16:29 UTC, mzumsande reviewed
Concept ACK

The test `interface_usdt_utxocache.py` fails because `generate()` in `wallet.py` calls `scantxoutset`, which doesn't wipe the cache anymore. As a result, the number of utxos flushed to disk in later flushes changes.

Re: "currently-unused CreateUTXOSnapshot" in the PR description - it's used to create snapshots (`dumptxoutset`).

2024-10-15 15:47 UTC, achow101 commented
cc @davidgumberg @andrewtoth @l0rinc

2024-11-11 16:17 UTC, l0rinc commented
> The test interface_usdt_utxocache.py fails

I haven't reviewed the code in detail yet (since the [build is still failing](https://github.com/bitcoin/bitcoin/pull/30610#pullrequestreview-2277942711)).

<details>
<summary>reproduced build failure</summary>

```bash

> apt install systemtap-sdt-dev
> cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_USDT=ON && cmake --build build -j$(nproc)
> build/test/functional/interface_usdt_utxocache.py

2024-11-11T15:47:49.211000Z TestFramework (INFO): handle_utxocache_add(): UTXOCacheChange(outpoint=d09ca39938b434b19a3338ef6b410071d85d4450dd7dc1f7db1bf7d95a53709a:0, height=201, value=4999968800sat, is_coinbase=False)
2024-11-11T15:47:49.211000Z TestFramework (INFO): handle_utxocache_spent(): UTXOCacheChange(outpoint=fab2396e3f726e1801b9e7303cf294783a3fd7e19ddc8f2dfa55e25b01575b3e:0, height=77, value=5000000000sat, is_coinbase=True)
2024-11-11T15:47:49.211000Z TestFramework (INFO): check that we successfully traced 2 adds and 1 spent
2024-11-11T15:47:49.229000Z TestFramework (INFO): test the utxocache:flush tracepoint API
2024-11-11T15:47:49.229000Z TestFramework (INFO): hook into the utxocache:flush tracepoint
2024-11-11T15:47:50.288000Z TestFramework (INFO): stop the node to flush the UTXO cache
2024-11-11T15:47:50.390000Z TestFramework (INFO): handle_utxocache_flush(): UTXOCacheFlush(duration=11670, mode=FORCE_FLUSH, size=3, memory=262464, for_prune=False)
Exception ignored on calling ctypes callback function: <function PerfEventArray._open_perf_buffer.<locals>.raw_cb_ at 0x76705f695c60>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcc/table.py", line 991, in raw_cb_
    callback(cpu, data, size)
  File "/mnt/my_storage/bitcoin/build/test/functional/interface_usdt_utxocache.py", line 351, in handle_utxocache_flush
    expected_flushes.remove({
ValueError: list.remove(x): x not in list
2024-11-11T15:47:50.390000Z TestFramework (INFO): handle_utxocache_flush(): UTXOCacheFlush(duration=8205, mode=FORCE_FLUSH, size=0, memory=262240, for_prune=False)
2024-11-11T15:47:50.408000Z TestFramework (INFO): check that we don't expect additional flushes
2024-11-11T15:47:50.408000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/mnt/my_storage/bitcoin/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/mnt/my_storage/bitcoin/build/test/functional/interface_usdt_utxocache.py", line 151, in run_test
    self.test_flush()
  File "/mnt/my_storage/bitcoin/build/test/functional/interface_usdt_utxocache.py", line 380, in test_flush
    assert_equal(0, len(expected_flushes))
  File "/mnt/my_storage/bitcoin/test/functional/test_framework/util.py", line 77, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(0 == 1)
2024-11-11T15:47:50.460000Z TestFramework (INFO): Stopping nodes

</details>

> it is an optimization, but only affects the `scantxoutset` and `gettxoutsetinfo` RPCs

I've measured the effect of this change on the mentioned RPCs with up-to-date tip (869861 blocks):

<details>
<summary>gettxoutsetinfo benchmarks</summary>

```bash
hyperfine \
--show-output \
--warmup 1 --runs 10 \
--export-json /mnt/gettxoutsetinfo-30610.json \
--parameter-list COMMIT 900b17239fb25750fd30b4af6e6c38096374b71f,226b6c7d6e69c1f032079c8bc5af5710d8e54efb \
--prepare 'killall -q bitcoind; git checkout {COMMIT} && git clean -fxd && git reset --hard && cmake -B build && cmake --build build -j$(nproc) && ./build/src/bitcoind -datadir=/mnt/my_storage/BitcoinData -daemon -connect=0 -rpcuser=benchmark -rpcpassword=benchmark && sleep 10' \
--cleanup './build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark stop && sleep 10 && killall -9 bitcoind || true' \
'COMMIT={COMMIT} ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData gettxoutsetinfo >/dev/null'
```

</details>

<details>
<summary>individual measurements</summary>

```bash
"command": "COMMIT=900b17239fb25750fd30b4af6e6c38096374b71f ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData gettxoutsetinfo >/dev/null",
"times": [ 194.38279658410002, 259.16496413609997, 209.65035661110002, 207.9064897821, 245.2373909041, 200.04822835410002, 227.2078635091, 192.6374527831, 160.2041179331, 141.44879581310002 ],

"command": "COMMIT=226b6c7d6e69c1f032079c8bc5af5710d8e54efb ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData gettxoutsetinfo >/dev/null",
"times": [ 138.6323105461, 138.80884732910002, 137.4915245871, 137.2168089111, 139.4260206461, 144.2785081071, 136.9866460371, 137.38376074410002, 138.23486413010002, 136.55915986710002 ],
```

</details>

```bash
Summary
  'COMMIT=226b6c7d6e69c1f032079c8bc5af5710d8e54efb ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData gettxoutsetinfo >/dev/null' ran
    1.47 ± 0.26 times faster than 'COMMIT=900b17239fb25750fd30b4af6e6c38096374b71f ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData gettxoutsetinfo >/dev/null'
```

---

<details>
<summary>scantxoutset benchmark</summary>

```bash
hyperfine \
--show-output \
--warmup 1 --runs 10 \
--export-json /mnt/scantxoutset-30610.json \
--parameter-list COMMIT 900b17239fb25750fd30b4af6e6c38096374b71f,226b6c7d6e69c1f032079c8bc5af5710d8e54efb \
--prepare 'killall -q bitcoind; git checkout {COMMIT} && git clean -fxd && git reset --hard && cmake -B build && cmake --build build -j$(nproc) && ./build/src/bitcoind -datadir=/mnt/my_storage/BitcoinData -daemon -connect=0 -rpcuser=benchmark -rpcpassword=benchmark && sleep 10' \
--cleanup './build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark stop && sleep 10 && killall -9 bitcoind || true' \
"COMMIT={COMMIT} ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData scantxoutset start '[\"addr(32ixEdVJWo3kmvJGMTZq5jAQVZZeuwnqzo)\"]' >/dev/null"
```

</details>

<details>
<summary>individual measurements</summary>

```bash
"command": "COMMIT=900b17239fb25750fd30b4af6e6c38096374b71f ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData scantxoutset start '[\"addr(32ixEdVJWo3kmvJGMTZq5jAQVZZeuwnqzo)\"]' >/dev/null",
"times": [ 62.82799487242, 60.64005598342, 60.99546379442, 60.31839828842, 64.55913160942, 63.55735657542, 62.07198356042, 62.17213781942, 63.035974236419996, 61.785472937419996 ],

"command": "COMMIT=226b6c7d6e69c1f032079c8bc5af5710d8e54efb ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData scantxoutset start '[\"addr(32ixEdVJWo3kmvJGMTZq5jAQVZZeuwnqzo)\"]' >/dev/null",
"times": [ 61.64325996342, 61.09686494542, 61.077064575419996, 61.28694446342, 60.94913395142, 61.24807362942, 61.204911535419996, 61.23621690842, 61.174668652419996, 61.04969869342 ],
```

</details>

```bash
Summary
  'COMMIT=226b6c7d6e69c1f032079c8bc5af5710d8e54efb ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData scantxoutset start '["addr(32ixEdVJWo3kmvJGMTZq5jAQVZZeuwnqzo)"]' >/dev/null' ran
    1.02 ± 0.02 times faster than 'COMMIT=900b17239fb25750fd30b4af6e6c38096374b71f ./build/src/bitcoin-cli -rpcuser=benchmark -rpcpassword=benchmark -datadir=/mnt/my_storage/BitcoinData scantxoutset start '["addr(32ixEdVJWo3kmvJGMTZq5jAQVZZeuwnqzo)"]' >/dev/null'
```

2024-11-11 16:25 UTC, andrewtoth commented
The tests need to be fixed per https://github.com/bitcoin/bitcoin/pull/30610#pullrequestreview-2277942711.

@l0rinc what this PR accomplishes is not wiping the dbcache if calling those RPCs. It should not affect performance of the RPCs, but performance of connecting new blocks after calling the RPCs.

2024-11-14 14:39 UTC, l0rinc requested changes
>  It should not affect performance of the RPCs

It seems I have misunderstood multiple times what to benchmark here (IBD, reindex, RPC), so if there's anything that actually needs benchmarking, please describe it in more detail.

2024-11-14 16:02 UTC, andrewtoth commented
@l0rinc a way to test that this PR is working properly is to first run master and sync a few blocks. In the `UpdateTip` logs you will see a `cache=` value that increases. Running either of these RPCs should make the next `UpdateTip` reset a few MB at most.
When doing the same test on this branch, the next `UpdateTip` value should be the same or higher than the previous.

2025-10-22 14:11 UTC, achow101 commented
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

2025-10-22 14:11 UTC, closed without merging

2025-10-22 14:47 UTC, l0rinc commented
Revived in https://github.com/bitcoin/bitcoin/pull/33680, let's continue review there

2026-07-05 16:00 UTC, pablomartin4btc commented
> Revived in #33680, let's continue review there

Since that one got merged, please remove the "Up for grabs" label to avoid confusion. Thanks!