doc: cmake: prepend "build" to functional/test_runner.py
bitcoin/bitcoin pull request #30859
Opened 2024-09-10 04:08 UTC by LarryRuane

This is a small follow-on to #30741. Also, improve the error message if someone runs the functional tests the old way (outside of the build directory).

2024-09-10 04:21 UTC, LarryRuane commented
This patch would have helped me; I'm new to `cmake`; after building it for the first time, I tried to run the functional tests (the way I was used to), and it failed in a strange way:
```
$ test/functional/test_runner.py 
Traceback (most recent call last):
  File "/sd/g/bitcoin/test/functional/test_runner.py", line 950, in <module>
    main()
  File "/sd/g/bitcoin/test/functional/test_runner.py", line 465, in main
    config.read_file(open(configfile, encoding="utf8"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sd/g/bitcoin/test/functional/../config.ini'
```
Aware that we're now using `cmake`, I checked the top-level README, and it looked like I was running the test correctly:

> These tests can be run (if the [test dependencies](/test) are installed) with: `test/functional/test_runner.py`

This was pretty confusing for a while. I finally figured out that I need to run the test script from the `build` directory. This PR updates the documentation (in the two places I found after a fairly careful search).

I also thought it would be helpful to improve the error message in case someone else does this. With this PR, it looks like this:
```
$ test/functional/test_runner.py 
Traceback (most recent call last):
  File "/sd/g/bitcoin/test/functional/test_runner.py", line 952, in <module>
    main()
  File "/sd/g/bitcoin/test/functional/test_runner.py", line 466, in main
    raise Exception(f"config.ini file {configfile} not found, be sure to run the this script from within the build directory")
Exception: config.ini file /sd/g/bitcoin/test/functional/../config.ini not found, be sure to run the this script from within the build directory
```

2024-09-10 04:45 UTC, tdb3 reviewed
Thanks for noticing this. I'd support the documentation change without changing the python programs.

2024-09-13 16:30 UTC, jonatack reviewed
Concept ACK. I came across this as well, and the new error message would indeed be helpful. (Bonus points if the message can be defined in one place, didn't check.)

2024-09-13 20:05 UTC, furszy reviewed
Concept ACK. I keep calling the src test files by inertia..

2024-09-16 11:02 UTC, pablomartin4btc reviewed
ACK 15cc65649b78ffcbd1e1b302c2e4866623cee294

> (Bonus points if the message can be defined in one place, didn't check.)

I agree. `ConfigParser` should not raise an exception if the config file path is invalid?

2024-09-20 10:15 UTC, fanquake commented on src/test/README.md
> +(assuming `build` is your build directory). To recompile
You're adding `(assuming build is your build directory)` here, but 3 lines up it already says `Assuming the build directory is named build,`.

2024-09-20 10:15 UTC, fanquake commented on src/test/README.md
> +(assuming `build` is your build directory).
Same here. I don't think we need to duplicate `(assuming build is your build directory)` 10 lines apart. Especially when all the build commands here used `build` as the build dir.

2024-09-20 10:15 UTC, fanquake commented on src/crc32c/README.md
> +for example,`build/`) (re)builds the project and
You can't modify the subtree here.

2024-09-20 10:15 UTC, fanquake commented on doc/developer-notes.md
> +(assuming `build` is your build directory);
2 lines above, this already says `Assuming the build directory is named build,`

2024-09-20 16:29 UTC, LarryRuane commented
@fanquake - thanks, I'll fix all these this weekend.

2024-10-08 16:08 UTC, fanquake commented on test/functional/test_framework/test_framework.py
> +        if not os.path.isfile(self.options.configfile):
Think I agree with this as well.

2024-10-08 17:32 UTC, LarryRuane commented on test/functional/test_framework/test_framework.py
> +        if not os.path.isfile(self.options.configfile):
Thanks, I don't mind removing the code changes at all (I was on the fence on this part of the change), should we wait a little while to see if there are other opinions?

2024-10-08 20:19 UTC, fanquake commented on test/functional/test_framework/test_framework.py
> +        if not os.path.isfile(self.options.configfile):
I think it'd be good to just get this finished so the docs are updated. So that we don't end up with even more PRs to fix the same docs.

2024-10-09 22:45 UTC, tdb3 approved these changes
ACK c15ef096ce317ae911dd756593adeac9d9a0b5a1

2024-10-09 23:14 UTC, jonatack commented on README.md
> +(assuming `build` is your build directory).
After [this push](https://github.com/bitcoin/bitcoin/compare/96f4820f1f274ad371aaa37f8247305183e4642c..cd9297c42447f41b95eea6794535a08341f479dd#diff-ec54487d37183db6e158a11eb3560af15758aba1bd7e253c6b3a58ad3ad16e39R13), ISTM that either the following change is now inadvertently missing, or the PR needs a new title.

```diff
-Running `test/functional/test_runner.py` with the `--coverage` argument tracks which RPCs are
+Running `build/test/functional/test_runner.py` (assuming `build` is your build
+directory) with the `--coverage` argument tracks which RPCs are
```

2024-10-09 23:18 UTC, jonatack requested changes
After [this push](https://github.com/bitcoin/bitcoin/compare/96f4820f1f274ad371aaa37f8247305183e4642c..cd9297c42447f41b95eea6794535a08341f479dd#diff-ec54487d37183db6e158a11eb3560af15758aba1bd7e253c6b3a58ad3ad16e39R13), ISTM that either the following change is now inadvertently missing, or the PR needs a new title and description.

```diff
--- a/test/functional/README.md
+++ b/test/functional/README.md
@@ -10,7 +10,8 @@ that file and modify to fit your needs.
  
-Running `test/functional/test_runner.py` with the `--coverage` argument tracks which RPCs are
+Running `build/test/functional/test_runner.py` (assuming `build` is your build
+directory) with the `--coverage` argument tracks which RPCs are
 called by the tests and prints a report of uncovered RPCs in the summary. This
 ```

(redoing a review to appease the bot)

2024-10-09 23:21 UTC, jonatack requested changes
After [this push](https://github.com/bitcoin/bitcoin/compare/96f4820f1f274ad371aaa37f8247305183e4642c..cd9297c42447f41b95eea6794535a08341f479dd#diff-ec54487d37183db6e158a11eb3560af15758aba1bd7e253c6b3a58ad3ad16e39R13), ISTM that the following change is now inadvertently missing.

```diff
--- a/test/functional/README.md
+++ b/test/functional/README.md
@@ -10,7 +10,8 @@ that file and modify to fit your needs.
  
-Running `test/functional/test_runner.py` with the `--coverage` argument tracks which RPCs are
+Running `build/test/functional/test_runner.py` (assuming `build` is your build
+directory) with the `--coverage` argument tracks which RPCs are
 called by the tests and prints a report of uncovered RPCs in the summary. This
```

2024-10-10 07:16 UTC, LarryRuane commented
Force pushed 6ab688c74b61c4403f831f1df54a350548ce8664 to restore the accidentally-dropped change that Jon pointed out.

2024-10-10 13:41 UTC, jonatack reviewed
LGTM modulo comment

2024-10-10 13:41 UTC, jonatack commented on test/functional/README.md
> +Running `build/test/functional/test_runner.py` with the `--coverage` argument tracks which RPCs are
Per feedback in https://github.com/bitcoin/bitcoin/pull/30859#discussion_r1759115295, begin this sentence with "Assuming the build directory is named `build`, running..."

I agreed with the feedback not to add it where it was already mentioned in other files, but in this file there is no other mention.

2024-10-11 17:26 UTC, LarryRuane commented
Force pushed Jon's suggestion, thanks - https://github.com/bitcoin/bitcoin/pull/30859#discussion_r1795456841

2024-10-12 00:26 UTC, tdb3 approved these changes
re ACK e64b2f1a16e8d0ad2cd181d84e3b70312e3cdf33

2024-10-15 10:10 UTC, merged