test: autogenerate bash completion
bitcoin/bitcoin pull request #30860
Opened 2024-09-10 08:26 UTC by BrandonOdiwuor

Fixes https://github.com/bitcoin/bitcoin/issues/17289, and follows up on https://github.com/bitcoin/bitcoin/pull/18606

Adds a functional test that parses available RPC commands, generates the associated bitcoin-cli autocomplete file and checks that the current autocomplete file matches.

An outdated autocomplete file can be updated via the --overwrite test parameter.

2024-09-10 15:44 UTC, fanquake commented
https://github.com/bitcoin/bitcoin/actions/runs/10788681404/job/29919981336?pr=30860#step:7:3564:
```bash
Run rpc with args ['/Users/runner/work/bitcoin/bitcoin/ci/scratch/build-x86_64-apple-darwin/src/test/fuzz/fuzz', PosixPath('/Users/runner/work/bitcoin/bitcoin/ci/scratch/qa-assets/fuzz_corpora/rpc')]Error: RPC command "format" not found in RPC_COMMANDS_SAFE_FOR_FUZZING or RPC_COMMANDS_NOT_SAFE_FOR_FUZZING. Please update src/test/fuzz/rpc.cpp.
libc++abi: terminating

Error: RPC command "format" not found in RPC_COMMANDS_SAFE_FOR_FUZZING or RPC_COMMANDS_NOT_SAFE_FOR_FUZZING. Please update src/test/fuzz/rpc.cpp.
libc++abi: terminating

Target ['/Users/runner/work/bitcoin/bitcoin/ci/scratch/build-x86_64-apple-darwin/src/test/fuzz/fuzz', PosixPath('/Users/runner/work/bitcoin/bitcoin/ci/scratch/qa-assets/fuzz_corpora/rpc')] failed with exit code -6
```

2024-11-15 15:44 UTC, luke-jr requested changes

2024-11-15 15:44 UTC, luke-jr commented on test/functional/tool_cli_bash_completion.py
> +        if self.options.completion is None or len(self.option.completion) == 0:
```suggestion
        if self.options.completion is None or len(self.options.completion) == 0:
```

2024-12-18 07:28 UTC, BrandonOdiwuor commented on test/functional/tool_cli_bash_completion.py
> +        if self.options.completion is None or len(self.option.completion) == 0:
fixed

2025-02-14 19:58 UTC, tnndbtc commented on test/functional/tool_cli_bash_completion.py
> +        generated = ""
Since there is a discussion (https://github.com/bitcoin/bitcoin/issues/17289#issuecomment-618736031) on whether it will slow down when user hit TAB key to send request to bitcoind for auto completion, what about we add those cword==1 commands in contrib/completions/bash/bitcoin-cli.bash so that it will not rely on the startup of bitcoind?

The suggested code is pasted below and tested:

        # create cword==1 block to avoid the calling of bitcoind to get auto complete
        commands = []
        for command in options:
            commands.append(command.command)
        commands_str = " ".join(commands)
        cword_1_block = f"""    if ((cword == 1)); then
        options=\"{commands_str}\"
        COMPREPLY=( $( compgen -W "$options" -- "$cur" ) )
        return 0\n    fi\n\n"""

        generated = cword_1_block

2025-02-14 20:21 UTC, tnndbtc commented
I tested the code in mac(Apple M1 chip) and it worked fine.  Steps are:
# run test and generate contrib/completions/bash/bitcoin-cli.bash:
% build/test/functional/test_runner.py test/functional/tool_cli_bash_completion.py --tmpdir /tmp --nocleanup --overwrite

# validate bash-completion on mac:
% brew info bash-completion

# switch to bash shell
% bash

# source the bash_completion script
% . /opt/homebrew/etc/profile.d/bash_completion.sh

# source bitcoin-cli bash
% source contrib/completions/bash/bitcoin-cli.bash

# then, without starting bitcoind
% bitcoin-cli con[TAB]

#this will auto complete to converttopsbt
% bitcoin-cli converttopsbt

#this will auto complete to converttopsbt
% bitcoin-cli converttopsbt somestring [TAB]
false  true

% bitcoin-cli converttopsbt some t[TAB]

# it will auto complete true
% bitcoin-cli converttopsbt some true

% bitcoin-cli converttopsbt some true t[TAB]

# it will auto complete false
% bitcoin-cli converttopsbt some true f[TAB]

% bitcoin-cli converttopsbt some true false

Also, traced the code, especially in test/functional/tool_cli_bash_completion.py:
    get_command_options
    generate_completion_block
and they look good to me.  Left an enhancement comment in the PR so that the author can review.

2025-10-22 14:21 UTC, achow101 commented
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

2025-10-22 14:21 UTC, closed without merging