rpc: combinerawtransaction now rejects unmergeable transactions
bitcoin/bitcoin pull request #31298
Opened 2024-11-15 21:24 UTC by adamandrews1

Previously, combinerawtransaction would silently return the first tx when asked to combine unrelated txs. Now, it will check tx mergeability and throws a descriptive error if tx cannot be merged.

fixes  #25980

2024-11-20 02:08 UTC, adamandrews1 commented
It seems like, with https://github.com/bitcoin/bitcoin/pull/31249, I should migrate these test changes as well. WIP

2024-11-20 21:31 UTC, 1440000bytes commented
Can this use the same approach and error message as `combinepsbt`?

2024-11-20 22:32 UTC, adamandrews1 commented
> Can this use the same approach and error message as `combinepsbt`?

This is the same functional approach and error message already.
Creating a PSBT involves stripping the scriptSig and scriptWitnesses. Later, the hashes are compared.  That's exactly what this change is doing too but the syntax is different. I can align the syntax to make it more clear it is doing the same thing.

2024-11-21 07:52 UTC, 1440000bytes commented
> Later, the hashes are compared. That's exactly what this change is doing too but the syntax is different.

```c++
bool PartiallySignedTransaction::Merge(const PartiallySignedTransaction& psbt)
{
    // Prohibited to merge two PSBTs over different transactions
    if (tx->GetHash() != psbt.tx->GetHash()) {
        return false;
    }
```

Right. Only the error message was different which looks same now,

2024-11-21 07:52 UTC, 1440000bytes approved these changes
utACK https://github.com/bitcoin/bitcoin/pull/31298/commits/85c216871a01aab003e1b1aba6246b4178afc929

2024-12-18 19:26 UTC, i-am-yuvi approved these changes
Tested ACK 85c216871a01aab003e1b1aba6246b4178afc929

Below is my full test setup:

## Tested on Regtest mode

### master@d2136d32bb4764e4035fb892d979c27f037fad93
- When checked with only 1 raw txn, returns only the txn (no error for missing txns)
- When checked for mergeability: 
     - returns only the first txn when unrelated txns were provided
     - doesn't show descriptive error for any mergeability issue
     

### combinerawtransaction-check@85c216871a01aab003e1b1aba6246b4178afc929
- When only 1 raw txn provided it returns missing inputs
- checking for mergeability:
     - shows descriptive error for mergeability issue 
for e.g.

```
error code: -8
error message:
Transaction 1 not compatible (different transactions)
```

Gives combine hex when same txns are provided
```
./build/src/bitcoin-cli combinerawtransaction '["0200000001a0d2e799d40d404da2daf128fc678fdd15f245bdd92c6e1ad15b45f7258a47b90000000000fdffffff01008c86470000000016001483f259c98962117d75154f35cb55cd60b88a257e00000000","0200000001a0d2e799d40d404da2daf128fc678fdd15f245bdd92c6e1ad15b45f7258a47b90000000000fdffffff01008c86470000000016001483f259c98962117d75154f35cb55cd60b88a257e00000000"]'
0200000001a0d2e799d40d404da2daf128fc678fdd15f245bdd92c6e1ad15b45f7258a47b90000000000fdffffff01008c86470000000016001483f259c98962117d75154f35cb55cd60b88a257e00000000
```

for inputs already spent:
```
error code: -25
error message:
Input not found or already spent
```

*Note: newly created wallet and txns were used during the test using ```createrawtransaction``` rpc in regtest mode* 

Also, the functional test LGTM:
```
Temporary test directory at /var/folders/jb/wlbrz0t95vl58wzxjt75wqmh0000gn/T/test_runner_₿_🏃_20241219_004940
Remaining jobs: [rpc_createmultisig.py]
1/1 - rpc_createmultisig.py passed, Duration: 3 s

TEST                  | STATUS    | DURATION

rpc_createmultisig.py | ✓ Passed  | 3 s

ALL                   | ✓ Passed  | 3 s (accumulated) 
Runtime: 3 s
```

2024-12-27 18:29 UTC, danielabrozzoni commented on src/rpc/rawtransaction.cpp
> +                input.scriptWitness.SetNull();
I don't think it's needed to clear the script witness, as it's not taken into account when calculating the txid

2025-01-13 23:00 UTC, adamandrews1 commented on src/rpc/rawtransaction.cpp
> +                input.scriptWitness.SetNull();
This is done to align the method with PSBT. It could be removed without breaking the change. But it also is just clearing data which should take minimal time. I think it's worth keeping to align with PSBT format.

2025-01-14 23:29 UTC, brunoerg commented on src/rpc/rawtransaction.cpp
> +                input.scriptWitness.SetNull();
No objections on it but maybe you could update the documentation, it says: "This involves stripping sigscripts from each tx and ensuring txid is consistent." but you're also stripping the script witness.

2025-02-15 22:17 UTC, adamandrews1 commented on src/rpc/rawtransaction.cpp
> +                input.scriptWitness.SetNull();
@brunoerg I think you are right, I will update the description here to make it explicit we are tracking PSBT here 👍🏻

2025-02-19 11:20 UTC, zaidmstrr commented on src/rpc/rawtransaction.cpp
> +    for (unsigned int idx {0}; idx < txs.size(); idx++) {
```suggestion
    for (unsigned int idx{0}; idx < txs.size(); idx++) {
```
nit: don't need to add the extra space

2025-02-19 11:20 UTC, zaidmstrr commented on src/rpc/rawtransaction.cpp
> +        for (unsigned int k{0}; k < txVariantsCopy.size(); k++) {
```suggestion
        for (unsigned int k{0}; k < txVariantsCopy.size(); ++k) {
```
nit: `++k` should be given more prefrence then `k++ `

2025-02-19 11:20 UTC, zaidmstrr commented on src/rpc/rawtransaction.cpp
> +    for (unsigned int i{0}; i < mergedTx.vin.size(); i++) {
```suggestion
    for (unsigned int i{0}; i < mergedTx.vin.size(); ++i) {
```
nit: same for here `++i` should be prioritised.

2025-02-20 19:35 UTC, i-am-yuvi commented on src/rpc/rawtransaction.cpp
> +    for (unsigned int idx {0}; idx < txs.size(); idx++) {
It might be helpful to consider giving a `Concept ACK` or `NACK` before the review. I came across this idea [here](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#code-review).

2025-02-20 20:47 UTC, zaidmstrr commented
Concept ACK

2025-02-20 20:49 UTC, zaidmstrr commented on src/rpc/rawtransaction.cpp
> +    for (unsigned int idx {0}; idx < txs.size(); idx++) {
Done

2025-02-20 21:31 UTC, adamandrews1 commented on src/rpc/rawtransaction.cpp
> +    for (unsigned int idx {0}; idx < txs.size(); idx++) {
Fixed nit

2025-02-20 21:31 UTC, adamandrews1 commented on src/rpc/rawtransaction.cpp
> +        for (unsigned int k{0}; k < txVariantsCopy.size(); k++) {
Fixed nit

2025-02-20 21:31 UTC, adamandrews1 commented on src/rpc/rawtransaction.cpp
> +    for (unsigned int i{0}; i < mergedTx.vin.size(); i++) {
Fixed nit

2025-05-04 19:38 UTC, naiyoma reviewed
Tested ACK https://github.com/bitcoin/bitcoin/pull/31298/commits/9d31e94bf584e12269683b74b1c96c7ac883a760

I have tested the changes on regtest and got expected output 

```
bitcoin-cli -regtest combinerawtransaction "[\"$RAW_TX1\", \"$RAW_TX2\"]"
error code: -8
error message:
Transaction 1 not compatible (different transactions)
```

2025-05-04 20:27 UTC, naiyoma commented on src/rpc/rawtransaction.cpp
> +        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "Missing transactions");
nit: IMO, this could be a bit more descriptive

 ```diff
    // Can't merge < 2 items
     if (txs.size() < 2) {
-        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "Missing transactions");
+        throw JSONRPCError(
+            RPC_INVALID_PARAMETER,
+            txs.size() == 0 
+                ? "Missing transactions. At least two transactions required." 
+                : "Insufficient transactions. At least two transactions  required."
+        );
     }
```

2025-06-06 13:23 UTC, yuvicc reviewed
re-ACK 9d31e94bf584e12269683b74b1c96c7ac883a760

2025-06-27 21:12 UTC, achow101 commented on src/rpc/rawtransaction.cpp
> +    { // Test Tx relation for mergeability. This involves converting each tx to PSBT format (stripping sigscripts/witnesses) and ensuring txid is consistent.
This comment is incorrect, it's not doing anything related to PSBT. You can just say that the scriptSigs and scriptWitnesses are being stripped in order to do a txid comparison.

2025-06-27 22:05 UTC, adamandrews1 commented on src/rpc/rawtransaction.cpp
> +    { // Test Tx relation for mergeability. This involves converting each tx to PSBT format (stripping sigscripts/witnesses) and ensuring txid is consistent.
Thanks, I will update this comment

2025-09-15 22:35 UTC, achow101 commented
Are you still working on this?

2025-09-16 03:35 UTC, adamandrews1 commented
@achow101 I've rebased this and updated the comment. No other changes.

2025-09-24 13:40 UTC, theStack reviewed
Concept ACK

2025-09-24 13:40 UTC, theStack commented on src/rpc/rawtransaction.cpp
> +        std::vector<CMutableTransaction> txVariantsCopy(txVariants);
nit: as per our coding guidelines, [variable names should be in `camel_case`](https://github.com/bitcoin/bitcoin/blob/ad4a49090da81a3683fc50694ed7b42a80fdf90b/doc/developer-notes.md?plain=1#L38-L39), and new style should be favored over mimicking the surrounding style

2025-09-24 13:40 UTC, theStack commented on test/functional/rpc_createmultisig.py
> +        assert_raises_rpc_error(-8, "Transaction 1 not compatible (different transactions)", self.nodes[0].combinerawtransaction, [rawtx2['hex'], unrelatedTx])
could test more thoroughly by repeatedly modifying other fields that the txid commits to (w/o scriptSig), but this can be done in a follow-up

2025-11-07 14:34 UTC, rkrux reviewed
Concept ACK a26e9fd5b5908853d37b81915f5e12a5ad822f86

Thanks for adding the fix.

2025-11-07 14:34 UTC, rkrux commented on src/rpc/rawtransaction.cpp
> +                input.scriptWitness.SetNull();
> This is done to align the method with PSBT. It could be removed without breaking the change. But it also is just clearing data which should take minimal time. I think it's worth keeping to align with PSBT format.

I don't fully understand how it is aligning with PSBT, can you please explain? `GetHash()` used both here later and in `combinePSBT` RPC doesn't take the witness into account, making the removal of witness unnecessary.

https://github.com/bitcoin/bitcoin/blob/93e79181da8c952f270c4fa101828d1515999bab/src/primitives/transaction.cpp#L69-L72

2025-11-07 14:34 UTC, rkrux commented on src/rpc/rawtransaction.cpp
> +        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "Missing transactions");
Nit: Can consider to be more verbose in the error message.

```diff
- throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "Missing transactions");
+ throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "Missing transactions. At least two transactions required.");
```

2025-11-07 14:34 UTC, rkrux commented on test/functional/rpc_createmultisig.py
> +        assert_raises_rpc_error(-8, "Transaction 1 not compatible (different transactions)", self.nodes[0].combinerawtransaction, [rawtx2['hex'], unrelatedTx])
```diff
--- a/test/functional/rpc_createmultisig.py
+++ b/test/functional/rpc_createmultisig.py
@@ -149,17 +149,16 @@ class RpcCreateMultiSigTest(BitcoinTestFramework):
         assert_raises_rpc_error(-22, "TX decode failed", node2.combinerawtransaction, [rawtx2['hex'], rawtx3['hex'] + "00"])
         assert_raises_rpc_error(-22, "Missing transactions", node2.combinerawtransaction, [])
         assert_raises_rpc_error(-22, "Missing transactions", node2.combinerawtransaction, [rawtx2['hex']])
-        combined_rawtx = node2.combinerawtransaction([rawtx2["hex"], rawtx3["hex"]])
 
-        # transactions are not related
-        UNRELATED_TXID = "1d1d4e24ed99057e84c3f80fd8fbec79ed9e1acee37da269356ecea000000000"
-        unrelatedTx = self.nodes[2].createrawtransaction(inputs=[{'txid': UNRELATED_TXID, 'vout': 9}], outputs=[{out_addr: 99}])
-        assert_raises_rpc_error(-8, "Transaction 1 not compatible (different transactions)", self.nodes[0].combinerawtransaction, [rawtx2['hex'], unrelatedTx])
+        # similar transaction but with different amount to send
+        alteredTx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval * 2}])
+        assert_raises_rpc_error(-8, "Transaction 1 not compatible (different transactions)", self.nodes[0].combinerawtransaction, [rawtx2['hex'], alteredTx])
 
         # Accept duplicate transactions in combinerawtransaction
         dupeMergedTx = self.nodes[0].combinerawtransaction([rawtx2['hex'], rawtx2['hex']])
         assert_equal(rawtx2['hex'], dupeMergedTx)
 
+        combined_rawtx = node2.combinerawtransaction([rawtx2["hex"], rawtx3["hex"]])
         tx = node0.sendrawtransaction(combined_rawtx, 0)
         blk = self.generate(node0, 1)[0]
         assert tx in node0.getblock(blk)["tx"]
```

1. The error case can be added before creating the `combined_rawtx` instead of adding them in the middle.
2. `self.nodes[2]` -> `node2` to stick with the format used in the file.
3. Can consider using the same RPC that created `rawtx` earlier. Instead of hardcoding random transaction id, altering the amount to send also helps in reproducing the error scenario.

2025-11-07 14:34 UTC, rkrux commented on src/rpc/rawtransaction.cpp
> +                    throw JSONRPCError(RPC_INVALID_PARAMETER, strprintf("Transaction %d not compatible (different transactions)", k));
Nit: Reading `Transaction 1` can be confusing for the user if they are not aware that 0-based indexing is being used.

2025-11-18 21:06 UTC, achow101 commented on src/rpc/rawtransaction.cpp
> +    for (unsigned int idx{0}; idx < txs.size(); ++idx) {
nit: This is an unnecessary style change.

2025-11-18 21:06 UTC, achow101 commented on src/rpc/rawtransaction.cpp
> +    for (unsigned int i{0}; i < mergedTx.vin.size(); ++i) {
nit: This is an unnecessary style change.

2025-12-06 22:28 UTC, mossein commented
Tested ACK a26e9fd5b5908853d37b81915f5e12a5ad822f86

Built on macOS, ran 
rpc_createmultisig.py
 - passes. The approach of stripping scriptSigs/scriptWitnesses and comparing txids is clean.

Agree with the minor nits from other reviewers (style changes, error message verbosity).

2025-12-07 14:24 UTC, adamandrews1 commented
> Are you still working on this?

Yes, I will produce an additional patch addressing all comments in the coming days.

2025-12-08 12:31 UTC, adamandrews1 commented on src/rpc/rawtransaction.cpp
> +                    throw JSONRPCError(RPC_INVALID_PARAMETER, strprintf("Transaction %d not compatible (different transactions)", k));
switched to tx number (1-based indexing) for user reporting

2025-12-08 13:55 UTC, adamandrews1 commented on test/functional/rpc_createmultisig.py
> +        assert_raises_rpc_error(-8, "Transaction 1 not compatible (different transactions)", self.nodes[0].combinerawtransaction, [rawtx2['hex'], unrelatedTx])
these were great suggestions, thank you - added

2025-12-08 15:04 UTC, adamandrews1 commented
I've addressed all nits and rebased. Thank you to each of you who left thoughtful commentary.

2025-12-09 11:23 UTC, maflcko commented on test/functional/rpc_createmultisig.py
> +        unrelated_tx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}], 1)
LLM  (✨ experimental)

Possible places where named args may be used for integral literals (e.g. func(x, /*named_arg=*/0) in C++, and func(x, named_arg=0) in Python):

    node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}], 0, True, 1) in test/functional/rpc_createmultisig.py
    node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}], 1) in test/functional/rpc_createmultisig.py


Otherwise, it will be harder to read and understand the code. Also, it will be brittle, when args are reordered by accident.

2025-12-10 12:14 UTC, rkrux requested changes
Overall looking quite good.

I noticed that these new cases are added within the `do_multisig` function that is called several times here:
https://github.com/bitcoin/bitcoin/blob/56ce78d5f62c9eb9353d33eedd15495c1205465f/test/functional/rpc_createmultisig.py#L48-L51

Given the nature of the bug regarding the un-mergeable transactions, I feel testing this once should be sufficient in which case we can consider adding these cases in a separate function that should help in avoiding testing the fix multiple times. WDYT? (I have not formed a strong opinion on this though.)

2025-12-10 12:14 UTC, rkrux commented on test/functional/rpc_createmultisig.py
> +        assert_raises_rpc_error(-22, "Missing transactions", node2.combinerawtransaction, [rawtx2['hex']])
Let's assert the full error for thoroughness.

```diff
-        assert_raises_rpc_error(-22, "Missing transactions", node2.combinerawtransaction, [])
-        assert_raises_rpc_error(-22, "Missing transactions", node2.combinerawtransaction, [rawtx2['hex']])
+        assert_raises_rpc_error(-22, "Missing transactions. At least two transactions required.", node2.combinerawtransaction, [])
+        assert_raises_rpc_error(-22, "Missing transactions. At least two transactions required.", node2.combinerawtransaction, [rawtx2['hex']])
```

2025-12-10 12:14 UTC, rkrux commented on test/functional/rpc_createmultisig.py
> +        assert_raises_rpc_error(-8, "Transaction number 2 not compatible with first transaction", node0.combinerawtransaction, [rawtx2['hex'], unrelated_tx])
Thanks for adding 6 test cases, very nice. The new error is also easier to parse imo.
We can get rid of the duplication here. Consider the following diff:

```diff
-        # similar transaction but with different amount to send, transactions are not mergeable
-        unrelated_tx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval * 2}])
-        assert_raises_rpc_error(-8, "Transaction number 2 not compatible with first transaction", node0.combinerawtransaction, [rawtx2['hex'], unrelated_tx])
-
-        # similar transaction but with different version, transactions are not mergeable
-        unrelated_tx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}], 0, True, 1)
-        assert_raises_rpc_error(-8, "Transaction number 2 not compatible with first transaction", node0.combinerawtransaction, [rawtx2['hex'], unrelated_tx])
-
-        # similar transaction but with different locktime, transactions are not mergeable
-        unrelated_tx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}], 1)
-        assert_raises_rpc_error(-8, "Transaction number 2 not compatible with first transaction", node0.combinerawtransaction, [rawtx2['hex'], unrelated_tx])
-
-        # similar transaction but with different output address (scriptPubKey), transactions are not mergeable
         out_addr2 = getnewdestination('bech32')[2]
-        unrelated_tx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr2: outval}])
-        assert_raises_rpc_error(-8, "Transaction number 2 not compatible with first transaction", node0.combinerawtransaction, [rawtx2['hex'], unrelated_tx])
-
-        # similar transaction but with different sequence number, transactions are not mergeable
-        unrelated_tx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"], "sequence": 1}], [{out_addr: outval}])
-        assert_raises_rpc_error(-8, "Transaction number 2 not compatible with first transaction", node0.combinerawtransaction, [rawtx2['hex'], unrelated_tx])
-
-        # similar transaction but with different input vout index, transactions are not mergeable
-        unrelated_tx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"] + 1}], [{out_addr: outval}])
-        assert_raises_rpc_error(-8, "Transaction number 2 not compatible with first transaction", node0.combinerawtransaction, [rawtx2['hex'], unrelated_tx])
+        unmergeable_transaction_args = [
+            [[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval * 2}]], # similar transaction but with different amount to send
+            [[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}], 0, True, 1], # similar transaction but with different version
+            [[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}], 1], # similar transaction but with different locktime
+            [[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr2: outval}]], # similar transaction but with different output address (scriptPubKey)
+            [[{"txid": tx["txid"], "vout": tx["sent_vout"], "sequence": 1}], [{out_addr: outval}]], # similar transaction but with different sequence number
+            [[{"txid": tx["txid"], "vout": tx["sent_vout"] + 1}], [{out_addr: outval}]] # similar transaction but with different input vout index
+        ]
+
+        for rpc_args in unmergeable_transaction_args:
+            unrelated_tx = node2.createrawtransaction(*rpc_args)
+            assert_raises_rpc_error(-8, "Transaction number 2 not compatible with first transaction", node0.combinerawtransaction, [rawtx2['hex'], unrelated_tx])
 
         # Accept duplicate transactions in combinerawtransaction
         dupe_merged_tx = node2.combinerawtransaction([rawtx2['hex'], rawtx2['hex']])
```

2025-12-10 12:14 UTC, rkrux commented on test/functional/rpc_createmultisig.py
> +        unrelated_tx = node2.createrawtransaction([{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}], 1)
This is a nice suggestion that can be implemented.

2025-12-24 00:21 UTC, achow101 commented on src/rpc/rawtransaction.cpp
> +                if (txid != tx_variants_copy[k].GetHash()) {
In a516fe8ada1880f30c6e4553677a9a2580a17cb0 "rpc: combinerawtransaction now rejects unmergeable transactions"

nit: can be a single line `else if`

2025-12-29 17:31 UTC, adamandrews1 commented
> Overall looking quite good.
> 
> I noticed that these new cases are added within the `do_multisig` function that is called several times here:
> 
> https://github.com/bitcoin/bitcoin/blob/56ce78d5f62c9eb9353d33eedd15495c1205465f/test/functional/rpc_createmultisig.py#L48-L51
> 
> Given the nature of the bug regarding the un-mergeable transactions, I feel testing this once should be sufficient in which case we can consider adding these cases in a separate function that should help in avoiding testing the fix multiple times. WDYT? (I have not formed a strong opinion on this though.)

The tx mergeability constraints are invariant across output_type and n_sig etc, it should be sufficient to test them one time explicitly and disable during all other runs. Probably not a huge runtime cost as-is but there is definitely a fan-out that would adds additional overhead to all callers of `do_multisig` so got rid of that. Also integrated all other feedback.

2025-12-30 13:09 UTC, rkrux reviewed
> The tx mergeability constraints are invariant across output_type and n_sig etc, it should be sufficient to test them one time explicitly and disable during all other runs. Probably not a huge runtime cost as-is but there is definitely a fan-out that would adds additional overhead to all callers of do_multisig so got rid of that. Also integrated all other feedback.

Thanks for addressing all the feedback! I had a different approach in mind that creates a separate function for these checks but the latest implementation also looks fine to me.

Code is lgtm e3069ecd814db2ece640ba0427e7778b03f7314e

Shared 2 nits that could be addressed at the moment I believe.

2025-12-30 13:09 UTC, rkrux commented on src/rpc/rawtransaction.cpp
> +            } else if (txid != tx_variants_copy[k].GetHash()) {
Nit - this is set only once for the first transaction:

```diff
diff --git a/src/rpc/rawtransaction.cpp b/src/rpc/rawtransaction.cpp
index 1de4d200e8..d0038f25ad 100644
--- a/src/rpc/rawtransaction.cpp
+++ b/src/rpc/rawtransaction.cpp
@@ -622,7 +622,7 @@ static RPCHelpMan combinerawtransaction()
 
     { // Test Tx relation for mergeability. Strip scriptSigs and scriptWitnesses to facilitate txId comparison
         std::vector<CMutableTransaction> tx_variants_copy(txVariants);
-        Txid txid{};
+        Txid first_txid{};
         for (unsigned int k{0}; k < tx_variants_copy.size(); ++k) {
             // Remove all scriptSigs and scriptWitnesses from inputs
             for (CTxIn& input : tx_variants_copy[k].vin) {
@@ -630,8 +630,8 @@ static RPCHelpMan combinerawtransaction()
                 input.scriptWitness.SetNull();
             }
             if (k == 0) {
-                txid = tx_variants_copy[k].GetHash();
-            } else if (txid != tx_variants_copy[k].GetHash()) {
+                first_txid = tx_variants_copy[k].GetHash();
+            } else if (first_txid != tx_variants_copy[k].GetHash()) {
                 throw JSONRPCError(RPC_INVALID_PARAMETER, strprintf("Transaction number %d not compatible with first transaction", k+1));
             }
         }
```

2025-12-30 13:09 UTC, rkrux commented on test/functional/rpc_createmultisig.py
> +                ([[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}]], {"locktime": 0, "replaceable": True, "version": 1}), # similar transaction but with different version
Because non-positional arguments are used here for `version`, rest 2 (`locktime` and `replaceable`) are not required:

```diff
diff --git a/test/functional/rpc_createmultisig.py b/test/functional/rpc_createmultisig.py
index fa0f668922..199193cbbd 100755
--- a/test/functional/rpc_createmultisig.py
+++ b/test/functional/rpc_createmultisig.py
@@ -162,7 +162,7 @@ class RpcCreateMultiSigTest(BitcoinTestFramework):
             out_addr2 = getnewdestination('bech32')[2]
             unmergeable_transaction_args = [
                 ([[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval * 2}]], {}), # similar transaction but with different amount to send
-                ([[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}]], {"locktime": 0, "replaceable": True, "version": 1}), # similar transaction but with different version
+                ([[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}]], {"version": 1}), # similar transaction but with different version
                 ([[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}]], {"locktime": 1}), # similar transaction but with different locktime
                 ([[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr2: outval}]], {}), # similar transaction but with different output address (scriptPubKey)
                 ([[{"txid": tx["txid"], "vout": tx["sent_vout"], "sequence": 1}], [{out_addr: outval}]], {}), # similar transaction but with different sequence number
(END)
```

2026-01-19 23:12 UTC, achow101 commented
ACK e3069ecd814db2ece640ba0427e7778b03f7314e

2026-03-19 12:16 UTC, sedited commented
@adamandrews1 can you address the remaining nits here? I'm guessing the other reviewers are hesitant to provide more feedback while changes are already being requested.

2026-03-20 12:00 UTC, adamandrews1 commented
> @adamandrews1 can you address the remaining nits here? I'm guessing the other reviewers are hesitant to provide more feedback while changes are already being requested.

Sure, I can address.

2026-04-18 19:47 UTC, sedited commented
> Sure, I can address.

Pinging again since it has been a month. Just need to apply the two small diffs above by the looks of it.

2026-04-22 12:14 UTC, adamandrews1 commented
> > Sure, I can address.
> 
> 
> 
> Pinging again since it has been a month. Just need to apply the two small diffs above by the looks of it.

Thanks. Assure you this is still on my radar.

2026-04-26 11:10 UTC, adamandrews1 commented on src/rpc/rawtransaction.cpp
> +            } else if (txid != tx_variants_copy[k].GetHash()) {
renamed

2026-04-26 11:29 UTC, adamandrews1 commented on test/functional/rpc_createmultisig.py
> +                ([[{"txid": tx["txid"], "vout": tx["sent_vout"]}], [{out_addr: outval}]], {"locktime": 0, "replaceable": True, "version": 1}), # similar transaction but with different version
removed

2026-04-26 11:30 UTC, adamandrews1 commented
> > The tx mergeability constraints are invariant across output_type and n_sig etc, it should be sufficient to test them one time explicitly and disable during all other runs. Probably not a huge runtime cost as-is but there is definitely a fan-out that would adds additional overhead to all callers of do_multisig so got rid of that. Also integrated all other feedback.
> 
> Thanks for addressing all the feedback! I had a different approach in mind that creates a separate function for these checks but the latest implementation also looks fine to me.
> 
> Code is lgtm [e3069ec](https://github.com/bitcoin/bitcoin/commit/e3069ecd814db2ece640ba0427e7778b03f7314e)
> 
> Shared 2 nits that could be addressed at the moment I believe.

addressed 2 nits @rkrux @sedited

2026-04-26 21:50 UTC, fanquake commented
You'll need to squash your commits / remove the merge commit.

2026-04-27 00:58 UTC, adamandrews1 commented
> You'll need to squash your commits / remove the merge commit.

squashed and rebased

2026-04-27 09:23 UTC, rkrux approved these changes
ACK [6d86184](https://github.com/bitcoin/bitcoin/pull/31298/commits/6d86184a8bcc34186d217cc7cfbf7acc21af7ca4)

Thanks for addressing the nits.

2026-05-08 08:13 UTC, nervana21 commented
Concept ACK

2026-05-10 18:21 UTC, nervana21 commented
tACK 6d86184a8bcc34186d217cc7cfbf7acc21af7ca4

Small nit: I tend to agree with other reviewers who state that clearing the `scriptWitness` even though it's not necessary makes the code harder to reason about

2026-05-13 23:02 UTC, achow101 commented
ACK 6d86184a8bcc34186d217cc7cfbf7acc21af7ca4

2026-05-13 23:07 UTC, merged