ci, iwyu: Treat warnings as errors for specific targets
bitcoin/bitcoin pull request #31308
Opened 2024-11-17 21:00 UTC by hebasto

This PR is the first step towards treating IWYU warnings as errors. It utilises CMake's native support via the [`CMAKE_CXX_INCLUDE_WHAT_YOU_USE`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_INCLUDE_WHAT_YOU_USE.html)) variable. While this approach introduces some duplication at present, it will ultimately enable us to consolidate how the IWYU tool is executed, allowing for a choice between using the `iwyu_tool.py` script or CMake's built-in functionality.

At this stage, only the headers for the `bitcoin_crypto` target have been updated, and the CI will now treat any future IWYU warnings as errors.

Based on https://github.com/bitcoin/bitcoin/pull/31306.

2024-12-12 10:45 UTC, hebasto commented
Rebased.

2025-01-20 10:28 UTC, hebasto commented on ci/test/03_test_script.sh
> +  bash -c "cmake --build . ${MAKEJOBS} --clean-first --target ${TARGETS_WITH_FORCED_IWYU}"
> Could make sense to run this before the `tee /tmp/iwyu_ci.out` command, given that it errors?

This approach allows a developer to check other includes, not only the first one that fails.

> Maybe a `-- --keep-going` could be used for a slightly better output, if stuff is possibly missing?

I'm not sure what criteria you are using to define "better" in this case. The current branch adds one more config/build round details to the CI log and the following:
1. A message like the one posted in the PR description, if there is a warning.
2. Nothing, if there are no warnings.

2025-05-22 16:37 UTC, hebasto commented on ci/test/03_test_script.sh
> +  bash -c "cmake --build . ${MAKEJOBS} --clean-first --target ${TARGETS_WITH_FORCED_IWYU}"
> I think the message you posted in the PR description only shows a single error in a single dependency. I am wondering what happens if there is more than one error in different targets, possibly ones where cmake will never get to print the second error.

[Here](https://api.cirrus-ci.com/v1/task/5614699137466368/logs/ci.log) multiple error are reported.

2025-05-27 14:09 UTC, hebasto commented on ci/test/03_test_script.sh
> +  bash -c "cmake --build . ${MAKEJOBS} --clean-first --target ${TARGETS_WITH_FORCED_IWYU}"
1. The [change](https://github.com/bitcoin/bitcoin/compare/16c69e927cccc1e93beaa10c621afd6a8f422e6c..0c3c7d07599d0086d5151949a69ffc12b6166d19) touches 8 files. The modification in `src/crypto/siphash.h` is a no-op from IWYU's perspective.

2. CMake integrates the IWYU into the compilation step. Therefore, it reports an error for each object file individually.
However, the diagnostic output includes both headers and the source file:
```
[12:32:50.757] Warning: include-what-you-use reported diagnostics:
[12:32:50.757] 
[12:32:50.757] /ci_container_base/src/crypto/poly1305.h should add these lines:
[12:32:50.757] #include <span>      // for span
[12:32:50.757] 
[12:32:50.757] /ci_container_base/src/crypto/poly1305.h should remove these lines:
[12:32:50.757] 
[12:32:50.757] The full include-list for /ci_container_base/src/crypto/poly1305.h:
[12:32:50.757] #include <span.h>    // for UCharCast
[12:32:50.757] #include <stdint.h>  // for uint32_t
[12:32:50.757] #include <cassert>   // for assert
[12:32:50.757] #include <cstddef>   // for byte, size_t
[12:32:50.757] #include <span>      // for span
[12:32:50.757] ---
[12:32:50.757] 
[12:32:50.757] (/ci_container_base/src/crypto/poly1305.cpp has correct #includes/fwd-decls)
[12:32:50.757] 
[12:32:50.757] gmake[3]: *** [src/crypto/CMakeFiles/bitcoin_crypto.dir/build.make:188: src/crypto/CMakeFiles/bitcoin_crypto.dir/poly1305.cpp.o] Error 1
```

I can see all [changes](https://github.com/bitcoin/bitcoin/compare/16c69e927cccc1e93beaa10c621afd6a8f422e6c..0c3c7d07599d0086d5151949a69ffc12b6166d19), except the unrelated one, in the IWYU diagnostics. Am I missing anything in particular?

2025-05-28 12:09 UTC, maflcko reviewed
left some comments

2025-05-29 11:28 UTC, fanquake commented
> While this approach introduces some duplication at present, it will ultimately enable us to consolidate how the IWYU tool is executed, allowing for a choice between using the iwyu_tool.py script or CMake's built-in functionality.

Reading the PR description, it's not really clear why we'd need to retain using both tools? Either the CMake built-in should be better in some way, or at least equivalent in functionality, in which case we should just switch to using it?

2025-05-29 11:29 UTC, fanquake commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<emmintrin.h>", private, "<immintrin.h>", public ] },
Same here?

2025-05-29 17:12 UTC, hebasto commented on ci/test/03_test_script.sh
> +  bash -c "cmake --build . ${MAKEJOBS} --clean-first --target ${TARGETS_WITH_FORCED_IWYU}"
> Not sure if this is a valid concern, but an alternative approach would be to just call `git diff` below on the `TARGETS_WITH_FORCED_IWYU` folders (not targets). Then exit, when the diff is not empty?

Thanks! [Reworked](https://github.com/bitcoin/bitcoin/pull/31308#issuecomment-2920042768).

2025-06-02 15:28 UTC, maflcko reviewed
review ACK e9143a68f34f350d7fa4405389222da4dfa9a394 🎰

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: review ACK e9143a68f34f350d7fa4405389222da4dfa9a394 🎰
fi/hWQQqCAdnfz0F4yhi8AMYjYOl79DanoxZsC6Am2gCztYYNf/izs+yQjc7oCt14KzsBJkAcSvQN6BVRVniAQ==
```

</details>

2025-06-02 15:28 UTC, maflcko commented on ci/test/03_test_script.sh
> +  git --no-pager diff -- ':(exclude)src/leveldb/db/db_impl.cc'
nit in the first commit: Seems odd to exclude this without explanation in the code. Would an alternative be:

```diff
diff --git a/ci/test/03_test_script.sh b/ci/test/03_test_script.sh
index 3394c50b8b..db3d3d64de 100755
--- a/ci/test/03_test_script.sh
+++ b/ci/test/03_test_script.sh
@@ -33,7 +33,9 @@ echo "=== BEGIN env ==="
 env
 echo "=== END env ==="
 
-(
+if [ "$RUN_TIDY" != "true" ]; then
+  # The tidy task has no UB detector, so skip the patch there to avoid issues
+  # later on in the task.
   # compact->outputs[i].file_size is uninitialized memory, so reading it is UB.
   # The statistic bytes_written is only used for logging, which is disabled in
   # CI, so as a temporary minimal fix to work around UB and CI failures, leave
@@ -54,7 +56,7 @@ echo "=== END env ==="
    mutex_.Lock();
    stats_[compact->compaction->level() + 1].Add(stats);
 EOF
-)
+fi
 
 if [ "$RUN_FUZZ_TESTS" = "true" ]; then
   export DIR_FUZZ_IN=${DIR_QA_ASSETS}/fuzz_corpora/
```

?

2025-06-02 15:28 UTC, maflcko commented on ci/test/03_test_script.sh
> -  cd "${BASE_ROOT_DIR}/src"
q in the first commit: This is no longer needed, because cmake uses absolute paths in the compile commands?

2025-06-02 15:28 UTC, maflcko commented on src/index/coinstatsindex.h
> +#include <primitives/block.h>
5cd4bbb67c3c7e651b3d83c77ffb936f60a2c496: Looks wrong. This should be a fwd dcl

2025-06-02 15:28 UTC, maflcko commented on src/crypto/hmac_sha256.cpp
>  #include <string.h>
nit in eb4be21cc0bb93b0931a61b2af342946f09a9721: Wrong section and should be cstring to avoid confusing with string.h in our repo?

2025-06-02 15:28 UTC, maflcko commented on src/crypto/hmac_sha512.cpp
>  #include <string.h>
same...

2025-06-02 15:28 UTC, maflcko commented on ci/test/03_test_script.sh
> +  git diff --quiet -- ':(exclude)src/leveldb/db/db_impl.cc' || { git --no-pager diff -- ':(exclude)src/leveldb/db/db_impl.cc'; exit 1; }
e9143a68f34f350d7fa4405389222da4dfa9a394: Why not just `git diff --no-pager --exit-code`?

2025-06-02 16:40 UTC, fanquake commented on ci/test/03_test_script.sh
> +  # The tidy task has no UB detector, so skip the patch there to avoid issues
> to avoid issues

What issues? Do I understand correctly, that if we land the patch in the subtree, this will just break again?

2025-06-02 16:41 UTC, hebasto commented on ci/test/03_test_script.sh
> +  # The tidy task has no UB detector, so skip the patch there to avoid issues
The following `git diff` prints this patch even IWYU did not apply any modifications.

2025-06-02 16:42 UTC, fanquake commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<tuple>", public, "<array>", public ] },
?

2025-06-02 16:43 UTC, fanquake commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<emmintrin.h>", private, "<immintrin.h>", public ] },
?

2025-06-02 17:03 UTC, hebasto commented on ci/test/03_test_script.sh
> +  git --no-pager diff -- ':(exclude)src/leveldb/db/db_impl.cc'
Thanks! Reworked.

2025-06-02 17:03 UTC, hebasto commented on src/index/coinstatsindex.h
> +#include <primitives/block.h>
Sure! Fixed.

2025-06-02 17:04 UTC, hebasto commented on src/crypto/hmac_sha256.cpp
>  #include <string.h>
Thanks! Fixed.

2025-06-02 17:04 UTC, hebasto commented on src/crypto/hmac_sha512.cpp
>  #include <string.h>
Thanks! Fixed.

2025-06-02 17:04 UTC, hebasto commented on ci/test/03_test_script.sh
> +  git diff --quiet -- ':(exclude)src/leveldb/db/db_impl.cc' || { git --no-pager diff -- ':(exclude)src/leveldb/db/db_impl.cc'; exit 1; }
Thanks! Reworked.

2025-06-02 17:14 UTC, fanquake commented on ci/test/03_test_script.sh
> +  # The tidy task has no UB detector, so skip the patch there to avoid issues
Ok, so no an issue if we actually land the patch (and remove the related code in the CI).

2025-06-02 17:15 UTC, jonatack reviewed
Concept ACK

2025-06-02 17:15 UTC, jonatack commented on ci/test/03_test_script.sh
> +  # TODO: Consider enforcing IWYU across the entire codebase.
Last I looked, enforcing this across the codebase may require large changes at one time in some areas to untangle everything.

2025-06-02 18:16 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<emmintrin.h>", private, "<immintrin.h>", public ] },
As they form part of Intel’s API, these headers are not covered by IWYU’s mappings for the standard libraries, and in my view, they do not fall within the scope of the IWYU repository.

2025-06-02 18:16 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<emmintrin.h>", private, "<immintrin.h>", public ] },
As they form part of Intel’s API, these headers are not covered by IWYU’s mappings for the standard libraries, and in my view, they do not fall within the scope of the IWYU repository.

2025-06-02 18:20 UTC, fanquake commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<emmintrin.h>", private, "<immintrin.h>", public ] },
> they do not fall within the scope of the IWYU repository.

IWYU has mappings for intrinsics though?
 - https://github.com/include-what-you-use/include-what-you-use/blob/master/gcc-8.intrinsics.imp
 - https://github.com/include-what-you-use/include-what-you-use/blob/master/clang-6.intrinsics.imp

2025-06-03 06:31 UTC, maflcko commented
only changes are addressed nits

re-review ACK 92ac4c8353c612549afbd68a4db6dfb04cc41dad 🍞

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: re-review ACK 92ac4c8353c612549afbd68a4db6dfb04cc41dad 🍞
xIdLhdsyYvMngIMaaDU1eiGvAgl1sm5eg7S5tdSf7AK3oTKfKIk7+1i0wvSWq5ufz6uOZG6iKygZDc7JHnCqCg==
```

</details>

2025-06-03 06:33 UTC, maflcko commented on ci/test/03_test_script.sh
> +  # The tidy task has no UB detector, so skip the patch there to avoid issues
Doesn't matter much, but the comment could also say "... so skip the patch because it is not needed and to avoid issues ...".

2025-06-03 14:01 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<tuple>", public, "<array>", public ] },
> Is there an issue open for this upstream?

Please see https://github.com/include-what-you-use/include-what-you-use/issues/1763.

2025-06-03 14:02 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<tuple>", public, "<array>", public ] },
The issue could be worked around in different ways. For example, by using an OS image with the default GCC >= 14.

2025-06-03 15:09 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<emmintrin.h>", private, "<immintrin.h>", public ] },
> Same here?

Please see https://github.com/include-what-you-use/include-what-you-use/issues/1764.

2025-06-03 16:08 UTC, hebasto commented on ci/test/03_test_script.sh
> -  cd "${BASE_ROOT_DIR}/src"
I've tested the pre-CMake master branch @ 80f00cafdeef0600fa1a5e906686720786c2336c, and this line wasn't necessary there.

2025-06-03 16:55 UTC, hebasto commented
Rebased.

All feedback from @maflcko and @fanquake has been addressed.

The IWYU-related workarounds are now documented with references to the relevant upstream issues.

2025-06-03 16:55 UTC, hebasto commented on ci/test/03_test_script.sh
> +  # The tidy task has no UB detector, so skip the patch there to avoid issues
> Doesn't matter much, but the comment could also say "... so skip the patch because it is not needed and to avoid issues ...".

Thanks! [Adjusted](https://github.com/bitcoin/bitcoin/pull/31308#issuecomment-2936303614).

2025-06-03 16:56 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<tuple>", public, "<array>", public ] },
[Reworked](https://github.com/bitcoin/bitcoin/pull/31308#issuecomment-2936303614) into a local pragma.

2025-06-04 06:47 UTC, maflcko commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<iterator>", public, "<utility>", public ] },
I don't think this is right. This can lead to missing includes:

```
bash-5.2# cat map.imp 
[
  { include: [ "<iterator>", public, "<utility>", public ] },
]
bash-5.2# cat repr.cpp 
#include <utility>
#include <iterator>

void A(){
	int a{};
	int b{std::move(a)};
	auto* it{&b};
	std::advance(it,0);
}
bash-5.2# include-what-you-use  -Xiwyu --mapping_file=map.imp repr.cpp 

repr.cpp should add these lines:

repr.cpp should remove these lines:
- #include <iterator>  // lines 2-2

The full include-list for repr.cpp:
#include <utility>  // for move, advance
---
bash-5.2# vim repr.cpp # remove iterator include
bash-5.2# include-what-you-use  -Xiwyu --mapping_file=map.imp repr.cpp 
repr.cpp:8:7: error: no member named 'advance' in namespace 'std'
    8 |         std::advance(it,0);
      |         ~~~~~^
```

The correct fix is to just add the includes iwyu is asking for

2025-06-04 06:49 UTC, maflcko commented on src/crypto/hex_base.cpp
> +// IWYU pragma: no_include <tuple>
I don't think this is right. Can't this lead to missing the tuple include when it is required in the future?

The correct fix is to just add the includes iwyu is asking for

2025-06-07 09:45 UTC, maflcko commented
lgtm, except for the two missing includes

re-ACK ec42fb489a7eabed4dec155c6655d36114fa67ba 👜

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: re-ACK ec42fb489a7eabed4dec155c6655d36114fa67ba 👜
FEGC/u3sOGwaQIusYwFrEp5xYc5la53gzpRtrrSaUlHqwWAcpeIzsyPV2yxGl8A7HQezMFSpBdLyeqSk7dACAw==
```

</details>

2025-06-17 17:08 UTC, maflcko commented on src/index/txindex.cpp
> +#include <fcntl.h>
This will need to go through the wrapper header, no?


```
src/compat/compat.h:#include <fcntl.h>       // IWYU pragma: export
```

Even better would be to use the more correct `cstdio` include.

2025-07-11 14:22 UTC, hebasto commented
Rebased.

@maflcko 

Thank you for the review! Your feedback has been addressed.

2025-07-11 14:22 UTC, hebasto commented on src/index/txindex.cpp
> +#include <fcntl.h>
Sure. [Reworked](https://github.com/bitcoin/bitcoin/pull/31308#issuecomment-3062529488).

2025-07-11 14:23 UTC, hebasto commented on src/crypto/hex_base.cpp
> +// IWYU pragma: no_include <tuple>
Thanks! [Updated](https://github.com/bitcoin/bitcoin/pull/31308#issuecomment-3062529488).

2025-07-11 14:23 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { include: [ "<iterator>", public, "<utility>", public ] },
Thanks! [Updated](https://github.com/bitcoin/bitcoin/pull/31308#issuecomment-3062529488).

2025-07-14 11:57 UTC, fanquake requested changes
This makes the CI dependant on being run on x86_64; the tidy job will no-longer pass when run on aarch64.

2025-07-14 12:18 UTC, maflcko commented
may be good to fix the aarch64 ci. Otherwise:

re-ACK bfbf7de389649f848dffe23be6727df715648b01 🏖

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: re-ACK bfbf7de389649f848dffe23be6727df715648b01 🏖
n66Unsx6c1Vu6Scpy871MQQIyXO4stQjbv/K4mjljYVqrYRkWt1hzxtnkVXvywtkwJFyeLW3pQCHEsKnvW+NBg==
```

</details>

2025-07-14 12:19 UTC, fanquake commented
> may be good to fix the aarch64 ci.

How would you fix it, given IWYU is giving different recommendations, based on the architecture?

2025-07-14 12:37 UTC, ryanofsky commented
> How would you fix it, given IWYU is giving different recommendations, based on the architecture?

Easiest way is to use `// IWYU pragma: keep` when IWYU incorrectly tells you to remove an include that should be kept and `// IWYU pragma: no_include` when it tells you to add an include that shouldn't be added. The pragmas will suppress errors on whatever platform is complaining and be ignored on other platforms. I dealt with this recently in https://github.com/bitcoin-core/libmultiprocess/commit/0d5f1faae5da26205ef9563cb9cc157725ab9479

2025-07-14 12:49 UTC, maflcko commented
> `// IWYU pragma: no_include` when it tells you to add an include that shouldn't be added. The pragmas will suppress errors on whatever platform is complaining and be ignored on other platforms.

I wouldn't recommend to do this, because this can lead to missing includes, as also mentioned earlier in https://github.com/bitcoin/bitcoin/pull/31308#discussion_r2125793574. The correct fix is to just add the includes iwyu is asking for.

2025-07-14 13:05 UTC, ryanofsky commented
> The correct fix is to just add the includes iwyu is asking for.

I think this is about cases where IWYU on one platform asks you to add (or remove) an include, and IWYU on other platform asks you to remove (or add) the same include. A reasonable way to resolve these is to decide which IWYU is correct and add pragmas to silence the other IWYU. Other ways to resolve it could be to define mappings, or submit fixes upstream, or choose a single platform to be your canonical IWYU platform and ignore other platforms.

I think pragmas are helpful because they make it easier to enable IWYU more places and allow developers to run it locally, but they do have downsides because they can become incorrect over time and be a maintenance burden. Many approaches seem reasonable and I don't have a recommendation, this was just a suggestion.

2025-07-14 13:09 UTC, maflcko commented
Yes, the keep pragma seems useful, but I personally wouldn't recommend using the no_include pragma in this context

2025-07-17 15:07 UTC, hebasto commented
> may be good to fix the aarch64 ci.

Fixed.

2025-07-17 15:29 UTC, maflcko commented
review ACK ec37e518682ca6c7272d1eeaea099dc9b3375e41 🌙

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: review ACK ec37e518682ca6c7272d1eeaea099dc9b3375e41 🌙
EjPGTyq0n0WQ15FhnkFUC4zbt8c7vpF2xwZ9xoKGZoHNODb4bbMv5amsaljEr1puiAij6EN74zIKaF/6EHHLBA==
```

</details>

2025-07-17 15:30 UTC, fanquake commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  # libc symbols.
Has this been upstreamed / why is it needed?

2025-07-17 15:34 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  # libc symbols.
> Has this been upstreamed...

Not yet.

> why is it needed?

Otherwise, IWYU will suggest platform-specific headers instead of the standard one provided by the C library.

2025-08-14 11:24 UTC, hebasto commented
Rebased to resolve a conflict with the merged #33116.

2025-09-01 08:10 UTC, maflcko commented
Only change is rebase.

re-ACK a4fa7b97aa73b177ea416388acfc2aba25c79e19 🚇

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: re-ACK a4fa7b97aa73b177ea416388acfc2aba25c79e19 🚇
bRpP979EiaRYiW2rw/6yGXWljok64xDpRXXHzbyfOOiBMN+ftjgfNugbR0of17pwNoW+kOx/kZxEgzXhOkWhAQ==
```

</details>

2025-09-01 08:10 UTC, maflcko commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  # libc symbols.
seems fine to upstream this, but this shouldn't be a blocker, i'd say

2025-09-01 09:26 UTC, maflcko commented on ci/test/03_test_script.sh
> +  git --no-pager diff --exit-code
Could check the return code and print something to clarify this is an error, similar to the tidy error above:

```sh
    echo "^^^ ⚠️ Failure generated from clang-tidy"
    false
```

2025-09-01 10:34 UTC, hebasto commented
Rebased and addressed @maflcko's [comment](https://github.com/bitcoin/bitcoin/pull/31308#discussion_r2313401875).

2025-09-01 10:34 UTC, hebasto commented on ci/test/03_test_script.sh
> +  git --no-pager diff --exit-code
Thanks! [Done](https://github.com/bitcoin/bitcoin/pull/31308#issuecomment-3241834149).

2025-09-01 11:57 UTC, maflcko commented
re-ACK 1d49346465de8edec85bb2d498859b4fbc346935 📶

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: re-ACK 1d49346465de8edec85bb2d498859b4fbc346935 📶
2MJL8GNQQjZb4FgXDGl0qh67OHXwPeXDDWmlxONQfHs9hQfrdiETVAw+8nZ0IE+8qrWtyPqrQqZ7OXa2ZYcBCg==
```

</details>

2025-09-01 20:45 UTC, l0rinc reviewed
Concept ACK

2025-09-01 20:45 UTC, l0rinc commented on ci/test/03_test_script.sh
> +if [ "$RUN_TIDY" != "true" ]; then
could we fix this in https://github.com/bitcoin-core/leveldb-subtree/pulls instead?
I have opened https://github.com/bitcoin-core/leveldb-subtree/pull/56 (I'm also fine with doing it in a different PR, just wanted to give the possibility to solve it in a cleaner way)

2025-09-01 20:45 UTC, l0rinc commented on src/index/base.h
> +struct BlockRef;
not sure I understand why this was needed, but I haven't run the scripts, just tried to find out locally

2025-09-02 06:31 UTC, maflcko commented on ci/test/03_test_script.sh
> +if [ "$RUN_TIDY" != "true" ]; then
No objection, but I am not sure we should diverge the subtree for a test-only patch. Also, the patch is pre-existing, so it seems a bit unrelated to this pull.

Ideally, Google would fix the UB in some way or another, and then we can pull whatever their fix was, but that shouldn't be a blocker here.

2025-09-02 06:31 UTC, maflcko commented on src/index/base.h
> +struct BlockRef;
fwd decls are slimmer than a full include, and often sufficient, for example when the header only uses the types as pointers or references. IWYU will suggest them sometimes, when possible.

2025-09-02 06:51 UTC, l0rinc commented on ci/test/03_test_script.sh
> +if [ "$RUN_TIDY" != "true" ]; then
The main leveledb repo doesn't even compile for the past 8 months, not sure why we would wait for them. But as I mentioned, I don't mind doing it after the PR, just seems cleaner if we didn't need to change this section again.

2025-09-02 06:52 UTC, l0rinc commented on src/index/base.h
> +struct BlockRef;
I know, that wasn't my question. But I'll figure it out next, feel free to resolve it.

2025-09-02 08:01 UTC, hebasto commented on src/index/base.h
> +struct BlockRef;
https://github.com/bitcoin/bitcoin/blob/1d49346465de8edec85bb2d498859b4fbc346935/src/index/base.h#L128

2025-09-04 18:03 UTC, hebasto commented
@ryanofsky 

You may be interested in these changes.

2025-09-08 15:46 UTC, ryanofsky approved these changes
Code review ACK 1d49346465de8edec85bb2d498859b4fbc346935. Makes sense to try IWYU in a few directories like this to see how stable it is and make sure it won't cause problems.

2025-09-08 15:46 UTC, ryanofsky commented on ci/test/03_test_script.sh
> +  # needed and to avoid issues later on in the task.
In commit "ci: Do not patch `leveldb` to workaround UB in "tidy" CI job" (b495e2dc95db42e3219720f5beeb6c136d067a4a)

Could the comment clarify what the issues are? Even just a hint or pointer to more information would be helpful. if they are IWYU issues, maybe just say "to avoid IWYU issues"

2025-09-08 15:46 UTC, ryanofsky commented on ci/test/03_test_script.sh
> +  jq --arg patterns "$FILES_WITH_FORCED_IWYU" 'map(select(.file | test($patterns)))' "${BASE_BUILD_DIR}/compile_commands.json" > "${BASE_BUILD_DIR}/compile_commands_iwyu_errors.json"
In commit "ci, iwyu: Treat warnings as errors for specific directories" (1d49346465de8edec85bb2d498859b4fbc346935)

I think it'd be a little better to called this ENFORCED_IWYU instead of FORCED_IWYU. Both make sense but former seems a little clearer.

2025-09-08 15:56 UTC, fanquake commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  # libc symbols.
> Not yet.

Is there anything blocking that? It'd be good if we'd atleast report issues upstream, before adding workarounds (with little-to-no documentation).

2025-09-08 16:54 UTC, hebasto commented on ci/test/03_test_script.sh
> +  # needed and to avoid issues later on in the task.
Thanks! I’ve updated the comment to note that the tidy task uses `git diff`, which would be affected by the patch if it weren’t skipped.

2025-09-08 16:54 UTC, hebasto commented on ci/test/03_test_script.sh
> +  jq --arg patterns "$FILES_WITH_FORCED_IWYU" 'map(select(.file | test($patterns)))' "${BASE_BUILD_DIR}/compile_commands.json" > "${BASE_BUILD_DIR}/compile_commands_iwyu_errors.json"
Thanks! Taken.

2025-09-08 16:55 UTC, hebasto commented
The feedback from @ryanofsky has been addressed.

2025-09-08 17:16 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  # libc symbols.
An upstream issue: https://github.com/include-what-you-use/include-what-you-use/issues/1809.

2025-09-08 17:26 UTC, ryanofsky approved these changes
Code review ACK d03d861cb6d81f90f3b4add2db3dbdc0bf95a0ef. Just fixing up comment and changing variable name since last review. Thanks for the updates!

2025-09-08 17:26 UTC, ryanofsky commented on ci/test/03_test_script.sh
> +  # needed and to avoid issues later on in the task.
re: https://github.com/bitcoin/bitcoin/pull/31308#discussion_r2330818442

In commit "ci: Do not patch `leveldb` to workaround UB in "tidy" CI job" (b7248ee2462a26418f0ef1e0a0f04950269d37aa)

Thanks, with new comment I think I understand why this is needed now. This is fine as is, but in case you do want to update it, I think a change like following would make the link between `git diff` and the UB detector clearer:

```diff
--- a/ci/test/03_test_script.sh
+++ b/ci/test/03_test_script.sh
@@ -41,9 +41,10 @@ echo "=== BEGIN env ==="
 env
 echo "=== END env ==="
 
+# Don't apply patches in the tidy job, because it relies on the `git diff`
+# command to detect IWYU errors. It is safe to skip this patch in the tidy job
+# because it doesn't run a UB detector.
 if [ "$RUN_TIDY" != "true" ]; then
-  # The tidy task uses `git diff` command and has no UB detector, so skip the
-  # patch because it is not needed and to avoid issues later on in the task.
   # compact->outputs[i].file_size is uninitialized memory, so reading it is UB.
   # The statistic bytes_written is only used for logging, which is disabled in
   # CI, so as a temporary minimal fix to work around UB and CI failures, leave
```

Another approach to working with `git diff` might be to use `git apply --index` instead `patch -p1` to apply this patch, so the patch will just not be included in `git diff` output.

2025-09-08 17:33 UTC, hebasto commented on ci/test/03_test_script.sh
> +  # needed and to avoid issues later on in the task.
Thanks! The comments have been reworked per your suggestion.

2025-09-09 10:29 UTC, hebasto commented
Rebased due to a conflict with https://github.com/bitcoin/bitcoin/pull/30469.

2025-09-09 13:31 UTC, sipa commented
Concept ACK

2025-09-09 13:35 UTC, ryanofsky approved these changes
Code review ACK 02d2b5a11c921ef71c971ee80eb3dfbc75c8cb0d. Just rebased and update tidy patch comment again since last review

2025-10-22 11:23 UTC, maflcko commented
Only small changes:

* Rebase
* one minimal doc fixup
* one minimal symbol rename in the ci script

re-ACK 02d2b5a11c921ef71c971ee80eb3dfbc75c8cb0d 💮

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: re-ACK 02d2b5a11c921ef71c971ee80eb3dfbc75c8cb0d 💮
i6k+tDtPP9iRHFh7vqSwsKvwZGIQPp3PvB3+nmXymPC4FluFds6Qg6B9l4gWYCS6MeOr/J1S2JKTnHlyd54bAg==
```

</details>

2025-10-22 13:04 UTC, maflcko commented
Looks like the CI re-run passed after one month, so it seems reasonable stable

2025-10-25 16:37 UTC, maflcko commented
rfm?

2025-10-28 11:12 UTC, willcl-ark approved these changes
ACK 02d2b5a11c921ef71c971ee80eb3dfbc75c8cb0d

I like the approach here of enforcing as-we-go through the codebase. Something similar was done recently in `nixpkgs` [with their `treefmt` formatter](https://youtu.be/3m_cvSuOB-Y?si=GuuU3aC7IR_FKB6q).

Tested that this worked locally by modifying the test script and running.

<details>
<summary>Details</summary>

```bash
#!/usr/bin/env bash
set -x

BASE_ROOT_DIR="$HOME/src/core/bitcoin"
BASE_BUILD_DIR="$BASE_ROOT_DIR/build"
FILES_WITH_ENFORCED_IWYU="$HOME/src/core/bitcoin/src/(crypto|index)/.*\\.cpp"

jq --arg patterns "$FILES_WITH_ENFORCED_IWYU" 'map(select(.file | test($patterns)))' "${BASE_BUILD_DIR}/compile_commands.json" > "${BASE_BUILD_DIR}/compile_commands_iwyu_errors.json"
jq --arg patterns "$FILES_WITH_ENFORCED_IWYU" 'map(select(.file | test($patterns) | not))' "${BASE_BUILD_DIR}/compile_commands.json" > "${BASE_BUILD_DIR}/compile_commands_iwyu_warnings.json"

cd "${BASE_ROOT_DIR}" || exit

run_iwyu() {
    mv "${BASE_BUILD_DIR}/$1" "${BASE_BUILD_DIR}/compile_commands.json"
    "$(command -v iwyu_tool.py)" \
         -p "${BASE_BUILD_DIR}" "${MAKEJOBS}" \
         -- -Xiwyu --cxx17ns -Xiwyu --mapping_file="${BASE_ROOT_DIR}/contrib/devtools/iwyu/bitcoin.core.imp" \
         -Xiwyu --max_line_length=160 \
         2>&1 | tee /tmp/iwyu_ci.out
    "$(command -v fix_includes.py)" --nosafe_headers < /tmp/iwyu_ci.out
}

run_iwyu "compile_commands_iwyu_errors.json"
if ! ( git --no-pager diff --exit-code ); then
    echo "^^^ ⚠️ Failure generated from IWYU"
    false
fi

run_iwyu "compile_commands_iwyu_warnings.json"
git --no-pager diff
```

</details>

2025-10-28 11:52 UTC, merged

2026-07-04 11:29 UTC, hebasto commented on contrib/devtools/iwyu/bitcoin.core.imp
> +  { "include": [ "<tmmintrin.h>", "private", "<immintrin.h>", "public" ] },
This has been addressed upstream in https://github.com/include-what-you-use/include-what-you-use/commit/6a113bcf7017b8d5b7b4358c8a0fb16be96ad39a.