cluster mempool: introduce TxGraph
bitcoin/bitcoin pull request #31363
Opened 2024-11-24 15:59 UTC by sipa

Part of cluster mempool: #30289.

### 1. Overview

This introduces the `TxGraph` class, which encapsulates knowledge about the (effective) fees, sizes, and dependencies between all mempool transactions, but nothing else. In particular, it lacks knowledge about `CTransaction`, inputs, outputs, txids, wtxids, prioritization, validatity, policy rules, and a lot more. Being restricted to just those aspects of the mempool makes the behavior very easy to fully specify (ignoring the actual linearizations produced), and write simulation-based tests for (which are included in this PR).

### 2. Interface

The interface can be largely categorized into:
* Mutation functions:
  * `AddTransaction` (add a new transaction with specified feerate, and get a `Ref` object back to identify it).
  * `RemoveTransaction` (given a `Ref` object, remove the transaction).
  * `AddDependency` (given two `Ref` objects, add a dependency between them).
  * `SetTransactionFee` (modify the fee associated with a Ref object).
* Inspector functions:
  * `GetAncestors` (get the ancestor set in the form of `Ref*` pointers)
  * `GetAncestorsUnion` (like above, but for the union of ancestors of multiple `Ref*` pointers)
  * `GetDescendants` (get the descendant set in the form of `Ref*` pointers)
  * `GetDescendantsUnion` (like above, but for the union of ancestors of multiple `Ref*` pointers)
  * `GetCluster` (get the connected component set in the form of `Ref*` pointers, in the order they would be mined).
  * `GetIndividualFeerate` (get the feerate of a transaction)
  * `GetChunkFeerate` (get the mining score of a transaction)
  * `CountDistinctClusters` (count the number of distinct clusters a list of `Ref`s belong to)
* Staging functions:
  * `StartStaging` (make all future mutations operate on a proposed transaction graph)
  * `CommitStaging` (apply all the changes that are staged)
  * `AbortStaging` (discard all the changes that are staged)
* Miscellaneous functions:
  * `DoWork` (do queued-up computations now, so that future operations are fast)

This `TxGraph::Ref` type used as a "handle" on transactions in the graph can be inherited from, and the idea is that in the full cluster mempool implementation (#28676, after it is rebased on this), `CTxMempoolEntry` will inherit from it, and all actually used Ref objects will be `CTxMempoolEntry`s. With that, the mempool code can just cast any `Ref*` returned by txgraph to `CTxMempoolEntry*`.

### 3. Implementation

Internally the graph data is kept in clustered form (partitioned into connected components), for which linearizations are maintained and updated as needed using the `cluster_linearize.h` algorithms under the hood, but this is hidden from the users of this class. Implementation-wise, mutations are generally applied lazily, appending to queues of to-be-removed transactions and to-be-added dependencies, so they can be batched for higher performance. Inspectors will generally only evaluate as much as is needed to answer queries, with roughly 5 levels of processing to go to fully instantiated and acceptable cluster linearizations, in order:
1. `ApplyRemovals` (take batches of to-be-removed transactions and translate them to "holes" in the corresponding Clusters/DepGraphs).
2. `SplitAll` (creating holes in Clusters may cause them to break apart into smaller connected components, so make turn them into separate Clusters/linearizations).
3. `GroupClusters` (figure out which Clusters will need to be combined in order to add requested to-be-added dependencies, as these may span clusters).
4. `ApplyDependencies` (actually merge Clusters as precomputed by `GroupClusters`, and add the dependencies between them).
5. `MakeAcceptable` (perform the LIMO linearization algorithm on Clusters to make sure their linearizations are acceptable).

### 4. Future work

This is only an initial version of TxGraph, and some functionality is missing before #28676 can be rebased on top of it:
* The ability to get comparative feerate diagrams before/after for the set of staged changes (to evaluate RBF incentive-compatibility).
* Mining interface (ability to iterate transactions quickly in mining score order) (see #31444).
* Eviction interface (reverse of mining order, plus memory usage accounting) (see #31444).
* Ability to fix oversizedness of clusters (before or after committing) - this is needed for reorgs where aborting/rejecting the change just is not an option (see #31553).
* Interface for controlling how much effort is spent on LIMO. In this PR it is hardcoded.

Then there are further improvements possible which would not block other work:
* Making Cluster a virtual class with different implementations based on transaction count (which could dramatically reduce memory usage, as most Clusters are just a single transaction, for which the current implementation is overkill).
* The ability to have background thread(s) for improving cluster linearizations.

2024-12-05 14:22 UTC, jonatack commented
Concept ACK

2024-12-24 19:33 UTC, ismaelsadeeq reviewed
Concept ACK


> GetChunkFeerate (get the mining score of a transaction)


From reading the description and skimming through the code, IIUC `TxGraph` encapsulates knowledge about fees and sizes but lacks knowledge about prioritization. This implies that the fee it uses is the effective fee, not the modified fee that includes prioritization.

How are we accounting for the real mining score of a  `Ref` without that prioritization knowledge? The current mining algorithm uses the modified ancestor fee to calculate the mining score.

Could you clarify how prioritization will be handled post-cluster mempool?

2024-12-24 20:37 UTC, ismaelsadeeq commented
Thank you for clarifying. Reading 'lacks knowledge about prioritization' led me to infer that.
But I see now you are talking about `mapDeltas`

2025-01-22 20:51 UTC, Pumpkin1234567812 approved these changes

2025-01-23 17:35 UTC, instagibbs commented
> Unlinking only happens when the calling code destroys a Ref. Currently, unlinking can happen either through Ref destruction, or through TxGraph::Cleanup() (which unlinks anything not appearing in the graph anymore).

this would result in:
1) exists
1) removed
2) unlinked + destroyed

as the three possible states?

2025-01-27 21:22 UTC, ismaelsadeeq commented on src/txgraph.h
> +static constexpr unsigned MAX_CLUSTER_COUNT_LIMIT{64};
In  "txgraph: (feature) make max cluster count configurable and "oversize" state" 15da6fdd19813a08bf9571147f97e22b5390ecf9

Maybe comment why 64 selected and how having limit above this will hurt the node/miner? fwiw we have seen clusters with size more than 64 in the past https://bitcoincore.reviews/25038, but I think it's not a regular occurrence.

2025-02-10 22:02 UTC, ismaelsadeeq reviewed
Code review to 741a6a8c4d851cb10ecee810a09187bcbfa5af4c

2025-02-10 22:08 UTC, ismaelsadeeq commented on src/test/fuzz/cluster_linearize.cpp
> +        // Find which element in todo that corresponds to.
Yes this is much better now!
Thanks

2025-02-12 16:22 UTC, instagibbs reviewed
reviewed up to "txgraph: (feature) add initial version" 781c15bfca1ebaffe7b634196e19144f5ab10a50 , basically all nits at this point, logic all makes sense

One question I had coming up is use of `Assume()`, there is a number of places that `Assume()` is used, then subsequently may result in UB or weird behavior. In a few spots I gave suggestions but was wondering if there is thinking behind doing more (or Assert'ing) or not to handle that in release builds.

2025-02-12 21:15 UTC, ismaelsadeeq commented on src/txgraph.cpp
> +            linchunking.MarkDone(linchunking.GetChunk(0).transactions);
In  "txgraph: (tests) add internal sanity check function" 741a6a8c4d851cb10ecee810a09187bcbfa5af4c

Should we also compare that the list of transactions in chunk 0 matches `m_linearization` subset from from previous hit of the conditional statement to `lin_pos`?

2025-02-13 19:19 UTC, ismaelsadeeq commented on src/test/fuzz/txgraph.cpp
> +        auto choice = provider.ConsumeIntegralInRange<size_t>(0, choices - 1);
Makes sense thanks.

2025-02-13 19:20 UTC, ismaelsadeeq commented on src/test/fuzz/txgraph.cpp
> +    /** Function to pick any Ref (in sim real, sim.removed, or empty). */
nit: There is still one remaining in line 180.

2025-02-13 19:20 UTC, ismaelsadeeq commented on src/test/fuzz/txgraph.cpp
> +    LIMITED_WHILE(provider.remaining_bytes() > 0, 200) {
Yeah something like that that 

In most of the fuzz test in `src/test/fuzz/cluster_linearize.cpp` you provided a really nice description , which is just an overview of what the test is going to do before jumping to the instructions.

Here we just jump into the instructions without that context.

But this is nitty, you can ignore this comment and resolve.

2025-02-13 19:21 UTC, ismaelsadeeq commented on src/txgraph.cpp
> +            linchunking.MarkDone(linchunking.GetChunk(0).transactions);
Yeah I was thinking something like

<details>
<summary>diff</summary>

```diff
diff --git a/src/txgraph.cpp b/src/txgraph.cpp
index afaa46e6326..a9b3e446d26 100644
--- a/src/txgraph.cpp
+++ b/src/txgraph.cpp
@@ -1143,6 +1143,7 @@ void Cluster::SanityCheck(const TxGraphImpl& graph) const
 
     // Verify m_linearization.
     SetType m_done;
+    SetType last_chunk;
     assert(m_depgraph.IsAcyclic());
     for (auto lin_pos : m_linearization) {
         assert(lin_pos < m_mapping.size());
@@ -1155,9 +1156,12 @@ void Cluster::SanityCheck(const TxGraphImpl& graph) const
         assert(entry.m_locator.index == lin_pos);
         // Check linearization position and chunk feerate.
         if (!linchunking.GetChunk(0).transactions[lin_pos]) {
+            assert(linchunking.GetChunk(0).transactions == last_chunk);
+            last_chunk = SetType();
             linchunking.MarkDone(linchunking.GetChunk(0).transactions);
         }
         assert(entry.m_chunk_feerate == linchunking.GetChunk(0).feerate);
+        last_chunk.Set(lin_pos);
         // If this Cluster has an acceptable quality level, its chunks must be connected.
         if (m_quality == QualityLevel::ACCEPTABLE || m_quality == QualityLevel::OPTIMAL) {
             assert(m_depgraph.IsConnected(linchunking.GetChunk(0).transactions));
```
</details>

2025-02-13 22:28 UTC, ismaelsadeeq commented on src/txgraph.cpp
> +            Updated(graph);
I see this now 👍🏾

2025-02-14 17:36 UTC, ismaelsadeeq reviewed
Code Review e19bbc328236f64716034277857951184309cd14

It seems to me that this is designed with the flexibility to accommodate more levels, which explains the use of `std::vector` for `ClusterSet`

If yes then current approach is perfect else would it be better for `TxGraph` to maintain a `std::array` of two `ClusterSet? `main` and `staging and store their indexes in `TxGraph` as enums? This way, `Cluster` would only need to maintain that enum.  

In `ClusterSet`, we could introduce a boolean to indicate whether a set is active or not.  

The `main` set could always remain active, while `staging` would be flexible and toggleable.  

Thus, when we start staging, we can simply mark the back array as active, and once done, clear the back array and mark it as inactive.  

I believe this approach would reduce Assumes since we explicitly know we can only have two ClusterSet's.

2025-02-14 17:36 UTC, ismaelsadeeq commented on src/txgraph.cpp
>      auto& entry = m_entries[idx];
```suggestion
    Assume (level - MAX_LEVELS - 1);
    auto& entry = m_entries[idx];
```

2025-02-14 17:36 UTC, ismaelsadeeq commented on src/txgraph.cpp
> +            out.push_back(entry.m_locator[m_level - 1].cluster);
Should be set to avoid duplicates, will prevent de duplicating later on?

2025-02-18 20:07 UTC, ismaelsadeeq commented on src/txgraph.cpp
> +            out.push_back(entry.m_locator[m_level - 1].cluster);
Agreed, I calculated recently.
This is better.

The constant factors for GetDistinctClusters implementation using vector and then sorting is also better 👍🏾
Please resolve.

2025-02-20 22:08 UTC, Pumpkin1234567812 commented
ApplyDependencies(0);

2025-02-21 17:07 UTC, instagibbs reviewed
Looking good 11135464c5c3aef1ce8d2823120467a522ce2c87

I just have conceptual issues with what PostLinerize is guaranteeing us beyond what is explicitly stated in the header file. 

Pile of nits/questions otherwise

2025-02-21 22:25 UTC, sipa reviewed
Addressed most comments. I will address the `PostLinearize` related ones later.

2025-02-21 23:35 UTC, instagibbs commented on src/txgraph.h
> +    /** Like GetDescendants, but return the Refs for all transactions in the union of the provided
major reading comprehension issues it seems

2025-02-21 23:38 UTC, instagibbs commented on src/txgraph.cpp
> +        /** Which entries were removed in this ClusterSet (so they can be wiped on abort). */
yes, thanks

2025-02-21 23:57 UTC, instagibbs commented on src/txgraph.cpp
> +        // now avoids doing doable work later.
hah, was my first guess that I doubted :)

2025-02-22 00:01 UTC, instagibbs commented on src/txgraph.cpp
> +        m_entries[idx].m_locator[stage_level].SetMissing();
saw the updated comment/code in SanityCheck, makes sense

2025-02-22 00:02 UTC, instagibbs commented
verified changes, just waiting on further PostLinearization commentary

via `git range-diff master 11135464c5c3aef1ce8d2823120467a522ce2c87 d5abb86439e79d4adfbfbd46f833268bbca0bf6e`

2025-02-26 00:48 UTC, yancyribbens commented on src/cluster_linearize.h
> +            auto to_swap = linearization[len - 1 - (j - 1)];
The comment ` // j cannot be 0 here;` implies this should be `j != 0` instead of `j > 0`.  Since it's unsigned `j != 0` is also correct.

2025-02-27 19:01 UTC, instagibbs commented on src/txgraph.cpp
> +    // If the cluster was NEEDS_SPLIT_OPTIMAL, and we're thus going to produce OPTIMAL clusters, we
Update from offline conversation: This was a confusion about what we're calling "optimal". The splits clusters are already optimal in the sense of the diagram check, but not minimal or fully connected. PostLinearization makes sure that all chunks are connected/minimal.

Perhaps a rewording of this section to make it abundantly clear?

2025-03-03 15:54 UTC, instagibbs commented on src/txgraph.cpp
> +    // If the cluster was NEEDS_SPLIT_OPTIMAL, and we're thus going to produce OPTIMAL clusters, we
Also, as discussed offline, this seems like an easy scenario to write a fuzz test for as described above ^

2025-03-04 17:09 UTC, instagibbs commented
ACK 72a97c0a07ea6e5a95ab37c8d95e1ea02cff8e92

With the weaker claims in the code re:PostLinearization, it works for me, and obviates the need for an additional harness test.

`git range-diff master d5abb86439e79d4adfbfbd46f833268bbca0bf6e 72a97c0a07ea6e5a95ab37c8d95e1ea02cff8e92`

2025-03-06 20:29 UTC, ismaelsadeeq approved these changes
Code review ACK 72a97c0a07ea6e5a95ab37c8d95e1ea02cff8e92 🛸 

I've reviewed each commit and also looked at how the interface is being used by `CTxMemPool` in the big PR

2025-03-17 17:30 UTC, ajtowns reviewed
This seems fairly difficult to review -- there's a lot of mostly implicit background in what TxGraph does and why it does it that way, as evidenced by both the description in this PR and in the [review club](https://bitcoincore.reviews/31363).

When I started typing this comment, I was wondering if maybe it would make sense to make the commits here into more of a gentle introduction to TxGraph, rather than one commit that does everything, then optimisations. But I don't really think that approach would survive subsequent modifications to the code very well. Likewise for just adding more comments to the code.

Alternatively, I wonder if it would be helpful both for new devs and debugging to expose the TxGraph API as a python module, possibly with additional debugging handles so that you can examine internal state? I could imagine an interactive python notebook that allows you to interact with a real TxGraph being a useful experimental tool for learning/writing mempool code and also being something that could perhaps be reasonably maintained. [Here's](https://github.com/ajtowns/bitcoin/commits/202503-txgraph-python/) a rough take at what that might look like. It's using boost-python, which seems reasonable, but doesn't seem super friendly to pure-virtual classes (hence the tedious wrapper class) ~~or move-only objects (hence AddTransaction being wrapped via a constructor)~~. (EDIT: add link for "here's"; EDIT2: converting the `vector<Ref*>` stuff to python made the move-only Ref stuff irrelevant; the wrapper class isn't quite so tedious any more either really)

Comments below are mostly a bunch of nits/observations while familiarising myself with the code, feel free to ignore.

2025-03-18 18:03 UTC, ajtowns reviewed
Preliminary ACK 72a97c0a07ea6e5a95ab37c8d95e1ea02cff8e92

I think it's okay to merge this code:
 * as of this PR, it isn't actually used, so should not introduce bugs immediately
 * the fuzz testing is pretty good, so there should not be any catastrophic bugs even if it were used
 * while maybe the design could be improved, that can be done incrementally after it's merged
 * I'm reasonably confident I understand what's going on and can help find/fix bugs/problems if they occur
 * I think the design and implementation are a good step forward for implementing cluster mempool

On the other hand, calling this "preliminary" as:
 * I'm not yet confident that I could maintain this code if its authors all suddenly vanished
 * I'm a bit concerned that to contribute to mempool code you might need to be a triple expert -- C++, bitcoin, and industrial optimisation theory; not a show stopper, but as further PRs progress I'd like to gain confidence either that the optimisation parts can be safely treated as a very stable black box, or (ideally and) that we can reasonably onboard people to understand how the internals of the black box work.

2025-03-18 18:28 UTC, ismaelsadeeq commented on src/txgraph.cpp
> +    std::vector<ClusterSet> m_clustersets;
Curious to know this contrived use case, I also think it's a bit of an overkill in a previous comment https://github.com/bitcoin/bitcoin/pull/31363#pullrequestreview-2618143580, but @sipa made a compelling argument for it https://github.com/bitcoin/bitcoin/pull/31363#issuecomment-2666866811

2025-03-19 09:31 UTC, ajtowns commented on src/txgraph.cpp
> +    std::vector<ClusterSet> m_clustersets;
I think `StartStaging()` gets a bit simpler if you know that it can only be called with `m_clustersets.size()==1`:

```c++
 void TxGraphImpl::StartStaging() noexcept
 {
+    Assume(m_clustersets.size() == 1);  // vs < MAX_LEVELS
+    SplitAll(0); // vs m_clustersets.size() - 1
+    ApplyDependencies(0); // ditto
     m_clustersets.emplace_back();
+    auto& stage = m_clustersets[1]; // vs m_clustersets.back()
+    auto& main = m_clustersets[0]; // vs *(m_clustersets.rbegin() + 1);
     ...
```

That's the only use of `m_clustersets.rbegin()`, the remaining API of m_clustersets seems to be:

```c++
    class MainStageClusterSets
    {
    private:
        std::vector<ClusterSet> cs;

    public:
        MainStageClusterSets()
        {
            cs.reserve(MAX_LEVELS);
            cs.emplace_back();
        }

        bool UnfinishedTodo() const {
            for (auto& clusterset : cs) {
                if (!clusterset.m_deps_to_add.empty()) return true;
                if (!clusterset.m_to_remove.empty()) return true;
                if (!clusterset.m_removed.empty()) return true;
            }
            return false;
        }

        const ClusterSet& operator[](size_t i) const { return cs[i]; }
        ClusterSet& operator[](size_t i) { return cs[i]; }
        ClusterSet& back() { return cs.back(); }
        size_t size() const { return cs.size(); }

        void emplace_back() { cs.emplace_back(); }
        void pop_back() { cs.pop_back(); }
    };
    MainStageClusterSets m_clustersets;
```

which seem pretty straightforward to switch to a main/optional-stage model. Doing some renaming would make sense if so (emplace_back/pop_back to add/remove_staging; back to work maybe; size to has_staging maybe; maybe a templated ForEach() accepting a lambda taking a ClusterSet for iteration).

2025-03-19 12:10 UTC, ajtowns commented
> * However, it's also the case that if the compiler can prove a statement is side-effect free, it can optimize the call away in non-debug builds.

That makes sense. Might be a good idea to update doc/developer-notes.md pointing out that use case? It currently says:

> * `Assume` should be used to document assumptions when program execution can
>   safely continue even if the assumption is violated.

2025-03-19 21:34 UTC, sipa reviewed
Big change: `std::vector<ClusterSet>` is gone, replaced by `m_main_clusterset` and `m_staging_clusterset`.
* New helper functions `GetTopLevel()`, `GetSpecifiedLevel()`, `GetClusterSet()` made this fairly easy to do.
* Simplifications resulted in `ClearLocator`, `GetConflicts`, `PullIn`, `MakeTransactionsMissing`, `StartStaging`, `CommitStaging`, `ExtractCluster`.
* `CopyTo` was renamed to `CopyToStaging`.
* `LevelDown` was renamed to `MoveToMain`.
* `MakeTransactionsMissing` was renamed to `MakeStagingTransactionsMissing`.

Other changes:
* Various comments
* `Ref` objects are now allowed to outlive `TxGraph`.
* `GetChunkFeerate` (and its testing, plus `Entry::m_chunk_feerate` maintenance) was moved to a separate commit.

2025-03-20 00:34 UTC, ajtowns commented on src/txgraph.h
> +    /** Remove the specified transaction. This is a no-op if the transaction was already removed.
Maybe it would be helpful to explain in the header that AddTransaction() creates a Ref, which you're then expected to assign/move into your own container, which may be a subclass containing even more info about the tx, and then that serves as a permanent handle, even as the txgraph gets rearranged internally and that it's deleted from the graph either with RemoveTransaction explicitly or implicitly by destructing the Ref? Essentially expanding the "Data type used to reference transactions within a TxGraph" comment that's already there to be a bit more ELI5 maybe?

If you create an empty Ref (ie, construct it directly, not via AddTransaction) is there any way to associate that Ref with a TxGraph or is it forever useless as a Ref? Would it make any sense to have an AddTransaction variant that takes a Ref& argument rather than returning a new Ref? I guess equivalently, is an empty Ref useful for anything other than tests? Maybe "Non-empty Refs can only be created using AddTx" should be more explicit and say "You want to use AddTransaction() rather than constructing a Ref directly".

2025-03-20 00:41 UTC, ajtowns commented on src/txgraph.cpp
> +class TxGraphImpl;
Sounds like this is something that can be reconsidered when we get a PR that introduces variant Clusters then. Mark as resolved for now?

2025-03-20 06:50 UTC, ajtowns commented on src/txgraph.h
> +    virtual bool IsOversized(bool main_only = false) noexcept = 0;
If I'm understanding right, this seem like it makes `IsOversized()` largely unfixable by the client -- so the only reasonable strategy I can see is to do:

```c++
    StartStaging();
    // change transactions
    if (IsOversized() || otherwise_undesirable()) {
        AbortStaging();
    } else {
        CommitStaging();`
    }
```

That's a very reasonable strategy of course, so this isn't a complaint! Just that if so, it seems like it should be documented a bit more clearly?  I wonder a bit if `CommitStaging()` should have an `Assume(G_FUZZING || !m_oversized)` or something...

(In particular, if you ever end up with the main graph being oversized, I don't see how you can even discover which txs are contributing to the oversized-ness in order to remove them -- `GetCluster(ref)` will fail the `m_deps_to_add.empty()` check I think, so you can't use that, and if you do you'll just get a subset of the actual cluster that is within limits; same with `GetDescendants`)

2025-03-20 07:08 UTC, ajtowns commented on src/txgraph.h
> +    virtual bool IsOversized(bool main_only = false) noexcept = 0;
see also the TODO item

> * Ability to inspect the would-be-constructed clusters (so they can be "fixed" if they violate policy rules, as opposed to just accepted/rejected, before applying - this is needed for reorgs which are not optional).

2025-03-20 07:10 UTC, ajtowns commented
(conflicts with just merged #31519, Span to std::span)

2025-03-20 08:38 UTC, ajtowns commented on src/txgraph.h
> +    virtual bool IsOversized(bool main_only = false) noexcept = 0;
:+1: I think it makes sense for TxGraph to take care of all the topology checks and feerate comparison decisions, which includes finding the best txs (block building), finding the worst txs (eviction) and finding good subsets when limits would otherwise be exceeded (reorgs, "rbf"/"carve out" cases maybe). So this doesn't feel like a design break at all to me, but rather pretty much exactly parallel to `GetWorstMainChunk()` -- "here's a bunch of txs that you want to remove".

2025-03-20 09:01 UTC, ajtowns reviewed
ReACK 63b8f96e67f9ad649070a231532d48fb6c3573e4 . Needs a rebase anyway though.

The main/staging changes read better to me fwiw. The level stuff in the locators could be ungeneralised as well I suppose, but that doesn't seem likely to be much of an improvement.

2025-03-20 09:53 UTC, ismaelsadeeq commented on src/txgraph.h
> +     *  The transactions will be returned in a topologically-valid order of acceptable quality.
"acceptable quality" is more than just a topologically valid order.
It refers to a linearization that may not be optimal but is the best we can achieve for that cluster within resource limitations.

2025-03-20 11:23 UTC, ismaelsadeeq commented
> That makes sense. Might be a good idea to update doc/developer-notes.md pointing out that use case? It currently says:

Done in #32100

2025-03-20 13:40 UTC, instagibbs commented on src/txgraph.h
> +    virtual bool IsOversized(bool main_only = false) noexcept = 0;
> so the only reasonable strategy I can see is to do:

The other reason to not follow this strategy, aside from reorgs, is "kindred eviction", where the caller is in charge of gathering sufficient information try to get back to an un-oversized state in the staging area, using non-oversized main stage information as a guiding tool.

2025-03-20 14:55 UTC, instagibbs commented
reviewed via `git range-diff master 72a97c0a07ea6e5a95ab37c8d95e1ea02cff8e92 1601906941fa559ebbee7898453fa77f4606ad38`

> Ref objects are now allowed to outlive TxGraph

Can this get surfaced in the fuzz coverage with something that would previously fail?

2025-03-21 16:02 UTC, ajtowns commented
ReACK 1601906941fa559ebbee7898453fa77f4606ad38

2025-03-21 16:30 UTC, instagibbs commented
reACK 1601906941fa559ebbee7898453fa77f4606ad38

> Dropping the TxGraphImpl destructor body then causes segfaults (rather than a nice assertion failure).

Right, I got myself turned around on this thinking it was harder to achieve. I'd suggest adding coverage here or in a quick follow-up.

2025-03-22 00:06 UTC, sipa reviewed
Changes:
* Did a big pass through the interface documentation in txgraph.h
* Moved the support for Refs outliving TxGraph to a separate commit, and added the test suggested in https://github.com/bitcoin/bitcoin/pull/31363#issuecomment-2742606528.
* Some smaller things listed below:

2025-03-24 11:54 UTC, ismaelsadeeq reviewed
re-ACK 41b4434fed169570ce0976c6e58db0d4a9614aaa  after https://github.com/bitcoin/bitcoin/pull/31363#pullrequestreview-2707582068

The new doc is better, and it's explicit that ref's can outlive their txgraph.

2025-03-24 11:54 UTC, ismaelsadeeq commented on src/txgraph.cpp
> +void TxGraphImpl::DoWork() noexcept
As it is right now, it's unused in the main PR.

I've been thinking when `DoWork` can be called in the mempool lifecycle and whether that would make a difference because everything is done lazily and we only apply staged changes when we want to get the current state. (specifically a scenario where after some lazy additions it cheap to just call `DoWork` and not wait until we want to get a state.)


Maybe after trimming due to a reorg, after multiple additions of transactions e.g loading new mempool.

2025-03-24 13:07 UTC, ajtowns requested changes
range-diff review of 41b4434fed169570ce0976c6e58db0d4a9614aaa

Good to see it's now explicit which calls you can make on an oversized txgraph.

2025-03-24 13:07 UTC, ajtowns commented on src/txgraph.h
> +    virtual bool Exists(const Ref& arg, bool main_only = false) noexcept = 0;
Looks like comments for Exists/GetMainChunkFeerate/GetIndividualFeerate have been mixed up (in the "Add staging support" commit, I think)

2025-03-24 14:59 UTC, instagibbs commented
reACK b2ea3656481b4196acaf6a1b5f3949a9ba4cf48f

nice doc improvements

`git range-diff master 1601906941fa559ebbee7898453fa77f4606ad38 b2ea3656481b4196acaf6a1b5f3949a9ba4cf48f`

2025-03-26 18:25 UTC, ajtowns commented
reACK b2ea3656481b4196acaf6a1b5f3949a9ba4cf48f

2025-03-26 20:11 UTC, ismaelsadeeq reviewed
reACK  b2ea3656481b4196acaf6a1b5f3949a9ba4cf48f 🚀

2025-03-26 21:06 UTC, glozow reviewed
ACK b2ea3656481

Reviewed the structure to convince myself this approach makes sense to support the features required, and reviewed the `SimTxGraph` + differential fuzzer in closer detail. I haven't read through all the `TxGraphImpl` functions but did some manual mutation testing.

2025-03-26 21:13 UTC, glozow commented on src/cluster_linearize.h
> +            // elem needs to be place before anymore, and place_before would be empty.
nit 0aa874a357865dd4768091f26dff238e66fb8d83
```suggestion
            // elem needs to be placed before anymore, and place_before would be empty.
```

2025-03-26 21:43 UTC, merged

2025-03-27 14:31 UTC, glozow commented on src/test/fuzz/txgraph.cpp
> +            } else if (top_sim.removed.size() < 100 && command-- == 0) {
I was thinking that if all the transactions are descended from this tx, you'd add all of them to `to_remove` here. So if you started out with 99, you can end up with a lot more than 100 afterward. You wouldn't do more removals afterward, but you'd have more than 100.