lint: Move assertion linter into lint runner
bitcoin/bitcoin pull request #31435
Opened 2024-12-06 11:26 UTC by maflcko

On failure, this makes the output more consistent with the other linters. Each failure will be marked with an '⚠️ ' emoji and explanation, making it easier to spot.

Also, add --line-number to the filesystem linter.

Also, add newlines after each failing check, to visually separate different failures from each other.

Can be reviewed with:
`--color-moved=dimmed-zebra --color-moved-ws=ignore-all-space`

2024-12-12 18:59 UTC, hodlinator requested changes
Concept ACK faa0b09a4b6267399a214d7f5beaf4dfe9f3976c

Good call on integrating more of the comments from the old linter into the error messages.

Tested adding `assert()`/`CHECK_NONFATAL()`/`BOOST_ASSERT()` with expected results in *src/rpc/mining.cpp*.

Might as well avoid introducing the typo (see inline comment). That's the only light blocker for me.

---

nit: The whitespace changes are in the right direction, but I think they are still unclear with the current change.

### faa0b09a4b6267399a214d7f5beaf4dfe9f3976c

```
...
All checks passed!
src/rpc/mining.cpp:127:    BOOST_ASSERT(true);
src/rpc/mining.cpp:137:    BOOST_ASSERT(true);

^^^
BOOST_ASSERT must be replaced with Assert, BOOST_REQUIRE, or BOOST_CHECK to avoid an unessecary
include of the boost/assert.hpp dependency.
            
^---- ⚠️ Failure generated from lint check 'boost_assert'!
Check that boost assertions are not used


src/crc32c in HEAD currently refers to tree 454691a9b89ee8b9e1f71a48a7398edba49c3805
...
```

### With additional changes (7973da4cb9b7a6eaae7dfc1d3d681d9b75c5a226)

- No empty line separating errors and arrows ("^^^"). Keeping them together signals they are related.
- No empty line separating error message and linter failure line (not completely empty, it contains several spaces left over from Rust multi-line literal).
- Keep the linter description on the same line as the failure line, otherwise it looks like it's a description for the following step.
```
...
All checks passed!
src/rpc/mining.cpp:127:    BOOST_ASSERT(true);
src/rpc/mining.cpp:137:    BOOST_ASSERT(true);
^^^
BOOST_ASSERT must be replaced with Assert, BOOST_REQUIRE, or BOOST_CHECK to avoid an unessecary
include of the boost/assert.hpp dependency.
^---- ⚠️ Failure generated from lint check 'boost_assert' (Check that boost assertions are not used)!


src/crc32c in HEAD currently refers to tree 454691a9b89ee8b9e1f71a48a7398edba49c3805
...
```

2024-12-13 16:35 UTC, hodlinator approved these changes
ACK fcf0e873e3194158d718db107386f94f8e8e4a16

2024-12-13 16:35 UTC, hodlinator commented on test/lint/test_runner/src/main.rs
> +BOOST_ASSERT must be replaced with Assert, BOOST_REQUIRE, or BOOST_CHECK to avoid an unessecary
Glad you liked my commit! Unfortunately I'm currently operating on an unfamiliar keyboard, slipping my own "ĺint"-typo into the commit message. :upside_down_face:  Feel free to replace with e8f0e6efaf555a7d17bdb118464bd572bd5f3933, or not.

2024-12-13 16:49 UTC, hodlinator approved these changes
re-ACK e8f0e6efaf555a7d17bdb118464bd572bd5f3933

2024-12-24 02:00 UTC, davidgumberg commented
crACK https://github.com/bitcoin/bitcoin/commit/e8f0e6efaf555a7d17bdb118464bd572bd5f3933


Tested manually with the following diff:

<details>

<summary>git diff</summary>

```diff
diff --git a/src/coins.cpp b/src/coins.cpp
index 24a102b0bc..000068c7e2 100644
--- a/src/coins.cpp
+++ b/src/coins.cpp
@@ -21,6 +21,7 @@ std::unique_ptr<CCoinsViewCursor> CCoinsView::Cursor() const { return nullptr; }

 bool CCoinsView::HaveCoin(const COutPoint &outpoint) const
 {
+    BOOST_ASSERT(1);
     return GetCoin(outpoint).has_value();
 }

diff --git a/src/rpc/mining.cpp b/src/rpc/mining.cpp
index 60828c1711..0199be420b 100644
--- a/src/rpc/mining.cpp
+++ b/src/rpc/mining.cpp
@@ -133,6 +133,7 @@ static RPCHelpMan getnetworkhashps()

 static bool GenerateBlock(ChainstateManager& chainman, Mining& miner, CBlock&& block, uint64_t& max_tries, std::shared_ptr<const CBlock>& block_out, bool process_new_block)
 {
+    assert(1);
     block_out.reset();
     block.hashMerkleRoot = BlockMerkleRoot(block);

diff --git a/src/rpc/server_util.cpp b/src/rpc/server_util.cpp
index 0387cbb8e2..16b9827e13 100644
--- a/src/rpc/server_util.cpp
+++ b/src/rpc/server_util.cpp
@@ -20,6 +20,7 @@ using node::NodeContext;

 NodeContext& EnsureAnyNodeContext(const std::any& context)
 {
+    Assert(true);
     auto node_context = util::AnyPtr<NodeContext>(context);
     if (!node_context) {
         throw JSONRPCError(RPC_INTERNAL_ERROR, "Node context not found");
diff --git a/src/wallet/rpc/coins.cpp b/src/wallet/rpc/coins.cpp
index f1430a3c60..079c9e0644 100644
--- a/src/wallet/rpc/coins.cpp
+++ b/src/wallet/rpc/coins.cpp
@@ -467,6 +467,7 @@ RPCHelpMan getbalances()
     const auto bal = GetBalance(wallet);
     UniValue balances{UniValue::VOBJ};
     {
+        Assume(0);
         UniValue balances_mine{UniValue::VOBJ};
         balances_mine.pushKV("trusted", ValueFromAmount(bal.m_mine_trusted));
         balances_mine.pushKV("untrusted_pending", ValueFromAmount(bal.m_mine_untrusted_pending));
```

</details>

and got the expected output:

```console
$ cargo run -- --lint=rpc_assert --lint=boost_assert
src/rpc/mining.cpp:136:    assert(1);
src/rpc/server_util.cpp:23:    Assert(true);
src/wallet/rpc/coins.cpp:470:        Assume(0);
^^^
CHECK_NONFATAL(condition) or NONFATAL_UNREACHABLE should be used instead of assert for RPC code.

Aborting the whole process is undesirable for RPC code. So nonfatal
checks should be used over assert. See: src/util/check.h
^---- ⚠️  Failure generated from lint check 'rpc_assert' (Check that fatal assertions are not used in RPC code)!


src/coins.cpp:24:    BOOST_ASSERT(1);
^^^
BOOST_ASSERT must be replaced with Assert, BOOST_REQUIRE, or BOOST_CHECK to avoid an unnecessary
include of the boost/assert.hpp dependency.
^---- ⚠️  Failure generated from lint check 'boost_assert' (Check that boost assertions are not used)!
```

2025-01-05 20:19 UTC, TheCharlatan approved these changes
ACK e8f0e6efaf555a7d17bdb118464bd572bd5f3933

2025-01-06 13:35 UTC, merged