test: Embed univalue json tests in binary
bitcoin/bitcoin pull request #31542
Opened 2024-12-19 19:36 UTC by maflcko

All other benchmarks and tests have their data embedded, except for the univalue json tests.

This is not only confusing, but also problematic, when the test binary is moved to a different system for testing, because one has to put the test files in the source dir that was used at compile-time.

Fix all issues by embedding them. Also, re-enable a disabled test. Also, fix an issue in the GenerateHeaderFromJson.cmake.

Requested in https://github.com/bitcoin/bitcoin/pull/31434/files#r1876000910

2024-12-19 20:12 UTC, TheCharlatan commented
Nice, Concept ACK

2024-12-19 20:18 UTC, hebasto commented
Concept ACK. Thank you for picking this up!

2024-12-19 22:03 UTC, TheCharlatan approved these changes
ACK fabda022536c7a000a575bbb05059d27d29b5cca

2024-12-20 07:45 UTC, hebasto reviewed
Approach ACK fabda022536c7a000a575bbb05059d27d29b5cca.

Related: https://github.com/bitcoin/bitcoin/pull/30901 improves handling of data files in build scripts.

2024-12-20 07:45 UTC, hebasto commented on src/univalue/CMakeLists.txt
> +  generate_header_from_json(data/base58_encode_decode.json)
Drop this one?

2024-12-20 07:45 UTC, hebasto commented on src/univalue/CMakeLists.txt
> +  generate_header_from_json(test/fail3.json)
nit: Reorder?

2024-12-20 07:45 UTC, hebasto commented on src/univalue/CMakeLists.txt
> +    test/unitester.cpp)
style nit: Follow surrounding style:
```suggestion
    test/unitester.cpp
  )
```
?

2024-12-20 09:57 UTC, hebasto approved these changes
ACK faf23a8d0328f288d64dd697de4efedbc6970531.

2024-12-20 11:14 UTC, TheCharlatan approved these changes
Nice improvements, Re-ACK faedcc5fdabc508aaade9b461e44ea3a6670f36b

2024-12-20 11:16 UTC, l0rinc requested changes
Thanks for the cleanup, please consider a few simplification and unification recommendations

2024-12-20 11:16 UTC, l0rinc commented on src/univalue/test/unitester.cpp
> +#define TEST_FILE(name) {#name, json_tests::name}
I understand why a macro is the smallest change to make `runtest` happy, but I think we can avoid that weird string parsing and introduce enums instead:
```C++
enum class TestType { Fail, Pass, RoundTrip };
```
and define the test as:
```C++
inline constexpr std::map<std::string_view, TestType> tests{
    {json_tests::fail1, TestType::Fail},
    {json_tests::fail2, TestType::Fail},
    {json_tests::fail3, TestType::Fail},
...
```
which could simplify `runtest` to:
```C++
static void runtest(std::string_view data, TestType type) {
    UniValue val;
    bool testResult = val.read(std::string{data});

    if (type == TestType::Fail) {
        assert(!testResult);
        return;
    }
    ...
```

2024-12-20 13:07 UTC, hebasto approved these changes
re-ACK faedcc5fdabc508aaade9b461e44ea3a6670f36b.

2024-12-20 13:39 UTC, l0rinc commented on cmake/script/GenerateHeaderFromJson.cmake
> +string(REGEX REPLACE "[^\n][^\n]" "char(0x\\0)," formatted_bytes "${formatted_bytes}")
Extracted to https://github.com/bitcoin/bitcoin/pull/31547 - pease resolve the comment

2024-12-20 13:42 UTC, l0rinc commented
ACK faedcc5fdabc508aaade9b461e44ea3a6670f36b

Avoiding file reads during test setup is a step forward in portability 👍 
We can continue the refactors in follow-up PRs.

2024-12-20 14:17 UTC, l0rinc commented
ACK faf7eac364fb7f421a649b483286ac8681d92b31

The changes since last ACK:  [simplify char casting](https://github.com/bitcoin/bitcoin/pull/31547) and reformat the affected sources.

2024-12-31 16:49 UTC, fjahr commented
tACK faf7eac364fb7f421a649b483286ac8681d92b31

Reviewed code and verified that tests are still running as intended.

2025-01-02 10:12 UTC, TheCharlatan approved these changes
Re-ACK faf7eac364fb7f421a649b483286ac8681d92b31

2025-01-02 10:51 UTC, hebasto approved these changes
Re-ACK faf7eac364fb7f421a649b483286ac8681d92b31. The commit, which modifies CMake scripts, has been replaced with the one from https://github.com/bitcoin/bitcoin/pull/31547, and a formatting commit has been added since my recent [review](https://github.com/bitcoin/bitcoin/pull/31542#pullrequestreview-2517189261).

2025-01-03 18:39 UTC, achow101 commented
ACK faf7eac364fb7f421a649b483286ac8681d92b31

2025-01-03 18:58 UTC, merged