[rpc] Fix transaction size comments and RPC help text.
bitcoin/bitcoin pull request #8747
Opened 2016-09-16 19:07 UTC by jonnynewbs

As part of BIP 141, transaction sizes have been replaced by virtual size (with witness data discounted) as the metric for measuring the fee rate of a transaction. RPC now returns the virtual size of the transaction instead of the serialized size. However, code comments and RPC help text have not been updated everywhere to reflect this change.

This PR fixes various comments and RPC help text.

2016-09-18 00:03 UTC, sdaftuar approved these changes

2016-09-18 15:57 UTC, MarcoFalke commented
utACK 2ff29a7

2016-09-19 14:43 UTC, laanwj approved these changes
utACK https://github.com/bitcoin/bitcoin/pull/8747/commits/2ff29a76766249ddc92ea210b16699dd705e0343

2016-09-20 00:06 UTC, luke-jr commented on src/rpc/blockchain.cpp
> +    return "    \"size\" : n,             (numeric) virtual transaction size as defined in BIP 141. This is different from actual serialized size for witness transactions as witness data is discounte
This is a bug. :(

2016-09-20 00:06 UTC, luke-jr commented on src/rpc/blockchain.cpp
> +            "  \"bytes\": xxxxx,              (numeric) Sum of all virtual transaction sizes as defined in BIP 141. Differs from actual serialized size because witness data is discounted\n"
This also shouldn't be virtual.

2016-09-20 00:07 UTC, luke-jr requested changes
The reasonable/expected behaviour in at least these cases is to give real sizes, not "virtual size" nonsense.

2016-09-20 07:25 UTC, jonasschnelli approved these changes

2016-09-20 12:39 UTC, jonnynewbs commented on src/rpc/blockchain.cpp
> +    return "    \"size\" : n,             (numeric) virtual transaction size as defined in BIP 141. This is different from actual serialized size for witness transactions as witness data is discounte
This commit updates the RPC help text to reflect what the function call actually returns. If you think there's a problem with the RPC function, I suggest you raise an issue against that code.

2016-09-20 12:39 UTC, jonnynewbs commented on src/rpc/blockchain.cpp
> +            "  \"bytes\": xxxxx,              (numeric) Sum of all virtual transaction sizes as defined in BIP 141. Differs from actual serialized size because witness data is discounted\n"
See above

2016-09-20 20:43 UTC, luke-jr commented on src/rpc/blockchain.cpp
> +    return "    \"size\" : n,             (numeric) virtual transaction size as defined in BIP 141. This is different from actual serialized size for witness transactions as witness data is discounte
Well, NACK changing documentation to match buggy behaviour rather than fixing the bug...

2016-09-20 21:20 UTC, sipa commented
I disagree this is a bug. Apart from miners, nobody should care about the
total serialized size.

2016-09-21 13:32 UTC, laanwj commented
@sipa so do you agree on this documentation change?

2016-09-21 13:50 UTC, sipa commented
@laanwj I agree with it, though there was some discussion in one of the former IRC meetings that we shouldn't call this virtual size.

2016-09-22 09:06 UTC, luke-jr commented
If we're not showing the size in bytes, then just get rid of the size/bytes fields and add weight...

2016-09-22 12:25 UTC, jonnynewbs commented
Removing fields from objects returned by RPC functions is a non-backwards compatible change, which may break clients using the API. I agree that adding weight may be useful for some users and we should consider extending the RPC return objects to include it. If you feel strongly about having weight returned RPC functions, let me know and I'll open a new PR.

This PR is simply to fix up the help text so it reflects what the function call is actually doing.

2016-09-22 14:25 UTC, TheBlueMatt commented
Strinctly speaking, this is wrong...BIP 141 defines virtual size as "Transaction weight / 4 (rounded up to nearest integer)." with weight being " Base transaction size * 3 + Total transaction size (ie. the same method as calculating Block weight from Base size and Total size).".

However, this method actually returns that iff sigops per byte of the tx is lower than sigops per byte of the block consensus rule. Not sure if it matters since that should be rare, but it is, strictly speaking, different.

2016-09-27 14:40 UTC, jnewbery commented
@TheBlueMatt - you're correct. The actual value returned will be higher than the virtual size if the sigsops per byte in the tx is greater the nBytesPerSigOp due to https://github.com/bitcoin/bitcoin/commit/ab942c15bd3854650afa810d7c22d7fd30d346c1.

I *could* expand the RPC text from:
```(numeric) Sum of all virtual transaction sizes as defined in BIP 141. Differs from actual serialized size because witness data is discounted\n"```
to
```(numeric) Sum of all virtual transaction sizes as defined in BIP 141. Differs from actual serialized size because witness data is discounted. If the sigsops per byte in the transaction is greater nBytesPerSigOp, then returns a size based on the cost of the sigops rather than the serialized size of the transaction.\n"```

I don't think that actually makes things clearer, but I'm happy to update the text if you think that's preferable.

2016-10-05 13:29 UTC, TheBlueMatt commented
Its relatively strange to me that it would be inconsistent with the BIP. If we want to keep it this way, I'd say changing the BIP is sufficient as the help text refers to that. Alternatively, we could change the return value to be consistent with the BIP. Either way, I agree, expanding the RPC help text is strange.

2016-11-16 09:52 UTC, laanwj commented
Closing this, as there seems to be strong disagreement about this and the discussion has bled out.

2016-11-16 13:31 UTC, morcos commented
@laanwj please don't close this.   I don't think anyone (other than possibly @luke-jr) disagrees that this is an clear improvement.  The existing help text is confusing and this is far more accurate.  @TheBlueMatt 's comments are a more obscure technical refinement, but I don't think meant as a blocker to merging this. 

I think its important that we make an effort to properly document and educate our users about how the software works.  The whole concept of "virtual size" is a bit unfortunate but I don't see any way around keeping it unless we want to radically change how people think about feerates.  We can't be held up from making clear improvements to the software just because one person vehemently disagrees.

utACK from me

2016-11-16 17:20 UTC, jnewbery commented
Travis appeared to fail because of an unrelated environment setup issue. I've rebased this PR which will kick off another travis run.

2016-11-17 05:46 UTC, bitcoinfees commented
There seems to be a conflict - `getrawmempool` defines "size" as the virtual size, whereas `getrawtransaction` defines it as the serialized size (and using "vsize" instead for virtual size).  This doc change helps to clarify the difference, but to avoid confusion perhaps the term "size" should be made to mean the same thing in all RPC calls.

Oh and in `getblock` RPC, "size" also refers to serialized size and not "weight / 4".

2016-11-17 12:45 UTC, jnewbery commented
@bitcoinfees - yes, I completely agree with everything you say, and that it's confusing that 'size' means different things in different RPCs.

I didn't make any functional changes to the API since there may be applications that rely on the current behaviour. This PR simply updates the self-documentation in the RPCs so that it accurately describes what is being returned.

Perhaps we should change those RPC definitions, but that's a discussion for another PR and I don't think it should block this documentation fix.

2016-11-17 13:08 UTC, luke-jr commented
It still doesn't make sense to document a bug rather than fixing it.

2016-11-17 13:27 UTC, morcos commented
@luke-jr but that is not the choice at hand.  The choice presented by this PR is to document the existing behavior or leave it improperly documented.  Choosing to document it does not preclude changing it in the future.  Although I think most of us do not consider it a bug.

I can't understand why this is even a question.  How can we argue against more clearly explaining to users what the behavior is?  We should always be willing to document existing behavior instead of stalling on that while arguing about whether to change the behavior.

2016-11-17 13:42 UTC, jnewbery commented
@luke-jr - I agree with @morcos. Nothing in this documentation fix precludes you from opening an issue or PR to change the API.

2016-12-07 14:31 UTC, morcos commented
@sipa @TheBlueMatt This PR has several ACK's (and @luke-jr's objection), but I think its held up from merging b/c lack of clear feedback from you two.  If you are OK with it could you say?

2016-12-07 20:01 UTC, sipa commented
ACK 2ddb53054579c70de061d95386e9a5a02255d53f

2016-12-08 07:16 UTC, paveljanik commented on src/rpc/mining.cpp
> +            "in BIP 141 (witness data is discounted)\n"
Dot at the end of sentence missing.

2016-12-08 17:05 UTC, jnewbery commented
Thanks @paveljanik . Comment fixed.

2016-12-09 06:09 UTC, paveljanik commented
ACK https://github.com/bitcoin/bitcoin/pull/8747/commits/d29505db22892548a5eca5567bf8acf4e950efea

2017-01-05 11:06 UTC, merged