[Doc] Add missing autogen to example builds
bitcoin/bitcoin pull request #8787
Opened 2016-09-22 03:18 UTC by AmirAbrams

The Windows cross-compile build examples are missing the `autogen.sh` step.  Without that step, `configure` doesn't exist and you get this error:
> `bash: ./configure: No such file or directory`

Using Ubuntu 16.04 64 bit.

2016-09-22 03:22 UTC, laanwj commented
ACK.

> Using Ubuntu 16.04 64 bit.

If you are cross-compiling from Ubuntu 16.04 I'd suggest reading #8732 #8653 #8730 #8511, there are serious current compatibility issues.

2016-09-22 03:23 UTC, luke-jr commented
configure comes with the source code packages. You should not be using git unless you are a developer.

2016-09-22 03:25 UTC, laanwj commented
But in practice most people following this guide seem to be cloning from git. No one uses the source tarball. Also IIRC we mention `autogen.sh` in all other places (such as build-unix.md).

It could ofc be added that it is optional.

2016-09-22 03:42 UTC, AmirAbrams commented
@luke-jr I always build from git but I am a developer and thought the document was intended for developers.  If not, then please close my PR but like @laanwj points out, build-osx.md and build-unix.md reference the autogen.sh step.  Maybe I can add an `if/fi` that checks for the configure file or explain the example is for source code packages?

2016-09-22 03:46 UTC, laanwj commented
> Maybe I can add an if/fi that checks for the configure file or explain the example is for source code packages?

Maybe just add a comment after it `# not required when building from tarball`. Adding a fi/if construction sounds like overkill.

2016-09-22 22:49 UTC, MarcoFalke commented on doc/build-windows.md
> +    ./autogen.sh && ./configure --prefix=`pwd`/depends/i686-w64-mingw32
Agree with @laanwj

2016-09-22 22:49 UTC, maflcko requested changes

2016-09-22 22:55 UTC, AmirAbrams commented
Okay, like this?
```
cd ..
./autogen.sh # not required when building from tarball
./configure --prefix=`pwd`/depends/i686-w64-mingw32
```
If you agree, I will make the change and squash into one commit.

2016-09-24 01:17 UTC, AmirAbrams commented
I made the corrections and squashed my commits.

2016-09-25 09:52 UTC, merged