Multiple Selection for peer and ban tables
bitcoin/bitcoin pull request #8874
Opened 2016-10-04 00:07 UTC by achow101

Allows multiple selection and action for the nodes in the peer and ban tables in the Debug Window.

Closes #8864

2016-10-04 03:12 UTC, fanquake commented
OS X screenshots:
Current
![before](https://cloud.githubusercontent.com/assets/863730/19061364/cbe04ede-8a22-11e6-8ecc-8abe6292a139.png)
8874
![after](https://cloud.githubusercontent.com/assets/863730/19061367/d28b206a-8a22-11e6-865b-f219bd5a4116.png)

When  multiple nodes are selected the dropdown menu should be "Nodes".

2016-10-04 05:06 UTC, paveljanik commented
... or you can change the text to "Disconnect" and "Ban for 1 hour". I think we should use consistent terminology here. The bookmark is called "Peers" and we use "node" here.

2016-10-04 05:17 UTC, luke-jr commented
Our peers are nodes. Different terms for different things. Peer is the relationship, node is the thing.

Truncating the menu items does seem like the simplest approach here, though.

2016-10-04 12:33 UTC, achow101 commented
I've just removed `Node` so that it says `Disconnect`, `Ban for ..`, and `Unban`

2016-10-05 02:37 UTC, laanwj commented
Probably need #8885 in first to be able to test this re:banning.

2016-10-05 03:32 UTC, laanwj commented
Have tested d651056
I've been unable to ban/kick multiple peers. Either with Ctrl-click or Shift-click. Is there some other trick?
Ubuntu 16.04, Qt reports as 5.5.1.
It seems like it allows multiple selection (e.g. two nodes can be selected for a fraction of a second) but always ends up selecting the last clicked node. Maybe some rogue event handler?

2016-10-05 03:45 UTC, achow101 commented
Click, hold, and move your mouse across multiple rows. That's what works. I haven't figured out Ctrl+click or Shift+click yet.

2016-10-05 04:54 UTC, achow101 commented
@laanwj 763cc02 should allow for multiple selection with Ctrl-click, shift-click, and click n' drag.

2016-10-08 15:15 UTC, jonasschnelli commented
Needs rebase.

2016-10-08 23:37 UTC, achow101 commented
rebased

2016-10-09 10:07 UTC, jonasschnelli requested changes
Tested a bit. Selecting multiple peers (with shift key or with the mouse) results in some of them getting deselected short after the selection.

2016-10-09 14:50 UTC, achow101 commented on src/qt/rpcconsole.cpp
> +        clearSelectedNode();
Done

2016-10-09 14:51 UTC, achow101 commented
I'm not sure why some of them get deselected. I noticed that too, but I can't figure out a reason for why that happens.

2016-10-19 01:18 UTC, rebroad commented
Can we use keyboard shortcuts for selecting as per GUI standards? I.e. hold down shift while using the a cursor up/down to select multiple, or using spacebar and cursor up/down to toggle whether a node is selected or not (once at least one node is selected)?

2016-10-19 01:34 UTC, achow101 commented
@rebroad It's whatever [`QAbstractItemView::ExtendedSelection`](http://doc.qt.io/qt-4.8/qabstractitemview.html#SelectionMode-enum) specifies

2016-11-08 07:43 UTC, jonasschnelli commented
@achow101: Are you planing to finalizing this? IMO there are still the issue with auto-deselecting rows.

2016-11-08 13:18 UTC, achow101 commented
@jonasschnelli Yes, I do plan on finishing this. However, I am having trouble with figuring out why there is auto-deselecting.

2016-11-08 13:52 UTC, achow101 commented
rebased.

I think I figured out why it was auto-deselecting. It loses the selection after the model is refresehed.

2016-11-08 15:42 UTC, achow101 commented
I think I fixed the problem.

2016-11-08 20:12 UTC, achow101 commented
Actually fixed it this time.

2016-11-08 20:42 UTC, paveljanik commented
ACK https://github.com/bitcoin/bitcoin/pull/8874/commits/1077577546334bc26daa3ab8580f24063a0b67c6

2016-11-09 10:05 UTC, laanwj commented
Seems to work well enough now. If there are still minor issues with selection they can be fixed later.
ACK 1077577

2016-11-09 10:05 UTC, merged

2016-11-09 10:18 UTC, jonasschnelli commented
Post merge ACK.