Add all standard TXO types to bitcoin-tx
bitcoin/bitcoin pull request #8883
Opened 2016-10-04 21:29 UTC by jnewbery

bitcoin-tx can currently create transactions with the following TXO types:

- Pay to Pub Key Hash
- null data (OP_RETURN)
- Pay to Script Hash

This PR enhances bitcoin-tx so all remaining standard TXO types can be created:

- Pay to Pub Key
- Multi-sig
    - bare multi-sig
    - multi-sig in Pay To Script Hash
    - multi-sig in Pay to Witness Script Hash
    - multi-sig in Pay to Witness Script Hash, wrapped in P2SH
- Pay to Witness Pub Key Hash
    - Pay to Witness Pub Key Hash, wrapped in P2SH
- Pay to Witness Script Hash
    - Pay to Witness Script Hash, wrapped in P2SH

The PR also includes new test cases for all tx types.

2016-10-05 07:10 UTC, fanquake commented
Windows builds are failing:
```
make[2]: Entering directory `/home/travis/build/bitcoin/bitcoin/build/src'
  CXX      bitcoin_tx-bitcoin-tx.o
../../src/bitcoin-tx.cpp: In function ‘void MutateTxAddOutMultiSig(CMutableTransaction&, const string&)’:
../../src/bitcoin-tx.cpp:309:5: error: ‘uint’ was not declared in this scope
     uint required = std::stoul(vStrInputParts[1]);
     ^
../../src/bitcoin-tx.cpp:309:10: error: expected ‘;’ before ‘required’
     uint required = std::stoul(vStrInputParts[1]);
          ^
../../src/bitcoin-tx.cpp:312:10: error: expected ‘;’ before ‘numkeys’
     uint numkeys = std::stoul(vStrInputParts[2]);
          ^
../../src/bitcoin-tx.cpp:315:33: error: ‘numkeys’ was not declared in this scope
     if (vStrInputParts.size() < numkeys + 3)
                                 ^
../../src/bitcoin-tx.cpp:318:9: error: ‘required’ was not declared in this scope
     if (required < 1 || required > 20 || numkeys < 1 || numkeys > 20 || numkeys < required)
         ^
../../src/bitcoin-tx.cpp:318:42: error: ‘numkeys’ was not declared in this scope
     if (required < 1 || required > 20 || numkeys < 1 || numkeys > 20 || numkeys < required)
                                          ^
../../src/bitcoin-tx.cpp:324:14: error: expected ‘;’ before ‘pos’
     for(uint pos = 1; pos <= numkeys; pos++) {
              ^
../../src/bitcoin-tx.cpp:324:23: error: ‘pos’ was not declared in this scope
     for(uint pos = 1; pos <= numkeys; pos++) {
                       ^
../../src/bitcoin-tx.cpp:324:30: error: ‘numkeys’ was not declared in this scope
     for(uint pos = 1; pos <= numkeys; pos++) {
                              ^
../../src/bitcoin-tx.cpp:334:34: error: ‘numkeys’ was not declared in this scope
     if (vStrInputParts.size() == numkeys + 4) {
                                  ^
../../src/bitcoin-tx.cpp:344:49: error: ‘required’ was not declared in this scope
     CScript scriptPubKey = GetScriptForMultisig(required, pubkeys);
                                                 ^
make[2]: *** [bitcoin_tx-bitcoin-tx.o] Error 1
make[2]: Leaving directory `/home/travis/build/bitcoin/bitcoin/build/src'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/bitcoin/bitcoin/build/src'
make: *** [check-recursive] Error 1
```

2016-10-05 18:18 UTC, paveljanik commented
Concept ACK

New warning:
```
bitcoin-tx.cpp:283:25: warning: declaration shadows a local variable [-Wshadow]
        CBitcoinAddress addr(scriptPubKey);
                        ^
bitcoin-tx.cpp:265:21: note: previous declaration is here
    CBitcoinAddress addr(scriptPubKey);
                    ^
1 warning generated.
```

2016-10-05 19:04 UTC, jnewbery commented
Thanks @paveljanik . Fixed in squashed commit.

2016-10-05 19:18 UTC, paveljanik commented
`-Wshadow` clean now, thanks!

I'll read the changes later tonight.

2016-10-05 20:19 UTC, paveljanik commented on src/bitcoin-tx.cpp
> +            _("Optionally add the \"W\" flag to produce a pay-to-witness-script-hash output") + ". " +
Why do you sometimes translate dot at the end of sentence and sometimes not?

2016-10-05 20:20 UTC, paveljanik commented on src/bitcoin-tx.cpp
> +    // Seperate into VALUE:ADDRESS
Separate (e -> a)?

2016-10-05 20:21 UTC, paveljanik commented on src/bitcoin-tx.cpp
> +    boost::split(vStrInputParts, strInput, boost::is_any_of(":"));
This adds another dependency on boost. But as we already use it in this file, it is OK.

2016-10-05 21:15 UTC, czzarr commented on src/bitcoin-tx.cpp
> +    // Seperate into VALUE:ADDRESS
fixed

2016-10-05 21:35 UTC, czzarr commented on src/bitcoin-tx.cpp
> +            _("Optionally add the \"W\" flag to produce a pay-to-witness-script-hash output") + ". " +
for some reason I get a compile error when I put the dot in the sentence:
```
bitcoin-tx.cpp:79:13: error: expected ')'
            _("Optionally add the \"W\" flag to produce a pay-to-witness-pubkey-hash output") + ". " +
            ^
bitcoin-tx.cpp:78:35: note: to match this '('
        strUsage += HelpMessageOpt("outpubkey=VALUE:PUBKEY[:FLAGS]", _("Add pay-to-pubkey output to TX. ")
                                  ^
1 error generated.
```

2016-10-05 21:46 UTC, czzarr commented on src/bitcoin-tx.cpp
> +    // Extract and validate VALUE
done in https://github.com/bitcoin/bitcoin/pull/8883/commits/79cd9275db714603f4a3c55360b3d52a945d95da

2016-10-08 14:52 UTC, jonasschnelli commented
Concept ACK.

2016-10-08 14:53 UTC, jonasschnelli requested changes

2016-10-08 14:53 UTC, jonasschnelli commented on src/bitcoin-tx.cpp
> +    if (bSegWit) {
Is there a reason for `bSegWit` and not directly use `(flags.find("W") != string::pos)`?

2016-10-08 14:53 UTC, jonasschnelli commented on src/bitcoin-tx.cpp
> +    if (bScriptHash) {
maybe a `else if`?

2016-10-08 14:53 UTC, jonasschnelli commented on src/bitcoin-tx.cpp
> +    CScript scriptPubKey = GetScriptForRawPubKey(pubkey);
Does this result in supporting pure `P2PK` (not `P2PKH`)?

2016-10-11 09:05 UTC, jnewbery commented on src/bitcoin-tx.cpp
> +    CScript scriptPubKey = GetScriptForRawPubKey(pubkey);
Yes - without either flag, the TXO will be a P2PK.

- With just the `H` flag, the TXO is a P2SH
- With just the `W` flag, the TXO is a P2WPK
- With both the `H` and `W` flags, the TXO is a P2WPK wrapped in a P2SH

2016-10-11 09:05 UTC, jnewbery commented on src/bitcoin-tx.cpp
> +    if (bSegWit) {
See below. The flags are not exclusive. I need to put the `flags.find()` test inside the  `(vStrInputParts.size() == 3)` so I may as well parse for both flags at the same point and store the result in variables.

2016-10-11 09:05 UTC, jnewbery commented on src/bitcoin-tx.cpp
> +    if (bScriptHash) {
They're not exclusive. If both flags are used, we output a P2WPKH wrapped in P2SH.

2016-10-18 20:33 UTC, jnewbery commented
Rebased. @jonasschnelli - are you happy with my responses above?

2016-10-19 12:13 UTC, jonasschnelli commented
@jnewbery: Yes.
utACK, will test now...

2016-10-19 12:16 UTC, jonasschnelli commented
Travis is failing on the new tests:
```
Running test/bitcoin-util-test.py...
make[4]: Entering directory `/home/travis/build/bitcoin/bitcoin/build/src'
Output data mismatch for txcreatescript1.json
make[3]: *** [check-local] Error 1
make[3]: *** Waiting for unfinished jobs....
```

2016-10-24 14:39 UTC, jnewbery commented
I've fixed the failing testcases and squashed the commits. @jonasschnelli - please let me know if you have any further feedback for this PR.

2016-10-28 08:59 UTC, jonasschnelli approved these changes

2016-10-28 08:59 UTC, jonasschnelli commented
slightly tested ACK e5fecbf64d1dad360490294d1aad79497dcb1de7.
Someone should verify the unit tests fixtures.

2016-12-14 09:24 UTC, laanwj commented
utACK.
Needs rebase though.

2016-12-23 13:44 UTC, jnewbery commented
rebased

2017-01-09 22:26 UTC, jnewbery commented
Rebased. I had to do a couple of large merges (removing std namespace and updating default tx version). @laanwj - let me know if there's anything I can do to help get this merged into master.

2017-01-12 11:24 UTC, merged