Update bitcoin-qt.desktop
bitcoin/bitcoin pull request #8908
Opened 2016-10-11 09:37 UTC by s-matthew-english

I'd like to get the hang of how to make pull requests and contribute. there was no German there, but Turkish and French- many Bitcoiners are German- so- maybe it would be useful

2016-10-11 09:50 UTC, MarcoFalke commented
This should probably be changed to just "Bitcoin Core GUI".

2016-10-11 10:28 UTC, maflcko requested changes

2016-10-11 10:28 UTC, MarcoFalke commented on contrib/debian/bitcoin-qt.desktop
>  Name=Bitcoin
"Bitcoin Core" or "Bitcoin Core GUI"

2016-10-11 10:28 UTC, MarcoFalke commented on contrib/debian/bitcoin-qt.desktop
>  Comment=Bitcoin P2P Cryptocurrency
I checked some programs and the default seems to be imperative style, so maybe change to:

Connect to the Bitcoin P2P Network

2016-10-11 12:07 UTC, s-matthew-english commented
it's there some kind of- particular naming convention for the branch, if it should be merged? I guess I didn't do that correctly in this instance

2016-10-11 12:47 UTC, s-matthew-english commented
I think I've made the change you requested, is it so?

2016-10-11 14:54 UTC, MarcoFalke commented on contrib/debian/bitcoin-qt.desktop
> +Comment[de]=Bitcoin, eine virtuelle kryptographische peer-to-peer Währung
I guess this should match the English one. I.e.


"Verbinde mit dem Bitcoin peer-to-peer Netzwerk" (oder ähnlich)

2016-10-11 15:07 UTC, s-matthew-english commented on contrib/debian/bitcoin-qt.desktop
> +Comment[de]=Bitcoin, eine virtuelle kryptographische peer-to-peer Währung
ok cool, I've made the change.

2016-10-11 16:37 UTC, MarcoFalke commented on contrib/debian/bitcoin-qt.desktop
>  Name=Bitcoin
Please change this to "Bitcoin Core".

2016-10-17 13:35 UTC, s-matthew-english commented
I think I've made a mistake which is, I made those changes directly in the window of GitHub, and they don't exist on my local repo, seems they're only in this patch here. Is there some way to incorporate those changes to my local repo so I can do the squashing procedure?

2016-10-17 13:50 UTC, laanwj commented
> Is there some way to incorporate those changes to my local repo so I can do the squashing procedure?

```
git pull origin patch-4
```
(where `origin` is the name that you gave to your github remote)

2016-10-17 13:52 UTC, s-matthew-english commented
so- origin/master? or...

2016-10-17 13:55 UTC, s-matthew-english commented
now I need to issue the command `git rebase -i HEAD~n` isn't it? do you know how I can figure out what is `n`?

2016-10-17 13:57 UTC, fanquake commented
@s-matthew-english `n` is the number of commits you've made.

2016-10-17 14:00 UTC, s-matthew-english commented
my terminal tells me I'm ahead of origin/master by 5 commits, so then- is it 5? how can I check that?

2016-10-17 14:47 UTC, s-matthew-english commented
hmm, I've been trying to squash it for a while now, did it work?

2016-10-17 14:56 UTC, s-matthew-english commented
I think I squashed them, I followed this tutorial: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

2016-10-17 14:59 UTC, achow101 commented
@s-matthew-english didn't seem to work. Did you force push?

2016-10-17 14:59 UTC, s-matthew-english commented
yeah :/ strange

2016-10-17 15:00 UTC, s-matthew-english commented
do I force push it to upstream/master or origin/master?

2016-10-17 15:01 UTC, achow101 commented
it depends on which one points to your repo. It's probably origin/master, but you can try both. The worst that will happen is that you will get an error about not being able to push to one of those.

2016-10-17 15:16 UTC, s-matthew-english commented
what about this: 

https://github.com/s-matthew-english/bitcoin/commit/238fbceeabe38b8e78635eb380ac10b2861197e5

2016-10-17 15:20 UTC, achow101 commented
Close. Do it for your patch-4 branch. Also, the commit message should be cut down to just one message that describes the changes simply.

2016-10-17 15:30 UTC, s-matthew-english commented
hmm, is there a way to retroactively change to commit mesage? I think I've now done it for patch-4, did it work?

2016-10-17 15:32 UTC, achow101 commented
Nope. something very wrong happened. I think you pushed your whole master branch.

2016-10-17 15:34 UTC, s-matthew-english commented
:/ shit- is there a way to... back it up to before I did that and then take another crack at it?

2016-10-17 15:35 UTC, achow101 commented
At this point you could just do it the "hard" way. Reset to Bitcoin master (`git reset --hard upstream/master` assuming upstream is to bitcoin/bitcoin) then make your final changes, commit, and force push.

2016-10-17 15:38 UTC, s-matthew-english commented
on which branch 'patch-4'?

On Mon, Oct 17, 2016 at 5:36 PM, Andrew C <notifications@github.com> wrote:

> At this point you could just do it the "hard" way. Reset to Bitcoin master
> (git reset --hard upstream/master assuming upstream is to
> bitcoin/bitcoin) then make your final changes, commit, and force push.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/8908#issuecomment-254243795>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIonIN8wQ9bs4D6FHdTP5hOONYbQYSyhks5q05YIgaJpZM4KTb1V>
> .
>

2016-10-17 15:38 UTC, achow101 commented
yes

2016-10-17 15:42 UTC, s-matthew-english commented
:/ but when I run 'git merge-base patch-4 upstream/master' it says only
"noop"

On Mon, Oct 17, 2016 at 5:39 PM, Andrew C <notifications@github.com> wrote:

> yes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/8908#issuecomment-254244715>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIonIPtppENShC7-cH9nGZJAcHc6Zq_8ks5q05a_gaJpZM4KTb1V>
> .
>

2016-10-17 15:43 UTC, sipa commented
Maybe this discussion can be held more effectively on IRC?

2016-10-17 15:44 UTC, achow101 commented
Don't do any merges. Just reset the branch like I told you above. You should end up doing something like this:

```
git checkout patch-4
git reset --hard upstream/master

# Do your changes again

git commit -a
git push -f origin
```

2016-10-17 15:50 UTC, s-matthew-english commented
ok- I think I've just done it- did it work?

On Mon, Oct 17, 2016 at 5:45 PM, Andrew C <notifications@github.com> wrote:

> Don't do any merges. Just reset the branch like I told you above. You
> should end up doing something like this:
>
> git checkout patch-4
> git reset --hard upstream/master
>
> # Do your changes again
>
> git commit -a
> git push -f origin
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/8908#issuecomment-254246228>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIonIMek2Y1hGI3b1EB3dr4R5P1g1syfks5q05f_gaJpZM4KTb1V>
> .
>

2016-10-17 15:53 UTC, achow101 commented
Almost. Somehow a change to src/crypto/hmac_sha256.cpp slipped in.

Just remove that change and then use `git commit -a --amend` to modify the existing commit.

2016-10-17 15:57 UTC, s-matthew-english commented
ok- I think I've done it. is it so?

On Mon, Oct 17, 2016 at 5:54 PM, Andrew C <notifications@github.com> wrote:

> Almost. Somehow a change to src/crypto/hmac_sha256.cpp slipped in.
>
> Just remove that change and then use git commit -a --amend to modify the
> existing commit.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/8908#issuecomment-254249019>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIonIAMrSy4XKlQAaz51fLHkQ1-0s4k2ks5q05o_gaJpZM4KTb1V>
> .
>

2016-10-17 16:00 UTC, achow101 commented
Yes, it is correct now.

2016-10-17 16:01 UTC, MarcoFalke commented
Please do a last `git commit --ammend` and make sure to apply the second git commit message rule: http://chris.beams.io/posts/git-commit/#seven-rules

2016-10-17 16:02 UTC, s-matthew-english commented
:D cool- thank you for helping me figure this out

On Mon, Oct 17, 2016 at 6:01 PM, Andrew C <notifications@github.com> wrote:

> Yes, it is correct now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin/bitcoin/pull/8908#issuecomment-254250929>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIonIGIh8mufhLQd6WseIENp0t8MWSVDks5q05vHgaJpZM4KTb1V>
> .
>

2016-10-17 16:05 UTC, s-matthew-english commented
how about that one?

2016-10-17 18:20 UTC, MarcoFalke commented
utACK 164196b

2016-10-18 06:25 UTC, jonasschnelli commented
utACK 164196b7c8aecb72dd20c8681bb24b81b18aecaa

2016-10-18 19:19 UTC, TheBlueMatt commented
utACK 164196b7c8aecb72dd20c8681bb24b81b18aecaa

2016-10-18 19:20 UTC, merged