Fix init segfault where InitLoadWallet() calls ATMP before genesis
bitcoin/bitcoin pull request #8928
Opened 2016-10-15 17:21 UTC by TheBlueMatt

I honestly have no idea how the wallet.py tests are passing for anyone, but they reliably cause segfault here for me.

2016-10-16 10:18 UTC, MarcoFalke commented
utACK 37aefff5fcf7169a1b07ff8939850f630640f7e7

2016-10-18 21:21 UTC, laanwj commented on src/init.cpp
> +#ifdef ENABLE_WALLET
It's unfortunate that this has to introduce a new `#ifdef ENABLE_WALLET` here, and ref to pWalletMain.
We're trying to get rid of them to remove the circular dependency between` _wallet` and `_server` libs (#7965), and in the interest of multi-wallet support.

2016-10-18 21:23 UTC, laanwj commented
utACK otherwise

2016-10-19 09:08 UTC, MarcoFalke commented on src/init.cpp
> +#ifdef ENABLE_WALLET
It could be combined with the guard a few lines below, but this won't solve the larger problem.

I think for a bugfix this is fine.

2016-10-19 12:04 UTC, jonasschnelli requested changes

2016-10-19 16:10 UTC, laanwj commented on src/init.cpp
> +#ifdef ENABLE_WALLET
Yes I agree, let's merge this as it is a necessary bugfix, this can be improved later.

2016-10-19 16:11 UTC, merged

2016-10-19 16:12 UTC, laanwj commented on src/init.cpp
> +        pwalletMain->ReacceptWalletTransactions();
@jonasschnelli we can do this later