[Qt] fix coincontrol sort issue
bitcoin/bitcoin pull request #9185
Opened 2016-11-18 10:13 UTC by jonasschnelli

Reported by @gmaxwell 
The sort order for the amount column is lexicographical resulting in a order like "1 10 2 20 200 3 ...".

The attempts of this PR is to fix this.

2016-11-18 12:18 UTC, laanwj requested changes

2016-11-18 12:18 UTC, laanwj commented on src/qt/coincontroldialog.cpp
> +            itemOutput->setData(COLUMN_AMOUNT_INT64, Qt::DisplayRole, QVariant((qlonglong)out.tx->vout[out.i].nValue)); // padding so that sorting works correctly
Let's get rid of the hidden _INT64 columns completely, they should no longer be necessary.

2016-11-18 12:18 UTC, laanwj commented on src/qt/coincontroldialog.cpp
> +            itemOutput->setData(COLUMN_AMOUNT_INT64, Qt::DisplayRole, QVariant((qlonglong)out.tx->vout[out.i].nValue)); // padding so that sorting works correctly
Also: function strPad can go after this.

2016-11-18 13:16 UTC, laanwj commented
Working on a patch

2016-11-18 13:39 UTC, laanwj commented
Please cherry-pick the top commit from: https://github.com/laanwj/bitcoin/tree/2016_11_trol_cleanup into this. I've done some further cleanups and fixes:

- Do sorting for date, amount and confirmations column as longlong, not unsigned longlong.
- Use `UserRole` to store our own data for sorting. This makes it treated as  ancillary data prevents it from being displayed.
- Get rid of `getMappedColumn` `strPad` - these are no longer necessary.
- Get rid of hidden `_INT64` columns.
- Start enumeration from 0 (otherwise values are undefined).

2016-11-20 19:20 UTC, jonasschnelli commented
Thanks @laanwj!
Cherry picked your 4231032

2016-11-21 07:45 UTC, laanwj approved these changes

2016-11-21 07:46 UTC, laanwj commented
@gmaxwell Can you please test this in your environment and confirm whether the problem is fixed?

2016-11-21 12:56 UTC, jonasschnelli commented
Tested ACK (Ubuntu) after @laanwj commit.
Binaries: https://bitcoin.jonasschnelli.ch/pulls/9185/

Waiting for @gmaxwell's re-test

<img width="735" alt="bildschirmfoto 2016-11-21 um 13 55 27" src="https://cloud.githubusercontent.com/assets/178464/20483425/403e6474-aff2-11e6-9a68-1e01908c8561.png">

2016-11-22 06:22 UTC, gmaxwell commented
tested ACK!

2016-11-22 07:31 UTC, merged