Separate different uses of minimum fees
bitcoin/bitcoin pull request #9380
Opened 2016-12-19 21:03 UTC by morcos

I've been meaning to do this for a while.
There is no behavior change here, but there were unintended consequences of having these all of these different notions linked to minRelayTxFee.

- blockmintxfee should be set by miners to reflect their marginal cost of transmitting extra bytes.
- incrementalrelayfee was previously hard-coded to the default minRelayTxFee, but it should be configurable so it can be adjusted to reflect the cost of network wide relay of transactions.
- dustrelayfee should not be accidentally changed when someone wants to limit their mempool to higher fee transactions.

I plan a future change to make the wallet smarter about not generating change outputs near the dust limit at all.  I also think we should consider splitting dust into 2 dust limits if we ever raise it again and first raise the creation limit and second the standard limit a version later.  Since it is not clear we'll ever need to increase the dust limit, this change isn't introduced now.

2016-12-24 22:38 UTC, gmaxwell commented
utACK.  My comment on reading the code was that we need to split the wallet and non-wallet behavior (esp for dust) but I see that your PR comment mentions an intention to do that later.

2017-01-04 18:33 UTC, morcos commented
rebased

2017-01-12 23:33 UTC, jtimon commented
utACK 947b63a
If it is decided to hide some or all of the new options and only expose them after 0.14 branches for translation reasons that's fine with me too (although I don't see how no documentation is better than documentation in English).

2017-01-13 17:08 UTC, instagibbs commented
utACK 947b63a06043480a3a9f490b0d5485486f73e5bd

2017-01-13 21:34 UTC, sdaftuar requested changes
Couple nits, concept ACK, haven't tested yet (but plan to).

2017-01-13 21:34 UTC, sdaftuar commented on src/init.cpp
> +        strUsage += HelpMessageOpt("-incrementalrelayfee=<amt>", strprintf(_("Fee rate (in %s/kB) used to define cost of free relay, used for mempool limiting and BIP 125 replacement. (default: %s)")
Is this not supposed to be translated?  Also, "cost of free relay" is a very confusing phrase.  Perhaps "cost of relay"?

2017-01-13 21:34 UTC, sdaftuar commented on src/txmempool.h
> +      *  The incrementalRelayFee policy variable is used to bound the time it
Should still mention what minReasonableRelayFee constructor arg is for --  I guess fee estimation wants the min relay fee?

2017-01-13 21:34 UTC, sdaftuar commented on src/init.cpp
> +        strUsage += HelpMessageOpt("-dustrelayfee=<amt>", strprintf(_("Fee rate (in %s/kB) used to defined dust, the size of an output such that it will cost about 1/3 of its value in fees at this fe
This should not be translated?  Also, "size of an output" -> "value of an output"?

2017-01-13 23:09 UTC, sipa commented
Concept ACK

2017-01-13 23:58 UTC, morcos commented on src/txmempool.h
> +      *  The incrementalRelayFee policy variable is used to bound the time it
Removed in #9548 actually, but I will address your other points...

2017-01-14 11:09 UTC, MarcoFalke commented on src/init.cpp
> +        strUsage += HelpMessageOpt("-dustrelayfee=<amt>", strprintf(_("Fee rate (in %s/kB) used to defined dust, the size of an output such that it will cost about 1/3 of its value in fees at this fe
This should not be called dust*relay*fee, but dustfee. My reasoning is that dustfee has more implications than just setting a relay fee rate.

2017-01-14 11:10 UTC, MarcoFalke commented
ACK, but needs all debug strings removed from the translations.

2017-01-16 13:44 UTC, morcos commented
Removed translation strings for -debug options.

Ideally this would get merged in time to keep the translation of `-blockmintxfee`.  I think it is ready for merge other than any disagreement over the name of `-dustrelayfee`.  I'm happy to change it if we agree on something else.     `-dustminfee`, `-dustdefinefee`, `-dustfee` or just leave it?

2017-01-16 18:31 UTC, laanwj commented
utACK eb30d1a

2017-01-16 18:33 UTC, merged