[RPC] dumpmasterprivkey command
bitcoin/bitcoin pull request #9504
Opened 2017-01-10 19:18 UTC by achow101

RPC command to export the master private key from a wallet.

2017-01-10 19:46 UTC, luke-jr commented
`dumpwallet` already does this...?

2017-01-10 19:49 UTC, achow101 commented
`dumpwallet` requires that you dump to a file then find that file and open it to get the master private key. This just gives it to you with the command.

2017-01-11 07:31 UTC, jonasschnelli requested changes
Not sure if we should add more private key exporting features because it increases the risk of doing something wrong with that.

If we are going to add this, it would require...
... add `dumpmasterprivkey` to the UI's sensitiv data filter
... add a test somewhere

2017-01-11 07:31 UTC, jonasschnelli commented on src/wallet/rpcwallet.cpp
> +    { "wallet",             "dumpmasterprivkey",        &dumpmasterprivkey,         true,   {} },
nit: column alignment.

2017-01-11 07:31 UTC, jonasschnelli commented on src/wallet/rpcdump.cpp
> +    CKeyID masterKeyID = pwalletMain->GetHDChain().masterKeyID;
Use `CWallet::IsHDEnabled()`?

2017-01-11 07:31 UTC, jonasschnelli commented on src/wallet/rpcdump.cpp
> +    CKeyID masterKeyID = pwalletMain->GetHDChain().masterKeyID;
Well,... you need the masterKeys `CKeyID` anyway,... but I guess it would still make sense to use `CWallet::IsHDEnabled()`

2017-01-11 16:06 UTC, achow101 commented
@jonasschnelli there is no sensitive data filter for the `dump*` commands. The user is not entering sensitive data, only sensitive data being output.

2017-01-11 16:20 UTC, achow101 commented
Addressed nits and added a test.

It may need more tests, but I'm not sure what actually needs to be tested.

2017-01-11 17:51 UTC, jonasschnelli commented
> @jonasschnelli there is no sensitive data filter for the dump* commands. The user is not entering sensitive data, only sensitive data being output.

Argh. Right. I was confusing the sensitiv history filter with the idea of having a filter that disables certain sensitive commands.

2018-02-08 19:13 UTC, achow101 commented
Closing this for now

2018-02-08 19:13 UTC, closed without merging