Improve readability by removing redundant casts to same type (on all platforms)
bitcoin/bitcoin pull request #9598
Opened 2017-01-20 08:45 UTC by practicalswift

2017-01-20 08:52 UTC, practicalswift commented
A portable cleanup this time hopefully :-)

2017-01-20 23:43 UTC, luke-jr requested changes

2017-01-20 23:43 UTC, luke-jr commented on src/primitives/transaction.cpp
> +        unsigned int offset = 41U + std::min(110U, it->scriptSig.size());
It seems like this is a regression? size_t is not necessarily the same size as unsigned int.

But the current code is also non-ideal. It should probably be:

```C++
size_t offset = 41U + std::min(size_t(110), it->scriptSig.size());
```

2017-01-20 23:45 UTC, sipa commented on src/primitives/transaction.cpp
> +        unsigned int offset = 41U + std::min(110U, it->scriptSig.size());
Even better:
```c++
size_t offset = 41U + std::min<size_t>(110, it->scriptSig.size());
```

2017-01-21 06:47 UTC, practicalswift commented on src/primitives/transaction.cpp
> +        unsigned int offset = 41U + std::min(110U, it->scriptSig.size());
@luke-jr @sipa Good points! Fixed, squashed and pushed :-)

2017-01-24 01:58 UTC, dcousens approved these changes

2017-02-27 22:18 UTC, practicalswift commented
Any changes needed before merge? :-)

2017-02-28 12:31 UTC, paveljanik commented
What is the problem you are trying to solve? It is very hard to review similar tasks because of multiple architectures...

2017-02-28 13:23 UTC, practicalswift commented
@paveljanik The goal of this PR is to improve readability by removing redundant casts. Let me know if you see any need for any of these explicit casts and I'll adjust my PR accordingly. My reading is that they're all redundant.

More specifically my reading is that:
* `&vDataToHash[0] + nblocks * 4` is guaranteed to be of type `const uint8_t*`.
* `FD_SETSIZE - nBind - MIN_CORE_FILEDESCRIPTORS - MAX_ADDNODE_CONNECTIONS` is guaranteed to be of type `int`.
* `&privkey[…]` is guaranteed to be of type `unsigned char*`.
* `&vchSig[…]` is guaranteed to be of type `unsigned char*`.

Let me know if I'm mistaken :-)

2017-03-08 09:21 UTC, practicalswift commented
Conflicts resolved. Rebased and pushed!

2017-04-10 12:16 UTC, practicalswift commented
Adding link to [avoid casts (ES.48)](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es48-avoid-casts) in the C++ Core Guidelines.

2017-07-15 13:00 UTC, practicalswift commented
Rebased!

2017-07-15 18:04 UTC, sipa commented
utACK a0e84aa34827538cbc06d5c9a32c658b0919d181

2017-07-16 15:36 UTC, TheBlueMatt commented
utACK a0e84aa34827538cbc06d5c9a32c658b0919d181

2017-10-30 12:58 UTC, practicalswift commented
Is this one ready for merge? :-)

2017-12-21 12:36 UTC, practicalswift commented
Rebased!

2018-03-06 18:38 UTC, sipa commented
Still utACK 06edc23f7409160adaaea5dd8d80b5dcaf696f99

2018-03-06 21:42 UTC, practicalswift commented
@laanwj Does this PR have a chance of getting merged? If so I'll keep rebasing :-)

2018-03-07 13:34 UTC, MarcoFalke commented
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

utACK 06edc23f7409160adaaea5dd8d80b5dcaf696f99
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJan+puAAoJENLqSFDnUoslqv0P/0oRpXH3nuTlCdwrsNgba/ol
TeJvBMzrFWerQQ4bqX1qSKTkBDDqvAqmybEm4nFsEmR74FaPSftCVP2P8PFpxkZP
WtVCFvsWhiTtvfDXWui0c2llsFrmqsB4Ivf3rbHkU92OIqMS5tqvmmBuaNiA5K/Q
k7vqj6lkl2zG81mjXQFj18mps9L2Ik8yVS7VbHZO5FyLnJxQsRJQ96nr86h0rO7Z
IFiOdlkfGmEBwD0KWwFMNqetQUw399maMHsBYibugofWuupyOqD6eZp6AOkre7dD
0ickdOPF6ATzWI6me34SIueviJiuTf9nF19E0GmTu1sVkRsJVx6EKXGN3YhwJmlL
6hKuUe/RWRWHMVEP1KkXF+jxHgEjoWfTg3kocG2ZRkR6vvIJNPi1ux0ZGQQDfj5P
Gaz84AKrxl9hpYwQy1+35F7H885cSQvU+FVigpUCmxtHvHxcwy5vs9xvlMQwIDy1
M9EWN3Mu1oeNx9hyJMt+kZu0XQsUIJa+sE1sGg7PhsrG29znOpI7/o6LisaP2pYY
CJUy+5jRUDK8GhRP9qnzgooMm89h9Fer/LZKNyoo7xs/tPY2829VPk3JnDpSNH1A
13Bb0EwWBhjP33tTXzLL1VrH3OhvMBY9ruv5R/+d72jeVZHlD40iLEbvviSYb4Q8
O4eaEgNGRgovkm3mteye
=nBtN
-----END PGP SIGNATURE-----

2018-03-07 16:42 UTC, MeshCollider commented
utACK https://github.com/bitcoin/bitcoin/commit/06edc23f7409160adaaea5dd8d80b5dcaf696f99

2018-03-07 16:48 UTC, merged

2018-06-19 10:35 UTC, anton48 commented
Hi!

the change to file 'init.cpp' breaks compilation on FreeBSD:

> init.cpp:965:32: error: no matching function for call to 'min'
    nMaxConnections = std::max(std::min(nMaxConnections, FD_SETSIZE - nBind - MIN_CORE_FILEDESCRIPTORS - MAX_ADDNODE_CONNECTIONS), 0);
                               ^~~~~~~~
/usr/include/c++/v1/algorithm:2581:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('int' vs. 'unsigned int')
min(const _Tp& __a, const _Tp& __b)
^
/usr/include/c++/v1/algorithm:2591:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'int'
min(initializer_list<_Tp> __t, _Compare __comp)
^
/usr/include/c++/v1/algorithm:2573:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
min(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/usr/include/c++/v1/algorithm:2599:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
min(initializer_list<_Tp> __t)
^
1 error generated.

> 

and actually this change reverts pull request from 2013: https://github.com/bitcoin/bitcoin/pull/2695

2018-06-19 12:00 UTC, practicalswift commented
@anton48 Thanks for reporting! I'll investigate! :-)

2018-06-19 13:50 UTC, practicalswift commented
@anton48 Fix in #13503. Please confirm it solves the problem :-)