remove TestBlockValidity from CreateNewBlock critical path
bitcoin/bitcoin pull request #9858
Opened 2017-02-25 19:57 UTC by jameshilliard

Rational for removal:

- This is effectively a fatal error to miners regardless, there is no meaningful downside to removing this because getting an invalid template is not practically any worse than getting no template.

- Due to cs_main locks this causes a large variance in GBT response times and further encourages undesirable workarounds such as validationless mining.

- Invalid blocks are much more likely to originate from stratum server bugs, something like [this](https://github.com/bitcoin/bitcoin/pull/9000) is probably a better way to test block validity.

I've been running with this TestBlockValidity call removed in production for a few months at this point.

2017-02-25 21:41 UTC, luke-jr requested changes
This seems to remove the test entirely, not just from the critical path.

Getting an invalid template *is* worse than "no template", because it *causes* validationless mining. As such, arguing that this check encourages validationless is meaningless: encouraging is less bad than causing.

(Note that [BIP 23 Block Proposals](https://github.com/bitcoin/bips/blob/master/bip-0023.mediawiki#Block_Proposal) would be better than the faux mining stuff to do a later re-test.)

Also note that CNB is *not* in the critical path for validationless mining. As soon as validation of a block completes (and no sooner), miners *should* switch to empty blocks on top of that, and not be waiting for CNB anyway. A non-zero delay here *will* always exist, and it's just a matter of implementing the empty block logic correctly (waiting for validation of the prevblock).

That all being said, it might be okay to *simply* remove it from the critical path, provided it is still checked after GBT returns, and has a reasonably sufficient way of stopping mining if it's invalid (eg, perhaps call `blocknotify` handlers and `abort`?)

2017-02-25 21:41 UTC, theuni commented
I can agree with the idea that BlockAssembler shouldn't need to resort to the heaviness of TestBlockValidity, but we do need _some_ checks here.

As to your points
- Grinding for a minute on a block that will be rejected is not worse than an extra quick call to gbt?
- cs_main is already locked. This change does not reduce locking, only shaves down the time that it's held. Also, technically, this change would make this validation-less mining :(
- Your example uses TestBlockValidity :)

2017-02-25 22:48 UTC, jameshilliard commented
Getting an invalid template here should never happen unless there is a bug within bitcoind, this TestBlockValidity call is only an internal sanity check, my definition of validationless mining would be mining on top of a block that you haven't validated, this does not change that.

@luke-jr 

- Not all pool software is capable of bypassing GBT, that requires implementing p2p networking in the stratum server which adds quite a bit of complexity.

- My point is that CNB is in the critical path for validating mining, at least for stratum servers that don't implement p2p themselves.

@theuni 

- My assumption is that if TestBlockValidity fails subsequent calls are also likely to fail.

- Yes, removing TestBlockValidity does however significantly reduce CreateNewBlock times from my testing, I'm assuming locking is a major factor since TestBlockValidity introduces a large amount of variance in CreateNewBlock times as well.

2017-02-26 01:49 UTC, luke-jr commented
`blocknotify` should be sufficient to begin empty-block mining. But perhaps it would make sense to have bitcoind's GBT itself handle the empty template?

2017-02-26 02:37 UTC, jameshilliard commented
@luke-jr Well you would have to cache some things like nversion if you just use blocknotify right? CreateNewBlock itself seems to be quite fast without TestBlockValidity so I'm not sure sending empty blocks out first is worth the extra bandwidth/complexity.

2017-02-26 18:46 UTC, TheBlueMatt commented
I'm totally in favor of removing TBV from the critical-path, but only if we trigger some background checker that will print to debug.log (and probably assert) if it returned a template it later found to be invalid.

2017-02-26 19:35 UTC, jameshilliard commented
@TheBlueMatt I made an [attempt](https://github.com/bitcoin/bitcoin/pull/7167) to do that before but the way I was doing it there didn't look viable.

2017-02-26 21:33 UTC, sipa commented
I believe that @jameshilliard assumption that if CNB ever produces an invalid block, it is likely that it will keep doing so is right, and if so, the only benefit of running TBV is better reporting (so developers can fix the bug), not actually changing what is being mined. The better reporting may be useful, as miners may use GBT under circumstances that aren't covered by any tests during rcs, but it seems we have a pretty good track record the last few releases.

I think there are two reasonable approaches:
* Run a background thread that occasionally runs TBV on the CNB results. It doesn't have to test everything, and it can do do with a delay. Unfortunately, TBV's locking of cs_main may interfere with other CNB calls.
* Make the TBV call optional like in #9859, and leave it on in unit and RPC tests, but off by default in production.

2017-02-26 21:58 UTC, jameshilliard commented
@sipa I think just making it optional is probably best, doing block proposals within the stratum server would be good since it can be done completely outside of the critical path, although I'm not sure how easy it would be to add support for that in the various stratum servers themselves. I like cory's faux-mining for testing a little more at least for non-production testing since it can be done without modification of the stratum server.

2017-02-27 23:41 UTC, gmaxwell commented
I don't think making it optional is useful.  It will almost never be run where it needs to be run. And more options mean more mostly untested code that will catch fire later when someone does happen to use it.

> Run a background thread that occasionally runs TBV on the CNB results. It doesn't have to test everything, and it can do so with a delay. Unfortunately, TBV's locking of cs_main may interfere with other CNB calls.

We should be able to get the locking into a state where it can return a cached template without taking cs_main.  In which case, running the test immediately after returning a result will run it during a time when its mostly only returning a cached result. Moreover the test could be made interruptible, in case a new block arrives-- this is also important for BIP23 block proposal testing.

I do disagree that mining an invalid block is equal to or better than a delay:  A shutdown lets you fall over to another daemon, a shutdown tells you something is broken so you fix it rather than days of fake mining, and a shutdown also prevents you from making blocks that cause false confirmations for SPV clients propagated around broken nodes that broadcast without validating.  -- but the whole question should be moot, since we should be able to perform this check without adding any meaningful delay.

2017-02-28 00:37 UTC, jameshilliard commented
@gmaxwell My thoughts are that this should probably be only used for testing and not in production under normal circumstances.

In regards to failover I would expect that a bug in CNB would likely be deterministic and cause failures on all other pool nodes as well that run similar mempool policy.

2017-03-07 17:40 UTC, jtimon commented on src/miner.h
> +    std::unique_ptr<CBlockTemplate> CreateNewBlock(const CScript& scriptPubKeyIn, bool TestBlock = false);
Do we need a default value here?
Do we really save that much disruption by not passing false explicitly where it's needed?

Bikeshedding: s/TestBlock/fValidateBlock/ ?

2018-08-25 16:30 UTC, MarcoFalke commented
Closing for now. Let me know when you continue to work on this

2018-08-25 16:30 UTC, closed without merging