Don't require segwit in getblocktemplate for segwit signalling or mining
bitcoin/bitcoin pull request #9955
Opened 2017-03-08 22:00 UTC by sdaftuar

Segwit's version bit will be signalled for all invocations of CreateNewBlock,
and not specifying segwit only will cause CreateNewBlock to skip transactions
with witness from being selected. (Note that CreateNewBlock's performance may suffer if the mempool has witness transactions that are being skipped, so this is not a recommended configuration.)

Originally we didn't signal segwit unless the getblocktemplate caller explicitly indicated support, in order to prevent segwit from activating before any miners actually had support for the witness commitment.  Now that many blocks are signalling segwit already, this is not a material concern.

Also, I need to figure out how to add a test to segwit.py to check that witness transactions would in fact be skipped.

As per IRC discussion, I think we should consider this for backport to the 0.14 branch.

2017-03-08 22:04 UTC, gmaxwell reviewed
Concept ACK.

2017-03-08 22:17 UTC, luke-jr requested changes

2017-03-08 22:17 UTC, luke-jr commented on qa/rpc-tests/segwit.py
> +        # selected for mining.
Should test that witness tx can't sneak in as an ancestor of non-witness, too.

2017-03-08 22:17 UTC, luke-jr commented on src/rpc/mining.cpp
>      if (!pblocktemplate->vchCoinbaseCommitment.empty() && setClientRules.find(segwit_info.name) != setClientRules.end()) {
Use `fMineWitnessTransactions` here?

2017-03-08 22:17 UTC, luke-jr commented on src/rpc/mining.cpp
> +        pblocktemplate = BlockAssembler(Params()).CreateNewBlock(scriptDummy, fMineWitnessTransactions);
This is cached across calls, so it requires a bit more complexity.

2017-03-08 22:20 UTC, JeremyRubin commented
Maybe transactions with a witness should not get inserted into the mempool?

2017-03-09 01:48 UTC, sdaftuar commented on qa/rpc-tests/segwit.py
> +        # selected for mining.
I concur.

2017-03-09 01:48 UTC, sdaftuar commented on src/rpc/mining.cpp
>      if (!pblocktemplate->vchCoinbaseCommitment.empty() && setClientRules.find(segwit_info.name) != setClientRules.end()) {
Addressed in 24428bd.

2017-03-09 01:48 UTC, sdaftuar commented on src/rpc/mining.cpp
> +        pblocktemplate = BlockAssembler(Params()).CreateNewBlock(scriptDummy, fMineWitnessTransactions);
I think I fixed this in 24428bd.

2017-03-09 01:59 UTC, sdaftuar commented
> Maybe transactions with a witness should not get inserted into the mempool?

@JeremyRubin Sure, and miners could also continue to use 0.13.0 or older for `getblocktemplate` (while submitting their blocks to later version software, which would work just fine post-segwit activation).  Many working configurations are possible; I think we're just trying to add a simple way to support more miners out of the box.  Personally I don't think it's worth making big code changes -- like redoing mempool policy on the fly for miners who aren't invoking gbt with segwit support -- to achieve this functionality, as this isn't a recommended setup, just a tolerable one.

(If we wanted to make CNB fast in this configuration, then I think the easiest thing to do would be to say add an `int` to each mempool entry that counts the number of ancestors that have witnesses, and use that skip over transactions faster in CNB, but this doesn't seem worth it to me.)

2017-03-09 02:14 UTC, luke-jr approved these changes
utACK (might be better to have two caches, but I doubt it matters)

2017-03-09 09:03 UTC, laanwj commented
Concept ACK

2017-03-09 18:53 UTC, sdaftuar commented on qa/rpc-tests/segwit.py
> +        # selected for mining.
Done in 7db565c

2017-03-09 18:57 UTC, sdaftuar commented
Added a test to `segwit.py`

2017-03-10 13:30 UTC, sdaftuar commented
Rebased (conflict was in `segwit.py`) and squashed the fixup commit.

2017-03-10 16:59 UTC, TheBlueMatt commented
utACK a4a20d8a8de77b45e33cbdb8018dc30c9176fccd

2017-03-12 06:02 UTC, gmaxwell commented
ACK.

Had to go refresh myself on the proper meaning of the "!' prefix. Perhaps the documentation (e.g. BIPs) should be updated to give that a name, "Mandatory prefix". BIP 145 also needs a clear and direct call out to the extensions established in BIP9, not after it's already using them.  Otherwise it's easily confusing. :)

2017-03-14 10:31 UTC, laanwj commented
Merge conflict in segwit.py after #9970

2017-03-14 10:53 UTC, sdaftuar commented
Rebased.

2017-03-14 11:56 UTC, merged